// Zwischenablage auf der Mac-Seite des Clients.
//
// Dieselbe Schnittstelle wie clipboard.rs (Windows): watch() meldet einer
// Rolle (Herkunft), was der Benutzer hier kopiert hat (Text oder eine
// Dateiliste, siehe Inhalt), set() legt Text ab und set_dateien() eine
// Dateiliste, beide ohne die eigene Ueberwachung auszuloesen. Hier werden
// nur Pfade gelesen bzw. abgelegt, nie Dateien; die uebertraegt ein eigener
// Teil (dateien.rs). Es gibt einen Waechter; was er liest, verteilt er wie
// unter Windows an jede angemeldete Rolle mit Gegenueber
// (ablage_ruhe::Verteiler, dort auch das Entdoppeln je Rolle). Auf dem Mac
// meldet sich nur der Client an - die Host-Rolle des Macs hat ihre eigene
// Ablage (host/clipboard.m).
//
// NSPasteboard schickt keine Nachricht bei Aenderungen; es gibt nur den
// changeCount. Deshalb fragt ein Faden alle 300 ms nach. Ist die Zahl
// gestiegen, wird wie unter Windows erst gelesen, wenn sie sich
// ablage_ruhe::RUHE lang nicht mehr bewegt hat (Entprellen), und dieselbe
// Dateiliste geht innerhalb von ablage_ruhe::DOPPEL_FRIST nur einmal hinaus
// (Entdoppeln; Integrationstest, Befunde 1 und 2). Nach dem eigenen
// Schreiben merken wir uns die neue Zahl (wie OWN_SEQ in clipboard.rs),
// damit das eigene set() nicht als Kopie des Benutzers zurueckgemeldet wird.
// Waechter und set() laufen unter EINER Sperre, damit der Waechter nie
// zwischen clearContents und setString liest.
//
// Gelesen wird nach derselben Regel wie auf dem Mac-Host (host/clipboard.m):
// verdeckte Eintraege (Passwoerter) bleiben auf diesem Rechner. Tragen
// Eintraege Dateiverweise (public.file-url, Finder legt je Datei einen
// Eintrag an), wird die Dateiliste gemeldet und kein Text - auch nicht der
// Name, den Finder zusaetzlich als Text ablegt. Sonst zaehlt der Text des
// ersten Eintrags.
//
// Gelesen wird nur, solange eine angemeldete Rolle ein Gegenueber hat (der
// Client: waehrend einer Sitzung, `sitzung`). Ohne zaehlt der Waechter nur
// den changeCount mit: ab macOS 15.4 kann jedes Lesen des
// Inhalts durch ein Programm die Rueckfrage des Systems ausloesen (siehe
// host/clipboard.m), und was ohne Sitzung kopiert wurde, braucht niemand -
// es geht auch beim Sitzungsbeginn nicht nachtraeglich hinaus. Dieselbe
// Regel gilt unter Windows (clipboard.rs) fuer Client und Host-Rolle.
//
// Was vom Host kommt, traegt org.nspasteboard.TransientType und
// org.nspasteboard.AutoGeneratedType: Verwalter der Zwischenablage nehmen es
// dann nicht in ihren Verlauf auf - wie CanIncludeInClipboardHistory = 0
// unter Windows (clipboard.rs). Und es gilt nur fuer diesen Mac
// (prepareForNewContentsWithOptions mit NSPasteboardContentsCurrentHostOnly):
// die Universelle Zwischenablage traegt es nicht auf iPhone oder iPad - wie
// CanUploadToCloudClipboard = 0 unter Windows und wie beim Mac-Host
// (host/clipboard.m). Der eigene Lesefilter bleibt davon unberuehrt:
// fluechtig heisst nicht verdeckt.
//
// Alles ueber objc_msgSend von Hand, keine Kiste: objc_getClass,
// sel_registerName, objc_msgSend (mit passendem Funktionszeiger-Typ je
// Aufruf) und ein Autorelease-Pool je Durchlauf. Gelinkt wird AppKit (fuer
// NSPasteboard und die Konstanten NSPasteboardTypeString und
// NSPasteboardTypeFileURL) und libobjc.

use std::ffi::{c_char, c_void, CStr, OsString};
use std::os::unix::ffi::{OsStrExt, OsStringExt};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, Once};
use std::time::{Duration, Instant};

pub use crate::ablage_ruhe::Inhalt;
use crate::ablage_ruhe::{Entpreller, Verteilt, Verteiler, RUHE};
use crate::protokoll::Herkunft;

/// Obergrenze fuer einen Uebertragungsvorgang - wie auf Windows. Groesseres
/// wird stillschweigend verworfen statt abgeschnitten.
const MAX_BYTES: usize = 4 * 1024 * 1024;

/// Abstand zwischen zwei Blicken auf den changeCount.
const TAKT: Duration = Duration::from_millis(300);

/// NSUTF8StringEncoding
const NS_UTF8: usize = 4;

/// Kennzeichen aus der Verabredung unter nspasteboard.org: Passwortverwalter
/// markieren damit Inhalte, die nicht mitgeschrieben werden sollen. Ein
/// solcher Eintrag geht nicht ueber die Leitung - wie auf dem Mac-Host.
/// UNGEPRUEFT: Branchenkonvention, keine Apple-Dokumentation.
const VERDECKT: &CStr = c"org.nspasteboard.ConcealedType";

/// Kennzeichen aus derselben Verabredung: der Inhalt ist fluechtig und
/// gehoert in keinen Verlauf. Setzt set() an allem, was vom Host kommt.
/// UNGEPRUEFT wie VERDECKT: Branchenkonvention.
const FLUECHTIG: &CStr = c"org.nspasteboard.TransientType";

/// Kennzeichen aus derselben Verabredung: der Inhalt ist nicht vom Nutzer
/// kopiert, sondern von einem Programm erzeugt - wie beim Mac-Host.
/// UNGEPRUEFT wie VERDECKT: Branchenkonvention.
const AUTOGEN: &CStr = c"org.nspasteboard.AutoGeneratedType";

/// NSPasteboardContentsCurrentHostOnly (1 << 0): der Inhalt bleibt auf
/// diesem Rechner, die Universelle Zwischenablage (Handoff) nimmt ihn nicht
/// mit. UNGEPRUEFT: ob Handoff das beachtet, laesst sich nur auf Hardware
/// mit einem zweiten Apple-Geraet pruefen.
const NUR_DIESER_MAC: usize = 1;

// ------------------------------------------------------------------- FFI

type Id = *mut c_void;
type Sel = *mut c_void;

#[link(name = "objc")]
extern "C" {
    fn objc_getClass(name: *const c_char) -> Id;
    fn sel_registerName(name: *const c_char) -> Sel;
    fn objc_msgSend();
    fn objc_autoreleasePoolPush() -> *mut c_void;
    fn objc_autoreleasePoolPop(pool: *mut c_void);
}

#[link(name = "AppKit", kind = "framework")]
extern "C" {
    static NSPasteboardTypeString: Id;
    static NSPasteboardTypeFileURL: Id;
}

fn klasse(name: &CStr) -> Id {
    unsafe { objc_getClass(name.as_ptr()) }
}

fn sel(name: &CStr) -> Sel {
    unsafe { sel_registerName(name.as_ptr()) }
}

/// [obj sel] -> id
unsafe fn msg_id(obj: Id, s: Sel) -> Id {
    let f: unsafe extern "C" fn(Id, Sel) -> Id = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s)
}

/// [obj sel] -> NSInteger
unsafe fn msg_int(obj: Id, s: Sel) -> isize {
    let f: unsafe extern "C" fn(Id, Sel) -> isize = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s)
}

/// [obj sel] -> BOOL
unsafe fn msg_bool(obj: Id, s: Sel) -> bool {
    let f: unsafe extern "C" fn(Id, Sel) -> u8 = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s) != 0
}

/// [obj sel:arg] -> id
unsafe fn msg_id_1(obj: Id, s: Sel, a: Id) -> Id {
    let f: unsafe extern "C" fn(Id, Sel, Id) -> Id = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a)
}

/// [obj sel:NSUInteger] -> id (objectAtIndex:)
unsafe fn msg_id_u(obj: Id, s: Sel, a: usize) -> Id {
    let f: unsafe extern "C" fn(Id, Sel, usize) -> Id = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a)
}

/// [obj sel:arg] -> BOOL (writeObjects:)
unsafe fn msg_bool_1(obj: Id, s: Sel, a: Id) -> bool {
    let f: unsafe extern "C" fn(Id, Sel, Id) -> u8 = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a) != 0
}

/// [obj sel:arg] -> NSUInteger
unsafe fn msg_uint_1(obj: Id, s: Sel, a: usize) -> usize {
    let f: unsafe extern "C" fn(Id, Sel, usize) -> usize = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a)
}

/// [obj sel:NSUInteger] -> NSInteger
unsafe fn msg_int_1(obj: Id, s: Sel, a: usize) -> isize {
    let f: unsafe extern "C" fn(Id, Sel, usize) -> isize = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a)
}

/// [obj sel:a forType:b] -> BOOL
unsafe fn msg_bool_2(obj: Id, s: Sel, a: Id, b: Id) -> bool {
    let f: unsafe extern "C" fn(Id, Sel, Id, Id) -> u8 = std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, a, b) != 0
}

/// [NSString alloc] initWithBytes:length:encoding: -> id (eigene Zaehlung)
unsafe fn msg_init_bytes(obj: Id, s: Sel, bytes: *const c_void, len: usize, enc: usize) -> Id {
    let f: unsafe extern "C" fn(Id, Sel, *const c_void, usize, usize) -> Id =
        std::mem::transmute(objc_msgSend as *const c_void);
    f(obj, s, bytes, len, enc)
}

/// [NSArray arrayWithObjects:count:] -> id (autoreleased)
unsafe fn ns_liste(objekte: &[Id]) -> Id {
    let k = klasse(c"NSArray");
    if k.is_null() {
        return std::ptr::null_mut();
    }
    let f: unsafe extern "C" fn(Id, Sel, *const Id, usize) -> Id = std::mem::transmute(objc_msgSend as *const c_void);
    f(k, sel(c"arrayWithObjects:count:"), objekte.as_ptr(), objekte.len())
}

/// NSString aus einer C-Zeichenkette. Autoreleased: braucht einen Pool.
unsafe fn ns_text(s: &CStr) -> Id {
    let k = klasse(c"NSString");
    if k.is_null() {
        return std::ptr::null_mut();
    }
    msg_id_1(k, sel(c"stringWithUTF8String:"), s.as_ptr() as Id)
}

/// NSString aus UTF-8-Bytes, ohne Abschneiden an einem NUL. Eigene
/// Zaehlung: der Aufrufer gibt ihn mit release frei. Null bei ungueltigem
/// UTF-8.
unsafe fn ns_text_bytes(bytes: &[u8]) -> Id {
    let k = klasse(c"NSString");
    if k.is_null() {
        return std::ptr::null_mut();
    }
    let roh = msg_id(k, sel(c"alloc"));
    msg_init_bytes(roh, sel(c"initWithBytes:length:encoding:"), bytes.as_ptr() as *const c_void, bytes.len(), NS_UTF8)
}

/// Traegt der Eintrag diesen Typ? [item availableTypeFromArray:@[typ]]
unsafe fn hat_typ(item: Id, typ: Id) -> bool {
    let k = klasse(c"NSArray");
    if k.is_null() || typ.is_null() {
        return false;
    }
    let liste = msg_id_1(k, sel(c"arrayWithObject:"), typ);
    !liste.is_null() && !msg_id_1(item, sel(c"availableTypeFromArray:"), liste).is_null()
}

/// Ein Autorelease-Pool fuer die Dauer eines Geltungsbereichs.
struct Pool(*mut c_void);

impl Pool {
    fn neu() -> Pool {
        Pool(unsafe { objc_autoreleasePoolPush() })
    }
}

impl Drop for Pool {
    fn drop(&mut self) {
        unsafe { objc_autoreleasePoolPop(self.0) }
    }
}

// ------------------------------------------------------------ Zustand

/// changeCount nach dem eigenen Schreiben: einmal nach clearContents, einmal
/// nach setString - je nachdem, wann der Waechter hinschaut, muss einer
/// von beiden passen. Gilt fuer Text und Dateilisten.
static EIGEN: Mutex<(isize, isize)> = Mutex::new((-1, -1));

/// Serialisiert set() und set_dateien() gegen den Waechter (siehe Kopf).
static SPERRE: Mutex<()> = Mutex::new(());

/// Laeuft eine Sitzung? Nur dann liest der Waechter den Inhalt.
static SITZUNG: AtomicBool = AtomicBool::new(false);

/// Zaehlt jeden Sitzungswechsel: dieselbe Dateiliste in einer neuen Sitzung
/// ist eine neue Kopie (Entdoppler).
static SITZUNGS_WECHSEL: AtomicU64 = AtomicU64::new(0);

/// Die angemeldeten Rollen des einen Waechters.
static VERTEILER: Verteiler = Verteiler::neu();

/// Der Waechterfaden laeuft nur einmal, gleich wie viele Rollen sich anmelden.
static WAECHTER: Once = Once::new();

/// Sitzung beginnt (true, der Host hat angenommen) oder endet (false).
pub fn sitzung(an: bool) {
    if SITZUNG.swap(an, Ordering::Relaxed) != an {
        SITZUNGS_WECHSEL.fetch_add(1, Ordering::Relaxed);
    }
}

/// Das Gegenueber des Clients fuer seine Anmeldung (watch): Some(Nummer des
/// Sitzungswechsels) waehrend einer Sitzung, sonst None.
pub fn client_gegenueber() -> Option<u64> {
    SITZUNG.load(Ordering::Relaxed).then(|| SITZUNGS_WECHSEL.load(Ordering::Relaxed))
}

/// Eine Zeile des Waechters: ins Protokoll jeder Rolle, fuer die gerade
/// gelesen wird; ohne eine solche (Tests) in das des Fadens.
fn waechter_zeile(text: &str) {
    let rollen = VERTEILER.mit_gegenueber();
    if rollen.is_empty() {
        crate::protokoll::zeile(text.to_string());
    }
    for h in rollen {
        crate::protokoll::zeile_als(h, text.to_string());
    }
}

/// Das allgemeine Brett. Null, wenn AppKit nicht da ist - dann tut alles
/// hier still nichts.
fn brett() -> Id {
    let k = klasse(c"NSPasteboard");
    if k.is_null() {
        return std::ptr::null_mut();
    }
    unsafe { msg_id(k, sel(c"generalPasteboard")) }
}

fn change_count(b: Id) -> isize {
    unsafe { msg_int(b, sel(c"changeCount")) }
}

// ------------------------------------------------------------------- Lesen

/// Was auf dem Brett liegt: eine Dateiliste, wenn Eintraege Dateiverweise
/// (public.file-url) tragen, sonst der Text des ERSTEN Eintrags. Bewusst
/// ueber pasteboardItems und nicht ueber [b stringForType:]: der bequeme Weg
/// auf Brettebene haengt bei mehreren Eintraegen deren Text aneinander.
///
/// Betrachtet werden alle Eintraege: Finder legt je Datei einen an, und ein
/// verdeckter Eintrag irgendwo haelt alles zurueck. None, wenn etwas
/// verdeckt ist, ein Dateiverweis sich nicht aufloesen laesst (lieber keine
/// Liste als eine halbe), nichts Textartiges anliegt oder der Text die
/// Obergrenze reisst. Laeuft im eigenen Pool: die Rueckgaben sind
/// autoreleased.
fn lesen(b: Id) -> Option<Inhalt> {
    let _pool = Pool::neu();
    unsafe {
        let eintraege = msg_id(b, sel(c"pasteboardItems"));
        if eintraege.is_null() {
            return None;
        }
        let anzahl = msg_int(eintraege, sel(c"count"));
        if anzahl <= 0 {
            return None;
        }
        // Verdeckte Inhalte (Passwoerter) bleiben auf diesem Rechner. Laesst
        // sich das Kennzeichen nicht einmal anlegen, wird nichts gelesen -
        // im Zweifel lieber keine Kopie als ein Passwort auf dem Host.
        let verdeckt = ns_text(VERDECKT);
        if verdeckt.is_null() {
            return None;
        }
        let mut pfade = Vec::new();
        let mut dateiverweise = 0usize;
        let mut unaufloesbar = false;
        for i in 0..anzahl as usize {
            let item = msg_id_u(eintraege, sel(c"objectAtIndex:"), i);
            if item.is_null() {
                continue;
            }
            if hat_typ(item, verdeckt) {
                waechter_zeile("Zwischenablage: Eintrag ist als verdeckt markiert, nicht uebertragen");
                return None;
            }
            if hat_typ(item, NSPasteboardTypeFileURL) {
                dateiverweise += 1;
                // Mehr Dateiverweise liest der Waechter nicht: mehr als
                // EINTRAEGE_MAX (Spezifikation 2.6) koennen ohnehin nicht
                // hinaus, einer darueber reicht dem Sender fuer "zu viele".
                if pfade.len() <= crate::dateien::EINTRAEGE_MAX as usize {
                    match dateiverweis(item) {
                        Some(p) => pfade.push(p),
                        None => unaufloesbar = true,
                    }
                }
            }
        }
        if dateiverweise > 0 {
            if unaufloesbar {
                waechter_zeile("Zwischenablage: Dateiverweis nicht aufloesbar, nichts uebertragen");
                return None;
            }
            return Some(Inhalt::Dateien(pfade));
        }

        if anzahl > 1 {
            waechter_zeile(&format!("Zwischenablage: {anzahl} Eintraege, nur der erste wird uebertragen"));
        }
        let item = msg_id(eintraege, sel(c"firstObject"));
        if item.is_null() {
            return None;
        }
        let s = msg_id_1(item, sel(c"stringForType:"), NSPasteboardTypeString);
        if s.is_null() {
            return None;
        }
        let len = msg_uint_1(s, sel(c"lengthOfBytesUsingEncoding:"), NS_UTF8);
        if len == 0 || len > MAX_BYTES {
            return None;
        }
        let p = msg_id(s, sel(c"UTF8String")) as *const u8;
        if p.is_null() {
            return None;
        }
        let bytes = std::slice::from_raw_parts(p, len);
        Some(Inhalt::Text(String::from_utf8_lossy(bytes).into_owned()))
    }
}

/// Text vom Brett zum Einfuegen in ein eigenes Feld (Adresse und Passwort,
/// Cmd+V). Anders als der Waechter liest es auch ohne Sitzung und auch
/// verdeckte Eintraege (etwa das Passwort, das der Mac-Host kopiert): der
/// Nutzer fuegt selbst ein, und der Text bleibt in diesem Programm - er
/// geht nicht zum Host. None: kein Text, zu gross oder kein AppKit.
pub fn text_einfuegen() -> Option<String> {
    let _pool = Pool::neu();
    let b = brett();
    if b.is_null() {
        return None;
    }
    unsafe {
        let s = msg_id_1(b, sel(c"stringForType:"), NSPasteboardTypeString);
        if s.is_null() {
            return None;
        }
        let len = msg_uint_1(s, sel(c"lengthOfBytesUsingEncoding:"), NS_UTF8);
        if len == 0 || len > MAX_BYTES {
            return None;
        }
        let p = msg_id(s, sel(c"UTF8String")) as *const u8;
        if p.is_null() {
            return None;
        }
        Some(String::from_utf8_lossy(std::slice::from_raw_parts(p, len)).into_owned())
    }
}

/// Der Pfad hinter dem Dateiverweis (public.file-url) eines Eintrags, ueber
/// datei_url. Der Pfad kommt aus `path`, also in der Schreibweise des
/// Verweises. Die kann Umlaute zerlegt (NFD) tragen - fileURLWithPath: legt
/// sie so an -, auch wenn der Name auf der Platte zusammengesetzt steht; auf
/// APFS meinen beide Schreibweisen dieselbe Datei. Nur innerhalb eines Pools
/// aufrufen.
unsafe fn dateiverweis(item: Id) -> Option<PathBuf> {
    let s = msg_id_1(item, sel(c"stringForType:"), NSPasteboardTypeFileURL);
    let url = datei_url(s)?;
    let pfad = msg_id(url, sel(c"path"));
    if pfad.is_null() {
        return None;
    }
    let p = msg_id(pfad, sel(c"UTF8String")) as *const c_char;
    if p.is_null() {
        return None;
    }
    let bytes = CStr::from_ptr(p).to_bytes();
    if !bytes.starts_with(b"/") {
        return None;
    }
    Some(PathBuf::from(OsString::from_vec(bytes.to_vec())))
}

/// Aus dem Text eines Dateiverweises ein Pfad-URL. Finder legt oft
/// Datei-Referenz-URLs ab (file:///.file/id=...); die werden ueber
/// filePathURL aufgeloest - das braucht die Datei, ein geloeschter Verweis
/// ergibt also None. Gewoehnliche Pfad-URLs werden nur umgeformt, ohne das
/// Dateisystem zu fragen. None auch, wenn es kein Datei-URL ist. Nur
/// innerhalb eines Pools aufrufen (autoreleased).
unsafe fn datei_url(text: Id) -> Option<Id> {
    let url_klasse = klasse(c"NSURL");
    if text.is_null() || url_klasse.is_null() {
        return None;
    }
    let mut url = msg_id_1(url_klasse, sel(c"URLWithString:"), text);
    if url.is_null() {
        return None;
    }
    if msg_bool(url, sel(c"isFileReferenceURL")) {
        url = msg_id(url, sel(c"filePathURL"));
        if url.is_null() {
            return None;
        }
    }
    if !msg_bool(url, sel(c"isFileURL")) {
        return None;
    }
    Some(url)
}

// ----------------------------------------------------------------- Schreiben

/// Schreibt Text auf das Brett, ohne die eigene Ueberwachung auszuloesen.
/// Scheitert still: ein verlorener Kopiervorgang ist hinnehmbar, ein Absturz
/// des Clients waehrend einer laufenden Sitzung nicht.
pub fn set(text: &str) {
    if text.len() > MAX_BYTES {
        return;
    }
    let _sperre = SPERRE.lock().unwrap_or_else(|e| e.into_inner());
    let b = brett();
    if b.is_null() {
        return;
    }
    if let Some(zaehler) = ablegen(b, text) {
        if let Ok(mut e) = EIGEN.lock() {
            *e = zaehler;
        }
    }
}

/// Legt `text` als einzigen Eintrag auf `b`: nur fuer diesen Mac, als
/// fluechtig und programmerzeugt gekennzeichnet (FLUECHTIG, AUTOGEN). Gibt
/// den changeCount nach dem Leeren und nach dem letzten Schreiben zurueck -
/// beide muss der Waechter als eigenen Vorgang erkennen.
fn ablegen(b: Id, text: &str) -> Option<(isize, isize)> {
    let _pool = Pool::neu();
    unsafe {
        // initWithBytes statt stringWithUTF8String: kein Abschneiden an
        // einem NUL im Text, und die Laenge steht fest.
        let s = ns_text_bytes(text.as_bytes());
        if s.is_null() {
            return None;
        }
        // Leeren wie clearContents, dazu "nur dieser Mac"; die Rueckgabe ist
        // wie dort der neue changeCount.
        let nach_leeren = msg_int_1(b, sel(c"prepareForNewContentsWithOptions:"), NUR_DIESER_MAC);
        let ok = msg_bool_2(b, sel(c"setString:forType:"), s, NSPasteboardTypeString);
        let _ = msg_id(s, sel(c"release"));
        // Die Kennzeichen an denselben (ersten) Eintrag, mit leerem Wert -
        // gezaehlt wird der Stand danach, damit auch dieser Schritt als
        // eigener Vorgang gilt.
        let leer = ns_text(c"");
        for kennzeichen in [FLUECHTIG, AUTOGEN] {
            let typ = ns_text(kennzeichen);
            if ok && !typ.is_null() && !leer.is_null() {
                let _ = msg_bool_2(b, sel(c"setString:forType:"), leer, typ);
            }
        }
        let nach_setzen = if ok { change_count(b) } else { nach_leeren };
        Some((nach_leeren, nach_setzen))
    }
}

/// Legt eine Dateiliste auf das allgemeine Brett, so dass "Einsetzen" im
/// Finder die Dateien kopiert - ohne die eigene Ueberwachung auszuloesen
/// (Zaehlung wie bei set()). Je Pfad ein Eintrag mit public.file-url, als
/// fluechtig und programmerzeugt gekennzeichnet, nur fuer diesen Mac.
/// `pfade` sind vollstaendige Pfade der obersten Eintraege; die Dateien
/// selbst werden hier nicht gelesen. true, wenn die Liste auf dem Brett
/// liegt; false bei leerer oder ungueltiger Liste (dann bleibt das Brett,
/// wie es ist) oder wenn das Schreiben scheitert. Aufrufer ist der
/// Empfaenger der Dateiuebertragung (dateien.rs) in seinem Schreibfaden;
/// `h` ist seine Rolle: in ihr Protokoll geht die Zeile, wenn das Schreiben
/// scheitert (wie unter Windows).
pub fn set_dateien(h: Herkunft, pfade: &[PathBuf]) -> bool {
    let _sperre = SPERRE.lock().unwrap_or_else(|e| e.into_inner());
    let b = brett();
    if b.is_null() {
        return false;
    }
    dateien_setzen(h, b, pfade)
}

/// set_dateien auf dem Brett `b`, mit der Zaehlung fuer den Widerhall.
fn dateien_setzen(h: Herkunft, b: Id, pfade: &[PathBuf]) -> bool {
    match dateien_ablegen(b, pfade) {
        Some((zaehler, ok)) => {
            if let Ok(mut e) = EIGEN.lock() {
                *e = zaehler;
            }
            if !ok {
                crate::protokoll::zeile_als(h, "Zwischenablage: Dateiliste nicht abgelegt (writeObjects: gescheitert)".into());
            }
            ok
        }
        None => false,
    }
}

/// Legt je Pfad einen NSPasteboardItem mit public.file-url (absoluteString
/// von fileURLWithPath:) und den Kennzeichen FLUECHTIG und AUTOGEN auf `b`,
/// vorher prepareForNewContentsWithOptions: "nur dieser Mac". Gibt die
/// Zaehler wie `ablegen` zurueck und ob writeObjects: gelang. None, wenn
/// schon das Bauen der Eintraege scheitert (leere Liste, relativer Pfad,
/// NUL, kein UTF-8) - dann ist das Brett unberuehrt.
fn dateien_ablegen(b: Id, pfade: &[PathBuf]) -> Option<((isize, isize), bool)> {
    if pfade.is_empty() {
        return None;
    }
    let _pool = Pool::neu();
    unsafe {
        let mut items: Vec<Id> = Vec::with_capacity(pfade.len());
        for p in pfade {
            match datei_eintrag(p) {
                Some(item) => items.push(item),
                None => {
                    for i in items {
                        let _ = msg_id(i, sel(c"release"));
                    }
                    return None;
                }
            }
        }
        let liste = ns_liste(&items);
        let geschrieben = if liste.is_null() {
            None
        } else {
            let nach_leeren = msg_int_1(b, sel(c"prepareForNewContentsWithOptions:"), NUR_DIESER_MAC);
            let ok = msg_bool_1(b, sel(c"writeObjects:"), liste);
            let nach_setzen = if ok { change_count(b) } else { nach_leeren };
            Some(((nach_leeren, nach_setzen), ok))
        };
        for i in items {
            let _ = msg_id(i, sel(c"release"));
        }
        geschrieben
    }
}

/// Ein Eintrag fuer `pfad`: public.file-url plus FLUECHTIG und AUTOGEN.
/// Eigene Zaehlung (alloc/init), der Aufrufer gibt ihn frei. Nur innerhalb
/// eines Pools aufrufen.
unsafe fn datei_eintrag(pfad: &PathBuf) -> Option<Id> {
    let bytes = pfad.as_os_str().as_bytes();
    if !pfad.is_absolute() || bytes.contains(&0) {
        return None;
    }
    let url_klasse = klasse(c"NSURL");
    let item_klasse = klasse(c"NSPasteboardItem");
    let leer = ns_text(c"");
    let fluechtig = ns_text(FLUECHTIG);
    let autogen = ns_text(AUTOGEN);
    if url_klasse.is_null() || item_klasse.is_null() || leer.is_null() || fluechtig.is_null() || autogen.is_null() {
        return None;
    }
    let s = ns_text_bytes(bytes);
    if s.is_null() {
        return None;
    }
    // fileURLWithPath: fragt das Dateisystem, ob es ein Ordner ist, und
    // haengt dann den Schraegstrich an - so erkennt Finder Ordner.
    let url = msg_id_1(url_klasse, sel(c"fileURLWithPath:"), s);
    let _ = msg_id(s, sel(c"release"));
    if url.is_null() {
        return None;
    }
    let text = msg_id(url, sel(c"absoluteString"));
    if text.is_null() {
        return None;
    }
    let item = msg_id(msg_id(item_klasse, sel(c"alloc")), sel(c"init"));
    if item.is_null() {
        return None;
    }
    let setzen = sel(c"setString:forType:");
    if !msg_bool_2(item, setzen, text, NSPasteboardTypeFileURL)
        || !msg_bool_2(item, setzen, leer, fluechtig)
        || !msg_bool_2(item, setzen, leer, autogen)
    {
        let _ = msg_id(item, sel(c"release"));
        return None;
    }
    Some(item)
}

/// Stammt dieser changeCount von unserem eigenen set()?
fn eigener_vorgang(count: isize) -> bool {
    EIGEN
        .lock()
        .map(|e| count == e.0 || count == e.1)
        .unwrap_or(false)
}

// -------------------------------------------------------------- Ueberwachung

/// Ein Blick des Waechters auf `b`: hat sich der changeCount seit `zuletzt`
/// bewegt, und stammt die Aenderung nicht von uns, wird gelesen - aber nur
/// mit laufender Sitzung. Ohne sie wird nur mitgezaehlt; eine Aenderung von
/// vorher holt auch der Sitzungsbeginn nicht nach.
fn nachsehen(b: Id, zuletzt: &mut isize, sitzung: bool, lesen: impl FnOnce(Id) -> Option<Inhalt>) -> Option<Inhalt> {
    let jetzt = change_count(b);
    if jetzt == *zuletzt {
        return None;
    }
    *zuletzt = jetzt;
    if eigener_vorgang(jetzt) || !sitzung {
        return None; // unser eigener Schreibvorgang, oder niemand zum Senden
    }
    lesen(b)
}

/// Was der Waechter zwischen zwei Blicken weiss.
struct Wache {
    /// changeCount beim letzten Blick - bewegt er sich, beginnt die Ruhe neu.
    gesehen: isize,
    /// changeCount, ueber den nachsehen() zuletzt entschieden hat.
    zuletzt: isize,
    ruhe: Entpreller,
}

impl Wache {
    fn neu(b: Id) -> Wache {
        let c = change_count(b);
        Wache { gesehen: c, zuletzt: c, ruhe: Entpreller::neu(RUHE) }
    }

    /// Ein Blick auf `b` zur Zeit `jetzt`: hat sich der changeCount bewegt,
    /// beginnt die Ruhe (neu); ist sie um, wird einmal nachgesehen (nachsehen:
    /// nur mit Gegenueber - `sitzung`: irgendeine Rolle hat eines -, nie der
    /// eigene Vorgang). Eine Aenderung ohne Gegenueber wird nur mitgezaehlt -
    /// auch dann, wenn die Sitzung waehrend der Ruhe beginnt. Entdoppelt wird
    /// danach beim Verteilen, je Rolle. Unter SPERRE aufrufen.
    fn blick(&mut self, b: Id, jetzt: Instant, sitzung: bool, lesen: impl FnOnce(Id) -> Option<Inhalt>) -> Option<Inhalt> {
        let c = change_count(b);
        if c != self.gesehen {
            self.gesehen = c;
            if sitzung {
                self.ruhe.aenderung(jetzt);
            } else {
                self.zuletzt = c;
                self.ruhe.verwerfen();
            }
            return None;
        }
        if !self.ruhe.faellig(jetzt) {
            return None;
        }
        nachsehen(b, &mut self.zuletzt, sitzung, lesen).filter(|i| !i.leer())
    }
}

/// Was der Waechter las, an die Rollen (ablage_ruhe::Verteiler); eine
/// Dateiliste, die eine Rolle gerade eben schon bekam, steht nur in ihrem
/// Protokoll.
fn verteilen(v: &Verteiler, inhalt: &Inhalt, jetzt: Instant) {
    for (h, verteilt) in v.verteilen(inhalt, jetzt) {
        if verteilt == Verteilt::Doppelt {
            crate::protokoll::zeile_als(h, "Zwischenablage: dieselbe Dateiliste noch einmal gemeldet - uebergangen".into());
        }
    }
}

/// Meldet die Rolle `h` beim Waechter an und startet ihn beim ersten Mal in
/// einem eigenen Faden (einer fuer alle Rollen; eine zweite Anmeldung
/// derselben Rolle ersetzt die erste). `gegenueber` sagt, ob die Rolle
/// gerade ein Gegenueber hat und in welcher Sitzung (der Client nimmt
/// client_gegenueber). `cb` bekommt jeden Text und jede Dateiliste, die der
/// Benutzer auf dem Mac kopiert, solange diese Rolle ein Gegenueber hat;
/// eigene Schreibvorgaenge aus `set` und `set_dateien` sind bereits
/// herausgefiltert. Was beim Start oder ohne Gegenueber auf das Brett kam,
/// wird nicht gemeldet - wie auf Windows, wo erst die naechste Aenderung in
/// einer Sitzung zaehlt. Gemeldet wird erst, wenn das Brett RUHE lang ruhig
/// war (Wache::blick), und dieselbe Dateiliste je Rolle nur einmal
/// (ablage_ruhe::Verteiler). Beide Rueckrufe laufen ausserhalb der Sperre im
/// Faden des Waechters.
pub fn watch(
    h: Herkunft,
    gegenueber: impl Fn() -> Option<u64> + Send + Sync + 'static,
    cb: impl Fn(Inhalt) + Send + Sync + 'static,
) {
    VERTEILER.anmelden(h, Arc::new(gegenueber), Arc::new(cb));
    WAECHTER.call_once(|| {
        std::thread::spawn(|| {
            let b = brett();
            if b.is_null() {
                eprintln!("Zwischenablage: Ueberwachung nicht gestartet: NSPasteboard fehlt");
                return;
            }
            let mut wache = Wache::neu(b);
            loop {
                // Im Takt - aber nicht laenger als bis zum Ende der Ruhe.
                std::thread::sleep(wache.ruhe.schlaf(Instant::now(), TAKT));
                // Wer ein Gegenueber hat, fragt der Verteiler vor der Sperre -
                // die Rueckrufe der Rollen laufen nie unter ihr.
                let da = VERTEILER.jemand_da();
                let inhalt = {
                    let _sperre = SPERRE.lock().unwrap_or_else(|e| e.into_inner());
                    wache.blick(b, Instant::now(), da, lesen)
                };
                if let Some(i) = inhalt {
                    verteilen(&VERTEILER, &i, Instant::now());
                }
            }
        });
    });
}

// --------------------------------------------------------------------- Tests

#[cfg(test)]
mod tests {
    use super::*;

    /// Ein eigenes, namenloses Brett - nie das allgemeine. Am Ende des Tests
    /// mit releaseGlobally wieder freigeben.
    unsafe fn eigenes_brett() -> Id {
        let b = msg_id(klasse(c"NSPasteboard"), sel(c"pasteboardWithUniqueName"));
        assert!(!b.is_null(), "kein eigenes Brett");
        b
    }

    /// Spielt den Benutzer: legt je Eintrag die Paare (Typ, Wert) in EINEM
    /// writeObjects: auf `b`, an set()/set_dateien() und ihrer Zaehlung
    /// vorbei.
    unsafe fn nutzer_kopiert(b: Id, eintraege: &[Vec<(Id, Id)>]) {
        let mut items: Vec<Id> = Vec::new();
        for paare in eintraege {
            let item = msg_id(msg_id(klasse(c"NSPasteboardItem"), sel(c"alloc")), sel(c"init"));
            for (typ, wert) in paare {
                assert!(msg_bool_2(item, sel(c"setString:forType:"), *wert, *typ));
            }
            items.push(item);
        }
        let liste = ns_liste(&items);
        let _ = msg_int(b, sel(c"clearContents"));
        assert!(msg_bool_1(b, sel(c"writeObjects:"), liste), "writeObjects: scheitert");
        for i in items {
            let _ = msg_id(i, sel(c"release"));
        }
    }

    /// NSString aus einem &str (autoreleased ueber den Pool des Tests).
    unsafe fn ns(s: &str) -> Id {
        let t = ns_text_bytes(s.as_bytes());
        assert!(!t.is_null());
        msg_id(t, sel(c"autorelease"))
    }

    /// absoluteString von fileURLWithPath: - so legt set_dateien ab und so
    /// sieht ein gewoehnlicher Finder-Verweis aus.
    unsafe fn url_text(p: &PathBuf) -> Id {
        let url = msg_id_1(klasse(c"NSURL"), sel(c"fileURLWithPath:"), ns(p.to_str().unwrap()));
        assert!(!url.is_null());
        msg_id(url, sel(c"absoluteString"))
    }

    /// Meldet `inhalt` dieselben Dateien wie `pfade`, in derselben
    /// Reihenfolge? Verglichen ueber Geraet und Inode: fileURLWithPath: legt
    /// Umlaute zerlegt (NFD) ab, die Testdateien stehen zusammengesetzt auf
    /// der Platte - auf APFS dieselbe Datei.
    fn gleiche_dateien(inhalt: &Option<Inhalt>, pfade: &[PathBuf]) -> bool {
        use std::os::unix::fs::MetadataExt;
        let Some(Inhalt::Dateien(gelesen)) = inhalt else {
            return false;
        };
        let kennung = |p: &PathBuf| std::fs::symlink_metadata(p).map(|m| (m.dev(), m.ino())).ok();
        gelesen.len() == pfade.len()
            && gelesen.iter().zip(pfade).all(|(g, p)| kennung(g).is_some() && kennung(g) == kennung(p))
    }

    unsafe fn rust_text(s: Id) -> String {
        assert!(!s.is_null());
        CStr::from_ptr(msg_id(s, sel(c"UTF8String")) as *const c_char).to_string_lossy().into_owned()
    }

    /// Echte Testdateien unter temp_dir ($TMPDIR), eigener Ordner je Lauf
    /// und Test: eine Datei, ein Ordner mit Leerzeichen, eine Datei mit
    /// Umlauten.
    fn testdateien(name: &str) -> (PathBuf, Vec<PathBuf>) {
        let ordner = std::env::temp_dir().join(format!("qc-test-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&ordner);
        let unter = ordner.join("Unterordner mit Leerzeichen");
        std::fs::create_dir_all(&unter).expect("Testordner");
        let a = ordner.join("a.txt");
        std::fs::write(&a, b"hallo").expect("Testdatei");
        let b = ordner.join("\u{e4}\u{f6}\u{fc} \u{20ac}.bin");
        std::fs::write(&b, [0u8, 1, 2]).expect("Testdatei");
        (ordner, vec![a, unter, b])
    }

    /// Setzen laesst den changeCount steigen, Lesen liefert denselben Text,
    /// und der neue Zaehler gilt als eigener Vorgang. Der vorherige Inhalt
    /// des Bretts wird danach zurueckgelegt. ACHTUNG: arbeitet auf dem
    /// allgemeinen Brett und faellt deshalb unter --skip clipboard.
    #[test]
    fn setzen_zaehlen_lesen() {
        let b = brett();
        assert!(!b.is_null(), "NSPasteboard fehlt");
        let vorher = match lesen(b) {
            Some(Inhalt::Text(t)) => Some(t),
            _ => None,
        };
        let c0 = change_count(b);

        let probe = "QuadChroma Probe: Zwischenablage \u{e4}\u{f6}\u{fc} \u{1F600}\nzweite Zeile";
        set(probe);
        let c1 = change_count(b);
        assert!(c1 > c0, "changeCount steigt nicht: {c0} -> {c1}");
        assert!(eigener_vorgang(c1), "eigener Vorgang nicht erkannt");
        assert_eq!(lesen(b), Some(Inhalt::Text(probe.into())));

        // Zweites Setzen: wieder ein Schritt weiter, alte Zahl gilt nicht mehr.
        set("zweite Probe");
        let c2 = change_count(b);
        assert!(c2 > c1);
        assert!(eigener_vorgang(c2));
        assert!(!eigener_vorgang(c1));
        assert_eq!(lesen(b), Some(Inhalt::Text("zweite Probe".into())));

        if let Some(v) = vorher {
            set(&v);
        }
    }

    /// Dieselbe Leseregel wie auf dem Mac-Host: ein verdeckter Eintrag geht
    /// nicht hinaus, von mehreren Texteintraegen zaehlt nur der erste, und
    /// ein Eintrag mit Dateiverweis geht als Dateiliste, nicht als Text.
    /// Geschrieben wird auf ein eigenes, namenloses Brett - die allgemeine
    /// Zwischenablage (und damit ein laufender Host) bekommt davon nichts mit.
    #[test]
    fn verdeckt_bleibt_hier() {
        let _pool = Pool::neu();
        unsafe {
            let b = eigenes_brett();
            let text = NSPasteboardTypeString;
            let verdeckt = ns_text(VERDECKT);
            let datei = NSPasteboardTypeFileURL;

            nutzer_kopiert(b, &[vec![(text, ns("geheim123")), (verdeckt, ns(""))]]);
            assert_eq!(lesen(b), None, "verdeckter Eintrag wurde gelesen");

            nutzer_kopiert(b, &[vec![(text, ns("offen"))]]);
            assert_eq!(lesen(b), Some(Inhalt::Text("offen".into())));

            nutzer_kopiert(b, &[vec![(text, ns("eins"))], vec![(text, ns("zwei"))]]);
            assert_eq!(lesen(b), Some(Inhalt::Text("eins".into())));

            // Nur der Verweis wird umgeformt, die Datei nicht angefasst.
            nutzer_kopiert(b, &[vec![(text, ns("probe.txt")), (datei, ns("file:///tmp/probe.txt"))]]);
            assert_eq!(
                lesen(b),
                Some(Inhalt::Dateien(vec![PathBuf::from("/tmp/probe.txt")])),
                "Datei als Text gelesen"
            );

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
    }

    /// Ohne Sitzung zaehlt der Waechter nur mit und liest nichts - auch beim
    /// Sitzungsbeginn nicht nachtraeglich. Eine neue Kopie in der Sitzung
    /// wird gelesen. Eigenes, namenloses Brett.
    #[test]
    fn ohne_sitzung_wird_nicht_gelesen() {
        let _pool = Pool::neu();
        unsafe {
            let b = eigenes_brett();
            let mut zuletzt = change_count(b);
            let gelesen = std::cell::Cell::new(0);
            let zaehlend = |b: Id| {
                gelesen.set(gelesen.get() + 1);
                lesen(b)
            };

            assert!(ablegen(b, "kopiert ohne Sitzung").is_some());
            assert_eq!(nachsehen(b, &mut zuletzt, false, zaehlend), None);
            assert_eq!(gelesen.get(), 0, "ohne Sitzung gelesen");
            assert_eq!(zuletzt, change_count(b), "Aenderung nicht mitgezaehlt");

            // Die Sitzung beginnt: die Kopie von vorher bleibt hier.
            assert_eq!(nachsehen(b, &mut zuletzt, true, zaehlend), None);
            assert_eq!(gelesen.get(), 0, "alte Kopie beim Sitzungsbeginn gelesen");

            assert!(ablegen(b, "kopiert in der Sitzung").is_some());
            assert_eq!(
                nachsehen(b, &mut zuletzt, true, zaehlend),
                Some(Inhalt::Text("kopiert in der Sitzung".into()))
            );
            assert_eq!(gelesen.get(), 1);

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
    }

    /// Was vom Host kommt, liegt als ein Eintrag mit Text und den
    /// Kennzeichen FLUECHTIG und AUTOGEN auf dem Brett; der zurueckgegebene
    /// Zaehler ist der Stand nach dem letzten Schreiben (sonst erkennte der
    /// Waechter den eigenen Vorgang nicht). Der Lesefilter nimmt fluechtige
    /// Eintraege weiter an - fluechtig heisst nicht verdeckt. UNGEPRUEFT:
    /// "nur dieser Mac" (NUR_DIESER_MAC) zeigt die Typliste nicht.
    #[test]
    fn vom_host_fluechtig() {
        let _pool = Pool::neu();
        unsafe {
            let b = eigenes_brett();
            let (nach_leeren, nach_setzen) = ablegen(b, "von drueben").expect("ablegen");
            assert_eq!(nach_setzen, change_count(b));
            assert!(nach_setzen >= nach_leeren);
            let eintraege = msg_id(b, sel(c"pasteboardItems"));
            assert_eq!(msg_int(eintraege, sel(c"count")), 1);
            let item = msg_id(eintraege, sel(c"firstObject"));
            assert!(hat_typ(item, ns_text(FLUECHTIG)), "Kennzeichen fehlt");
            assert!(hat_typ(item, ns_text(AUTOGEN)), "Kennzeichen AUTOGEN fehlt");
            assert!(hat_typ(item, NSPasteboardTypeString));
            assert_eq!(lesen(b), Some(Inhalt::Text("von drueben".into())));
            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
    }

    /// set_dateien auf einem eigenen Brett: je Pfad ein Eintrag mit
    /// public.file-url (absoluteString von fileURLWithPath:) und beiden
    /// Kennzeichen, der Zaehler steht nach dem letzten Schreiben, und lesen()
    /// liefert genau die Pfade zurueck. Nur Dateien unter $TMPDIR.
    #[test]
    fn dateien_vom_host_ablegen() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("dateien_vom_host_ablegen");
        unsafe {
            let b = eigenes_brett();
            let ((nach_leeren, nach_setzen), ok) = dateien_ablegen(b, &pfade).expect("dateien_ablegen");
            assert!(ok, "writeObjects: scheitert");
            assert_eq!(nach_setzen, change_count(b));
            assert!(nach_setzen >= nach_leeren);

            let eintraege = msg_id(b, sel(c"pasteboardItems"));
            assert_eq!(msg_int(eintraege, sel(c"count")), pfade.len() as isize, "ein Eintrag je Pfad");
            for (i, p) in pfade.iter().enumerate() {
                let item = msg_id_u(eintraege, sel(c"objectAtIndex:"), i);
                let wert = msg_id_1(item, sel(c"stringForType:"), NSPasteboardTypeFileURL);
                assert_eq!(rust_text(wert), rust_text(url_text(p)), "Verweis {i}");
                assert!(hat_typ(item, ns_text(FLUECHTIG)), "FLUECHTIG fehlt an Eintrag {i}");
                assert!(hat_typ(item, ns_text(AUTOGEN)), "AUTOGEN fehlt an Eintrag {i}");
            }
            // Der Ordner traegt den Schraegstrich, so erkennt Finder ihn.
            assert!(rust_text(url_text(&pfade[1])).ends_with('/'));
            let gelesen = lesen(b);
            assert!(gleiche_dateien(&gelesen, &pfade), "andere Dateien gelesen: {gelesen:?}");

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Was set_dateien ablegt, meldet der Waechter nicht zurueck (Zaehlung
    /// wie bei Text); eine Kopie des Benutzers danach schon.
    #[test]
    fn dateien_ohne_widerhall() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("dateien_ohne_widerhall");
        unsafe {
            let b = eigenes_brett();
            let mut zuletzt = change_count(b);
            let gelesen = std::cell::Cell::new(0);
            let zaehlend = |b: Id| {
                gelesen.set(gelesen.get() + 1);
                lesen(b)
            };

            assert!(dateien_setzen(Herkunft::Client, b, &pfade), "dateien_setzen scheitert");
            assert_eq!(nachsehen(b, &mut zuletzt, true, zaehlend), None, "eigene Dateiliste zurueckgemeldet");
            assert_eq!(gelesen.get(), 0, "eigene Dateiliste gelesen");

            nutzer_kopiert(b, &[vec![(NSPasteboardTypeFileURL, url_text(&pfade[0]))]]);
            assert_eq!(nachsehen(b, &mut zuletzt, true, zaehlend), Some(Inhalt::Dateien(vec![pfade[0].clone()])));
            assert_eq!(gelesen.get(), 1);

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Der Waechter entprellt und entdoppelt (Integrationstest, Befunde 1
    /// und 2), auf einem eigenen Brett und mit vorgegebener Zeit: zwei
    /// Kopien dicht hintereinander ergeben EIN Lesen, erst RUHE nach der
    /// letzten; dieselbe Dateiliste gleich danach noch einmal geht nicht
    /// hinaus, nach einem Text oder nach DOPPEL_FRIST schon. Eine Kopie ohne
    /// Sitzung wird nie gelesen, auch wenn die Sitzung waehrend der Ruhe
    /// beginnt. Gemeldet wird ueber einen eigenen Verteiler mit dem Client
    /// als einziger Rolle - wie im Betrieb (watch).
    #[test]
    fn waechter_entprellt_und_entdoppelt() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("waechter_entprellt");
        unsafe {
            let b = eigenes_brett();
            let mut w = Wache::neu(b);
            let t0 = Instant::now();
            let ms = |n: u64| t0 + Duration::from_millis(n);
            let gelesen = std::cell::Cell::new(0);
            let zaehlend = |b: Id| {
                gelesen.set(gelesen.get() + 1);
                lesen(b)
            };
            let dateien = |p: &[PathBuf]| -> Vec<Vec<(Id, Id)>> {
                p.iter().map(|p| vec![(NSPasteboardTypeFileURL, url_text(p))]).collect()
            };
            let alle = dateien(&pfade);
            let v = Verteiler::neu();
            let nummer = Arc::new(AtomicU64::new(1));
            let gemeldet = Arc::new(Mutex::new(Vec::<Inhalt>::new()));
            let (n2, g2) = (nummer.clone(), gemeldet.clone());
            v.anmelden(
                Herkunft::Client,
                Arc::new(move || Some(n2.load(Ordering::SeqCst))),
                Arc::new(move |i| g2.lock().unwrap().push(i)),
            );
            // Ein Blick des Waechters mit Sitzung `an` (Nummer `nr`); was er
            // liest, geht an den Verteiler, und was dort gemeldet wurde, kommt
            // zurueck.
            let schau = |w: &mut Wache, t: Instant, an: bool, nr: u64| -> Option<Inhalt> {
                nummer.store(nr, Ordering::SeqCst);
                let roh = w.blick(b, t, an, &zaehlend)?;
                verteilen(&v, &roh, t);
                gemeldet.lock().unwrap().pop()
            };

            // Zwei Meldungen derselben Kopie, 100 ms auseinander.
            nutzer_kopiert(b, &alle);
            assert_eq!(schau(&mut w, ms(0), true, 1), None);
            nutzer_kopiert(b, &alle);
            assert_eq!(schau(&mut w, ms(100), true, 1), None);
            assert_eq!(schau(&mut w, ms(200), true, 1), None, "vor der Ruhe gelesen");
            assert_eq!(gelesen.get(), 0);
            let r = schau(&mut w, ms(250), true, 1);
            assert!(gleiche_dateien(&r, &pfade), "nach der Ruhe nicht gemeldet: {r:?}");
            assert_eq!(schau(&mut w, ms(400), true, 1), None, "zweimal gemeldet");
            assert_eq!(gelesen.get(), 1);

            // Dieselbe Liste noch einmal (neuer changeCount): gelesen, aber
            // innerhalb der Frist nicht gemeldet.
            nutzer_kopiert(b, &alle);
            assert_eq!(schau(&mut w, ms(500), true, 1), None);
            assert_eq!(schau(&mut w, ms(650), true, 1), None, "dieselbe Liste doppelt gemeldet");
            assert_eq!(gelesen.get(), 2);
            // Ein Text dazwischen: danach ist dieselbe Liste eine neue Kopie.
            nutzer_kopiert(b, &[vec![(NSPasteboardTypeString, ns("Text"))]]);
            assert_eq!(schau(&mut w, ms(700), true, 1), None);
            assert_eq!(schau(&mut w, ms(850), true, 1), Some(Inhalt::Text("Text".into())));
            nutzer_kopiert(b, &alle);
            assert_eq!(schau(&mut w, ms(900), true, 1), None);
            assert!(gleiche_dateien(&schau(&mut w, ms(1050), true, 1), &pfade));
            // Nach der Frist ebenso.
            nutzer_kopiert(b, &alle);
            assert_eq!(schau(&mut w, ms(3100), true, 1), None);
            assert!(gleiche_dateien(&schau(&mut w, ms(3250), true, 1), &pfade));

            // Ohne Sitzung kopiert, Sitzung beginnt waehrend der Ruhe: nie gelesen.
            let vorher = gelesen.get();
            nutzer_kopiert(b, &dateien(&pfade[..1]));
            assert_eq!(schau(&mut w, ms(4000), false, 1), None);
            assert_eq!(schau(&mut w, ms(4100), true, 2), None);
            assert_eq!(schau(&mut w, ms(4500), true, 2), None);
            assert_eq!(gelesen.get(), vorher, "Kopie ohne Sitzung gelesen");

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Wie Finder: mehrere Dateien, je Datei ein Eintrag mit Namen als Text
    /// und dem Verweis. Gemeldet werden alle Pfade und kein Text.
    #[test]
    fn dateien_alle_eintraege() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("dateien_alle_eintraege");
        unsafe {
            let b = eigenes_brett();
            let eintraege: Vec<Vec<(Id, Id)>> = pfade
                .iter()
                .map(|p| {
                    let name = p.file_name().unwrap().to_str().unwrap();
                    vec![(NSPasteboardTypeString, ns(name)), (NSPasteboardTypeFileURL, url_text(p))]
                })
                .collect();
            nutzer_kopiert(b, &eintraege);
            let gelesen = lesen(b);
            assert!(gleiche_dateien(&gelesen, &pfade), "andere Dateien gelesen: {gelesen:?}");

            // Ein Texteintrag vorn aendert nichts: Dateien gehen vor.
            let mut gemischt = vec![vec![(NSPasteboardTypeString, ns("nur Text"))]];
            gemischt.extend(eintraege);
            nutzer_kopiert(b, &gemischt);
            let gelesen = lesen(b);
            assert!(gleiche_dateien(&gelesen, &pfade), "andere Dateien gelesen: {gelesen:?}");

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Finder legt oft Datei-Referenz-URLs ab (file:///.file/id=...): die
    /// werden ueber filePathURL zum Pfad aufgeloest.
    #[test]
    fn dateien_referenz_aufgeloest() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("dateien_referenz_aufgeloest");
        unsafe {
            let b = eigenes_brett();
            let url = msg_id_1(klasse(c"NSURL"), sel(c"fileURLWithPath:"), ns(pfade[0].to_str().unwrap()));
            let referenz = msg_id(url, sel(c"fileReferenceURL"));
            assert!(!referenz.is_null(), "keine Referenz-URL");
            let referenz = msg_id(referenz, sel(c"absoluteString"));
            assert!(rust_text(referenz).starts_with("file:///.file/id="), "{}", rust_text(referenz));
            nutzer_kopiert(b, &[vec![(NSPasteboardTypeFileURL, referenz)]]);

            // Auch der unaufgeloeste Verweis (/.file/id=...) oeffnet dieselbe
            // Datei - als Pfad taugt er trotzdem nicht: sein Name waere
            // "id=...", und der geht als Dateiname hinaus. Also auch den
            // Namen pruefen.
            let gelesen = lesen(b);
            assert!(gleiche_dateien(&gelesen, &pfade[..1]), "Referenz falsch aufgeloest: {gelesen:?}");
            let Some(Inhalt::Dateien(liste)) = &gelesen else { unreachable!() };
            assert!(!liste[0].starts_with("/.file"), "Referenz nicht aufgeloest: {:?}", liste[0]);
            assert_eq!(liste[0].file_name(), pfade[0].file_name(), "Name nicht aus dem Pfad");
            // `path` loest eine Referenz zwar selbst auf; datei_url liefert
            // aber schon den Pfad-URL (filePathURL), wie ihn jeder weitere
            // Schritt erwartet.
            let aufgeloest = datei_url(referenz).expect("Referenz nicht aufloesbar");
            let aufgeloest = rust_text(msg_id(aufgeloest, sel(c"absoluteString")));
            assert!(
                aufgeloest.starts_with("file:///") && !aufgeloest.starts_with("file:///.file/"),
                "kein Pfad-URL: {aufgeloest}"
            );

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Ein verdecktes Kennzeichen an irgendeinem Eintrag haelt die ganze
    /// Dateiliste zurueck - auch am zweiten.
    #[test]
    fn dateien_verdeckt_bleibt_hier() {
        let _pool = Pool::neu();
        let (ordner, pfade) = testdateien("dateien_verdeckt_bleibt_hier");
        unsafe {
            let b = eigenes_brett();
            let verdeckt = ns_text(VERDECKT);
            let datei = NSPasteboardTypeFileURL;

            nutzer_kopiert(b, &[vec![(datei, url_text(&pfade[0])), (verdeckt, ns(""))]]);
            assert_eq!(lesen(b), None, "verdeckte Datei (erster Eintrag) gelesen");

            nutzer_kopiert(
                b,
                &[vec![(datei, url_text(&pfade[0]))], vec![(datei, url_text(&pfade[2])), (verdeckt, ns(""))]],
            );
            assert_eq!(lesen(b), None, "verdeckte Datei (zweiter Eintrag) gelesen");

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
        let _ = std::fs::remove_dir_all(ordner);
    }

    /// Ungueltiges: eine leere oder relative Liste laesst das Brett, wie es
    /// ist; ein Verweis, der sich nicht aufloesen laesst oder keine Datei
    /// meint, ergibt nichts - weder Dateien noch Text.
    #[test]
    fn dateien_ungueltig() {
        let _pool = Pool::neu();
        unsafe {
            let b = eigenes_brett();
            nutzer_kopiert(b, &[vec![(NSPasteboardTypeString, ns("bleibt"))]]);
            let vorher = change_count(b);
            assert!(!dateien_setzen(Herkunft::Client, b, &[]));
            assert!(!dateien_setzen(Herkunft::Client, b, &[PathBuf::from("relativ/a.txt")]));
            assert!(!dateien_setzen(Herkunft::Client, b, &[PathBuf::from("/tmp/a\u{0}b")]));
            assert_eq!(change_count(b), vorher, "ungueltige Liste hat das Brett angefasst");
            assert_eq!(lesen(b), Some(Inhalt::Text("bleibt".into())));

            for verweis in ["file:///.file/id=1.1", "https://example.org/a.txt"] {
                nutzer_kopiert(b, &[vec![(NSPasteboardTypeString, ns("a.txt")), (NSPasteboardTypeFileURL, ns(verweis))]]);
                assert_eq!(lesen(b), None, "Verweis {verweis} ergab etwas");
            }

            let _ = msg_id(b, sel(c"releaseGlobally"));
        }
    }
}
