// Sprachtabellen ausserhalb Europas plus Tuerkisch:
// Russisch (ru), Chinesisch vereinfacht (zh), Japanisch (ja), Tuerkisch (tr).
//
// Aufbau und Schluessel wie in strings.rs. Jede Tabelle enthaelt jeden
// Schluessel genau einmal.

use crate::strings::{Key::*, Lang};

pub static RU: Lang = Lang {
    code: "ru",
    name: "Русский",
    table: &[
        (AppSubtitle, "Удалённый рабочий стол с полной цветопередачей"),
        (Connect, "Подключиться"),
        (Disconnect, "Отключиться"),
        (HostAddress, "Адрес хоста"),
        (SearchingHosts, "Поиск хостов"),
        (NoHostsFound, "Хосты не найдены"),
        (FoundHosts, "Найденные хосты"),
        (Settings, "Настройки"),
        (Language, "Язык"),
        (Quit, "Выход"),
        (Connecting, "Подключение"),
        (Connected, "Подключено"),
        (ConnectionLost, "Соединение потеряно"),
        (Reconnecting, "Переподключение"),
        (Fullscreen, "Полный экран"),
        (PixelExact, "Пиксель в пиксель"),
        (Stretch, "По размеру окна"),
        (ShowOverlay, "Показывать статистику"),
        (Fps, "Кадров в секунду"),
        (DecodeTime, "Время декодирования"),
        (Bitrate, "Битрейт"),
        (Resolution, "Разрешение"),
        (Codec, "Кодек"),
        (Latency, "Задержка"),
        (EncodeTime, "Время кодирования"),
        (NetworkTime, "Время передачи"),
        (AudioBuffer, "Буфер звука"),
        (Dropped, "Потеряно"),
        (MaxBitrate, "Макс. битрейт"),
        (MaxFps, "Макс. частота кадров"),
        (ExpertMode, "Экспертный режим"),
        (GamingMode, "Игровой режим"),
        (FixedRate, "Постоянная частота кадров"),
        (FixedRateHint, "Удерживает частоту кадров, даже когда ничего не движется. Постоянная нагрузка на хост."),
        (Sound, "Звук"),
        (HoldEscHint, "Удерживайте ESC для меню"),
        (NerdMode, "Режим гика"),
        (More, "Ещё"),
        (Back, "Назад"),
        (SavedForHost, "Сохранено для этого хоста"),
        (Queue, "Захват и очередь"),
        (OneFrame, "Один кадр"),
        (Bottleneck, "Узкое место"),
        (TabPicture, "Изображение"),
        (TabDisplay, "Экран"),
        (CodecConverted, "с конвертацией"),
        (CodecSwitching, "Смена кодека"),
        (HostCpu, "Процессор хоста"),
        (HostGpu, "Графика хоста"),
        (HostRam, "Память хоста"),
        (NoDisplay, "У хоста сейчас нет экрана"),
        (Encryption, "Шифрование"),
        (EncryptionOn, "вкл."),
        (EncryptionOff, "выкл."),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Буфер обмена"),
        (DecoderLabel, "Декодер"),
        (DecoderAuto, "Автоматически"),
        (DecoderSoftware, "Программный"),
        (DecoderNvidia, "Видеокарта"),
        (DisplayLabel, "Экран"),
        (DisplayStage, "Экран"),
        (ClientCpu, "Процессор клиента"),
        (Monitor, "Монитор"),
        (Skipped, "пропущено"),
        (PairingTitle, "Сопряжение с хостом"),
        (PairingHint, "Введите код, показанный на хосте"),
        (PairingCode, "Код сопряжения"),
        (PairingWrong, "Неверный код"),
        (PairingOk, "Сопряжено"),
        (SecuredWith, "Защищено · код подтверждения"),
        (HostFingerprint, "Отпечаток ключа хоста"),
        (NotPaired, "Этот хост ещё не знает ваше устройство. Запустите хост с ключом --pair и подключитесь снова."),
        (FirstContact, "Первый контакт с этим хостом. Сравните код с тем, что показан на хосте."),
        (ErrorConnectRefused, "Хост отклонил подключение"),
        (ErrorTimeout, "Хост не отвечает"),
        (ErrorProtocol, "Хост использует другой протокол"),
        (ErrorNoDecoder, "Нет декодера для этого формата"),
        (TipBitrate, "Верхняя граница битрейта. При движении кодер использует её полностью; в чужих сетях лучше 25–50."),
        (TipFps, "Целевая частота кадров. Больше, чем даёт экран Mac, не получится."),
        (TipGaming, "Чаще ключевые кадры и меньше допустимого отставания: ровнее при движении, стоит немного битрейта."),
        (TipSound, "Передавать звук. Выкл. экономит около 3 Мбит/с; хост тогда звук не отправляет."),
        (TipCodec, "Кодек хоста, переключается на ходу; картинка на миг замирает. \"с конвертацией\" стоит один лишний проход."),
        (TipFullscreen, "Полный экран без рамки. В окне картинка вписывается."),
        (TipPixelExact, "Картинка 1:1 без масштабирования. Если окно меньше, видна только часть."),
        (TipShowOverlay, "Показывать статистику слева вверху. Какие строки – справа."),
        (TipNerdMode, "Расширенная статистика: цепочка задержки в виде полосы, нагрузка хоста и клиента."),
        (TipStatRows, "Какие строки показывает статистика."),
        (TipDecoderAuto, "Видеокарта, если она поддерживает кодек, иначе программно."),
        (TipDecoderSoftware, "Декодирование на процессоре. Работает везде, стоит процессорного времени."),
        (TipDecoderGpu, "Декодирование на видеокарте. Если не выходит, клиент возвращается к программному и говорит почему."),
        (TipDisconnect, "Завершить соединение, назад на начальный экран."),
        (TabShortcuts, "Клавиши"),
        (ShortcutMenu, "Открыть меню (этот ESC никогда не доходит до Mac)"),
        (ShortcutBack, "Назад на начальный экран"),
        (ShortcutWinKey, "Клавиша Windows = клавиша Command на Mac"),
        (ShortcutOthers, "Все остальные клавиши идут на Mac. Передаётся положение клавиши, а не символ – кириллица и AltGr работают сами собой."),
        // Benchmark
        (TabBenchmark, "Бенчмарк"),
        (BenchStart, "Старт"),
        (BenchAbort, "Отмена"),
        (BenchApply, "Применить"),
        (BenchDuration, "Длительность шага"),
        (BenchTestPattern, "Тестовая картинка"),
        (BenchStep, "Шаг {n} из {m}"),
        (BenchPhaseSettings, "применение настроек"),
        (BenchPhaseSettle, "стабилизация"),
        (BenchPhaseMeasure, "измерение"),
        (BenchFailed, "не удался"),
        (BenchDone, "Готово"),
        (BenchAborted, "Отменено"),
        (BenchMeasured, "измерено"),
        (BenchChain, "Цепочка"),
        (BenchColFps, "fps"),
        (BenchColDropped, "потеряно"),
        (BenchColHostCpu, "CPU хоста"),
        (BenchRecommendation, "Рекомендация"),
        (BenchNoRecommendation, "Ни один шаг не прошёл. Попробуйте меньший битрейт или частоту кадров."),
        (BenchHint, "Измеряется то, что сейчас происходит на Mac. Шаги сравнимы только тогда, когда что-то движется – достаточно воспроизводимого видео."),
        (BenchHintPattern, "С тестовой картинкой каждый шаг видит одно и то же движущееся содержимое – на Mac ничего не должно быть запущено."),
        (TipBenchStart, "По очереди измеряет все комбинации выбранных кодеков, частот кадров и битрейтов, каждую в течение заданного времени. Картинка идёт дальше, меню может оставаться открытым."),
        (TipBenchApply, "Установить рекомендованный кодек и настройки и сохранить их для этого хоста."),
        (TipBenchDuration, "Время измерения на шаг. Дольше – стабильнее; 5 с обычно достаточно."),
        (TipBenchHint, "Шаг проходит, если цепочка укладывается в полтора кадра, приходит не менее 95 % кадров, ни один не потерян и кодер укладывается в свой бюджет на кадр. Рекомендуется лучшее качество цвета, которое проходит на самой высокой частоте кадров, с самым высоким битрейтом, при котором оно ещё проходит."),
        (TipBenchTestPattern, "На время измерения хост показывает вместо экрана фиксированный движущийся узор – каждый шаг измеряет одно и то же содержимое."),
    ],
};

pub static ZH: Lang = Lang {
    code: "zh",
    name: "简体中文",
    table: &[
        (AppSubtitle, "完整色彩细节的远程桌面"),
        (Connect, "连接"),
        (Disconnect, "断开连接"),
        (HostAddress, "主机地址"),
        (SearchingHosts, "正在搜索主机"),
        (NoHostsFound, "未找到主机"),
        (FoundHosts, "找到的主机"),
        (Settings, "设置"),
        (Language, "语言"),
        (Quit, "退出"),
        (Connecting, "正在连接"),
        (Connected, "已连接"),
        (ConnectionLost, "连接已断开"),
        (Reconnecting, "正在重新连接"),
        (Fullscreen, "全屏"),
        (PixelExact, "像素对应"),
        (Stretch, "适应窗口"),
        (ShowOverlay, "显示统计"),
        (Fps, "每秒帧数"),
        (DecodeTime, "解码时间"),
        (Bitrate, "码率"),
        (Resolution, "分辨率"),
        (Codec, "编解码器"),
        (Latency, "延迟"),
        (EncodeTime, "编码时间"),
        (NetworkTime, "传输时间"),
        (AudioBuffer, "音频缓冲"),
        (Dropped, "丢帧"),
        (MaxBitrate, "最大码率"),
        (MaxFps, "最高帧率"),
        (ExpertMode, "专家模式"),
        (GamingMode, "游戏模式"),
        (FixedRate, "固定帧率"),
        (FixedRateHint, "即使画面静止也保持帧率。主机会持续承受负载。"),
        (Sound, "声音"),
        (HoldEscHint, "继续按住 ESC 打开菜单"),
        (NerdMode, "极客模式"),
        (More, "更多"),
        (Back, "返回"),
        (SavedForHost, "已为此主机保存"),
        (Queue, "采集与排队"),
        (OneFrame, "一帧"),
        (Bottleneck, "瓶颈"),
        (TabPicture, "画面"),
        (TabDisplay, "显示"),
        (CodecConverted, "需转换"),
        (CodecSwitching, "正在切换编解码器"),
        (HostCpu, "主机 CPU"),
        (HostGpu, "主机 GPU"),
        (HostRam, "主机内存"),
        (NoDisplay, "主机目前没有显示器"),
        (Encryption, "加密"),
        (EncryptionOn, "开"),
        (EncryptionOff, "关"),
        (AudioEnabled, "音频"),
        (ClipboardEnabled, "剪贴板"),
        (DecoderLabel, "解码器"),
        (DecoderAuto, "自动"),
        (DecoderSoftware, "软件"),
        (DecoderNvidia, "显卡"),
        (DisplayLabel, "显示"),
        (DisplayStage, "显示"),
        (ClientCpu, "客户端 CPU"),
        (Monitor, "显示器"),
        (Skipped, "跳过"),
        (PairingTitle, "与主机配对"),
        (PairingHint, "输入主机上显示的配对码"),
        (PairingCode, "配对码"),
        (PairingWrong, "配对码错误"),
        (PairingOk, "已配对"),
        (SecuredWith, "已保护 · 校验码"),
        (HostFingerprint, "主机指纹"),
        (NotPaired, "此主机尚未记录你的设备。请使用 --pair 启动主机后重新连接。"),
        (FirstContact, "首次连接此主机。请与主机上显示的代码进行核对。"),
        (ErrorConnectRefused, "主机拒绝了连接"),
        (ErrorTimeout, "主机无响应"),
        (ErrorProtocol, "对方使用的协议不同"),
        (ErrorNoDecoder, "没有此格式的解码器"),
        (TipBitrate, "码率上限。画面运动时编码器会用满；在非自家网络上建议 25 到 50。"),
        (TipFps, "目标帧率。无法超过 Mac 显示器的刷新率。"),
        (TipGaming, "更频繁的关键帧，允许的积压更少：运动时更平稳，略微多耗码率。"),
        (TipSound, "传输声音。关闭可节省约 3 Mbit/s，主机将不再发送声音。"),
        (TipCodec, "主机的编解码器，可在运行中切换；画面会短暂停顿。\"需转换\" 会多一次处理。"),
        (TipFullscreen, "无边框全屏。窗口模式下画面按比例适应。"),
        (TipPixelExact, "画面 1:1 不缩放。窗口较小时只显示一部分。"),
        (TipShowOverlay, "在左上角显示统计。显示哪些行，在右侧选择。"),
        (TipNerdMode, "扩展统计：延迟链以条形显示，以及主机和客户端的负载。"),
        (TipStatRows, "统计显示哪些行。"),
        (TipDecoderAuto, "显卡支持该编解码器时用显卡，否则用软件。"),
        (TipDecoderSoftware, "在处理器上解码。到处都能用，占用 CPU 时间。"),
        (TipDecoderGpu, "在显卡上解码。若不行，客户端会回退到软件并说明原因。"),
        (TipDisconnect, "断开连接，返回起始画面。"),
        (TabShortcuts, "快捷键"),
        (ShortcutMenu, "打开菜单（这个 ESC 不会传到 Mac）"),
        (ShortcutBack, "返回起始画面"),
        (ShortcutWinKey, "Windows 键 = Mac 的 Command 键"),
        (ShortcutOthers, "其他所有按键都发送到 Mac。传输的是按键位置而非字符，重音字母和 AltGr 自然正确。"),
        // Benchmark
        (TabBenchmark, "基准测试"),
        (BenchStart, "开始"),
        (BenchAbort, "取消"),
        (BenchApply, "应用"),
        (BenchDuration, "每步时长"),
        (BenchTestPattern, "测试图案"),
        (BenchStep, "第 {n} 步，共 {m} 步"),
        (BenchPhaseSettings, "正在应用设置"),
        (BenchPhaseSettle, "稳定中"),
        (BenchPhaseMeasure, "测量中"),
        (BenchFailed, "失败"),
        (BenchDone, "完成"),
        (BenchAborted, "已取消"),
        (BenchMeasured, "实测"),
        (BenchChain, "链路"),
        (BenchColFps, "fps"),
        (BenchColDropped, "丢帧"),
        (BenchColHostCpu, "主机 CPU"),
        (BenchRecommendation, "推荐"),
        (BenchNoRecommendation, "没有任何一步通过。请尝试更低的码率或帧率。"),
        (BenchHint, "测量的是 Mac 上此刻正在发生的内容。只有画面在动时各步才有可比性，播放一段视频即可。"),
        (BenchHintPattern, "开启测试图案后，每一步看到的都是相同的运动画面，Mac 上无需运行任何东西。"),
        (TipBenchStart, "依次测试所选编解码器、帧率和码率的所有组合，每个组合持续设定的时长。画面继续运行，菜单可以保持打开。"),
        (TipBenchApply, "应用推荐的编解码器和设置，并为此主机保存。"),
        (TipBenchDuration, "每步的测量时间。更长更稳定；通常 5 秒足够。"),
        (TipBenchHint, "一步通过的条件：链路保持在一帧半以内，至少 95 % 的帧到达，没有丢帧，且编码器在每帧的时间预算内。推荐：在最高帧率下通过的最佳色彩质量，取其仍能通过的最高码率。"),
        (TipBenchTestPattern, "测试期间主机显示固定的运动图案而非屏幕内容，每一步测量的都是相同内容。"),
    ],
};

pub static JA: Lang = Lang {
    code: "ja",
    name: "日本語",
    table: &[
        (AppSubtitle, "色を落とさないリモートデスクトップ"),
        (Connect, "接続"),
        (Disconnect, "切断"),
        (HostAddress, "ホストのアドレス"),
        (SearchingHosts, "ホストを検索中"),
        (NoHostsFound, "ホストが見つかりません"),
        (FoundHosts, "見つかったホスト"),
        (Settings, "設定"),
        (Language, "言語"),
        (Quit, "終了"),
        (Connecting, "接続中"),
        (Connected, "接続済み"),
        (ConnectionLost, "接続が切れました"),
        (Reconnecting, "再接続中"),
        (Fullscreen, "全画面"),
        (PixelExact, "等倍表示"),
        (Stretch, "ウィンドウに合わせる"),
        (ShowOverlay, "統計を表示"),
        (Fps, "フレームレート"),
        (DecodeTime, "デコード時間"),
        (Bitrate, "ビットレート"),
        (Resolution, "解像度"),
        (Codec, "コーデック"),
        (Latency, "遅延"),
        (EncodeTime, "エンコード時間"),
        (NetworkTime, "転送時間"),
        (AudioBuffer, "音声バッファ"),
        (Dropped, "ドロップ"),
        (MaxBitrate, "最大ビットレート"),
        (MaxFps, "最大フレームレート"),
        (ExpertMode, "エキスパートモード"),
        (GamingMode, "ゲームモード"),
        (FixedRate, "固定フレームレート"),
        (FixedRateHint, "画面が静止していてもフレームレートを維持します。ホストに常に負荷がかかります。"),
        (Sound, "音声"),
        (HoldEscHint, "ESC を押し続けてメニューを開く"),
        (NerdMode, "ギークモード"),
        (More, "その他"),
        (Back, "戻る"),
        (SavedForHost, "このホストに保存しました"),
        (Queue, "キャプチャと待機"),
        (OneFrame, "1フレーム"),
        (Bottleneck, "ボトルネック"),
        (TabPicture, "映像"),
        (TabDisplay, "表示"),
        (CodecConverted, "変換あり"),
        (CodecSwitching, "コーデック切り替え中"),
        (HostCpu, "ホストのCPU"),
        (HostGpu, "ホストのGPU"),
        (HostRam, "ホストのメモリ"),
        (NoDisplay, "現在ホストにディスプレイがありません"),
        (Encryption, "暗号化"),
        (EncryptionOn, "オン"),
        (EncryptionOff, "オフ"),
        (AudioEnabled, "音声"),
        (ClipboardEnabled, "クリップボード"),
        (DecoderLabel, "デコーダー"),
        (DecoderAuto, "自動"),
        (DecoderSoftware, "ソフトウェア"),
        (DecoderNvidia, "GPU"),
        (DisplayLabel, "表示"),
        (DisplayStage, "表示"),
        (ClientCpu, "クライアントのCPU"),
        (Monitor, "モニター"),
        (Skipped, "スキップ"),
        (PairingTitle, "ホストとペアリング"),
        (PairingHint, "ホストに表示されたコードを入力"),
        (PairingCode, "ペアリングコード"),
        (PairingWrong, "コードが違います"),
        (PairingOk, "ペアリング済み"),
        (SecuredWith, "保護済み · 確認コード"),
        (HostFingerprint, "ホストのフィンガープリント"),
        (NotPaired, "このホストはまだお使いのデバイスを認識していません。--pair を付けてホストを起動し、もう一度接続してください。"),
        (FirstContact, "このホストへの初回接続です。ホストに表示されているコードと見比べてください。"),
        (ErrorConnectRefused, "ホストに接続を拒否されました"),
        (ErrorTimeout, "ホストから応答がありません"),
        (ErrorProtocol, "相手のプロトコルが異なります"),
        (ErrorNoDecoder, "この形式のデコーダーがありません"),
        (TipBitrate, "ビットレートの上限。動きがあるとエンコーダーは上限まで使います。自分以外のネットワークでは 25〜50 が無難です。"),
        (TipFps, "目標フレームレート。Mac のディスプレイが出せる以上にはなりません。"),
        (TipGaming, "キーフレームを増やし、許容する遅れを減らします。動きのある場面で安定しますが、ビットレートを少し消費します。"),
        (TipSound, "音声を送ります。オフにすると約 3 Mbit/s 節約でき、ホストは音声を送りません。"),
        (TipCodec, "ホストのコーデック。動作中に切り替わり、映像が一瞬止まります。「変換あり」は処理が一段増えます。"),
        (TipFullscreen, "枠なしの全画面。ウィンドウでは映像をはめ込みます。"),
        (TipPixelExact, "拡大縮小なしの等倍表示。ウィンドウが小さいと一部だけ見えます。"),
        (TipShowOverlay, "左上に統計を表示します。どの行を出すかは右側で選びます。"),
        (TipNerdMode, "拡張統計：遅延の内訳をバーで、ホストとクライアントの負荷も表示します。"),
        (TipStatRows, "統計に表示する行。"),
        (TipDecoderAuto, "コーデックに対応していれば GPU、そうでなければソフトウェア。"),
        (TipDecoderSoftware, "CPU でデコードします。どこでも動きますが、処理時間がかかります。"),
        (TipDecoderGpu, "GPU でデコードします。できない場合はソフトウェアに戻り、理由を表示します。"),
        (TipDisconnect, "接続を終了して開始画面に戻ります。"),
        (TabShortcuts, "ショートカット"),
        (ShortcutMenu, "メニューを開く（この ESC は Mac には届きません）"),
        (ShortcutBack, "開始画面に戻る"),
        (ShortcutWinKey, "Windows キー = Mac の Command キー"),
        (ShortcutOthers, "他のキーはすべて Mac に送られます。送るのは文字ではなくキーの位置なので、記号や AltGr もそのまま使えます。"),
        // Benchmark
        (TabBenchmark, "ベンチマーク"),
        (BenchStart, "開始"),
        (BenchAbort, "中止"),
        (BenchApply, "適用"),
        (BenchDuration, "1ステップの時間"),
        (BenchTestPattern, "テストパターン"),
        (BenchStep, "ステップ {n} / {m}"),
        (BenchPhaseSettings, "設定を適用中"),
        (BenchPhaseSettle, "安定待ち"),
        (BenchPhaseMeasure, "計測中"),
        (BenchFailed, "失敗"),
        (BenchDone, "完了"),
        (BenchAborted, "中止済み"),
        (BenchMeasured, "実測"),
        (BenchChain, "経路"),
        (BenchColFps, "fps"),
        (BenchColDropped, "ドロップ"),
        (BenchColHostCpu, "ホストCPU"),
        (BenchRecommendation, "おすすめ"),
        (BenchNoRecommendation, "合格したステップがありません。ビットレートかフレームレートを下げてみてください。"),
        (BenchHint, "計測するのは今 Mac で起きていることです。何かが動いているときだけステップを比較できます。動画を再生しておけば十分です。"),
        (BenchHintPattern, "テストパターンをオンにすると、どのステップも同じ動く映像を見ます。Mac 側で何かを動かす必要はありません。"),
        (TipBenchStart, "選んだコーデック、フレームレート、ビットレートのすべての組み合わせを順に、設定した時間ずつ計測します。映像は流れたままで、メニューを開いたままでも構いません。"),
        (TipBenchApply, "おすすめのコーデックと設定を適用し、このホスト用に保存します。"),
        (TipBenchDuration, "1ステップあたりの計測時間。長いほど安定します。通常は 5 秒で十分です。"),
        (TipBenchHint, "経路が1.5フレーム以内に収まり、フレームの 95 % 以上が届き、ドロップがなく、エンコーダーがフレーム予算内に収まればステップは合格です。おすすめは、最高フレームレートで合格する最良の色品質を、まだ合格する最高のビットレートで選んだものです。"),
        (TipBenchTestPattern, "計測中、ホストは画面の代わりに固定の動くパターンを表示します。どのステップも同じ内容を計測します。"),
    ],
};

pub static TR: Lang = Lang {
    code: "tr",
    name: "Türkçe",
    table: &[
        (AppSubtitle, "Tam renk ayrıntısıyla uzak masaüstü"),
        (Connect, "Bağlan"),
        (Disconnect, "Bağlantıyı kes"),
        (HostAddress, "Host adresi"),
        (SearchingHosts, "Host aranıyor"),
        (NoHostsFound, "Host bulunamadı"),
        (FoundHosts, "Bulunan hostlar"),
        (Settings, "Ayarlar"),
        (Language, "Dil"),
        (Quit, "Çıkış"),
        (Connecting, "Bağlanılıyor"),
        (Connected, "Bağlandı"),
        (ConnectionLost, "Bağlantı koptu"),
        (Reconnecting, "Yeniden bağlanılıyor"),
        (Fullscreen, "Tam ekran"),
        (PixelExact, "Birebir piksel"),
        (Stretch, "Pencereye sığdır"),
        (ShowOverlay, "İstatistikleri göster"),
        (Fps, "Saniyedeki kare"),
        (DecodeTime, "Kod çözme süresi"),
        (Bitrate, "Bit hızı"),
        (Resolution, "Çözünürlük"),
        (Codec, "Codec"),
        (Latency, "Gecikme"),
        (EncodeTime, "Kodlama süresi"),
        (NetworkTime, "Aktarım süresi"),
        (AudioBuffer, "Ses arabelleği"),
        (Dropped, "Atlanan kare"),
        (MaxBitrate, "En yüksek bit hızı"),
        (MaxFps, "En yüksek kare hızı"),
        (ExpertMode, "Uzman modu"),
        (GamingMode, "Oyun modu"),
        (FixedRate, "Sabit kare hızı"),
        (FixedRateHint, "Hiçbir şey hareket etmese de kare hızını korur. Host'ta sürekli yük oluşur."),
        (Sound, "Ses"),
        (HoldEscHint, "Menü için ESC'yi basılı tutun"),
        (NerdMode, "Nerd modu"),
        (More, "Daha fazla"),
        (Back, "Geri"),
        (SavedForHost, "Bu host için kaydedildi"),
        (Queue, "Yakalama ve bekleme"),
        (OneFrame, "Bir kare"),
        (Bottleneck, "Darboğaz"),
        (TabPicture, "Görüntü"),
        (TabDisplay, "Ekran"),
        (CodecConverted, "dönüştürülmüş"),
        (CodecSwitching, "Codec değiştiriliyor"),
        (HostCpu, "Host işlemcisi"),
        (HostGpu, "Host ekran kartı"),
        (HostRam, "Host belleği"),
        (NoDisplay, "Host'un şu anda ekranı yok"),
        (Encryption, "Şifreleme"),
        (EncryptionOn, "açık"),
        (EncryptionOff, "kapalı"),
        (AudioEnabled, "Ses"),
        (ClipboardEnabled, "Pano"),
        (DecoderLabel, "Kod çözücü"),
        (DecoderAuto, "Otomatik"),
        (DecoderSoftware, "Yazılım"),
        (DecoderNvidia, "Ekran kartı"),
        (DisplayLabel, "Ekran"),
        (DisplayStage, "Ekran"),
        (ClientCpu, "İstemci işlemcisi"),
        (Monitor, "Monitör"),
        (Skipped, "gösterilmedi"),
        (PairingTitle, "Host ile eşleştir"),
        (PairingHint, "Host'ta görünen kodu girin"),
        (PairingCode, "Eşleştirme kodu"),
        (PairingWrong, "Kod yanlış"),
        (PairingOk, "Eşleştirildi"),
        (SecuredWith, "Güvenli · doğrulama kodu"),
        (HostFingerprint, "Host parmak izi"),
        (NotPaired, "Bu host cihazınızı henüz tanımıyor. Host'u --pair ile başlatıp yeniden bağlanın."),
        (FirstContact, "Bu host ile ilk bağlantı. Kodu host'ta görünenle karşılaştırın."),
        (ErrorConnectRefused, "Host bağlantıyı reddetti"),
        (ErrorTimeout, "Host yanıt vermedi"),
        (ErrorProtocol, "Karşı taraf farklı bir protokol kullanıyor"),
        (ErrorNoDecoder, "Bu biçim için kod çözücü yok"),
        (TipBitrate, "Bit hızının üst sınırı. Hareket olunca kodlayıcı tamamını kullanır; yabancı ağlarda 25 ile 50 arası daha iyi."),
        (TipFps, "Hedef kare hızı. Mac'in ekranının verdiğinden fazlası olmaz."),
        (TipGaming, "Daha sık anahtar kare ve daha az birikime izin: harekette daha düzgün, biraz bit hızına mal olur."),
        (TipSound, "Ses aktar. Kapalıyken yaklaşık 3 Mbit/s tasarruf; host o zaman hiç ses göndermez."),
        (TipCodec, "Host'un codec'i, çalışırken değiştirilir; görüntü kısa süre durur. \"dönüştürülmüş\" bir ek geçişe mal olur."),
        (TipFullscreen, "Kenarlıksız tam ekran. Pencerede görüntü sığdırılır."),
        (TipPixelExact, "Görüntü 1:1, ölçekleme yok. Pencere küçükse bir kesit görürsünüz."),
        (TipShowOverlay, "İstatistikleri sol üstte göster. Hangi satırlar, sağda seçilir."),
        (TipNerdMode, "Genişletilmiş istatistik: gecikme zinciri çubuk olarak, host ve istemci yükü."),
        (TipStatRows, "İstatistiğin hangi satırları gösterdiği."),
        (TipDecoderAuto, "Codec'i destekliyorsa ekran kartı, yoksa yazılım."),
        (TipDecoderSoftware, "İşlemcide kod çözme. Her yerde çalışır, işlem süresine mal olur."),
        (TipDecoderGpu, "Ekran kartında kod çözme. Yapamazsa istemci yazılıma döner ve nedenini söyler."),
        (TipDisconnect, "Bağlantıyı bitir, başlangıç ekranına dön."),
        (TabShortcuts, "Kısayollar"),
        (ShortcutMenu, "Menüyü aç (bu ESC Mac'e hiç ulaşmaz)"),
        (ShortcutBack, "Başlangıç ekranına dön"),
        (ShortcutWinKey, "Windows tuşu = Mac'in Command tuşu"),
        (ShortcutOthers, "Diğer tüm tuşlar Mac'e gider. Karakter değil tuşun konumu iletilir – Türkçe harfler ve AltGr kendiliğinden doğru çalışır."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Başlat"),
        (BenchAbort, "İptal"),
        (BenchApply, "Uygula"),
        (BenchDuration, "Adım başına süre"),
        (BenchTestPattern, "Test deseni"),
        (BenchStep, "Adım {n}/{m}"),
        (BenchPhaseSettings, "ayarlar uygulanıyor"),
        (BenchPhaseSettle, "oturuyor"),
        (BenchPhaseMeasure, "ölçülüyor"),
        (BenchFailed, "başarısız"),
        (BenchDone, "Bitti"),
        (BenchAborted, "İptal edildi"),
        (BenchMeasured, "ölçülen"),
        (BenchChain, "Zincir"),
        (BenchColFps, "fps"),
        (BenchColDropped, "atlanan"),
        (BenchColHostCpu, "Host CPU"),
        (BenchRecommendation, "Öneri"),
        (BenchNoRecommendation, "Hiçbir adım geçmedi. Daha düşük bit hızı veya kare hızı deneyin."),
        (BenchHint, "Ölçülen, şu anda Mac'te olup bitendir. Adımlar ancak bir şey hareket ederken karşılaştırılabilir – oynayan bir video yeter."),
        (BenchHintPattern, "Test deseni açıkken her adım aynı hareketli içeriği görür – Mac'te hiçbir şeyin çalışması gerekmez."),
        (TipBenchStart, "Seçilen codec'lerin, kare hızlarının ve bit hızlarının tüm kombinasyonlarını sırayla, her birini ayarlanan süre boyunca ölçer. Görüntü akmaya devam eder, menü açık kalabilir."),
        (TipBenchApply, "Önerilen codec'i ve ayarları uygula ve bu host için kaydet."),
        (TipBenchDuration, "Adım başına ölçüm süresi. Daha uzun daha kararlıdır; genelde 5 s yeter."),
        (TipBenchHint, "Zincir bir buçuk kare içinde kalır, karelerin en az % 95'i ulaşır, hiçbiri atlanmaz ve kodlayıcı kare bütçesinde kalırsa adım geçer. Önerilen: en yüksek kare hızında geçen en iyi renk kalitesi, hâlâ geçtiği en yüksek bit hızıyla."),
        (TipBenchTestPattern, "Çalıştırma boyunca host ekran yerine sabit, hareketli bir desen gösterir – her adım aynı içeriği ölçer."),
    ],
};
