// Sprachtabellen: Estnisch, Lettisch, Litauisch, Slowenisch, Kroatisch,
// Ukrainisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static ET: Lang = Lang {
    code: "et",
    name: "Eesti",
    table: &[
        (AppSubtitle, "Kaugtöölaud täieliku värvitäpsusega"),
        (Connect, "Ühenda"),
        (Disconnect, "Katkesta ühendus"),
        (HostAddress, "Hosti aadress"),
        (SearchingHosts, "Otsin hoste"),
        (NoHostsFound, "Hoste ei leitud"),
        (FoundHosts, "Leitud hostid"),
        (Settings, "Sätted"),
        (Language, "Keel"),
        (Quit, "Välju"),
        (Connecting, "Ühendan"),
        (Connected, "Ühendatud"),
        (ConnectionLost, "Ühendus katkes"),
        (Reconnecting, "Ühendan uuesti"),
        (Fullscreen, "Täisekraan"),
        (PixelExact, "Pikslitäpne"),
        (Stretch, "Sobita aknasse"),
        (ShowOverlay, "Näita statistikat"),
        (Fps, "Kaadrit sekundis"),
        (DecodeTime, "Dekodeerimisaeg"),
        (Bitrate, "Bitikiirus"),
        (Resolution, "Eraldusvõime"),
        (Codec, "Koodek"),
        (Latency, "Viivitus"),
        (EncodeTime, "Kodeerimisaeg"),
        (NetworkTime, "Ülekandeaeg"),
        (AudioBuffer, "Helipuhver"),
        (Dropped, "Vahelejäänud"),
        (MaxBitrate, "Suurim bitikiirus"),
        (MaxFps, "Suurim kaadrisagedus"),
        (ExpertMode, "Eksperdirežiim"),
        (GamingMode, "Mängurežiim"),
        (FixedRate, "Püsiv kaadrisagedus"),
        (FixedRateHint, "Hoiab kaadrisagedust ka siis, kui miski ei liigu. Pidev koormus hostile."),
        (Sound, "Heli"),
        (HoldEscHint, "Hoia ESC all menüü avamiseks"),
        (NerdMode, "Tehniline vaade"),
        (More, "Veel"),
        (Back, "Tagasi"),
        (SavedForHost, "Salvestatud selle hosti jaoks"),
        (Queue, "Hõive ja ootamine"),
        (OneFrame, "Üks kaader"),
        (Bottleneck, "Kitsaskoht"),
        (TabPicture, "Pilt"),
        (TabDisplay, "Kuva"),
        (CodecConverted, "teisendatud"),
        (CodecSwitching, "Vahetan koodekit"),
        (HostCpu, "Hosti protsessor"),
        (HostGpu, "Hosti graafika"),
        (HostRam, "Hosti mälu"),
        (NoDisplay, "Hostil pole praegu ekraani"),
        (Encryption, "Krüptimine"),
        (EncryptionOn, "sees"),
        (EncryptionOff, "väljas"),
        (AudioEnabled, "Heli"),
        (ClipboardEnabled, "Lõikelaud"),
        (DecoderLabel, "Dekooder"),
        (DecoderAuto, "Automaatne"),
        (DecoderSoftware, "Tarkvara"),
        (DecoderNvidia, "Graafikakaart"),
        (DisplayLabel, "Kuva"),
        (DisplayStage, "Kuva"),
        (ClientCpu, "Kliendi protsessor"),
        (Monitor, "Monitor"),
        (Skipped, "esitamata"),
        (PairingTitle, "Seo hostiga"),
        (PairingHint, "Sisesta hostis kuvatud kood"),
        (PairingCode, "Sidumiskood"),
        (PairingWrong, "Vale kood"),
        (PairingOk, "Seotud"),
        (SecuredWith, "Turvatud · kontrollkood"),
        (HostFingerprint, "Hosti sõrmejälg"),
        (NotPaired, "See host ei tunne veel sinu seadet. Käivita host võtmega --pair ja ühenda uuesti."),
        (FirstContact, "Esimene kontakt selle hostiga. Võrdle koodi hostis kuvatuga."),
        (ErrorConnectRefused, "Host keeldus ühendusest"),
        (ErrorTimeout, "Host ei vastanud"),
        (ErrorProtocol, "Teine pool kasutab teist protokolli"),
        (ErrorNoDecoder, "Selle vormingu jaoks pole dekoodrit"),
        (TipBitrate, "Bitikiiruse ülempiir. Liikumise korral kasutab kooder selle täielikult ära; võõras võrgus pigem 25 kuni 50."),
        (TipFps, "Sihtkaadrisagedus. Rohkem, kui Maci ekraan annab, ei saa."),
        (TipGaming, "Sagedamad võtmekaadrid ja väiksem lubatud mahajäämus: ühtlasem liikumisel, maksab veidi bitikiirust."),
        (TipSound, "Heli edastamine. Väljas säästab umbes 3 Mbit/s; host ei saada siis heli."),
        (TipCodec, "Hosti koodek, vahetatakse töö ajal; pilt seisab hetkeks. \"teisendatud\" maksab ühe lisakäigu."),
        (TipFullscreen, "Raamita täisekraan. Aknas pilt sobitatakse."),
        (TipPixelExact, "Pilt 1:1 ilma skaleerimata. Kui aken on väiksem, näed väljalõiget."),
        (TipShowOverlay, "Näita statistikat üleval vasakul. Millised read, vali paremalt."),
        (TipNerdMode, "Laiendatud statistika: viivitusahel tulbana, hosti ja kliendi koormus."),
        (TipStatRows, "Millised read statistikas kuvatakse."),
        (TipDecoderAuto, "Graafikakaart, kui see koodekit toetab, muidu tarkvara."),
        (TipDecoderSoftware, "Dekodeerimine protsessoril. Töötab kõikjal, maksab arvutusaega."),
        (TipDecoderGpu, "Dekodeerimine graafikakaardil. Kui see ei õnnestu, läheb klient tarkvarale üle ja ütleb, miks."),
        (TipDisconnect, "Lõpeta ühendus, tagasi avakuvale."),
        (TabShortcuts, "Kiirklahvid"),
        (ShortcutMenu, "Ava menüü (see ESC ei jõua kunagi Macini)"),
        (ShortcutBack, "Tagasi avakuvale"),
        (ShortcutWinKey, "Windowsi klahv = Maci Command-klahv"),
        (ShortcutOthers, "Kõik teised klahvid lähevad Macile. Edastatakse klahvi asukoht, mitte märk – täpitähed ja AltGr töötavad iseenesest."),
        // Benchmark
        (TabBenchmark, "Jõudlustest"),
        (BenchStart, "Alusta"),
        (BenchAbort, "Katkesta"),
        (BenchApply, "Rakenda"),
        (BenchDuration, "Kestus sammu kohta"),
        (BenchTestPattern, "Testpilt"),
        (BenchStep, "Samm {n}/{m}"),
        (BenchPhaseSettings, "sätete rakendamine"),
        (BenchPhaseSettle, "stabiliseerumine"),
        (BenchPhaseMeasure, "mõõtmine"),
        (BenchFailed, "ebaõnnestus"),
        (BenchDone, "Valmis"),
        (BenchAborted, "Katkestatud"),
        (BenchMeasured, "mõõdetud"),
        (BenchChain, "Ahel"),
        (BenchColFps, "fps"),
        (BenchColDropped, "vahelejäänud"),
        (BenchColHostCpu, "Hosti CPU"),
        (BenchRecommendation, "Soovitus"),
        (BenchNoRecommendation, "Ükski samm ei läbinud. Proovi madalamat bitikiirust või kaadrisagedust."),
        (BenchHint, "Mõõdetakse seda, mis Macil praegu toimub. Sammud on võrreldavad ainult siis, kui miski liigub – piisab mängivast videost."),
        (BenchHintPattern, "Testpildiga näeb iga samm sama liikuvat sisu – Macil ei pea midagi töötama."),
        (TipBenchStart, "Mõõdab järjest kõik valitud koodekite, kaadrisageduste ja bitikiiruste kombinatsioonid, iga seatud kestuse jooksul. Pilt jookseb edasi ja menüü võib jääda lahti."),
        (TipBenchApply, "Sea soovitatud koodek ja sätted ning salvesta need selle hosti jaoks."),
        (TipBenchDuration, "Mõõteaeg sammu kohta. Pikem on stabiilsem; 5 s on enamasti küllalt."),
        (TipBenchHint, "Samm läbib, kui ahel püsib pooleteise kaadri sees, kohale jõuab vähemalt 95 % kaadritest, ükski ei jää vahele ja kooder püsib oma kaadrieelarves. Soovitatakse parimat värvikvaliteeti, mis läbib kõrgeimal kaadrisagedusel, kõrgeima bitikiirusega, millega see veel läbib."),
        (TipBenchTestPattern, "Jooksu ajaks näitab host ekraani asemel kindlat liikuvat mustrit – iga samm mõõdab sama sisu."),
    ],
};

pub static LV: Lang = Lang {
    code: "lv",
    name: "Latviešu",
    table: &[
        (AppSubtitle, "Attālā darbvirsma ar pilnu krāsu detalizāciju"),
        (Connect, "Savienot"),
        (Disconnect, "Atvienot"),
        (HostAddress, "Hosta adrese"),
        (SearchingHosts, "Meklē hostus"),
        (NoHostsFound, "Hosti nav atrasti"),
        (FoundHosts, "Atrastie hosti"),
        (Settings, "Iestatījumi"),
        (Language, "Valoda"),
        (Quit, "Iziet"),
        (Connecting, "Savienojas"),
        (Connected, "Savienots"),
        (ConnectionLost, "Savienojums pārtrūka"),
        (Reconnecting, "Savienojas atkārtoti"),
        (Fullscreen, "Pilnekrāns"),
        (PixelExact, "Pikseļu precizitāte"),
        (Stretch, "Ietilpināt logā"),
        (ShowOverlay, "Rādīt statistiku"),
        (Fps, "Kadri sekundē"),
        (DecodeTime, "Dekodēšanas laiks"),
        (Bitrate, "Bitu ātrums"),
        (Resolution, "Izšķirtspēja"),
        (Codec, "Kodeks"),
        (Latency, "Aizkave"),
        (EncodeTime, "Kodēšanas laiks"),
        (NetworkTime, "Pārraides laiks"),
        (AudioBuffer, "Audio buferis"),
        (Dropped, "Izlaisti"),
        (MaxBitrate, "Maksimālais bitu ātrums"),
        (MaxFps, "Maksimālais kadru ātrums"),
        (ExpertMode, "Eksperta režīms"),
        (GamingMode, "Spēļu režīms"),
        (FixedRate, "Fiksēts kadru ātrums"),
        (FixedRateHint, "Uztur kadru ātrumu arī tad, kad nekas nekustas. Pastāvīga slodze hostam."),
        (Sound, "Skaņa"),
        (HoldEscHint, "Turiet ESC, lai atvērtu izvēlni"),
        (NerdMode, "Nerda režīms"),
        (More, "Vairāk"),
        (Back, "Atpakaļ"),
        (SavedForHost, "Saglabāts šim hostam"),
        (Queue, "Uzņemšana un rinda"),
        (OneFrame, "Viens kadrs"),
        (Bottleneck, "Šaurā vieta"),
        (TabPicture, "Attēls"),
        (TabDisplay, "Ekrāns"),
        (CodecConverted, "konvertēts"),
        (CodecSwitching, "Pārslēdz kodeku"),
        (HostCpu, "Hosta procesors"),
        (HostGpu, "Hosta grafika"),
        (HostRam, "Hosta atmiņa"),
        (NoDisplay, "Hostam pašlaik nav ekrāna"),
        (Encryption, "Šifrēšana"),
        (EncryptionOn, "ieslēgta"),
        (EncryptionOff, "izslēgta"),
        (AudioEnabled, "Skaņa"),
        (ClipboardEnabled, "Starpliktuve"),
        (DecoderLabel, "Dekoders"),
        (DecoderAuto, "Automātiski"),
        (DecoderSoftware, "Programmatūra"),
        (DecoderNvidia, "Videokarte"),
        (DisplayLabel, "Ekrāns"),
        (DisplayStage, "Ekrāns"),
        (ClientCpu, "Klienta procesors"),
        (Monitor, "Monitors"),
        (Skipped, "nerādīti"),
        (PairingTitle, "Savienot pārī ar hostu"),
        (PairingHint, "Ievadiet hostā redzamo kodu"),
        (PairingCode, "Savienošanas kods"),
        (PairingWrong, "Nepareizs kods"),
        (PairingOk, "Savienots pārī"),
        (SecuredWith, "Aizsargāts · pārbaudes kods"),
        (HostFingerprint, "Hosta atslēgas nospiedums"),
        (NotPaired, "Šis hosts vēl nepazīst jūsu ierīci. Palaidiet hostu ar --pair un savienojiet vēlreiz."),
        (FirstContact, "Pirmais kontakts ar šo hostu. Salīdziniet kodu ar to, kas redzams hostā."),
        (ErrorConnectRefused, "Hosts noraidīja savienojumu"),
        (ErrorTimeout, "Hosts neatbildēja"),
        (ErrorProtocol, "Otra puse lieto citu protokolu"),
        (ErrorNoDecoder, "Šim formātam nav dekodera"),
        (TipBitrate, "Bitu ātruma augšējā robeža. Kustībā kodētājs to izmanto pilnībā; svešos tīklos labāk 25 līdz 50."),
        (TipFps, "Mērķa kadru ātrums. Vairāk, nekā dod Mac ekrāns, nav iespējams."),
        (TipGaming, "Biežāki atslēgkadri un mazāka pieļaujamā atpalikšana: vienmērīgāk kustībā, maksā nedaudz bitu ātruma."),
        (TipSound, "Pārraidīt skaņu. Izslēgts ietaupa apmēram 3 Mbit/s; hosts tad skaņu nesūta."),
        (TipCodec, "Hosta kodeks, maināms darbības laikā; attēls uz brīdi apstājas. \"konvertēts\" maksā vienu papildu soli."),
        (TipFullscreen, "Pilnekrāns bez malām. Logā attēls tiek ietilpināts."),
        (TipPixelExact, "Attēls 1:1 bez mērogošanas. Ja logs ir mazāks, redzams izgriezums."),
        (TipShowOverlay, "Rādīt statistiku augšā pa kreisi. Kuras rindas – pa labi."),
        (TipNerdMode, "Paplašināta statistika: aizkaves ķēde kā josla, hosta un klienta slodze."),
        (TipStatRows, "Kuras rindas statistika rāda."),
        (TipDecoderAuto, "Videokarte, ja tā atbalsta kodeku, citādi programmatūra."),
        (TipDecoderSoftware, "Dekodēšana uz procesora. Darbojas visur, maksā skaitļošanas laiku."),
        (TipDecoderGpu, "Dekodēšana uz videokartes. Ja tā nevar, klients pāriet uz programmatūru un pasaka, kāpēc."),
        (TipDisconnect, "Beigt savienojumu, atpakaļ uz sākuma ekrānu."),
        (TabShortcuts, "Īsinājumtaustiņi"),
        (ShortcutMenu, "Atvērt izvēlni (šis ESC nekad nenonāk līdz Mac)"),
        (ShortcutBack, "Atpakaļ uz sākuma ekrānu"),
        (ShortcutWinKey, "Windows taustiņš = Mac Command taustiņš"),
        (ShortcutOthers, "Visi pārējie taustiņi iet uz Mac. Tiek pārraidīta taustiņa pozīcija, nevis rakstzīme – garumzīmes, mīkstinājumi un AltGr darbojas paši."),
        // Benchmark
        (TabBenchmark, "Veiktspējas tests"),
        (BenchStart, "Sākt"),
        (BenchAbort, "Atcelt"),
        (BenchApply, "Lietot"),
        (BenchDuration, "Ilgums vienam solim"),
        (BenchTestPattern, "Testa attēls"),
        (BenchStep, "{n}. solis no {m}"),
        (BenchPhaseSettings, "iestatījumi tiek lietoti"),
        (BenchPhaseSettle, "stabilizācija"),
        (BenchPhaseMeasure, "mērīšana"),
        (BenchFailed, "neizdevās"),
        (BenchDone, "Pabeigts"),
        (BenchAborted, "Atcelts"),
        (BenchMeasured, "izmērīts"),
        (BenchChain, "Ķēde"),
        (BenchColFps, "fps"),
        (BenchColDropped, "izlaisti"),
        (BenchColHostCpu, "Hosta CPU"),
        (BenchRecommendation, "Ieteikums"),
        (BenchNoRecommendation, "Neviens solis neizturēja. Mēģiniet zemāku bitu ātrumu vai kadru ātrumu."),
        (BenchHint, "Mērīts tiek tas, kas šobrīd notiek Mac. Soļi ir salīdzināmi tikai tad, ja kaut kas kustas – pietiek ar atskaņotu video."),
        (BenchHintPattern, "Ar testa attēlu katrs solis redz vienu un to pašu kustīgo saturu – Mac nekam nav jādarbojas."),
        (TipBenchStart, "Pēc kārtas izmēra visas izvēlēto kodeku, kadru ātrumu un bitu ātrumu kombinācijas, katru iestatīto laiku. Attēls turpina darboties, un izvēlne var palikt atvērta."),
        (TipBenchApply, "Iestatīt ieteikto kodeku un iestatījumus un saglabāt tos šim hostam."),
        (TipBenchDuration, "Mērīšanas laiks vienam solim. Ilgāks ir stabilāks; 5 s parasti pietiek."),
        (TipBenchHint, "Solis iztur, ja ķēde iekļaujas pusotrā kadrā, pienāk vismaz 95 % kadru, neviens netiek izlaists un kodētājs iekļaujas savā kadra budžetā. Ieteicama labākā krāsu kvalitāte, kas iztur pie augstākā kadru ātruma, ar augstāko bitu ātrumu, ar kuru tā vēl iztur."),
        (TipBenchTestPattern, "Testa laikā hosts ekrāna vietā rāda fiksētu kustīgu rakstu – katrs solis mēra vienu un to pašu saturu."),
    ],
};

pub static LT: Lang = Lang {
    code: "lt",
    name: "Lietuvių",
    table: &[
        (AppSubtitle, "Nuotolinis darbalaukis su visa spalvų raiška"),
        (Connect, "Prisijungti"),
        (Disconnect, "Atsijungti"),
        (HostAddress, "Hosto adresas"),
        (SearchingHosts, "Ieškoma hostų"),
        (NoHostsFound, "Hostų nerasta"),
        (FoundHosts, "Rasti hostai"),
        (Settings, "Nustatymai"),
        (Language, "Kalba"),
        (Quit, "Išeiti"),
        (Connecting, "Jungiamasi"),
        (Connected, "Prisijungta"),
        (ConnectionLost, "Ryšys nutrūko"),
        (Reconnecting, "Jungiamasi iš naujo"),
        (Fullscreen, "Visas ekranas"),
        (PixelExact, "Pikselių tikslumas"),
        (Stretch, "Pritaikyti prie lango"),
        (ShowOverlay, "Rodyti statistiką"),
        (Fps, "Kadrai per sekundę"),
        (DecodeTime, "Dekodavimo laikas"),
        (Bitrate, "Bitų sparta"),
        (Resolution, "Skiriamoji geba"),
        (Codec, "Kodekas"),
        (Latency, "Delsa"),
        (EncodeTime, "Kodavimo laikas"),
        (NetworkTime, "Perdavimo laikas"),
        (AudioBuffer, "Garso buferis"),
        (Dropped, "Praleista"),
        (MaxBitrate, "Didžiausia bitų sparta"),
        (MaxFps, "Didžiausias kadrų dažnis"),
        (ExpertMode, "Eksperto režimas"),
        (GamingMode, "Žaidimų režimas"),
        (FixedRate, "Pastovus kadrų dažnis"),
        (FixedRateHint, "Išlaiko kadrų dažnį, net kai niekas nejuda. Nuolatinė hosto apkrova."),
        (Sound, "Garsas"),
        (HoldEscHint, "Laikykite ESC, kad atsidarytų meniu"),
        (NerdMode, "Nerdo režimas"),
        (More, "Daugiau"),
        (Back, "Atgal"),
        (SavedForHost, "Įrašyta šiam hostui"),
        (Queue, "Fiksavimas ir eilė"),
        (OneFrame, "Vienas kadras"),
        (Bottleneck, "Siauroji vieta"),
        (TabPicture, "Vaizdas"),
        (TabDisplay, "Ekranas"),
        (CodecConverted, "konvertuota"),
        (CodecSwitching, "Keičiamas kodekas"),
        (HostCpu, "Hosto procesorius"),
        (HostGpu, "Hosto grafika"),
        (HostRam, "Hosto atmintis"),
        (NoDisplay, "Hostas šiuo metu neturi ekrano"),
        (Encryption, "Šifravimas"),
        (EncryptionOn, "įjungtas"),
        (EncryptionOff, "išjungtas"),
        (AudioEnabled, "Garsas"),
        (ClipboardEnabled, "Iškarpinė"),
        (DecoderLabel, "Dekoderis"),
        (DecoderAuto, "Automatinis"),
        (DecoderSoftware, "Programinis"),
        (DecoderNvidia, "Vaizdo plokštė"),
        (DisplayLabel, "Ekranas"),
        (DisplayStage, "Ekranas"),
        (ClientCpu, "Kliento procesorius"),
        (Monitor, "Monitorius"),
        (Skipped, "nerodyta"),
        (PairingTitle, "Susieti su hostu"),
        (PairingHint, "Įveskite hoste rodomą kodą"),
        (PairingCode, "Susiejimo kodas"),
        (PairingWrong, "Neteisingas kodas"),
        (PairingOk, "Susieta"),
        (SecuredWith, "Apsaugota · patvirtinimo kodas"),
        (HostFingerprint, "Hosto rakto atspaudas"),
        (NotPaired, "Šis hostas dar nepažįsta jūsų įrenginio. Paleiskite hostą su --pair ir prisijunkite iš naujo."),
        (FirstContact, "Pirmas kontaktas su šiuo hostu. Palyginkite kodą su rodomu hoste."),
        (ErrorConnectRefused, "Hostas atmetė ryšį"),
        (ErrorTimeout, "Hostas neatsakė"),
        (ErrorProtocol, "Kita pusė naudoja kitą protokolą"),
        (ErrorNoDecoder, "Šiam formatui nėra dekoderio"),
        (TipBitrate, "Viršutinė bitų spartos riba. Judant koderis ją išnaudoja visą; svetimuose tinkluose geriau 25–50."),
        (TipFps, "Tikslinis kadrų dažnis. Daugiau, nei duoda Mac ekranas, neįmanoma."),
        (TipGaming, "Dažnesni raktiniai kadrai ir mažesnis leidžiamas atsilikimas: tolygiau judant, kainuoja šiek tiek bitų spartos."),
        (TipSound, "Perduoti garsą. Išjungus sutaupoma apie 3 Mbit/s; hostas tada garso nesiunčia."),
        (TipCodec, "Hosto kodekas, keičiamas darbo metu; vaizdas akimirkai sustoja. \"konvertuota\" kainuoja vieną papildomą žingsnį."),
        (TipFullscreen, "Visas ekranas be rėmelių. Lange vaizdas pritaikomas."),
        (TipPixelExact, "Vaizdas 1:1 be mastelio. Jei langas mažesnis, matoma tik dalis."),
        (TipShowOverlay, "Rodyti statistiką viršuje kairėje. Kurias eilutes – dešinėje."),
        (TipNerdMode, "Išplėsta statistika: delsos grandinė kaip juosta, hosto ir kliento apkrova."),
        (TipStatRows, "Kurias eilutes rodo statistika."),
        (TipDecoderAuto, "Vaizdo plokštė, jei ji palaiko kodeką, kitaip programinis."),
        (TipDecoderSoftware, "Dekodavimas procesoriuje. Veikia visur, kainuoja skaičiavimo laiko."),
        (TipDecoderGpu, "Dekodavimas vaizdo plokštėje. Jei nepavyksta, klientas grįžta prie programinio ir pasako, kodėl."),
        (TipDisconnect, "Baigti ryšį, grįžti į pradinį ekraną."),
        (TabShortcuts, "Spartieji klavišai"),
        (ShortcutMenu, "Atidaryti meniu (šis ESC niekada nepasiekia Mac)"),
        (ShortcutBack, "Grįžti į pradinį ekraną"),
        (ShortcutWinKey, "Windows klavišas = Mac Command klavišas"),
        (ShortcutOthers, "Visi kiti klavišai keliauja į Mac. Perduodama klavišo padėtis, o ne simbolis – lietuviškos raidės ir AltGr veikia savaime."),
        // Benchmark
        (TabBenchmark, "Našumo testas"),
        (BenchStart, "Pradėti"),
        (BenchAbort, "Atšaukti"),
        (BenchApply, "Taikyti"),
        (BenchDuration, "Trukmė vienam žingsniui"),
        (BenchTestPattern, "Bandomasis vaizdas"),
        (BenchStep, "Žingsnis {n} iš {m}"),
        (BenchPhaseSettings, "taikomi nustatymai"),
        (BenchPhaseSettle, "stabilizuojasi"),
        (BenchPhaseMeasure, "matuojama"),
        (BenchFailed, "nepavyko"),
        (BenchDone, "Baigta"),
        (BenchAborted, "Atšaukta"),
        (BenchMeasured, "išmatuota"),
        (BenchChain, "Grandinė"),
        (BenchColFps, "fps"),
        (BenchColDropped, "praleista"),
        (BenchColHostCpu, "Hosto CPU"),
        (BenchRecommendation, "Rekomendacija"),
        (BenchNoRecommendation, "Nė vienas žingsnis nepraėjo. Pabandykite mažesnę bitų spartą arba kadrų dažnį."),
        (BenchHint, "Matuojama tai, kas dabar vyksta Mac. Žingsniai palyginami tik tada, kai kas nors juda – pakanka grojamo vaizdo įrašo."),
        (BenchHintPattern, "Su bandomuoju vaizdu kiekvienas žingsnis mato tą patį judantį turinį – Mac nieko nereikia paleisti."),
        (TipBenchStart, "Iš eilės išmatuoja visas pasirinktų kodekų, kadrų dažnių ir bitų spartų kombinacijas, kiekvieną nustatytą laiką. Vaizdas rodomas toliau, meniu gali likti atidarytas."),
        (TipBenchApply, "Nustatyti rekomenduojamą kodeką ir nustatymus ir įrašyti juos šiam hostui."),
        (TipBenchDuration, "Matavimo laikas vienam žingsniui. Ilgesnis stabilesnis; 5 s paprastai pakanka."),
        (TipBenchHint, "Žingsnis praeina, kai grandinė telpa į pusantro kadro, atkeliauja bent 95 % kadrų, nė vienas nepraleidžiamas ir koderis telpa į savo kadro biudžetą. Rekomenduojama geriausia spalvų kokybė, kuri praeina esant didžiausiam kadrų dažniui, su didžiausia bitų sparta, su kuria dar praeina."),
        (TipBenchTestPattern, "Testo metu hostas vietoj ekrano rodo fiksuotą judantį raštą – kiekvienas žingsnis matuoja tą patį turinį."),
    ],
};

pub static SL: Lang = Lang {
    code: "sl",
    name: "Slovenščina",
    table: &[
        (AppSubtitle, "Oddaljeno namizje s polno barvno ločljivostjo"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini povezavo"),
        (HostAddress, "Naslov gostitelja"),
        (SearchingHosts, "Iskanje gostiteljev"),
        (NoHostsFound, "Ni najdenih gostiteljev"),
        (FoundHosts, "Najdeni gostitelji"),
        (Settings, "Nastavitve"),
        (Language, "Jezik"),
        (Quit, "Končaj"),
        (Connecting, "Povezovanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Povezava prekinjena"),
        (Reconnecting, "Ponovno povezovanje"),
        (Fullscreen, "Celozaslonsko"),
        (PixelExact, "Pikselna natančnost"),
        (Stretch, "Prilagodi oknu"),
        (ShowOverlay, "Prikaži statistiko"),
        (Fps, "Sličic na sekundo"),
        (DecodeTime, "Čas dekodiranja"),
        (Bitrate, "Bitna hitrost"),
        (Resolution, "Ločljivost"),
        (Codec, "Kodek"),
        (Latency, "Zakasnitev"),
        (EncodeTime, "Čas kodiranja"),
        (NetworkTime, "Čas prenosa"),
        (AudioBuffer, "Zvočni medpomnilnik"),
        (Dropped, "Izpuščene"),
        (MaxBitrate, "Največja bitna hitrost"),
        (MaxFps, "Največja hitrost sličic"),
        (ExpertMode, "Strokovni način"),
        (GamingMode, "Igralni način"),
        (FixedRate, "Stalna hitrost sličic"),
        (FixedRateHint, "Ohranja hitrost sličic tudi, ko se nič ne premika. Stalna obremenitev gostitelja."),
        (Sound, "Zvok"),
        (HoldEscHint, "Držite ESC za meni"),
        (NerdMode, "Nerdovski način"),
        (More, "Več"),
        (Back, "Nazaj"),
        (SavedForHost, "Shranjeno za tega gostitelja"),
        (Queue, "Zajem in čakanje"),
        (OneFrame, "Ena sličica"),
        (Bottleneck, "Ozko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbo"),
        (CodecSwitching, "Menjava kodeka"),
        (HostCpu, "Procesor gostitelja"),
        (HostGpu, "Grafika gostitelja"),
        (HostRam, "Pomnilnik gostitelja"),
        (NoDisplay, "Gostitelj trenutno nima zaslona"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "vklopljeno"),
        (EncryptionOff, "izklopljeno"),
        (AudioEnabled, "Zvok"),
        (ClipboardEnabled, "Odložišče"),
        (DecoderLabel, "Dekodirnik"),
        (DecoderAuto, "Samodejno"),
        (DecoderSoftware, "Programsko"),
        (DecoderNvidia, "Grafična kartica"),
        (DisplayLabel, "Prikaz"),
        (DisplayStage, "Prikaz"),
        (ClientCpu, "Procesor odjemalca"),
        (Monitor, "Monitor"),
        (Skipped, "preskočene"),
        (PairingTitle, "Seznanitev z gostiteljem"),
        (PairingHint, "Vnesite kodo, prikazano na gostitelju"),
        (PairingCode, "Koda za seznanitev"),
        (PairingWrong, "Napačna koda"),
        (PairingOk, "Seznanjeno"),
        (SecuredWith, "Zavarovano · overitvena koda"),
        (HostFingerprint, "Prstni odtis gostitelja"),
        (NotPaired, "Ta gostitelj še ne pozna vaše naprave. Zaženite gostitelja z --pair in se znova povežite."),
        (FirstContact, "Prvi stik s tem gostiteljem. Primerjajte kodo s tisto na gostitelju."),
        (ErrorConnectRefused, "Gostitelj je zavrnil povezavo"),
        (ErrorTimeout, "Gostitelj se ni odzval"),
        (ErrorProtocol, "Nasprotna stran uporablja drug protokol"),
        (ErrorNoDecoder, "Za to obliko ni dekodirnika"),
        (TipBitrate, "Zgornja meja bitne hitrosti. Ob gibanju jo kodirnik izkoristi v celoti; v tujih omrežjih raje 25 do 50."),
        (TipFps, "Ciljna hitrost sličic. Več, kot daje zaslon Maca, ni mogoče."),
        (TipGaming, "Pogostejše ključne sličice in manj dovoljenega zaostanka: enakomerneje ob gibanju, stane nekaj bitne hitrosti."),
        (TipSound, "Prenašaj zvok. Izklopljeno prihrani okoli 3 Mbit/s; gostitelj takrat zvoka ne pošilja."),
        (TipCodec, "Kodek gostitelja, menjava med delovanjem; slika se za hip ustavi. \"s pretvorbo\" stane en prehod več."),
        (TipFullscreen, "Celozaslonsko brez robov. V oknu se slika prilagodi."),
        (TipPixelExact, "Slika 1:1 brez skaliranja. Če je okno manjše, vidite izrez."),
        (TipShowOverlay, "Prikaži statistiko zgoraj levo. Katere vrstice, nastavite desno."),
        (TipNerdMode, "Razširjena statistika: veriga zakasnitve kot stolpec, obremenitev gostitelja in odjemalca."),
        (TipStatRows, "Katere vrstice statistika prikazuje."),
        (TipDecoderAuto, "Grafična kartica, če obvlada kodek, sicer programsko."),
        (TipDecoderSoftware, "Dekodiranje na procesorju. Deluje povsod, stane računski čas."),
        (TipDecoderGpu, "Dekodiranje na grafični kartici. Če ne gre, se odjemalec vrne na programsko in pove, zakaj."),
        (TipDisconnect, "Prekini povezavo, nazaj na začetni zaslon."),
        (TabShortcuts, "Bližnjice"),
        (ShortcutMenu, "Odpri meni (ta ESC nikoli ne pride do Maca)"),
        (ShortcutBack, "Nazaj na začetni zaslon"),
        (ShortcutWinKey, "Tipka Windows = tipka Command na Macu"),
        (ShortcutOthers, "Vse druge tipke gredo na Mac. Prenaša se položaj tipke, ne znak – šumniki in AltGr delujejo sami od sebe."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Zaženi"),
        (BenchAbort, "Prekliči"),
        (BenchApply, "Uporabi"),
        (BenchDuration, "Trajanje na korak"),
        (BenchTestPattern, "Preizkusna slika"),
        (BenchStep, "Korak {n} od {m}"),
        (BenchPhaseSettings, "nastavljanje"),
        (BenchPhaseSettle, "umirjanje"),
        (BenchPhaseMeasure, "merjenje"),
        (BenchFailed, "ni uspel"),
        (BenchDone, "Končano"),
        (BenchAborted, "Preklicano"),
        (BenchMeasured, "izmerjeno"),
        (BenchChain, "Veriga"),
        (BenchColFps, "fps"),
        (BenchColDropped, "izpuščene"),
        (BenchColHostCpu, "CPU gostitelja"),
        (BenchRecommendation, "Priporočilo"),
        (BenchNoRecommendation, "Noben korak ni uspel. Poskusite nižjo bitno hitrost ali hitrost sličic."),
        (BenchHint, "Meri se to, kar se trenutno dogaja na Macu. Koraki so primerljivi le, ko se kaj premika – dovolj je predvajan video."),
        (BenchHintPattern, "S preizkusno sliko vsak korak vidi isto gibljivo vsebino – na Macu ni treba, da kaj teče."),
        (TipBenchStart, "Po vrsti izmeri vse kombinacije izbranih kodekov, hitrosti sličic in bitnih hitrosti, vsako za nastavljeni čas. Slika teče naprej, meni lahko ostane odprt."),
        (TipBenchApply, "Nastavi priporočeni kodek in nastavitve ter jih shrani za tega gostitelja."),
        (TipBenchDuration, "Čas merjenja na korak. Daljši je mirnejši; 5 s običajno zadostuje."),
        (TipBenchHint, "Korak uspe, če veriga ostane znotraj ene in pol sličice, prispe vsaj 95 % sličic, nobena ni izpuščena in kodirnik ostane v svojem proračunu na sličico. Priporočena je najboljša barvna kakovost, ki uspe pri najvišji hitrosti sličic, z najvišjo bitno hitrostjo, pri kateri še uspe."),
        (TipBenchTestPattern, "Med izvajanjem gostitelj namesto zaslona kaže stalen gibljiv vzorec – vsak korak meri isto vsebino."),
    ],
};

pub static HR: Lang = Lang {
    code: "hr",
    name: "Hrvatski",
    table: &[
        (AppSubtitle, "Udaljena radna površina s punim detaljima boje"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini vezu"),
        (HostAddress, "Adresa hosta"),
        (SearchingHosts, "Traženje hostova"),
        (NoHostsFound, "Nema pronađenih hostova"),
        (FoundHosts, "Pronađeni hostovi"),
        (Settings, "Postavke"),
        (Language, "Jezik"),
        (Quit, "Izlaz"),
        (Connecting, "Povezivanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Veza prekinuta"),
        (Reconnecting, "Ponovno povezivanje"),
        (Fullscreen, "Cijeli zaslon"),
        (PixelExact, "Pikselna točnost"),
        (Stretch, "Prilagodi prozoru"),
        (ShowOverlay, "Prikaži statistiku"),
        (Fps, "Sličica u sekundi"),
        (DecodeTime, "Vrijeme dekodiranja"),
        (Bitrate, "Brzina prijenosa"),
        (Resolution, "Razlučivost"),
        (Codec, "Kodek"),
        (Latency, "Kašnjenje"),
        (EncodeTime, "Vrijeme kodiranja"),
        (NetworkTime, "Vrijeme prijenosa"),
        (AudioBuffer, "Međuspremnik zvuka"),
        (Dropped, "Ispušteno"),
        (MaxBitrate, "Najveća brzina prijenosa"),
        (MaxFps, "Najveći broj sličica"),
        (ExpertMode, "Stručni način"),
        (GamingMode, "Način za igre"),
        (FixedRate, "Stalan broj sličica"),
        (FixedRateHint, "Održava broj sličica i kad se ništa ne miče. Stalno opterećenje hosta."),
        (Sound, "Zvuk"),
        (HoldEscHint, "Držite ESC za izbornik"),
        (NerdMode, "Način za nerdove"),
        (More, "Više"),
        (Back, "Natrag"),
        (SavedForHost, "Spremljeno za ovaj host"),
        (Queue, "Snimanje i čekanje"),
        (OneFrame, "Jedna sličica"),
        (Bottleneck, "Usko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbom"),
        (CodecSwitching, "Promjena kodeka"),
        (HostCpu, "Procesor hosta"),
        (HostGpu, "Grafika hosta"),
        (HostRam, "Memorija hosta"),
        (NoDisplay, "Host trenutno nema zaslon"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "uključeno"),
        (EncryptionOff, "isključeno"),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Međuspremnik"),
        (DecoderLabel, "Dekoder"),
        (DecoderAuto, "Automatski"),
        (DecoderSoftware, "Softverski"),
        (DecoderNvidia, "Grafička kartica"),
        (DisplayLabel, "Prikaz"),
        (DisplayStage, "Prikaz"),
        (ClientCpu, "Procesor klijenta"),
        (Monitor, "Monitor"),
        (Skipped, "preskočeno"),
        (PairingTitle, "Uparivanje s hostom"),
        (PairingHint, "Unesite kod prikazan na hostu"),
        (PairingCode, "Kod za uparivanje"),
        (PairingWrong, "Netočan kod"),
        (PairingOk, "Upareno"),
        (SecuredWith, "Zaštićeno · kod za provjeru"),
        (HostFingerprint, "Otisak ključa hosta"),
        (NotPaired, "Ovaj host još ne poznaje vaš uređaj. Pokrenite host s --pair i povežite se ponovno."),
        (FirstContact, "Prvi kontakt s ovim hostom. Usporedite kod s onim na hostu."),
        (ErrorConnectRefused, "Host je odbio vezu"),
        (ErrorTimeout, "Host nije odgovorio"),
        (ErrorProtocol, "Druga strana koristi drugi protokol"),
        (ErrorNoDecoder, "Nema dekodera za ovaj format"),
        (TipBitrate, "Gornja granica brzine prijenosa. Pri pokretu enkoder je iskoristi u cijelosti; u tuđim mrežama radije 25 do 50."),
        (TipFps, "Ciljani broj sličica. Više nego što daje zaslon Maca nije moguće."),
        (TipGaming, "Češće ključne sličice i manje dopuštenog zaostatka: ujednačenije pri pokretu, košta nešto brzine prijenosa."),
        (TipSound, "Prenosi zvuk. Isključeno štedi oko 3 Mbit/s; host tada ne šalje zvuk."),
        (TipCodec, "Kodek hosta, mijenja se u radu; slika na trenutak stane. \"s pretvorbom\" košta jedan prolaz više."),
        (TipFullscreen, "Cijeli zaslon bez rubova. U prozoru se slika prilagođava."),
        (TipPixelExact, "Slika 1:1 bez skaliranja. Ako je prozor manji, vidi se isječak."),
        (TipShowOverlay, "Prikaži statistiku gore lijevo. Koji redci, odabire se desno."),
        (TipNerdMode, "Proširena statistika: lanac kašnjenja kao traka, opterećenje hosta i klijenta."),
        (TipStatRows, "Koje retke statistika prikazuje."),
        (TipDecoderAuto, "Grafička kartica ako podržava kodek, inače softverski."),
        (TipDecoderSoftware, "Dekodiranje na procesoru. Radi svugdje, košta računsko vrijeme."),
        (TipDecoderGpu, "Dekodiranje na grafičkoj kartici. Ako ne može, klijent se vraća na softverski i kaže zašto."),
        (TipDisconnect, "Prekini vezu, natrag na početni zaslon."),
        (TabShortcuts, "Prečaci"),
        (ShortcutMenu, "Otvori izbornik (ovaj ESC nikad ne stiže do Maca)"),
        (ShortcutBack, "Natrag na početni zaslon"),
        (ShortcutWinKey, "Tipka Windows = tipka Command na Macu"),
        (ShortcutOthers, "Sve ostale tipke idu na Mac. Prenosi se položaj tipke, ne znak – č, ć, š, ž i AltGr rade sami od sebe."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Pokreni"),
        (BenchAbort, "Odustani"),
        (BenchApply, "Primijeni"),
        (BenchDuration, "Trajanje po koraku"),
        (BenchTestPattern, "Testna slika"),
        (BenchStep, "Korak {n} od {m}"),
        (BenchPhaseSettings, "postavljanje"),
        (BenchPhaseSettle, "smirivanje"),
        (BenchPhaseMeasure, "mjerenje"),
        (BenchFailed, "neuspješan"),
        (BenchDone, "Gotovo"),
        (BenchAborted, "Prekinuto"),
        (BenchMeasured, "izmjereno"),
        (BenchChain, "Lanac"),
        (BenchColFps, "fps"),
        (BenchColDropped, "ispušteno"),
        (BenchColHostCpu, "CPU hosta"),
        (BenchRecommendation, "Preporuka"),
        (BenchNoRecommendation, "Nijedan korak nije prošao. Pokušajte s nižom brzinom prijenosa ili manjim brojem sličica."),
        (BenchHint, "Mjeri se ono što se trenutno događa na Macu. Koraci su usporedivi samo kad se nešto miče – dovoljan je video koji se reproducira."),
        (BenchHintPattern, "S testnom slikom svaki korak vidi isti pokretni sadržaj – na Macu ne mora ništa raditi."),
        (TipBenchStart, "Redom mjeri sve kombinacije odabranih kodeka, brojeva sličica i brzina prijenosa, svaku tijekom postavljenog vremena. Slika teče dalje, a izbornik može ostati otvoren."),
        (TipBenchApply, "Postavi preporučeni kodek i postavke te ih spremi za ovaj host."),
        (TipBenchDuration, "Vrijeme mjerenja po koraku. Dulje je stabilnije; 5 s obično je dovoljno."),
        (TipBenchHint, "Korak prolazi ako lanac ostane unutar jedne i pol sličice, stigne barem 95 % sličica, nijedna nije ispuštena i enkoder ostane unutar svog proračuna po sličici. Preporučuje se najbolja kvaliteta boje koja prolazi pri najvećem broju sličica, s najvećom brzinom prijenosa pri kojoj još prolazi."),
        (TipBenchTestPattern, "Za vrijeme izvođenja host umjesto zaslona prikazuje fiksni pokretni uzorak – svaki korak mjeri isti sadržaj."),
    ],
};

pub static UK: Lang = Lang {
    code: "uk",
    name: "Українська",
    table: &[
        (AppSubtitle, "Віддалений робочий стіл з повною деталізацією кольору"),
        (Connect, "Підключитися"),
        (Disconnect, "Відключитися"),
        (HostAddress, "Адреса хоста"),
        (SearchingHosts, "Пошук хостів"),
        (NoHostsFound, "Хостів не знайдено"),
        (FoundHosts, "Знайдені хости"),
        (Settings, "Налаштування"),
        (Language, "Мова"),
        (Quit, "Вийти"),
        (Connecting, "Підключення"),
        (Connected, "Підключено"),
        (ConnectionLost, "З'єднання втрачено"),
        (Reconnecting, "Повторне підключення"),
        (Fullscreen, "Повний екран"),
        (PixelExact, "Піксельна точність"),
        (Stretch, "Вписати у вікно"),
        (ShowOverlay, "Показати статистику"),
        (Fps, "Кадрів за секунду"),
        (DecodeTime, "Час декодування"),
        (Bitrate, "Бітрейт"),
        (Resolution, "Роздільність"),
        (Codec, "Кодек"),
        (Latency, "Затримка"),
        (EncodeTime, "Час кодування"),
        (NetworkTime, "Час передачі"),
        (AudioBuffer, "Буфер звуку"),
        (Dropped, "Пропущено"),
        (MaxBitrate, "Максимальний бітрейт"),
        (MaxFps, "Максимальна частота кадрів"),
        (ExpertMode, "Режим експерта"),
        (GamingMode, "Ігровий режим"),
        (FixedRate, "Стала частота кадрів"),
        (FixedRateHint, "Утримує частоту кадрів, навіть коли нічого не рухається. Постійне навантаження на хост."),
        (Sound, "Звук"),
        (HoldEscHint, "Утримуйте ESC для меню"),
        (NerdMode, "Режим нерда"),
        (More, "Більше"),
        (Back, "Назад"),
        (SavedForHost, "Збережено для цього хоста"),
        (Queue, "Захоплення і черга"),
        (OneFrame, "Один кадр"),
        (Bottleneck, "Вузьке місце"),
        (TabPicture, "Зображення"),
        (TabDisplay, "Екран"),
        (CodecConverted, "з перетворенням"),
        (CodecSwitching, "Зміна кодека"),
        (HostCpu, "Процесор хоста"),
        (HostGpu, "Графіка хоста"),
        (HostRam, "Пам'ять хоста"),
        (NoDisplay, "У хоста зараз немає екрана"),
        (Encryption, "Шифрування"),
        (EncryptionOn, "увімкнено"),
        (EncryptionOff, "вимкнено"),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Буфер обміну"),
        (DecoderLabel, "Декодер"),
        (DecoderAuto, "Автоматично"),
        (DecoderSoftware, "Програмний"),
        (DecoderNvidia, "Відеокарта"),
        (DisplayLabel, "Екран"),
        (DisplayStage, "Екран"),
        (ClientCpu, "Процесор клієнта"),
        (Monitor, "Монітор"),
        (Skipped, "не показано"),
        (PairingTitle, "Створення пари з хостом"),
        (PairingHint, "Введіть код, показаний на хості"),
        (PairingCode, "Код підключення"),
        (PairingWrong, "Неправильний код"),
        (PairingOk, "Пару створено"),
        (SecuredWith, "Захищено · код підтвердження"),
        (HostFingerprint, "Відбиток ключа хоста"),
        (NotPaired, "Цей хост ще не знає вашого пристрою. Запустіть хост із --pair і підключіться знову."),
        (FirstContact, "Перший контакт із цим хостом. Порівняйте код із тим, що на хості."),
        (ErrorConnectRefused, "Хост відхилив з'єднання"),
        (ErrorTimeout, "Хост не відповів"),
        (ErrorProtocol, "Інша сторона використовує інший протокол"),
        (ErrorNoDecoder, "Немає декодера для цього формату"),
        (TipBitrate, "Верхня межа бітрейту. Під час руху кодер використовує її повністю; в чужих мережах краще 25–50."),
        (TipFps, "Цільова частота кадрів. Більше, ніж дає екран Mac, не вийде."),
        (TipGaming, "Частіші ключові кадри й менше допустиме відставання: рівніше під час руху, коштує трохи бітрейту."),
        (TipSound, "Передавати звук. Вимкнено заощаджує близько 3 Мбіт/с; хост тоді звук не надсилає."),
        (TipCodec, "Кодек хоста, перемикається на ходу; зображення на мить завмирає. \"з перетворенням\" коштує один додатковий прохід."),
        (TipFullscreen, "Повний екран без рамки. У вікні зображення вписується."),
        (TipPixelExact, "Зображення 1:1 без масштабування. Якщо вікно менше, видно лише частину."),
        (TipShowOverlay, "Показувати статистику вгорі ліворуч. Які рядки – праворуч."),
        (TipNerdMode, "Розширена статистика: ланцюжок затримки як смуга, навантаження хоста і клієнта."),
        (TipStatRows, "Які рядки показує статистика."),
        (TipDecoderAuto, "Відеокарта, якщо вона підтримує кодек, інакше програмно."),
        (TipDecoderSoftware, "Декодування на процесорі. Працює всюди, коштує процесорного часу."),
        (TipDecoderGpu, "Декодування на відеокарті. Якщо не вдається, клієнт повертається до програмного і каже чому."),
        (TipDisconnect, "Завершити з'єднання, назад до початкового екрана."),
        (TabShortcuts, "Клавіші"),
        (ShortcutMenu, "Відкрити меню (цей ESC ніколи не доходить до Mac)"),
        (ShortcutBack, "Назад до початкового екрана"),
        (ShortcutWinKey, "Клавіша Windows = клавіша Command на Mac"),
        (ShortcutOthers, "Усі інші клавіші йдуть на Mac. Передається положення клавіші, а не символ – кирилиця та AltGr працюють самі собою."),
        // Benchmark
        (TabBenchmark, "Бенчмарк"),
        (BenchStart, "Старт"),
        (BenchAbort, "Скасувати"),
        (BenchApply, "Застосувати"),
        (BenchDuration, "Тривалість кроку"),
        (BenchTestPattern, "Тестове зображення"),
        (BenchStep, "Крок {n} з {m}"),
        (BenchPhaseSettings, "застосування налаштувань"),
        (BenchPhaseSettle, "стабілізація"),
        (BenchPhaseMeasure, "вимірювання"),
        (BenchFailed, "невдалий"),
        (BenchDone, "Готово"),
        (BenchAborted, "Скасовано"),
        (BenchMeasured, "виміряно"),
        (BenchChain, "Ланцюжок"),
        (BenchColFps, "fps"),
        (BenchColDropped, "пропущено"),
        (BenchColHostCpu, "CPU хоста"),
        (BenchRecommendation, "Рекомендація"),
        (BenchNoRecommendation, "Жоден крок не пройшов. Спробуйте нижчий бітрейт або частоту кадрів."),
        (BenchHint, "Вимірюється те, що зараз відбувається на Mac. Кроки можна порівнювати лише тоді, коли щось рухається – достатньо відео, що відтворюється."),
        (BenchHintPattern, "З тестовим зображенням кожен крок бачить той самий рухомий вміст – на Mac нічого не має працювати."),
        (TipBenchStart, "По черзі вимірює всі комбінації вибраних кодеків, частот кадрів і бітрейтів, кожну протягом заданого часу. Зображення йде далі, меню може лишатися відкритим."),
        (TipBenchApply, "Установити рекомендований кодек і налаштування та зберегти їх для цього хоста."),
        (TipBenchDuration, "Час вимірювання на крок. Довше – стабільніше; 5 с зазвичай достатньо."),
        (TipBenchHint, "Крок проходить, якщо ланцюжок вкладається в півтора кадру, надходить щонайменше 95 % кадрів, жоден не пропущено і кодер вкладається у свій бюджет на кадр. Рекомендується найкраща якість кольору, яка проходить на найвищій частоті кадрів, із найвищим бітрейтом, за якого вона ще проходить."),
        (TipBenchTestPattern, "На час вимірювання хост показує замість екрана фіксований рухомий візерунок – кожен крок вимірює той самий вміст."),
    ],
};
