// Sprachtabellen ausserhalb Europas plus Tuerkisch:
// Russisch (ru), Chinesisch vereinfacht (zh), Japanisch (ja), Tuerkisch (tr).
//
// Aufbau und Schluessel wie in strings.rs. Jede Tabelle enthaelt jeden
// Schluessel genau einmal.

use crate::strings::{Key::*, Lang};

pub static RU: Lang = Lang {
    code: "ru",
    name: "Русский",
    table: &[
        (AppSubtitle, "Удалённый рабочий стол с полной цветопередачей"),
        (Connect, "Подключиться"),
        (Disconnect, "Отключиться"),
        (HostAddress, "Адрес хоста"),
        (SearchingHosts, "Поиск хостов"),
        (NoHostsFound, "Хосты не найдены"),
        (FoundHosts, "Найденные хосты"),
        (Settings, "Настройки"),
        (Language, "Язык"),
        (Quit, "Выход"),
        (Connecting, "Подключение"),
        (Connected, "Подключено"),
        (ConnectionLost, "Соединение потеряно"),
        (Reconnecting, "Переподключение"),
        (Fullscreen, "Полный экран"),
        (PixelExact, "Пиксель в пиксель"),
        (Stretch, "По размеру окна"),
        (ShowOverlay, "Показывать статистику"),
        (Fps, "Кадров в секунду"),
        (DecodeTime, "Время декодирования"),
        (Bitrate, "Битрейт"),
        (Resolution, "Разрешение"),
        (Codec, "Кодек"),
        (Latency, "Задержка"),
        (EncodeTime, "Время кодирования"),
        (NetworkTime, "Время передачи"),
        (AudioBuffer, "Буфер звука"),
        (Dropped, "Потеряно"),
        (MaxBitrate, "Макс. битрейт"),
        (MaxFps, "Макс. частота кадров"),
        (ExpertMode, "Экспертный режим"),
        (GamingMode, "Игровой режим"),
        (FixedRate, "Постоянная частота кадров"),
        (FixedRateHint, "Удерживает частоту кадров, даже когда ничего не движется. Постоянная нагрузка на хост."),
        (Sound, "Звук"),
        (HoldEscHint, "Удерживайте ESC для меню"),
        (NerdMode, "Режим гика"),
        (More, "Ещё"),
        (Back, "Назад"),
        (SavedForHost, "Сохранено для этого хоста"),
        (Queue, "Захват и очередь"),
        (OneFrame, "Один кадр"),
        (Bottleneck, "Узкое место"),
        (TabPicture, "Изображение"),
        (TabDisplay, "Экран"),
        (CodecConverted, "с конвертацией"),
        (CodecSwitching, "Смена кодека"),
        (HostCpu, "Процессор хоста"),
        (HostGpu, "Графика хоста"),
        (HostRam, "Память хоста"),
        (NoDisplay, "У хоста сейчас нет экрана"),
        (Encryption, "Шифрование"),
        (EncryptionOn, "вкл."),
        (EncryptionOff, "выкл."),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Буфер обмена"),
        (DecoderLabel, "Декодер"),
        (RoleAuto, "Автоматически"),
        (RoleCpu, "Процессор"),
        (RoleGpu, "Видеокарта"),
        (RoleGpuN, "Видеокарта {n}"),
        (RoleIntegrated, "Встроенная"),
        (NextStartHint, "действует со следующего запуска"),
        (AdapterWithOutput, "с выходом на экран"),
        (AdapterNoOutput, "без выхода на экран"),
        (TipOnly420, "Только 4:2:0 и H.264 (D3D11VA); при 4:4:4 клиент возвращается к процессору – смените кодек на вкладке Изображение."),
        (DisplayLabel, "Экран"),
        (DisplayStage, "Экран"),
        (ClientCpu, "Процессор клиента"),
        (Monitor, "Монитор"),
        (Skipped, "пропущено"),
        (SecuredWith, "Защищено · код подтверждения"),
        (HostFingerprint, "Отпечаток ключа хоста"),
        (ErrorConnectRefused, "Хост отклонил подключение"),
        (ErrorTimeout, "Хост не отвечает"),
        (ErrorProtocol, "Хост использует другой протокол"),
        (ErrorNoDecoder, "Нет декодера для этого формата"),
        (SessionTakenOver, "Сеанс перешёл к другому устройству."),
        (KeyFileDamaged, "Файл ключа {p} повреждён и оставлен как есть. Проверьте или удалите его – тогда будет создан новый ключ, и устройство придётся снова разрешить с помощью пароля."),
        (FileUnreadable, "Не удаётся прочитать {p} – подключение не выполняется."),
        (FileNotUtf8, "{p} сохранён не в UTF-8 – подключение не выполняется."),
        (FileNotWritable, "Не удаётся записать {p} – подключение не выполняется."),
        (StorageUnavailable, "Папка для ключей и настроек недоступна – подключение не выполняется."),
        (ErrorAddress, "Не удаётся разрешить адрес {n}"),
        (ErrorNoConnection, "Нет подключения к хосту"),
        (ErrorHandshake, "Не удалось установить защищённое подключение"),
        (ErrorFfmpegStart, "Не удалось запустить FFmpeg"),
        (ErrorSound, "Звук недоступен"),
        (ErrorGpuDisplay, "Видеокарта непригодна, вывод идёт программно"),
        (ErrorGpuLost, "Видеокарта потеряна – перезапустите с ключом --anzeige cpu"),
        (ErrorPixelFormat, "Декодер выдаёт изображения, которые этот клиент не может показать"),
        (DecoderFallback, "Выбранная видеокарта не декодирует – работает программный декодер"),
        (TipBitrate, "Верхняя граница битрейта. При движении кодер использует её полностью; в чужих сетях лучше 25–50."),
        (TipFps, "Целевая частота кадров. Больше, чем даёт экран Mac, не получится."),
        (TipGaming, "Чаще ключевые кадры и меньше допустимого отставания: ровнее при движении, стоит немного битрейта."),
        (TipSound, "Передавать звук. Выкл. экономит около 3 Мбит/с; хост тогда звук не отправляет."),
        (TipCodec, "Кодек хоста, переключается на ходу; картинка на миг замирает. \"с конвертацией\" стоит один лишний проход."),
        (TipFullscreen, "Полный экран без рамки. В окне картинка вписывается."),
        (TipPixelExact, "Картинка 1:1 без масштабирования. Если окно меньше, видна только часть."),
        (TipShowOverlay, "Показывать статистику слева вверху. Какие строки – справа."),
        (TipNerdMode, "Расширенная статистика: цепочка задержки в виде полосы, нагрузка хоста и клиента."),
        (TipStatRows, "Какие строки показывает статистика."),
        (TipDecoderAuto, "NVDEC на карте NVIDIA; иначе D3D11VA на карте, которая рисует (только 4:2:0 и H.264); иначе процессор."),
        (TipDecoderCpu, "Декодирование на процессоре. Работает везде, стоит процессорного времени."),
        (TipDecoderGpu, "Декодирование на видеокарте. Если не выходит, клиент возвращается к процессору и говорит почему."),
        (TipDecoderIntegrated, "Декодирование на встроенной графике (D3D11VA). Если не выходит, клиент возвращается к процессору и говорит почему."),
        (TipDisplayAuto, "Direct3D 11 на первой карте с выходом на экран, иначе на первой карте NVIDIA, иначе на первой, какая есть. Без карты: процессор. Действует со следующего запуска."),
        (TipDisplayGpu, "Рисование через Direct3D 11 на этой карте. Действует со следующего запуска."),
        (TipDisplayIntegrated, "Рисование через Direct3D 11 на встроенной графике – к ней обычно подключён экран. Действует со следующего запуска."),
        (TipDisplayCpu, "Рисование на процессоре, без Direct3D. Работает везде, стоит процессорного времени. Действует со следующего запуска."),
        (TipDisconnect, "Завершить соединение, назад на начальный экран."),
        (TabShortcuts, "Клавиши"),
        (ShortcutMenu, "Открыть меню (этот ESC никогда не доходит до Mac)"),
        (ShortcutBack, "Назад на начальный экран"),
        (ShortcutWinKey, "Клавиша Windows = клавиша Command на Mac"),
        (ShortcutOthers, "Все остальные клавиши идут на Mac. Передаётся положение клавиши, а не символ – кириллица и AltGr работают сами собой."),
        // Benchmark
        (TabBenchmark, "Бенчмарк"),
        (BenchStart, "Старт"),
        (BenchAbort, "Отмена"),
        (BenchApply, "Применить"),
        (BenchDuration, "Длительность шага"),
        (BenchTestPattern, "Тестовая картинка"),
        (BenchStep, "Шаг {n} из {m}"),
        (BenchPhaseSettings, "применение настроек"),
        (BenchPhaseSettle, "стабилизация"),
        (BenchPhaseMeasure, "измерение"),
        (BenchFailed, "не удался"),
        (BenchDone, "Готово"),
        (BenchAborted, "Отменено"),
        (BenchMeasured, "измерено"),
        (BenchChain, "Цепочка"),
        (BenchColFps, "fps"),
        (BenchColDropped, "потеряно"),
        (BenchColHostCpu, "CPU хоста"),
        (BenchRecommendation, "Рекомендация"),
        (BenchNoRecommendation, "Ни один шаг не прошёл: цепочка больше 30 ms или слишком мало кадров. Попробуйте меньшую частоту кадров или битрейт."),
        (BenchHint, "Измеряется то, что сейчас происходит на Mac. Шаги сравнимы только тогда, когда что-то движется – достаточно воспроизводимого видео."),
        (BenchHintPattern, "С тестовой картинкой каждый шаг видит одно и то же движущееся содержимое – на Mac ничего не должно быть запущено."),
        (TipBenchStart, "По очереди измеряет все комбинации выбранных кодеков, частот кадров и битрейтов, каждую в течение заданного времени. Картинка идёт дальше, меню может оставаться открытым."),
        (TipBenchApply, "Установить рекомендованный кодек и настройки и сохранить их для этого хоста."),
        (TipBenchDuration, "Время измерения на шаг. Дольше – стабильнее; 5 с обычно достаточно."),
        (TipBenchHint, "Шаг проходит, если приходит не менее 95 % целевой частоты кадров, потеряно менее 1 % кадров и вся цепочка укладывается в 30 ms – независимо от частоты кадров. Время кодера хоста показывается, но не оценивается. Рекомендуется: лучшее качество цвета, которое проходит на самой высокой частоте кадров, с самым высоким битрейтом."),
        (TipBenchTestPattern, "На время измерения хост показывает вместо экрана фиксированный движущийся узор – каждый шаг измеряет одно и то же содержимое."),
        (DesktopShortcut, "Ярлык"),
        (TipDesktopShortcut, "Создаёт на рабочем столе ярлык для этого хоста. Двойной щелчок сразу подключает."),
        (DesktopShortcutCreated, "Ярлык создан на рабочем столе: {n}"),
        (DesktopShortcutFailed, "Ярлык не создан: {n}"),
        (DesktopShortcutDescription, "QuadChroma: подключиться к {n} ({m})"),
        (FilesSending, "Отправка файлов: {n} из {m}"),
        (FilesReceiving, "Получение файлов: {n} из {m}"),
        (FilesReady, "Файлы готовы к вставке: {n}"),
        (FilesSent, "Файлы переданы: {n}"),
        (FilesAborted, "Передача файлов прервана: {n}"),
        (FilesTooLarge, "Файлы не переданы: более 4 GB или 10 000 элементов"),
        (FilesPeerOld, "Другая сторона пока не может принимать файлы."),
        (TrayOpen, "Открыть"),
        (TrayConnect, "Подключиться: {n}"),
        (TrayQuit, "Выход"),
        (TrayStillRunning, "QuadChroma продолжает работать в области уведомлений."),
        (TrayStillRunningMac, "QuadChroma продолжает работать в строке меню."),
        (FilesAbortLocal, "этим устройством"),
        (FilesAbortPeer, "другой стороной"),
        (FilesAbortConnection, "соединение прервано"),
        (FilesAbortTimeout, "тайм-аут без прогресса"),
        (FilesAbortNoSpace, "недостаточно места на диске"),
        (FilesAbortInvalid, "недопустимые данные"),
        (FilesAbortRead, "ошибка чтения"),
        (FilesAbortWrite, "ошибка записи"),
        (FilesAbortClipboard, "буфер обмена недоступен"),
        (ScreenLabel, "Экран хоста"),
        (ScreenAuto, "Автоматически"),
        (TipScreen, "Какой экран хоста ты видишь. Автоматически следует за главным экраном; фиксированный экран действует, пока ты не выберешь другое."),
        (ScreenSwitching, "Смена экрана …"),
        (ScreenFallback, "{n} не подключён – запасной: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Пароль для компьютера {n}"),
        (AccessText, "{n} ещё не знает это устройство. Введите пароль, указанный в меню QuadChroma на компьютере {n}."),
        (AccessOrAllow, "Или попросите кого-нибудь у компьютера {n} нажать \"Разрешить\"."),
        (AccessCode, "Код: {c}"),
        (AccessPassword, "Пароль"),
        (AccessShow, "Показать"),
        (AccessCancel, "Отмена"),
        (AccessChecking, "Проверка …"),
        (AccessWrong, "Неверный пароль."),
        (AccessWait, "Слишком много попыток. Повторите через {s} с."),
        (AccessNewIdentity, "Устройство по этому адресу сменило идентификатор (ID {i})."),
        (MsgRefused, "Компьютер {n} отклонил подключение."),
        (MsgNoAnswer, "Компьютер {n} не отвечает. Попробуйте ещё раз."),
        (MsgTooManyAttempts, "Слишком много попыток. Подождите немного и попробуйте снова."),
        (MsgHostOutdated, "На компьютере {n} установлена более старая версия QuadChroma. Обновите её там."),
        (MsgHostProofBad, "Компьютер {n} не смог подтвердить пароль. Подключение прервано в целях безопасности."),
        (MsgOtherDevice, "По этому адресу отвечает другое устройство."),
        (MsgIdNotFound, "В сети не найдено устройство с ID {i}."),
        (StartId, "ID {i}"),
        (StartShare, "Открыть доступ к этому ПК"),
        (StartSharing, "Доступ открыт"),
        (HostReady, "Готов к подключениям"),
        (HostConnected, "Подключено: {n}"),
        (HostDeviceId, "ID устройства: {i}"),
        (HostPassword, "Пароль: {p}"),
        (HostCopied, "Скопировано"),
        (HostChangePassword, "Изменить пароль …"),
        (HostRandomPassword, "Новый случайный пароль"),
        (HostNewPassword, "Новый пароль (не менее 8 символов)"),
        (HostRepeatPassword, "Повторите пароль"),
        (HostPasswordsDiffer, "Пароли не совпадают."),
        (HostPasswordShort, "Нужно не менее 8 символов."),
        (HostPasswordSaved, "Пароль сохранён."),
        (HostPasswordUnreadable, "Файл пароля не читается – новые устройства только через \"Разрешить\"."),
        (HostDevices, "Разрешённые устройства"),
        (HostNoDevices, "Устройств пока нет"),
        (HostDeviceLine, "{n} – ID {i} – с {d}"),
        (HostRemove, "Удалить"),
        (HostRemoveAll, "Удалить все устройства …"),
        (HostRemoveAllAsk, "Удалить все разрешённые устройства? Им снова понадобится пароль."),
        (HostListDamaged, "Список устройств повреждён"),
        (HostListReset, "Сбросить список устройств"),
        (HostRequest, "{n} (ID {i}) хочет управлять этим компьютером."),
        (HostAllow, "Разрешить"),
        (HostDeny, "Отклонить"),
        (HostStartLogin, "Запускать при входе"),
        (HostStartWindows, "Запускать вместе с Windows"),
        (HostMoveToApps, "Сначала переместите QuadChroma в папку Программы"),
        (HostScreenMissing, "Запись экрана не разрешена – открыть Системные настройки …"),
        (HostAccessMissing, "Универсальный доступ не разрешён – открыть Системные настройки …"),
        (HostPortBusy, "Порт {p} занят другой программой"),
        (HostQuit, "Выход из QuadChroma"),
        (HostStopSharing, "Закрыть доступ"),
        (HostTooltip, "QuadChroma – доступ к этому ПК открыт (ID {i})"),
        (HostOk, "OK"),
        (AccessHide, "Скрыть"),
        (MsgShareFailed, "Не удалось открыть доступ к этому ПК."),
        (MsgDeviceRemoved, "{n} больше не знает это устройство. Подключитесь снова и введите пароль."),
        (HostPasswordNotSaved, "Не удалось сохранить пароль."),
        (HostPasswordInvalid, "Пароль содержит недопустимые символы."),
        (HostPasswordTitle, "Изменить пароль"),
        (MsgHostUnverified, "Компьютер {n} не подтвердил свою подлинность. Подключение прервано в целях безопасности."),
        (MsgHostQuit, "Компьютер {n} закрыл QuadChroma."),
        (MsgHostSharingOff, "Компьютер {n} прекратил предоставлять доступ."),
        (MsgHostRemovedYou, "Компьютер {n} удалил это устройство."),
        (MsgSelf, "Это и есть этот компьютер."),
        (TrayOpenApp, "Открыть QuadChroma"),
        (HostSharingIsOff, "Доступ отключён"),
        (DeviceNameChange, "Изменить имя устройства …"),
        (DeviceNameTitle, "Имя устройства"),
        (DeviceNameLabel, "Другие устройства видят этот компьютер под этим именем:"),
        (DeviceNameHint, "Оставьте пустым, чтобы использовать имя компьютера ({n})."),
        (DeviceNameTooLong, "Имя слишком длинное (не более 40 байт)."),
        (DeviceNameInvalid, "Имя содержит недопустимые символы."),
        (ThisComputer, "Этот компьютер: {n} · {i}"),
        (DeviceNameRename, "Переименовать"),
        (PreventSleep, "Не допускать спящего режима, пока работает QuadChroma"),
    ],
};

pub static ZH: Lang = Lang {
    code: "zh",
    name: "简体中文",
    table: &[
        (AppSubtitle, "完整色彩细节的远程桌面"),
        (Connect, "连接"),
        (Disconnect, "断开连接"),
        (HostAddress, "主机地址"),
        (SearchingHosts, "正在搜索主机"),
        (NoHostsFound, "未找到主机"),
        (FoundHosts, "找到的主机"),
        (Settings, "设置"),
        (Language, "语言"),
        (Quit, "退出"),
        (Connecting, "正在连接"),
        (Connected, "已连接"),
        (ConnectionLost, "连接已断开"),
        (Reconnecting, "正在重新连接"),
        (Fullscreen, "全屏"),
        (PixelExact, "像素对应"),
        (Stretch, "适应窗口"),
        (ShowOverlay, "显示统计"),
        (Fps, "每秒帧数"),
        (DecodeTime, "解码时间"),
        (Bitrate, "码率"),
        (Resolution, "分辨率"),
        (Codec, "编解码器"),
        (Latency, "延迟"),
        (EncodeTime, "编码时间"),
        (NetworkTime, "传输时间"),
        (AudioBuffer, "音频缓冲"),
        (Dropped, "丢帧"),
        (MaxBitrate, "最大码率"),
        (MaxFps, "最高帧率"),
        (ExpertMode, "专家模式"),
        (GamingMode, "游戏模式"),
        (FixedRate, "固定帧率"),
        (FixedRateHint, "即使画面静止也保持帧率。主机会持续承受负载。"),
        (Sound, "声音"),
        (HoldEscHint, "继续按住 ESC 打开菜单"),
        (NerdMode, "极客模式"),
        (More, "更多"),
        (Back, "返回"),
        (SavedForHost, "已为此主机保存"),
        (Queue, "采集与排队"),
        (OneFrame, "一帧"),
        (Bottleneck, "瓶颈"),
        (TabPicture, "画面"),
        (TabDisplay, "显示"),
        (CodecConverted, "需转换"),
        (CodecSwitching, "正在切换编解码器"),
        (HostCpu, "主机 CPU"),
        (HostGpu, "主机 GPU"),
        (HostRam, "主机内存"),
        (NoDisplay, "主机目前没有显示器"),
        (Encryption, "加密"),
        (EncryptionOn, "开"),
        (EncryptionOff, "关"),
        (AudioEnabled, "音频"),
        (ClipboardEnabled, "剪贴板"),
        (DecoderLabel, "解码器"),
        (RoleAuto, "自动"),
        (RoleCpu, "处理器"),
        (RoleGpu, "显卡"),
        (RoleGpuN, "显卡 {n}"),
        (RoleIntegrated, "集成显卡"),
        (NextStartHint, "下次启动起生效"),
        (AdapterWithOutput, "有显示输出"),
        (AdapterNoOutput, "无显示输出"),
        (TipOnly420, "仅 4:2:0 和 H.264（D3D11VA）；4:4:4 会回退到处理器，请在画面标签页切换编解码器。"),
        (DisplayLabel, "显示"),
        (DisplayStage, "显示"),
        (ClientCpu, "客户端 CPU"),
        (Monitor, "显示器"),
        (Skipped, "跳过"),
        (SecuredWith, "已保护 · 校验码"),
        (HostFingerprint, "主机指纹"),
        (ErrorConnectRefused, "主机拒绝了连接"),
        (ErrorTimeout, "主机无响应"),
        (ErrorProtocol, "对方使用的协议不同"),
        (ErrorNoDecoder, "没有此格式的解码器"),
        (SessionTakenOver, "另一台设备已接管此会话。"),
        // umbruch() trennt nur an Leerzeichen: hinter jedem Satzende eins,
        // sonst bleibt der lange Rest nach dem Pfad eine einzige Zeile.
        (KeyFileDamaged, "密钥文件 {p} 已损坏，未作改动。 请检查或删除该文件：删除后会生成新密钥，须用密码重新允许此设备。"),
        (FileUnreadable, "无法读取 {p}，不会建立连接。"),
        (FileNotUtf8, "{p} 未以 UTF-8 保存，不会建立连接。"),
        (FileNotWritable, "无法写入 {p}，不会建立连接。"),
        (StorageUnavailable, "存放密钥和设置的文件夹不可用，不会建立连接。"),
        (ErrorAddress, "无法解析地址 {n}"),
        (ErrorNoConnection, "无法连接到主机"),
        (ErrorHandshake, "无法建立安全连接"),
        (ErrorFfmpegStart, "无法启动 FFmpeg"),
        (ErrorSound, "声音不可用"),
        (ErrorGpuDisplay, "显卡不可用，改用软件显示"),
        (ErrorGpuLost, "显卡已丢失，请使用 --anzeige cpu 重新启动"),
        (ErrorPixelFormat, "此客户端无法显示解码器输出的画面"),
        (DecoderFallback, "所选显卡无法解码，正在使用软件解码器"),
        (TipBitrate, "码率上限。画面运动时编码器会用满；在非自家网络上建议 25 到 50。"),
        (TipFps, "目标帧率。无法超过 Mac 显示器的刷新率。"),
        (TipGaming, "更频繁的关键帧，允许的积压更少：运动时更平稳，略微多耗码率。"),
        (TipSound, "传输声音。关闭可节省约 3 Mbit/s，主机将不再发送声音。"),
        (TipCodec, "主机的编解码器，可在运行中切换；画面会短暂停顿。\"需转换\" 会多一次处理。"),
        (TipFullscreen, "无边框全屏。窗口模式下画面按比例适应。"),
        (TipPixelExact, "画面 1:1 不缩放。窗口较小时只显示一部分。"),
        (TipShowOverlay, "在左上角显示统计。显示哪些行，在右侧选择。"),
        (TipNerdMode, "扩展统计：延迟链以条形显示，以及主机和客户端的负载。"),
        (TipStatRows, "统计显示哪些行。"),
        (TipDecoderAuto, "NVIDIA 显卡上用 NVDEC；否则在负责绘制的显卡上用 D3D11VA（仅 4:2:0 和 H.264）；否则用处理器。"),
        (TipDecoderCpu, "在处理器上解码。到处都能用，占用 CPU 时间。"),
        (TipDecoderGpu, "在显卡上解码。若不行，客户端会回退到处理器并说明原因。"),
        (TipDecoderIntegrated, "在集成显卡上解码（D3D11VA）。若不行，客户端会回退到处理器并说明原因。"),
        (TipDisplayAuto, "在第一块有显示输出的显卡上用 Direct3D 11，否则第一块 NVIDIA 显卡，否则第一块可用的显卡。没有显卡时：处理器。下次启动起生效。"),
        (TipDisplayGpu, "在这块显卡上用 Direct3D 11 绘制。下次启动起生效。"),
        (TipDisplayIntegrated, "在集成显卡上用 Direct3D 11 绘制，显示器通常接在它上面。下次启动起生效。"),
        (TipDisplayCpu, "在处理器上绘制，不用 Direct3D。到处都能用，占用 CPU 时间。下次启动起生效。"),
        (TipDisconnect, "断开连接，返回起始画面。"),
        (TabShortcuts, "快捷键"),
        (ShortcutMenu, "打开菜单（这个 ESC 不会传到 Mac）"),
        (ShortcutBack, "返回起始画面"),
        (ShortcutWinKey, "Windows 键 = Mac 的 Command 键"),
        (ShortcutOthers, "其他所有按键都发送到 Mac。传输的是按键位置而非字符，重音字母和 AltGr 自然正确。"),
        // Benchmark
        (TabBenchmark, "基准测试"),
        (BenchStart, "开始"),
        (BenchAbort, "取消"),
        (BenchApply, "应用"),
        (BenchDuration, "每步时长"),
        (BenchTestPattern, "测试图案"),
        (BenchStep, "第 {n} 步，共 {m} 步"),
        (BenchPhaseSettings, "正在应用设置"),
        (BenchPhaseSettle, "稳定中"),
        (BenchPhaseMeasure, "测量中"),
        (BenchFailed, "失败"),
        (BenchDone, "完成"),
        (BenchAborted, "已取消"),
        (BenchMeasured, "实测"),
        (BenchChain, "链路"),
        (BenchColFps, "fps"),
        (BenchColDropped, "丢帧"),
        (BenchColHostCpu, "主机 CPU"),
        (BenchRecommendation, "推荐"),
        (BenchNoRecommendation, "没有任何一步通过：链路超过 30 ms 或帧数太少。请尝试更低的帧率或码率。"),
        (BenchHint, "测量的是 Mac 上此刻正在发生的内容。只有画面在动时各步才有可比性，播放一段视频即可。"),
        (BenchHintPattern, "开启测试图案后，每一步看到的都是相同的运动画面，Mac 上无需运行任何东西。"),
        (TipBenchStart, "依次测试所选编解码器、帧率和码率的所有组合，每个组合持续设定的时长。画面继续运行，菜单可以保持打开。"),
        (TipBenchApply, "应用推荐的编解码器和设置，并为此主机保存。"),
        (TipBenchDuration, "每步的测量时间。更长更稳定；通常 5 秒足够。"),
        (TipBenchHint, "一步通过的条件：至少达到目标帧率的 95 %，丢帧少于 1 %，且整条链路保持在 30 ms 以内——与帧率无关。主机的编码器耗时仅显示，不作评判。推荐：在最高帧率下通过的最佳色彩质量，取最高码率。"),
        (TipBenchTestPattern, "测试期间主机显示固定的运动图案而非屏幕内容，每一步测量的都是相同内容。"),
        (DesktopShortcut, "快捷方式"),
        (TipDesktopShortcut, "在桌面上创建此主机的快捷方式。双击即可立即连接。"),
        (DesktopShortcutCreated, "已在桌面上创建快捷方式：{n}"),
        (DesktopShortcutFailed, "未能创建快捷方式：{n}"),
        (DesktopShortcutDescription, "QuadChroma：连接到 {n}（{m}）"),
        (FilesSending, "正在发送文件：{n} / {m}"),
        (FilesReceiving, "正在接收文件：{n} / {m}"),
        (FilesReady, "文件已可粘贴：{n}"),
        (FilesSent, "文件已传输：{n}"),
        (FilesAborted, "文件传输已中止：{n}"),
        (FilesTooLarge, "文件未传输：超过 4 GB 或 10,000 个项目"),
        (FilesPeerOld, "对方暂时无法接收文件。"),
        (TrayOpen, "打开"),
        (TrayConnect, "连接：{n}"),
        (TrayQuit, "退出"),
        (TrayStillRunning, "QuadChroma 仍在通知区域中运行。"),
        (TrayStillRunningMac, "QuadChroma 仍在菜单栏中运行。"),
        (FilesAbortLocal, "由本设备中止"),
        (FilesAbortPeer, "由对方中止"),
        (FilesAbortConnection, "连接中断"),
        (FilesAbortTimeout, "超时，无进展"),
        (FilesAbortNoSpace, "磁盘空间不足"),
        (FilesAbortInvalid, "数据无效"),
        (FilesAbortRead, "读取错误"),
        (FilesAbortWrite, "写入错误"),
        (FilesAbortClipboard, "剪贴板不可用"),
        (ScreenLabel, "主机屏幕"),
        (ScreenAuto, "自动"),
        (TipScreen, "你看到主机的哪个屏幕。\"自动\" 跟随主屏幕；固定屏幕一直有效，直到你选择其他。"),
        (ScreenSwitching, "正在切换屏幕 …"),
        (ScreenFallback, "{n} 未连接 – 备用：{m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "{n} 的密码"),
        (AccessText, "{n} 尚未记录此设备。 请输入 {n} 上 QuadChroma 菜单中显示的密码。"),
        (AccessOrAllow, "或者请 {n} 旁边的人点击 \"允许\"。"),
        (AccessCode, "校验码：{c}"),
        (AccessPassword, "密码"),
        (AccessShow, "显示"),
        (AccessCancel, "取消"),
        (AccessChecking, "正在检查 …"),
        (AccessWrong, "密码错误。"),
        (AccessWait, "尝试次数过多。 请在 {s} 秒后重试。"),
        (AccessNewIdentity, "此地址上的设备身份已变更（ID {i}）。"),
        (MsgRefused, "{n} 拒绝了连接。"),
        (MsgNoAnswer, "{n} 没有响应。 请重试。"),
        (MsgTooManyAttempts, "尝试次数过多。 请稍候再试。"),
        (MsgHostOutdated, "{n} 使用的是较旧版本的 QuadChroma。 请在 {n} 上更新。"),
        (MsgHostProofBad, "{n} 无法确认密码。 为安全起见，连接已中断。"),
        (MsgOtherDevice, "此地址上应答的是另一台设备。"),
        (MsgIdNotFound, "网络中未找到 ID 为 {i} 的设备。"),
        (StartId, "ID {i}"),
        (StartShare, "共享此电脑"),
        (StartSharing, "共享已开启"),
        (HostReady, "等待连接"),
        (HostConnected, "已连接：{n}"),
        (HostDeviceId, "设备 ID：{i}"),
        (HostPassword, "密码：{p}"),
        (HostCopied, "已复制"),
        (HostChangePassword, "更改密码 …"),
        (HostRandomPassword, "新的随机密码"),
        (HostNewPassword, "新密码（至少 8 个字符）"),
        (HostRepeatPassword, "再次输入密码"),
        (HostPasswordsDiffer, "两次输入的密码不一致。"),
        (HostPasswordShort, "请至少输入 8 个字符。"),
        (HostPasswordSaved, "密码已保存。"),
        (HostPasswordUnreadable, "无法读取密码文件 – 新设备只能通过 \"允许\" 接入。"),
        (HostDevices, "已允许的设备"),
        (HostNoDevices, "暂无设备"),
        (HostDeviceLine, "{n} – ID {i} – 自 {d} 起"),
        (HostRemove, "移除"),
        (HostRemoveAll, "移除所有设备 …"),
        (HostRemoveAllAsk, "要移除所有已允许的设备吗？ 之后它们需要重新输入密码。"),
        (HostListDamaged, "设备列表已损坏"),
        (HostListReset, "重置设备列表"),
        (HostRequest, "{n}（ID {i}）想要控制这台电脑。"),
        (HostAllow, "允许"),
        (HostDeny, "拒绝"),
        (HostStartLogin, "登录时启动"),
        (HostStartWindows, "随 Windows 启动"),
        (HostMoveToApps, "请先将 QuadChroma 移到应用程序文件夹"),
        (HostScreenMissing, "屏幕录制未获允许 – 打开系统设置 …"),
        (HostAccessMissing, "辅助功能未获允许 – 打开系统设置 …"),
        (HostPortBusy, "端口 {p} 已被其他程序占用"),
        (HostQuit, "退出 QuadChroma"),
        (HostStopSharing, "停止共享"),
        (HostTooltip, "QuadChroma – 正在共享此电脑（ID {i}）"),
        (HostOk, "确定"),
        (AccessHide, "隐藏"),
        (MsgShareFailed, "无法开始共享此电脑。"),
        (MsgDeviceRemoved, "{n} 已不再记录此设备。 请重新连接并输入密码。"),
        (HostPasswordNotSaved, "无法保存密码。"),
        (HostPasswordInvalid, "密码包含不允许的字符。"),
        (HostPasswordTitle, "更改密码"),
        (MsgHostUnverified, "{n} 未能证明其身份。 为安全起见，连接已中断。"),
        (MsgHostQuit, "{n} 已关闭 QuadChroma。"),
        (MsgHostSharingOff, "{n} 已停止共享。"),
        (MsgHostRemovedYou, "{n} 已移除此设备。"),
        (MsgSelf, "这就是这台电脑。"),
        (TrayOpenApp, "打开 QuadChroma"),
        (HostSharingIsOff, "共享已关闭"),
        (DeviceNameChange, "更改设备名称 …"),
        (DeviceNameTitle, "设备名称"),
        (DeviceNameLabel, "其他设备看到的此电脑名称："),
        (DeviceNameHint, "留空则使用计算机名称（{n}）。"),
        (DeviceNameTooLong, "名称过长（最多 40 字节）。"),
        (DeviceNameInvalid, "名称包含不允许的字符。"),
        (ThisComputer, "此电脑：{n} · {i}"),
        (DeviceNameRename, "重命名"),
        (PreventSleep, "QuadChroma 运行时阻止睡眠"),
    ],
};

pub static JA: Lang = Lang {
    code: "ja",
    name: "日本語",
    table: &[
        (AppSubtitle, "色を落とさないリモートデスクトップ"),
        (Connect, "接続"),
        (Disconnect, "切断"),
        (HostAddress, "ホストのアドレス"),
        (SearchingHosts, "ホストを検索中"),
        (NoHostsFound, "ホストが見つかりません"),
        (FoundHosts, "見つかったホスト"),
        (Settings, "設定"),
        (Language, "言語"),
        (Quit, "終了"),
        (Connecting, "接続中"),
        (Connected, "接続済み"),
        (ConnectionLost, "接続が切れました"),
        (Reconnecting, "再接続中"),
        (Fullscreen, "全画面"),
        (PixelExact, "等倍表示"),
        (Stretch, "ウィンドウに合わせる"),
        (ShowOverlay, "統計を表示"),
        (Fps, "フレームレート"),
        (DecodeTime, "デコード時間"),
        (Bitrate, "ビットレート"),
        (Resolution, "解像度"),
        (Codec, "コーデック"),
        (Latency, "遅延"),
        (EncodeTime, "エンコード時間"),
        (NetworkTime, "転送時間"),
        (AudioBuffer, "音声バッファ"),
        (Dropped, "ドロップ"),
        (MaxBitrate, "最大ビットレート"),
        (MaxFps, "最大フレームレート"),
        (ExpertMode, "エキスパートモード"),
        (GamingMode, "ゲームモード"),
        (FixedRate, "固定フレームレート"),
        (FixedRateHint, "画面が静止していてもフレームレートを維持します。ホストに常に負荷がかかります。"),
        (Sound, "音声"),
        (HoldEscHint, "ESC を押し続けてメニューを開く"),
        (NerdMode, "ギークモード"),
        (More, "その他"),
        (Back, "戻る"),
        (SavedForHost, "このホストに保存しました"),
        (Queue, "キャプチャと待機"),
        (OneFrame, "1フレーム"),
        (Bottleneck, "ボトルネック"),
        (TabPicture, "映像"),
        (TabDisplay, "表示"),
        (CodecConverted, "変換あり"),
        (CodecSwitching, "コーデック切り替え中"),
        (HostCpu, "ホストのCPU"),
        (HostGpu, "ホストのGPU"),
        (HostRam, "ホストのメモリ"),
        (NoDisplay, "現在ホストにディスプレイがありません"),
        (Encryption, "暗号化"),
        (EncryptionOn, "オン"),
        (EncryptionOff, "オフ"),
        (AudioEnabled, "音声"),
        (ClipboardEnabled, "クリップボード"),
        (DecoderLabel, "デコーダー"),
        (RoleAuto, "自動"),
        (RoleCpu, "CPU"),
        (RoleGpu, "GPU"),
        (RoleGpuN, "GPU {n}"),
        (RoleIntegrated, "内蔵GPU"),
        (NextStartHint, "次回起動時から有効"),
        (AdapterWithOutput, "ディスプレイ出力あり"),
        (AdapterNoOutput, "ディスプレイ出力なし"),
        (TipOnly420, "4:2:0 と H.264 のみ（D3D11VA）。4:4:4 では CPU に戻ります。映像タブでコーデックを切り替えてください。"),
        (DisplayLabel, "表示"),
        (DisplayStage, "表示"),
        (ClientCpu, "クライアントのCPU"),
        (Monitor, "モニター"),
        (Skipped, "スキップ"),
        (SecuredWith, "保護済み · 確認コード"),
        (HostFingerprint, "ホストのフィンガープリント"),
        (ErrorConnectRefused, "ホストに接続を拒否されました"),
        (ErrorTimeout, "ホストから応答がありません"),
        (ErrorProtocol, "相手のプロトコルが異なります"),
        (ErrorNoDecoder, "この形式のデコーダーがありません"),
        (SessionTakenOver, "別のデバイスがセッションを引き継ぎました。"),
        // umbruch() trennt nur an Leerzeichen: hinter jedem Satzende eins,
        // sonst bleibt der lange Rest nach dem Pfad eine einzige Zeile.
        (KeyFileDamaged, "鍵ファイル {p} が壊れているため、変更せずに残しています。 確認するか削除してください。 削除すると新しい鍵が作成され、パスワードでこのデバイスを再度許可する必要があります。"),
        (FileUnreadable, "{p} を読み込めないため、接続しません。"),
        (FileNotUtf8, "{p} が UTF-8 で保存されていないため、接続しません。"),
        (FileNotWritable, "{p} に書き込めないため、接続しません。"),
        (StorageUnavailable, "鍵と設定を保存するフォルダーを利用できないため、接続しません。"),
        (ErrorAddress, "アドレス {n} を解決できません"),
        (ErrorNoConnection, "ホストに接続できません"),
        (ErrorHandshake, "安全な接続を確立できませんでした"),
        (ErrorFfmpegStart, "FFmpeg を起動できませんでした"),
        (ErrorSound, "音声を利用できません"),
        (ErrorGpuDisplay, "GPU を使用できないため、ソフトウェアで表示しています"),
        (ErrorGpuLost, "GPU が失われました。--anzeige cpu を付けて再起動してください"),
        (ErrorPixelFormat, "デコーダーが出力する映像を、このクライアントでは表示できません"),
        (DecoderFallback, "選択した GPU ではデコードできないため、ソフトウェアデコーダーを使用しています"),
        (TipBitrate, "ビットレートの上限。動きがあるとエンコーダーは上限まで使います。自分以外のネットワークでは 25〜50 が無難です。"),
        (TipFps, "目標フレームレート。Mac のディスプレイが出せる以上にはなりません。"),
        (TipGaming, "キーフレームを増やし、許容する遅れを減らします。動きのある場面で安定しますが、ビットレートを少し消費します。"),
        (TipSound, "音声を送ります。オフにすると約 3 Mbit/s 節約でき、ホストは音声を送りません。"),
        (TipCodec, "ホストのコーデック。動作中に切り替わり、映像が一瞬止まります。「変換あり」は処理が一段増えます。"),
        (TipFullscreen, "枠なしの全画面。ウィンドウでは映像をはめ込みます。"),
        (TipPixelExact, "拡大縮小なしの等倍表示。ウィンドウが小さいと一部だけ見えます。"),
        (TipShowOverlay, "左上に統計を表示します。どの行を出すかは右側で選びます。"),
        (TipNerdMode, "拡張統計：遅延の内訳をバーで、ホストとクライアントの負荷も表示します。"),
        (TipStatRows, "統計に表示する行。"),
        (TipDecoderAuto, "NVIDIA カードでは NVDEC、それ以外は描画する GPU で D3D11VA（4:2:0 と H.264 のみ）、それもなければ CPU。"),
        (TipDecoderCpu, "CPU でデコードします。どこでも動きますが、処理時間がかかります。"),
        (TipDecoderGpu, "GPU でデコードします。できない場合は CPU に戻り、理由を表示します。"),
        (TipDecoderIntegrated, "内蔵GPU でデコードします（D3D11VA）。できない場合は CPU に戻り、理由を表示します。"),
        (TipDisplayAuto, "ディスプレイ出力のある最初のカードで Direct3D 11、なければ最初の NVIDIA カード、なければ最初に見つかったカード。カードがなければ CPU。次回起動時から有効。"),
        (TipDisplayGpu, "このカードで Direct3D 11 を使って描画します。次回起動時から有効。"),
        (TipDisplayIntegrated, "内蔵GPU で Direct3D 11 を使って描画します。通常はここにディスプレイがつながっています。次回起動時から有効。"),
        (TipDisplayCpu, "Direct3D を使わず CPU で描画します。どこでも動きますが、処理時間がかかります。次回起動時から有効。"),
        (TipDisconnect, "接続を終了して開始画面に戻ります。"),
        (TabShortcuts, "ショートカット"),
        (ShortcutMenu, "メニューを開く（この ESC は Mac には届きません）"),
        (ShortcutBack, "開始画面に戻る"),
        (ShortcutWinKey, "Windows キー = Mac の Command キー"),
        (ShortcutOthers, "他のキーはすべて Mac に送られます。送るのは文字ではなくキーの位置なので、記号や AltGr もそのまま使えます。"),
        // Benchmark
        (TabBenchmark, "ベンチマーク"),
        (BenchStart, "開始"),
        (BenchAbort, "中止"),
        (BenchApply, "適用"),
        (BenchDuration, "1ステップの時間"),
        (BenchTestPattern, "テストパターン"),
        (BenchStep, "ステップ {n} / {m}"),
        (BenchPhaseSettings, "設定を適用中"),
        (BenchPhaseSettle, "安定待ち"),
        (BenchPhaseMeasure, "計測中"),
        (BenchFailed, "失敗"),
        (BenchDone, "完了"),
        (BenchAborted, "中止済み"),
        (BenchMeasured, "実測"),
        (BenchChain, "経路"),
        (BenchColFps, "fps"),
        (BenchColDropped, "ドロップ"),
        (BenchColHostCpu, "ホストCPU"),
        (BenchRecommendation, "おすすめ"),
        (BenchNoRecommendation, "合格したステップがありません：経路が 30 ms を超えているか、フレームが少なすぎます。フレームレートかビットレートを下げてみてください。"),
        (BenchHint, "計測するのは今 Mac で起きていることです。何かが動いているときだけステップを比較できます。動画を再生しておけば十分です。"),
        (BenchHintPattern, "テストパターンをオンにすると、どのステップも同じ動く映像を見ます。Mac 側で何かを動かす必要はありません。"),
        (TipBenchStart, "選んだコーデック、フレームレート、ビットレートのすべての組み合わせを順に、設定した時間ずつ計測します。映像は流れたままで、メニューを開いたままでも構いません。"),
        (TipBenchApply, "おすすめのコーデックと設定を適用し、このホスト用に保存します。"),
        (TipBenchDuration, "1ステップあたりの計測時間。長いほど安定します。通常は 5 秒で十分です。"),
        (TipBenchHint, "目標フレームレートの 95 % 以上が届き、ドロップが 1 % 未満で、経路全体が 30 ms 以内に収まればステップは合格です（フレームレートにかかわらず）。ホストのエンコーダー時間は表示されますが、判定には使われません。おすすめ：最高フレームレートで合格する最良の色品質を、最高のビットレートで。"),
        (TipBenchTestPattern, "計測中、ホストは画面の代わりに固定の動くパターンを表示します。どのステップも同じ内容を計測します。"),
        (DesktopShortcut, "デスクトップに追加"),
        (TipDesktopShortcut, "このホストへのショートカットをデスクトップに作成します。ダブルクリックするとすぐに接続します。"),
        (DesktopShortcutCreated, "デスクトップにショートカットを作成しました: {n}"),
        (DesktopShortcutFailed, "ショートカットを作成できませんでした: {n}"),
        (DesktopShortcutDescription, "QuadChroma: {n} に接続 ({m})"),
        (FilesSending, "ファイルを送信中: {n} / {m}"),
        (FilesReceiving, "ファイルを受信中: {n} / {m}"),
        (FilesReady, "貼り付けできるファイル: {n}"),
        (FilesSent, "ファイルを転送しました: {n}"),
        (FilesAborted, "ファイル転送を中止しました: {n}"),
        (FilesTooLarge, "ファイルは転送されません: 4 GB または 10,000 項目を超えています"),
        (FilesPeerOld, "相手側はまだファイルを受信できません。"),
        (TrayOpen, "開く"),
        (TrayConnect, "接続: {n}"),
        (TrayQuit, "終了"),
        (TrayStillRunning, "QuadChroma は通知領域で引き続き動作しています。"),
        (TrayStillRunningMac, "QuadChroma はメニューバーで引き続き動作しています。"),
        (FilesAbortLocal, "このデバイスで中止"),
        (FilesAbortPeer, "相手側で中止"),
        (FilesAbortConnection, "接続が中断されました"),
        (FilesAbortTimeout, "タイムアウト、進行なし"),
        (FilesAbortNoSpace, "ディスクの空き容量が不足しています"),
        (FilesAbortInvalid, "無効なデータ"),
        (FilesAbortRead, "読み取りエラー"),
        (FilesAbortWrite, "書き込みエラー"),
        (FilesAbortClipboard, "クリップボードを使用できません"),
        (ScreenLabel, "ホストの画面"),
        (ScreenAuto, "自動"),
        (TipScreen, "ホストのどの画面を見るか。「自動」はメイン画面に追従します。固定した画面は、別のものを選ぶまで有効です。"),
        (ScreenSwitching, "画面を切り替え中 …"),
        (ScreenFallback, "{n} は未接続 – 代替: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "{n} のパスワード"),
        (AccessText, "{n} はまだこのデバイスを認識していません。 {n} の QuadChroma メニューに表示されているパスワードを入力してください。"),
        (AccessOrAllow, "または、{n} の前にいる人に「許可」をクリックしてもらってください。"),
        (AccessCode, "確認コード: {c}"),
        (AccessPassword, "パスワード"),
        (AccessShow, "表示"),
        (AccessCancel, "中止"),
        (AccessChecking, "確認中 …"),
        (AccessWrong, "パスワードが違います。"),
        (AccessWait, "試行回数が多すぎます。 {s} 秒後にもう一度お試しください。"),
        (AccessNewIdentity, "このアドレスのデバイスの識別情報が変わりました（ID {i}）。"),
        (MsgRefused, "{n} に接続を拒否されました。"),
        (MsgNoAnswer, "{n} から応答がありません。 もう一度お試しください。"),
        (MsgTooManyAttempts, "試行回数が多すぎます。 しばらく待ってからもう一度お試しください。"),
        (MsgHostOutdated, "{n} は古いバージョンの QuadChroma を使っています。 {n} 側で更新してください。"),
        (MsgHostProofBad, "{n} はパスワードを確認できませんでした。 安全のため接続を中止しました。"),
        (MsgOtherDevice, "このアドレスでは別のデバイスが応答しています。"),
        (MsgIdNotFound, "ID {i} のデバイスがネットワーク上に見つかりません。"),
        (StartId, "ID {i}"),
        (StartShare, "この PC を共有"),
        (StartSharing, "共有中"),
        (HostReady, "接続を待機中"),
        (HostConnected, "接続中: {n}"),
        (HostDeviceId, "デバイス ID: {i}"),
        (HostPassword, "パスワード: {p}"),
        (HostCopied, "コピーしました"),
        (HostChangePassword, "パスワードを変更 …"),
        (HostRandomPassword, "新しいランダムパスワード"),
        (HostNewPassword, "新しいパスワード（8 文字以上）"),
        (HostRepeatPassword, "パスワードを再入力"),
        (HostPasswordsDiffer, "パスワードが一致しません。"),
        (HostPasswordShort, "8 文字以上で入力してください。"),
        (HostPasswordSaved, "パスワードを保存しました。"),
        (HostPasswordUnreadable, "パスワードファイルを読み込めません – 新しいデバイスは「許可」でのみ接続できます。"),
        (HostDevices, "許可したデバイス"),
        (HostNoDevices, "デバイスはまだありません"),
        (HostDeviceLine, "{n} – ID {i} – {d} から"),
        (HostRemove, "削除"),
        (HostRemoveAll, "すべてのデバイスを削除 …"),
        (HostRemoveAllAsk, "許可したデバイスをすべて削除しますか？ 削除すると再びパスワードが必要になります。"),
        (HostListDamaged, "デバイスリストが壊れています"),
        (HostListReset, "デバイスリストをリセット"),
        (HostRequest, "{n}（ID {i}）がこのコンピュータを操作しようとしています。"),
        (HostAllow, "許可"),
        (HostDeny, "拒否"),
        (HostStartLogin, "ログイン時に起動"),
        (HostStartWindows, "Windows と同時に起動"),
        (HostMoveToApps, "先に QuadChroma を「アプリケーション」フォルダに移動してください"),
        (HostScreenMissing, "画面収録が許可されていません – システム設定を開く …"),
        (HostAccessMissing, "アクセシビリティが許可されていません – システム設定を開く …"),
        (HostPortBusy, "ポート {p} は別のプログラムが使用中です"),
        (HostQuit, "QuadChroma を終了"),
        (HostStopSharing, "共有を停止"),
        (HostTooltip, "QuadChroma – この PC を共有中（ID {i}）"),
        (HostOk, "OK"),
        (AccessHide, "非表示"),
        (MsgShareFailed, "この PC の共有を開始できませんでした。"),
        (MsgDeviceRemoved, "{n} はこのデバイスをもう認識していません。 もう一度接続して、パスワードを入力してください。"),
        (HostPasswordNotSaved, "パスワードを保存できませんでした。"),
        (HostPasswordInvalid, "パスワードに使用できない文字が含まれています。"),
        (HostPasswordTitle, "パスワードを変更"),
        (MsgHostUnverified, "{n} は身元を証明しませんでした。 安全のため接続を中止しました。"),
        (MsgHostQuit, "{n} で QuadChroma が終了しました。"),
        (MsgHostSharingOff, "{n} が共有を停止しました。"),
        (MsgHostRemovedYou, "{n} がこのデバイスを削除しました。"),
        (MsgSelf, "これはこのコンピューターです。"),
        (TrayOpenApp, "QuadChroma を開く"),
        (HostSharingIsOff, "共有はオフです"),
        (DeviceNameChange, "デバイス名を変更 …"),
        (DeviceNameTitle, "デバイス名"),
        (DeviceNameLabel, "ほかのデバイスにはこの名前で表示されます:"),
        (DeviceNameHint, "空欄にするとコンピューター名（{n}）を使います。"),
        (DeviceNameTooLong, "名前が長すぎます（最大 40 バイト）。"),
        (DeviceNameInvalid, "名前に使用できない文字が含まれています。"),
        (ThisComputer, "このコンピューター: {n} · {i}"),
        (DeviceNameRename, "名前を変更"),
        (PreventSleep, "QuadChroma の実行中はスリープしない"),
    ],
};

pub static TR: Lang = Lang {
    code: "tr",
    name: "Türkçe",
    table: &[
        (AppSubtitle, "Tam renk ayrıntısıyla uzak masaüstü"),
        (Connect, "Bağlan"),
        (Disconnect, "Bağlantıyı kes"),
        (HostAddress, "Host adresi"),
        (SearchingHosts, "Host aranıyor"),
        (NoHostsFound, "Host bulunamadı"),
        (FoundHosts, "Bulunan hostlar"),
        (Settings, "Ayarlar"),
        (Language, "Dil"),
        (Quit, "Çıkış"),
        (Connecting, "Bağlanılıyor"),
        (Connected, "Bağlandı"),
        (ConnectionLost, "Bağlantı koptu"),
        (Reconnecting, "Yeniden bağlanılıyor"),
        (Fullscreen, "Tam ekran"),
        (PixelExact, "Birebir piksel"),
        (Stretch, "Pencereye sığdır"),
        (ShowOverlay, "İstatistikleri göster"),
        (Fps, "Saniyedeki kare"),
        (DecodeTime, "Kod çözme süresi"),
        (Bitrate, "Bit hızı"),
        (Resolution, "Çözünürlük"),
        (Codec, "Codec"),
        (Latency, "Gecikme"),
        (EncodeTime, "Kodlama süresi"),
        (NetworkTime, "Aktarım süresi"),
        (AudioBuffer, "Ses arabelleği"),
        (Dropped, "Atlanan kare"),
        (MaxBitrate, "En yüksek bit hızı"),
        (MaxFps, "En yüksek kare hızı"),
        (ExpertMode, "Uzman modu"),
        (GamingMode, "Oyun modu"),
        (FixedRate, "Sabit kare hızı"),
        (FixedRateHint, "Hiçbir şey hareket etmese de kare hızını korur. Host'ta sürekli yük oluşur."),
        (Sound, "Ses"),
        (HoldEscHint, "Menü için ESC'yi basılı tutun"),
        (NerdMode, "Nerd modu"),
        (More, "Daha fazla"),
        (Back, "Geri"),
        (SavedForHost, "Bu host için kaydedildi"),
        (Queue, "Yakalama ve bekleme"),
        (OneFrame, "Bir kare"),
        (Bottleneck, "Darboğaz"),
        (TabPicture, "Görüntü"),
        (TabDisplay, "Ekran"),
        (CodecConverted, "dönüştürülmüş"),
        (CodecSwitching, "Codec değiştiriliyor"),
        (HostCpu, "Host işlemcisi"),
        (HostGpu, "Host ekran kartı"),
        (HostRam, "Host belleği"),
        (NoDisplay, "Host'un şu anda ekranı yok"),
        (Encryption, "Şifreleme"),
        (EncryptionOn, "açık"),
        (EncryptionOff, "kapalı"),
        (AudioEnabled, "Ses"),
        (ClipboardEnabled, "Pano"),
        (DecoderLabel, "Kod çözücü"),
        (RoleAuto, "Otomatik"),
        (RoleCpu, "İşlemci"),
        (RoleGpu, "Ekran kartı"),
        (RoleGpuN, "Ekran kartı {n}"),
        (RoleIntegrated, "Tümleşik"),
        (NextStartHint, "sonraki başlatmadan itibaren geçerli"),
        (AdapterWithOutput, "ekran çıkışı var"),
        (AdapterNoOutput, "ekran çıkışı yok"),
        (TipOnly420, "Yalnızca 4:2:0 ve H.264 (D3D11VA); 4:4:4'te istemci işlemciye döner – codec'i Görüntü sekmesinde değiştirin."),
        (DisplayLabel, "Ekran"),
        (DisplayStage, "Ekran"),
        (ClientCpu, "İstemci işlemcisi"),
        (Monitor, "Monitör"),
        (Skipped, "gösterilmedi"),
        (SecuredWith, "Güvenli · doğrulama kodu"),
        (HostFingerprint, "Host parmak izi"),
        (ErrorConnectRefused, "Host bağlantıyı reddetti"),
        (ErrorTimeout, "Host yanıt vermedi"),
        (ErrorProtocol, "Karşı taraf farklı bir protokol kullanıyor"),
        (ErrorNoDecoder, "Bu biçim için kod çözücü yok"),
        (SessionTakenOver, "Oturumu başka bir cihaz devraldı."),
        (KeyFileDamaged, "{p} anahtar dosyası bozuk ve olduğu gibi bırakıldı. Dosyayı kontrol edin veya silin – ardından yeni bir anahtar oluşturulur ve bu cihaza parolayla yeniden izin verilmesi gerekir."),
        (FileUnreadable, "{p} okunamıyor – bağlantı kurulmuyor."),
        (FileNotUtf8, "{p} UTF-8 olarak kaydedilmemiş – bağlantı kurulmuyor."),
        (FileNotWritable, "{p} dosyasına yazılamıyor – bağlantı kurulmuyor."),
        (StorageUnavailable, "Anahtarlar ve ayarlar için klasör kullanılamıyor – bağlantı kurulmuyor."),
        (ErrorAddress, "{n} adresi çözümlenemiyor"),
        (ErrorNoConnection, "Host'a bağlantı yok"),
        (ErrorHandshake, "Güvenli bağlantı kurulamadı"),
        (ErrorFfmpegStart, "FFmpeg başlatılamadı"),
        (ErrorSound, "Ses kullanılamıyor"),
        (ErrorGpuDisplay, "Ekran kartı kullanılamıyor, görüntü yazılımla çiziliyor"),
        (ErrorGpuLost, "Ekran kartı kaybedildi – lütfen --anzeige cpu ile yeniden başlatın"),
        (ErrorPixelFormat, "Kod çözücü, bu istemcinin gösteremediği görüntüler veriyor"),
        (DecoderFallback, "Seçilen ekran kartı kod çözmüyor – yazılım kod çözücüsü çalışıyor"),
        (TipBitrate, "Bit hızının üst sınırı. Hareket olunca kodlayıcı tamamını kullanır; yabancı ağlarda 25 ile 50 arası daha iyi."),
        (TipFps, "Hedef kare hızı. Mac'in ekranının verdiğinden fazlası olmaz."),
        (TipGaming, "Daha sık anahtar kare ve daha az birikime izin: harekette daha düzgün, biraz bit hızına mal olur."),
        (TipSound, "Ses aktar. Kapalıyken yaklaşık 3 Mbit/s tasarruf; host o zaman hiç ses göndermez."),
        (TipCodec, "Host'un codec'i, çalışırken değiştirilir; görüntü kısa süre durur. \"dönüştürülmüş\" bir ek geçişe mal olur."),
        (TipFullscreen, "Kenarlıksız tam ekran. Pencerede görüntü sığdırılır."),
        (TipPixelExact, "Görüntü 1:1, ölçekleme yok. Pencere küçükse bir kesit görürsünüz."),
        (TipShowOverlay, "İstatistikleri sol üstte göster. Hangi satırlar, sağda seçilir."),
        (TipNerdMode, "Genişletilmiş istatistik: gecikme zinciri çubuk olarak, host ve istemci yükü."),
        (TipStatRows, "İstatistiğin hangi satırları gösterdiği."),
        (TipDecoderAuto, "NVIDIA kartta NVDEC; yoksa çizen kartta D3D11VA (yalnızca 4:2:0 ve H.264); yoksa işlemci."),
        (TipDecoderCpu, "İşlemcide kod çözme. Her yerde çalışır, işlem süresine mal olur."),
        (TipDecoderGpu, "Ekran kartında kod çözme. Yapamazsa istemci işlemciye döner ve nedenini söyler."),
        (TipDecoderIntegrated, "Tümleşik ekran kartında kod çözme (D3D11VA). Yapamazsa istemci işlemciye döner ve nedenini söyler."),
        (TipDisplayAuto, "Ekran çıkışı olan ilk kartta Direct3D 11, yoksa ilk NVIDIA kartı, yoksa bulunan ilk kart. Kart yoksa: işlemci. Sonraki başlatmadan itibaren geçerli."),
        (TipDisplayGpu, "Bu kartta Direct3D 11 ile çizim. Sonraki başlatmadan itibaren geçerli."),
        (TipDisplayIntegrated, "Tümleşik ekran kartında Direct3D 11 ile çizim – ekran genelde buna bağlıdır. Sonraki başlatmadan itibaren geçerli."),
        (TipDisplayCpu, "İşlemcide, Direct3D olmadan çizim. Her yerde çalışır, işlem süresine mal olur. Sonraki başlatmadan itibaren geçerli."),
        (TipDisconnect, "Bağlantıyı bitir, başlangıç ekranına dön."),
        (TabShortcuts, "Kısayollar"),
        (ShortcutMenu, "Menüyü aç (bu ESC Mac'e hiç ulaşmaz)"),
        (ShortcutBack, "Başlangıç ekranına dön"),
        (ShortcutWinKey, "Windows tuşu = Mac'in Command tuşu"),
        (ShortcutOthers, "Diğer tüm tuşlar Mac'e gider. Karakter değil tuşun konumu iletilir – Türkçe harfler ve AltGr kendiliğinden doğru çalışır."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Başlat"),
        (BenchAbort, "İptal"),
        (BenchApply, "Uygula"),
        (BenchDuration, "Adım başına süre"),
        (BenchTestPattern, "Test deseni"),
        (BenchStep, "Adım {n}/{m}"),
        (BenchPhaseSettings, "ayarlar uygulanıyor"),
        (BenchPhaseSettle, "oturuyor"),
        (BenchPhaseMeasure, "ölçülüyor"),
        (BenchFailed, "başarısız"),
        (BenchDone, "Bitti"),
        (BenchAborted, "İptal edildi"),
        (BenchMeasured, "ölçülen"),
        (BenchChain, "Zincir"),
        (BenchColFps, "fps"),
        (BenchColDropped, "atlanan"),
        (BenchColHostCpu, "Host CPU"),
        (BenchRecommendation, "Öneri"),
        (BenchNoRecommendation, "Hiçbir adım geçmedi: zincir 30 ms'nin üzerinde veya çok az kare. Daha düşük kare hızı veya bit hızı deneyin."),
        (BenchHint, "Ölçülen, şu anda Mac'te olup bitendir. Adımlar ancak bir şey hareket ederken karşılaştırılabilir – oynayan bir video yeter."),
        (BenchHintPattern, "Test deseni açıkken her adım aynı hareketli içeriği görür – Mac'te hiçbir şeyin çalışması gerekmez."),
        (TipBenchStart, "Seçilen codec'lerin, kare hızlarının ve bit hızlarının tüm kombinasyonlarını sırayla, her birini ayarlanan süre boyunca ölçer. Görüntü akmaya devam eder, menü açık kalabilir."),
        (TipBenchApply, "Önerilen codec'i ve ayarları uygula ve bu host için kaydet."),
        (TipBenchDuration, "Adım başına ölçüm süresi. Daha uzun daha kararlıdır; genelde 5 s yeter."),
        (TipBenchHint, "Hedef kare hızının en az % 95'i ulaşır, karelerin % 1'inden azı atlanır ve tüm zincir 30 ms içinde kalırsa adım geçer – kare hızından bağımsız olarak. Host'un kodlayıcı süresi gösterilir ama değerlendirilmez. Önerilen: en yüksek kare hızında geçen en iyi renk kalitesi, en yüksek bit hızıyla."),
        (TipBenchTestPattern, "Çalıştırma boyunca host ekran yerine sabit, hareketli bir desen gösterir – her adım aynı içeriği ölçer."),
        (DesktopShortcut, "Masaüstü kısayolu"),
        (TipDesktopShortcut, "Masaüstünde bu host için bir kısayol oluşturur. Çift tıklayınca hemen bağlanır."),
        (DesktopShortcutCreated, "Masaüstünde kısayol oluşturuldu: {n}"),
        (DesktopShortcutFailed, "Kısayol oluşturulamadı: {n}"),
        (DesktopShortcutDescription, "QuadChroma: {n} ile bağlan ({m})"),
        (FilesSending, "Dosyalar gönderiliyor: {n} / {m}"),
        (FilesReceiving, "Dosyalar alınıyor: {n} / {m}"),
        (FilesReady, "Yapıştırmaya hazır dosyalar: {n}"),
        (FilesSent, "Dosyalar aktarıldı: {n}"),
        (FilesAborted, "Dosya aktarımı iptal edildi: {n}"),
        (FilesTooLarge, "Dosyalar aktarılmadı: 4 GB'tan veya 10.000 öğeden fazla"),
        (FilesPeerOld, "Karşı taraf henüz dosya alamıyor."),
        (TrayOpen, "Aç"),
        (TrayConnect, "Bağlan: {n}"),
        (TrayQuit, "Çıkış"),
        (TrayStillRunning, "QuadChroma bildirim alanında çalışmaya devam ediyor."),
        (TrayStillRunningMac, "QuadChroma menü çubuğunda çalışmaya devam ediyor."),
        (FilesAbortLocal, "bu cihaz tarafından"),
        (FilesAbortPeer, "karşı taraf tarafından"),
        (FilesAbortConnection, "bağlantı kesildi"),
        (FilesAbortTimeout, "zaman aşımı, ilerleme yok"),
        (FilesAbortNoSpace, "yetersiz disk alanı"),
        (FilesAbortInvalid, "geçersiz veri"),
        (FilesAbortRead, "okuma hatası"),
        (FilesAbortWrite, "yazma hatası"),
        (FilesAbortClipboard, "pano kullanılamıyor"),
        (ScreenLabel, "Host ekranı"),
        (ScreenAuto, "Otomatik"),
        (TipScreen, "Host'un hangi ekranını gördüğün. Otomatik ana ekranı izler; sabit bir ekran, başka bir şey seçene kadar geçerlidir."),
        (ScreenSwitching, "Ekran değiştiriliyor …"),
        (ScreenFallback, "{n} bağlı değil – yedek: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "{n} için parola"),
        (AccessText, "{n} bu cihazı henüz tanımıyor. {n} üzerindeki QuadChroma menüsünde gösterilen parolayı girin."),
        (AccessOrAllow, "Ya da {n} başındaki birinden \"İzin ver\" düğmesine tıklamasını isteyin."),
        (AccessCode, "Kod: {c}"),
        (AccessPassword, "Parola"),
        (AccessShow, "Göster"),
        (AccessCancel, "İptal"),
        (AccessChecking, "Denetleniyor …"),
        (AccessWrong, "Yanlış parola."),
        (AccessWait, "Çok fazla deneme. {s} s sonra yeniden deneyin."),
        (AccessNewIdentity, "Bu adresteki cihazın yeni bir kimliği var (ID {i})."),
        (MsgRefused, "{n} bağlantıyı reddetti."),
        (MsgNoAnswer, "{n} yanıt vermiyor. Lütfen yeniden deneyin."),
        (MsgTooManyAttempts, "Çok fazla deneme. Lütfen biraz bekleyip yeniden deneyin."),
        (MsgHostOutdated, "{n} eski bir QuadChroma sürümü kullanıyor. Lütfen orada güncelleyin."),
        (MsgHostProofBad, "{n} parolayı doğrulayamadı. Güvenlik nedeniyle bağlantı kesildi."),
        (MsgOtherDevice, "Bu adreste başka bir cihaz yanıt veriyor."),
        (MsgIdNotFound, "Ağda ID'si {i} olan cihaz bulunamadı."),
        (StartId, "ID {i}"),
        (StartShare, "Bu bilgisayarı paylaş"),
        (StartSharing, "Paylaşım açık"),
        (HostReady, "Bağlantılara hazır"),
        (HostConnected, "Bağlı: {n}"),
        (HostDeviceId, "Cihaz ID'si: {i}"),
        (HostPassword, "Parola: {p}"),
        (HostCopied, "Kopyalandı"),
        (HostChangePassword, "Parolayı değiştir …"),
        (HostRandomPassword, "Yeni rastgele parola"),
        (HostNewPassword, "Yeni parola (en az 8 karakter)"),
        (HostRepeatPassword, "Parolayı tekrarlayın"),
        (HostPasswordsDiffer, "Parolalar eşleşmiyor."),
        (HostPasswordShort, "Lütfen en az 8 karakter girin."),
        (HostPasswordSaved, "Parola kaydedildi."),
        (HostPasswordUnreadable, "Parola dosyası okunamıyor – yeni cihazlar yalnızca \"İzin ver\" ile."),
        (HostDevices, "İzin verilen cihazlar"),
        (HostNoDevices, "Henüz cihaz yok"),
        (HostDeviceLine, "{n} – ID {i} – {d} tarihinden beri"),
        (HostRemove, "Kaldır"),
        (HostRemoveAll, "Tüm cihazları kaldır …"),
        (HostRemoveAllAsk, "İzin verilen tüm cihazlar kaldırılsın mı? Bu cihazlar yeniden parolaya ihtiyaç duyacak."),
        (HostListDamaged, "Cihaz listesi bozuk"),
        (HostListReset, "Cihaz listesini sıfırla"),
        (HostRequest, "{n} (ID {i}) bu bilgisayarı kontrol etmek istiyor."),
        (HostAllow, "İzin ver"),
        (HostDeny, "Reddet"),
        (HostStartLogin, "Oturum açılınca başlat"),
        (HostStartWindows, "Windows ile başlat"),
        (HostMoveToApps, "Önce QuadChroma'yı Uygulamalar klasörüne taşıyın"),
        (HostScreenMissing, "Ekran Kaydı izni yok – Sistem Ayarları'nı aç …"),
        (HostAccessMissing, "Erişilebilirlik izni yok – Sistem Ayarları'nı aç …"),
        (HostPortBusy, "{p} numaralı port başka bir program tarafından kullanılıyor"),
        (HostQuit, "QuadChroma'dan çıkış"),
        (HostStopSharing, "Paylaşımı durdur"),
        (HostTooltip, "QuadChroma – bu bilgisayar paylaşılıyor (ID {i})"),
        (HostOk, "Tamam"),
        (AccessHide, "Gizle"),
        (MsgShareFailed, "Bu bilgisayarın paylaşımı başlatılamadı."),
        (MsgDeviceRemoved, "{n} bu cihazı artık tanımıyor. Yeniden bağlanın ve parolayı girin."),
        (HostPasswordNotSaved, "Parola kaydedilemedi."),
        (HostPasswordInvalid, "Parola izin verilmeyen karakterler içeriyor."),
        (HostPasswordTitle, "Parolayı değiştir"),
        (MsgHostUnverified, "{n} kimliğini kanıtlamadı. Güvenlik nedeniyle bağlantı kesildi."),
        (MsgHostQuit, "{n} QuadChroma'yı kapattı."),
        (MsgHostSharingOff, "{n} paylaşımı durdurdu."),
        (MsgHostRemovedYou, "{n} bu cihazı kaldırdı."),
        (MsgSelf, "Bu zaten bu bilgisayar."),
        (TrayOpenApp, "QuadChroma'yı aç"),
        (HostSharingIsOff, "Paylaşım kapalı"),
        (DeviceNameChange, "Cihaz adını değiştir …"),
        (DeviceNameTitle, "Cihaz adı"),
        (DeviceNameLabel, "Diğer cihazlar bu bilgisayarı bu adla görür:"),
        (DeviceNameHint, "Bilgisayar adını kullanmak için boş bırakın ({n})."),
        (DeviceNameTooLong, "Ad çok uzun (en fazla 40 bayt)."),
        (DeviceNameInvalid, "Ad izin verilmeyen karakterler içeriyor."),
        (ThisComputer, "Bu bilgisayar: {n} · {i}"),
        (DeviceNameRename, "Yeniden adlandır"),
        (PreventSleep, "QuadChroma çalışırken uyku modunu engelle"),
    ],
};
