// Westeuropaeische Sprachen: Franzoesisch, Spanisch, Italienisch,
// Portugiesisch (Portugal) und Niederlaendisch.
//
// Ein Eintrag je Schluessel aus strings.rs, gleiche Reihenfolge wie dort.

use crate::strings::{Key::*, Lang};

pub static FR: Lang = Lang {
    code: "fr",
    name: "Français",
    table: &[
        (AppSubtitle, "Bureau à distance sans perte de couleur"),
        (Connect, "Se connecter"),
        (Disconnect, "Se déconnecter"),
        (HostAddress, "Adresse de l'hôte"),
        (SearchingHosts, "Recherche d'hôtes"),
        (NoHostsFound, "Aucun hôte trouvé"),
        (FoundHosts, "Hôtes trouvés"),
        (Settings, "Paramètres"),
        (Language, "Langue"),
        (Quit, "Quitter"),
        (Connecting, "Connexion en cours"),
        (Connected, "Connecté"),
        (ConnectionLost, "Connexion perdue"),
        (Reconnecting, "Reconnexion"),
        (Fullscreen, "Plein écran"),
        (PixelExact, "Pixel par pixel"),
        (Stretch, "Ajuster à la fenêtre"),
        (ShowOverlay, "Afficher les statistiques"),
        (Fps, "Images par seconde"),
        (DecodeTime, "Temps de décodage"),
        (Bitrate, "Débit"),
        (Resolution, "Résolution"),
        (Codec, "Codec"),
        (Latency, "Latence"),
        (EncodeTime, "Encodage"),
        (NetworkTime, "Réseau"),
        (AudioBuffer, "Tampon audio"),
        (Dropped, "Images perdues"),
        (MaxBitrate, "Débit maximal"),
        (MaxFps, "Fréquence d'images max"),
        (ExpertMode, "Mode expert"),
        (GamingMode, "Mode jeu"),
        (FixedRate, "Fréquence d'images fixe"),
        (FixedRateHint, "Maintient la fréquence même quand rien ne bouge. Charge permanente sur l'hôte."),
        (Sound, "Son"),
        (HoldEscHint, "Maintenez ESC pour le menu"),
        (NerdMode, "Mode geek"),
        (More, "Plus"),
        (Back, "Retour"),
        (SavedForHost, "Enregistré pour cet hôte"),
        (Queue, "Capture & attente"),
        (OneFrame, "Une image"),
        (Bottleneck, "Goulot d'étranglement"),
        (TabPicture, "Image"),
        (TabDisplay, "Affichage"),
        (CodecConverted, "converti"),
        (CodecSwitching, "Changement de codec"),
        (HostCpu, "CPU de l'hôte"),
        (HostGpu, "GPU de l'hôte"),
        (HostRam, "Mémoire de l'hôte"),
        (NoDisplay, "L'hôte n'a pas d'écran pour le moment"),
        (Encryption, "Chiffrement"),
        (EncryptionOn, "activé"),
        (EncryptionOff, "désactivé"),
        (AudioEnabled, "Son"),
        (ClipboardEnabled, "Presse-papiers"),
        (DecoderLabel, "Décodeur"),
        (RoleAuto, "Automatique"),
        (RoleCpu, "Logiciel"),
        (RoleGpu, "Carte graphique"),
        (DisplayLabel, "Affichage"),
        (DisplayStage, "Affichage"),
        (ClientCpu, "CPU du client"),
        (Monitor, "Moniteur"),
        (Skipped, "sautées"),
        (PairingTitle, "Associer à l'hôte"),
        (PairingHint, "Saisissez le code affiché sur l'hôte"),
        (PairingCode, "Code d'association"),
        (PairingWrong, "Code incorrect"),
        (PairingOk, "Associé"),
        (SecuredWith, "Sécurisé · code de vérification"),
        (HostFingerprint, "Empreinte de l'hôte"),
        (NotPaired, "Cet hôte ne connaît pas encore votre appareil. Démarrez l'hôte avec --pair et reconnectez-vous."),
        (FirstContact, "Premier contact avec cet hôte. Comparez le code avec celui affiché sur l'hôte."),
        (ErrorConnectRefused, "L'hôte a refusé la connexion"),
        (ErrorTimeout, "L'hôte ne répond pas"),
        (ErrorProtocol, "L'autre poste utilise un autre protocole"),
        (ErrorNoDecoder, "Aucun décodeur pour ce format"),
        (TipBitrate, "Limite supérieure du débit. L'encodeur l'utilise entièrement dès que ça bouge ; sur un réseau qui n'est pas le vôtre, préférez 25 à 50."),
        (TipFps, "Fréquence d'images visée. Impossible d'aller au-delà de ce que fournit l'écran du Mac."),
        (TipGaming, "Images clés plus fréquentes et moins de retard toléré : plus régulier quand ça bouge, coûte un peu de débit."),
        (TipSound, "Transmettre le son. Désactivé, économise environ 3 Mbit/s ; l'hôte n'envoie alors aucun son."),
        (TipCodec, "Codec de l'hôte, changé à chaud ; l'image se fige un instant. « converti » coûte une passe de plus."),
        (TipFullscreen, "Plein écran sans bordure. En fenêtre, l'image est ajustée."),
        (TipPixelExact, "Image 1:1 sans mise à l'échelle. Si la fenêtre est plus petite, seule une partie est visible."),
        (TipShowOverlay, "Afficher les statistiques en haut à gauche. Le choix des lignes se fait à droite."),
        (TipNerdMode, "Statistiques étendues : chaîne de latence en barre, charge de l'hôte et du client."),
        (TipStatRows, "Lignes affichées dans les statistiques."),
        (TipDecoderAuto, "Carte graphique si elle prend en charge le codec, sinon logiciel."),
        (TipDecoderCpu, "Décodage sur le processeur. Fonctionne partout, coûte du temps de calcul."),
        (TipDecoderGpu, "Décodage sur la carte graphique. Si elle n'y arrive pas, le client repasse en logiciel et en indique la raison."),
        (TipDisconnect, "Terminer la connexion, retour à l'écran d'accueil."),
        (TabShortcuts, "Raccourcis"),
        (ShortcutMenu, "Ouvrir le menu (cet ESC n'atteint jamais le Mac)"),
        (ShortcutBack, "Retour à l'écran d'accueil"),
        (ShortcutWinKey, "Touche Windows = touche Commande du Mac"),
        (ShortcutOthers, "Toutes les autres touches vont au Mac. C'est la position de la touche qui est transmise, pas le caractère – accents et AltGr fonctionnent d'eux-mêmes."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Démarrer"),
        (BenchAbort, "Annuler"),
        (BenchApply, "Appliquer"),
        (BenchDuration, "Durée par étape"),
        (BenchTestPattern, "Mire"),
        (BenchStep, "Étape {n} sur {m}"),
        (BenchPhaseSettings, "réglages en cours"),
        (BenchPhaseSettle, "stabilisation"),
        (BenchPhaseMeasure, "mesure"),
        (BenchFailed, "échec"),
        (BenchDone, "Terminé"),
        (BenchAborted, "Annulé"),
        (BenchMeasured, "mesuré"),
        (BenchChain, "Chaîne"),
        (BenchColFps, "ips"),
        (BenchColDropped, "perdues"),
        (BenchColHostCpu, "CPU hôte"),
        (BenchRecommendation, "Recommandation"),
        (BenchNoRecommendation, "Aucune étape n'a réussi. Essayez des débits ou des fréquences d'images plus bas."),
        (BenchHint, "La mesure reflète ce qui se passe sur le Mac en ce moment. Les étapes ne sont comparables que si quelque chose bouge – une vidéo en lecture suffit."),
        (BenchHintPattern, "Avec la mire, chaque étape voit le même contenu animé – rien n'a besoin de tourner sur le Mac."),
        (TipBenchStart, "Mesure tour à tour toutes les combinaisons des codecs, fréquences d'images et débits choisis, chacune pendant la durée réglée. L'image continue et le menu peut rester ouvert."),
        (TipBenchApply, "Régler le codec et les paramètres recommandés et les enregistrer pour cet hôte."),
        (TipBenchDuration, "Temps de mesure par étape. Plus long est plus stable ; 5 s suffisent en général."),
        (TipBenchHint, "Une étape réussit si la chaîne tient en une image et demie, si au moins 95 % des images arrivent, si aucune n'est perdue et si l'encodeur reste dans son budget par image. Recommandé : la meilleure qualité de couleur qui réussit à la fréquence d'images la plus élevée, au débit le plus élevé où elle réussit encore."),
        (TipBenchTestPattern, "Pendant toute la durée du test, l'hôte affiche un motif animé fixe à la place de l'écran – chaque étape mesure le même contenu."),
    ],
};

pub static ES: Lang = Lang {
    code: "es",
    name: "Español",
    table: &[
        (AppSubtitle, "Escritorio remoto sin pérdida de color"),
        (Connect, "Conectar"),
        (Disconnect, "Desconectar"),
        (HostAddress, "Dirección del host"),
        (SearchingHosts, "Buscando hosts"),
        (NoHostsFound, "No se encontraron hosts"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Ajustes"),
        (Language, "Idioma"),
        (Quit, "Salir"),
        (Connecting, "Conectando"),
        (Connected, "Conectado"),
        (ConnectionLost, "Conexión perdida"),
        (Reconnecting, "Reconectando"),
        (Fullscreen, "Pantalla completa"),
        (PixelExact, "Píxel a píxel"),
        (Stretch, "Ajustar a la ventana"),
        (ShowOverlay, "Mostrar estadísticas"),
        (Fps, "Fotogramas por segundo"),
        (DecodeTime, "Decodificación"),
        (Bitrate, "Tasa de bits"),
        (Resolution, "Resolución"),
        (Codec, "Códec"),
        (Latency, "Latencia"),
        (EncodeTime, "Codificación"),
        (NetworkTime, "Red"),
        (AudioBuffer, "Búfer de audio"),
        (Dropped, "Fotogramas perdidos"),
        (MaxBitrate, "Tasa de bits máxima"),
        (MaxFps, "Tasa de fotogramas máxima"),
        (ExpertMode, "Modo experto"),
        (GamingMode, "Modo juego"),
        (FixedRate, "Tasa de fotogramas fija"),
        (FixedRateHint, "Mantiene la tasa aunque no se mueva nada. Carga permanente en el host."),
        (Sound, "Sonido"),
        (HoldEscHint, "Mantén ESC para el menú"),
        (NerdMode, "Modo nerd"),
        (More, "Más"),
        (Back, "Atrás"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura y espera"),
        (OneFrame, "Un fotograma"),
        (Bottleneck, "Cuello de botella"),
        (TabPicture, "Imagen"),
        (TabDisplay, "Pantalla"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "Cambiando de códec"),
        (HostCpu, "CPU del host"),
        (HostGpu, "GPU del host"),
        (HostRam, "Memoria del host"),
        (NoDisplay, "El host no tiene pantalla en este momento"),
        (Encryption, "Cifrado"),
        (EncryptionOn, "activado"),
        (EncryptionOff, "desactivado"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Portapapeles"),
        (DecoderLabel, "Decodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Software"),
        (RoleGpu, "Tarjeta gráfica"),
        (DisplayLabel, "Pantalla"),
        (DisplayStage, "Pantalla"),
        (ClientCpu, "CPU del cliente"),
        (Monitor, "Monitor"),
        (Skipped, "omitidos"),
        (PairingTitle, "Emparejar con el host"),
        (PairingHint, "Introduce el código que aparece en el host"),
        (PairingCode, "Código de emparejamiento"),
        (PairingWrong, "Código incorrecto"),
        (PairingOk, "Emparejado"),
        (SecuredWith, "Protegido · código de verificación"),
        (HostFingerprint, "Huella del host"),
        (NotPaired, "Este host aún no conoce tu dispositivo. Inicia el host con --pair y vuelve a conectar."),
        (FirstContact, "Primer contacto con este host. Compara el código con el que aparece en el host."),
        (ErrorConnectRefused, "El host rechazó la conexión"),
        (ErrorTimeout, "El host no responde"),
        (ErrorProtocol, "El otro extremo usa otro protocolo"),
        (ErrorNoDecoder, "No hay decodificador para este formato"),
        (TipBitrate, "Límite superior de la tasa de bits. Con movimiento el codificador la usa entera; en redes ajenas, mejor entre 25 y 50."),
        (TipFps, "Tasa de fotogramas objetivo. No puede superar lo que entrega la pantalla del Mac."),
        (TipGaming, "Fotogramas clave más frecuentes y menos retraso permitido: más estable con movimiento, cuesta algo de tasa de bits."),
        (TipSound, "Transmitir el sonido. Desactivado ahorra unos 3 Mbit/s; el host entonces no envía sonido."),
        (TipCodec, "Códec del host, se cambia en marcha; la imagen se detiene un momento. \"convertido\" cuesta una pasada más."),
        (TipFullscreen, "Pantalla completa sin bordes. En ventana, la imagen se ajusta."),
        (TipPixelExact, "Imagen 1:1 sin escalar. Si la ventana es más pequeña, se ve un recorte."),
        (TipShowOverlay, "Mostrar las estadísticas arriba a la izquierda. Qué filas, a la derecha."),
        (TipNerdMode, "Estadísticas ampliadas: cadena de latencia como barra, carga del host y del cliente."),
        (TipStatRows, "Qué filas muestran las estadísticas."),
        (TipDecoderAuto, "Tarjeta gráfica si admite el códec; si no, software."),
        (TipDecoderCpu, "Decodificar en el procesador. Funciona en todas partes, cuesta tiempo de CPU."),
        (TipDecoderGpu, "Decodificar en la tarjeta gráfica. Si no puede, el cliente vuelve a software y dice por qué."),
        (TipDisconnect, "Terminar la conexión, volver a la pantalla de inicio."),
        (TabShortcuts, "Atajos"),
        (ShortcutMenu, "Abrir el menú (este ESC nunca llega al Mac)"),
        (ShortcutBack, "Volver a la pantalla de inicio"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando del Mac"),
        (ShortcutOthers, "Todas las demás teclas van al Mac. Se transmite la posición de la tecla, no el carácter: acentos y AltGr funcionan por sí solos."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duración por paso"),
        (BenchTestPattern, "Patrón de prueba"),
        (BenchStep, "Paso {n} de {m}"),
        (BenchPhaseSettings, "aplicando ajustes"),
        (BenchPhaseSettle, "estabilizando"),
        (BenchPhaseMeasure, "midiendo"),
        (BenchFailed, "fallido"),
        (BenchDone, "Terminado"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidos"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendación"),
        (BenchNoRecommendation, "Ningún paso ha pasado. Prueba tasas de bits o de fotogramas más bajas."),
        (BenchHint, "Se mide lo que ocurre en el Mac ahora mismo. Los pasos solo son comparables si algo se mueve: basta con un vídeo en reproducción."),
        (BenchHintPattern, "Con el patrón de prueba, cada paso ve el mismo contenido en movimiento: no hace falta que nada corra en el Mac."),
        (TipBenchStart, "Mide una tras otra todas las combinaciones de los códecs, tasas de fotogramas y tasas de bits elegidos, cada una durante el tiempo fijado. La imagen sigue en marcha y el menú puede quedar abierto."),
        (TipBenchApply, "Aplicar el códec y los ajustes recomendados y guardarlos para este host."),
        (TipBenchDuration, "Tiempo de medición por paso. Más largo es más estable; 5 s suelen bastar."),
        (TipBenchHint, "Un paso pasa si la cadena se mantiene en fotograma y medio, llegan al menos el 95 % de los fotogramas, no se pierde ninguno y el codificador se mantiene dentro de su presupuesto por fotograma. Se recomienda la mejor calidad de color que pasa a la tasa de fotogramas más alta, con la tasa de bits más alta con la que aún pasa."),
        (TipBenchTestPattern, "Durante la prueba, el host muestra un patrón fijo en movimiento en lugar de la pantalla: cada paso mide el mismo contenido."),
    ],
};

pub static IT: Lang = Lang {
    code: "it",
    name: "Italiano",
    table: &[
        (AppSubtitle, "Desktop remoto senza perdita di colore"),
        (Connect, "Connetti"),
        (Disconnect, "Disconnetti"),
        (HostAddress, "Indirizzo dell'host"),
        (SearchingHosts, "Ricerca host"),
        (NoHostsFound, "Nessun host trovato"),
        (FoundHosts, "Host trovati"),
        (Settings, "Impostazioni"),
        (Language, "Lingua"),
        (Quit, "Esci"),
        (Connecting, "Connessione in corso"),
        (Connected, "Connesso"),
        (ConnectionLost, "Connessione persa"),
        (Reconnecting, "Riconnessione"),
        (Fullscreen, "Schermo intero"),
        (PixelExact, "Pixel per pixel"),
        (Stretch, "Adatta alla finestra"),
        (ShowOverlay, "Mostra statistiche"),
        (Fps, "Fotogrammi al secondo"),
        (DecodeTime, "Tempo di decodifica"),
        (Bitrate, "Bitrate"),
        (Resolution, "Risoluzione"),
        (Codec, "Codec"),
        (Latency, "Latenza"),
        (EncodeTime, "Codifica"),
        (NetworkTime, "Rete"),
        (AudioBuffer, "Buffer audio"),
        (Dropped, "Fotogrammi persi"),
        (MaxBitrate, "Bitrate massimo"),
        (MaxFps, "Frequenza massima"),
        (ExpertMode, "Modalità esperto"),
        (GamingMode, "Modalità gioco"),
        (FixedRate, "Frequenza fissa"),
        (FixedRateHint, "Mantiene la frequenza anche quando nulla si muove. Carico continuo sull'host."),
        (Sound, "Audio"),
        (HoldEscHint, "Tieni premuto ESC per il menu"),
        (NerdMode, "Modalità nerd"),
        (More, "Altro"),
        (Back, "Indietro"),
        (SavedForHost, "Salvato per questo host"),
        (Queue, "Cattura e attesa"),
        (OneFrame, "Un fotogramma"),
        (Bottleneck, "Collo di bottiglia"),
        (TabPicture, "Immagine"),
        (TabDisplay, "Schermo"),
        (CodecConverted, "convertito"),
        (CodecSwitching, "Cambio codec in corso"),
        (HostCpu, "CPU dell'host"),
        (HostGpu, "GPU dell'host"),
        (HostRam, "Memoria dell'host"),
        (NoDisplay, "L'host al momento non ha uno schermo"),
        (Encryption, "Crittografia"),
        (EncryptionOn, "attivata"),
        (EncryptionOff, "disattivata"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Appunti"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatico"),
        (RoleCpu, "Software"),
        (RoleGpu, "Scheda grafica"),
        (DisplayLabel, "Schermo"),
        (DisplayStage, "Schermo"),
        (ClientCpu, "CPU del client"),
        (Monitor, "Monitor"),
        (Skipped, "saltati"),
        (PairingTitle, "Associa all'host"),
        (PairingHint, "Inserisci il codice mostrato sull'host"),
        (PairingCode, "Codice di associazione"),
        (PairingWrong, "Codice errato"),
        (PairingOk, "Associato"),
        (SecuredWith, "Protetto · codice di verifica"),
        (HostFingerprint, "Impronta dell'host"),
        (NotPaired, "Questo host non conosce ancora il tuo dispositivo. Avvia l'host con --pair e riconnettiti."),
        (FirstContact, "Primo contatto con questo host. Confronta il codice con quello mostrato sull'host."),
        (ErrorConnectRefused, "L'host ha rifiutato la connessione"),
        (ErrorTimeout, "L'host non risponde"),
        (ErrorProtocol, "La controparte usa un altro protocollo"),
        (ErrorNoDecoder, "Nessun decoder per questo formato"),
        (TipBitrate, "Limite superiore del bitrate. Con il movimento l'encoder lo usa tutto; su reti non tue meglio da 25 a 50."),
        (TipFps, "Frequenza fotogrammi desiderata. Non può superare quella dello schermo del Mac."),
        (TipGaming, "Keyframe più frequenti e meno arretrato consentito: più fluido con il movimento, costa un po' di bitrate."),
        (TipSound, "Trasmettere l'audio. Spento risparmia circa 3 Mbit/s; l'host allora non invia audio."),
        (TipCodec, "Codec dell'host, cambiato al volo; l'immagine si ferma un attimo. \"convertito\" costa un passaggio in più."),
        (TipFullscreen, "Schermo intero senza bordi. In finestra l'immagine viene adattata."),
        (TipPixelExact, "Immagine 1:1 senza ridimensionamento. Se la finestra è più piccola, si vede solo una parte."),
        (TipShowOverlay, "Mostra le statistiche in alto a sinistra. Quali righe, a destra."),
        (TipNerdMode, "Statistiche estese: catena di latenza come barra, carico di host e client."),
        (TipStatRows, "Quali righe mostrano le statistiche."),
        (TipDecoderAuto, "Scheda grafica se supporta il codec, altrimenti software."),
        (TipDecoderCpu, "Decodifica sul processore. Funziona ovunque, costa tempo di calcolo."),
        (TipDecoderGpu, "Decodifica sulla scheda grafica. Se non ci riesce, il client torna al software e spiega perché."),
        (TipDisconnect, "Chiudere la connessione, tornare alla schermata iniziale."),
        (TabShortcuts, "Scorciatoie"),
        (ShortcutMenu, "Apri il menu (questo ESC non arriva mai al Mac)"),
        (ShortcutBack, "Torna alla schermata iniziale"),
        (ShortcutWinKey, "Tasto Windows = tasto Comando del Mac"),
        (ShortcutOthers, "Tutti gli altri tasti vanno al Mac. Viene trasmessa la posizione del tasto, non il carattere: accenti e AltGr funzionano da soli."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Avvia"),
        (BenchAbort, "Annulla"),
        (BenchApply, "Applica"),
        (BenchDuration, "Durata per passo"),
        (BenchTestPattern, "Immagine di test"),
        (BenchStep, "Passo {n} di {m}"),
        (BenchPhaseSettings, "impostazioni in corso"),
        (BenchPhaseSettle, "assestamento"),
        (BenchPhaseMeasure, "misurazione"),
        (BenchFailed, "fallito"),
        (BenchDone, "Finito"),
        (BenchAborted, "Annullato"),
        (BenchMeasured, "misurato"),
        (BenchChain, "Catena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "persi"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Raccomandazione"),
        (BenchNoRecommendation, "Nessun passo superato. Prova bitrate o frequenze fotogrammi più bassi."),
        (BenchHint, "Si misura ciò che accade sul Mac in questo momento. I passi sono confrontabili solo se qualcosa si muove: basta un video in riproduzione."),
        (BenchHintPattern, "Con l'immagine di test ogni passo vede lo stesso contenuto in movimento: sul Mac non deve girare nulla."),
        (TipBenchStart, "Misura una dopo l'altra tutte le combinazioni di codec, frequenze fotogrammi e bitrate scelti, ciascuna per la durata impostata. L'immagine continua e il menu può restare aperto."),
        (TipBenchApply, "Impostare codec e impostazioni consigliati e salvarli per questo host."),
        (TipBenchDuration, "Tempo di misura per passo. Più lungo è più stabile; 5 s di solito bastano."),
        (TipBenchHint, "Un passo è superato se la catena resta entro un fotogramma e mezzo, arriva almeno il 95 % dei fotogrammi, nessuno viene perso e l'encoder resta nel suo budget per fotogramma. Consigliata la migliore qualità colore che supera alla frequenza fotogrammi più alta, con il bitrate più alto con cui supera ancora."),
        (TipBenchTestPattern, "Per la durata del test l'host mostra un motivo fisso in movimento al posto dello schermo: ogni passo misura lo stesso contenuto."),
    ],
};

pub static PT: Lang = Lang {
    code: "pt",
    name: "Português",
    table: &[
        (AppSubtitle, "Acesso remoto sem perda de cor"),
        (Connect, "Ligar"),
        (Disconnect, "Terminar ligação"),
        (HostAddress, "Endereço do host"),
        (SearchingHosts, "A procurar hosts"),
        (NoHostsFound, "Nenhum host encontrado"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Definições"),
        (Language, "Idioma"),
        (Quit, "Sair"),
        (Connecting, "A ligar"),
        (Connected, "Ligado"),
        (ConnectionLost, "Ligação perdida"),
        (Reconnecting, "A ligar novamente"),
        (Fullscreen, "Ecrã inteiro"),
        (PixelExact, "Pixel a pixel"),
        (Stretch, "Ajustar à janela"),
        (ShowOverlay, "Mostrar estatísticas"),
        (Fps, "Imagens por segundo"),
        (DecodeTime, "Descodificação"),
        (Bitrate, "Taxa de bits"),
        (Resolution, "Resolução"),
        (Codec, "Codec"),
        (Latency, "Latência"),
        (EncodeTime, "Codificação"),
        (NetworkTime, "Rede"),
        (AudioBuffer, "Buffer de áudio"),
        (Dropped, "Imagens perdidas"),
        (MaxBitrate, "Taxa de bits máxima"),
        (MaxFps, "Taxa de imagens máxima"),
        (ExpertMode, "Modo avançado"),
        (GamingMode, "Modo de jogo"),
        (FixedRate, "Taxa de imagens fixa"),
        (FixedRateHint, "Mantém a taxa mesmo quando nada se move. Carga permanente no host."),
        (Sound, "Som"),
        (HoldEscHint, "Mantenha ESC para o menu"),
        (NerdMode, "Modo nerd"),
        (More, "Mais"),
        (Back, "Voltar"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura e espera"),
        (OneFrame, "Uma imagem"),
        (Bottleneck, "Estrangulamento"),
        (TabPicture, "Imagem"),
        (TabDisplay, "Ecrã"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "A mudar de codec"),
        (HostCpu, "CPU do host"),
        (HostGpu, "GPU do host"),
        (HostRam, "Memória do host"),
        (NoDisplay, "O host não tem ecrã neste momento"),
        (Encryption, "Encriptação"),
        (EncryptionOn, "ativada"),
        (EncryptionOff, "desativada"),
        (AudioEnabled, "Áudio"),
        (ClipboardEnabled, "Área de transferência"),
        (DecoderLabel, "Descodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Software"),
        (RoleGpu, "Placa gráfica"),
        (DisplayLabel, "Ecrã"),
        (DisplayStage, "Ecrã"),
        (ClientCpu, "CPU do cliente"),
        (Monitor, "Monitor"),
        (Skipped, "saltadas"),
        (PairingTitle, "Emparelhar com o host"),
        (PairingHint, "Introduza o código mostrado no host"),
        (PairingCode, "Código de emparelhamento"),
        (PairingWrong, "Código incorreto"),
        (PairingOk, "Emparelhado"),
        (SecuredWith, "Protegido · código de verificação"),
        (HostFingerprint, "Impressão digital do host"),
        (NotPaired, "Este host ainda não conhece o seu dispositivo. Inicie o host com --pair e ligue novamente."),
        (FirstContact, "Primeiro contacto com este host. Compare o código com o que aparece no host."),
        (ErrorConnectRefused, "O host recusou a ligação"),
        (ErrorTimeout, "O host não responde"),
        (ErrorProtocol, "O outro lado usa outro protocolo"),
        (ErrorNoDecoder, "Sem descodificador para este formato"),
        (TipBitrate, "Limite superior da taxa de bits. Com movimento o codificador usa-a toda; em redes alheias, melhor entre 25 e 50."),
        (TipFps, "Taxa de imagens pretendida. Não pode exceder a que o ecrã do Mac fornece."),
        (TipGaming, "Imagens-chave mais frequentes e menos atraso tolerado: mais estável com movimento, custa alguma taxa de bits."),
        (TipSound, "Transmitir o som. Desligado poupa cerca de 3 Mbit/s; o host deixa então de enviar som."),
        (TipCodec, "Codec do host, mudado em funcionamento; a imagem para por um instante. \"convertido\" custa uma passagem a mais."),
        (TipFullscreen, "Ecrã inteiro sem margens. Em janela, a imagem é ajustada."),
        (TipPixelExact, "Imagem 1:1 sem redimensionar. Se a janela for mais pequena, vê-se apenas uma parte."),
        (TipShowOverlay, "Mostrar as estatísticas no canto superior esquerdo. Quais as linhas, à direita."),
        (TipNerdMode, "Estatísticas alargadas: cadeia de latência em barra, carga do host e do cliente."),
        (TipStatRows, "Que linhas as estatísticas mostram."),
        (TipDecoderAuto, "Placa gráfica se suportar o codec, senão software."),
        (TipDecoderCpu, "Descodificar no processador. Funciona em todo o lado, custa tempo de CPU."),
        (TipDecoderGpu, "Descodificar na placa gráfica. Se não conseguir, o cliente recorre ao software e diz porquê."),
        (TipDisconnect, "Terminar a ligação, voltar ao ecrã inicial."),
        (TabShortcuts, "Atalhos"),
        (ShortcutMenu, "Abrir o menu (este ESC nunca chega ao Mac)"),
        (ShortcutBack, "Voltar ao ecrã inicial"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando do Mac"),
        (ShortcutOthers, "Todas as outras teclas vão para o Mac. Transmite-se a posição da tecla, não o carácter: acentos e AltGr funcionam por si."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duração por passo"),
        (BenchTestPattern, "Padrão de teste"),
        (BenchStep, "Passo {n} de {m}"),
        (BenchPhaseSettings, "a aplicar definições"),
        (BenchPhaseSettle, "a estabilizar"),
        (BenchPhaseMeasure, "a medir"),
        (BenchFailed, "falhou"),
        (BenchDone, "Concluído"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadeia"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidas"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendação"),
        (BenchNoRecommendation, "Nenhum passo passou. Experimente taxas de bits ou de imagens mais baixas."),
        (BenchHint, "Mede-se o que acontece no Mac neste momento. Os passos só são comparáveis se algo se mover: basta um vídeo em reprodução."),
        (BenchHintPattern, "Com o padrão de teste, cada passo vê o mesmo conteúdo em movimento: nada precisa de correr no Mac."),
        (TipBenchStart, "Mede uma a uma todas as combinações dos codecs, taxas de imagens e taxas de bits escolhidos, cada uma durante o tempo definido. A imagem continua e o menu pode ficar aberto."),
        (TipBenchApply, "Definir o codec e as definições recomendados e guardá-los para este host."),
        (TipBenchDuration, "Tempo de medição por passo. Mais longo é mais estável; 5 s costumam chegar."),
        (TipBenchHint, "Um passo passa se a cadeia se mantiver dentro de uma imagem e meia, chegarem pelo menos 95 % das imagens, nenhuma for perdida e o codificador se mantiver dentro do seu orçamento por imagem. Recomenda-se a melhor qualidade de cor que passa à taxa de imagens mais alta, com a taxa de bits mais alta com que ainda passa."),
        (TipBenchTestPattern, "Durante o teste, o host mostra um padrão fixo em movimento em vez do ecrã: cada passo mede o mesmo conteúdo."),
    ],
};

pub static NL: Lang = Lang {
    code: "nl",
    name: "Nederlands",
    table: &[
        (AppSubtitle, "Extern bureaublad zonder kleurverlies"),
        (Connect, "Verbinden"),
        (Disconnect, "Verbinding verbreken"),
        (HostAddress, "Adres van de host"),
        (SearchingHosts, "Zoeken naar hosts"),
        (NoHostsFound, "Geen hosts gevonden"),
        (FoundHosts, "Gevonden hosts"),
        (Settings, "Instellingen"),
        (Language, "Taal"),
        (Quit, "Afsluiten"),
        (Connecting, "Bezig met verbinden"),
        (Connected, "Verbonden"),
        (ConnectionLost, "Verbinding verbroken"),
        (Reconnecting, "Opnieuw verbinden"),
        (Fullscreen, "Volledig scherm"),
        (PixelExact, "Pixel voor pixel"),
        (Stretch, "Aan venster aanpassen"),
        (ShowOverlay, "Statistieken tonen"),
        (Fps, "Beelden per seconde"),
        (DecodeTime, "Decodeertijd"),
        (Bitrate, "Bitrate"),
        (Resolution, "Resolutie"),
        (Codec, "Codec"),
        (Latency, "Vertraging"),
        (EncodeTime, "Encodeertijd"),
        (NetworkTime, "Netwerk"),
        (AudioBuffer, "Audiobuffer"),
        (Dropped, "Verloren beelden"),
        (MaxBitrate, "Maximale bitrate"),
        (MaxFps, "Maximale framerate"),
        (ExpertMode, "Expertmodus"),
        (GamingMode, "Spelmodus"),
        (FixedRate, "Vaste framerate"),
        (FixedRateHint, "Houdt de framerate vast, ook als er niets beweegt. Constante belasting op de host."),
        (Sound, "Geluid"),
        (HoldEscHint, "Houd ESC vast voor het menu"),
        (NerdMode, "Nerdmodus"),
        (More, "Meer"),
        (Back, "Terug"),
        (SavedForHost, "Opgeslagen voor deze host"),
        (Queue, "Opname & wachten"),
        (OneFrame, "Eén beeld"),
        (Bottleneck, "Knelpunt"),
        (TabPicture, "Beeld"),
        (TabDisplay, "Weergave"),
        (CodecConverted, "omgezet"),
        (CodecSwitching, "Codec wordt gewisseld"),
        (HostCpu, "Host-CPU"),
        (HostGpu, "Host-GPU"),
        (HostRam, "Hostgeheugen"),
        (NoDisplay, "De host heeft momenteel geen beeldscherm"),
        (Encryption, "Versleuteling"),
        (EncryptionOn, "aan"),
        (EncryptionOff, "uit"),
        (AudioEnabled, "Geluid"),
        (ClipboardEnabled, "Klembord"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatisch"),
        (RoleCpu, "Software"),
        (RoleGpu, "Videokaart"),
        (DisplayLabel, "Weergave"),
        (DisplayStage, "Weergave"),
        (ClientCpu, "Client-CPU"),
        (Monitor, "Monitor"),
        (Skipped, "overgeslagen"),
        (PairingTitle, "Koppelen met host"),
        (PairingHint, "Voer de code in die op de host staat"),
        (PairingCode, "Koppelcode"),
        (PairingWrong, "Onjuiste code"),
        (PairingOk, "Gekoppeld"),
        (SecuredWith, "Beveiligd · verificatiecode"),
        (HostFingerprint, "Vingerafdruk van de host"),
        (NotPaired, "Deze host kent je apparaat nog niet. Start de host met --pair en verbind opnieuw."),
        (FirstContact, "Eerste contact met deze host. Vergelijk de code met die op de host."),
        (ErrorConnectRefused, "Host heeft de verbinding geweigerd"),
        (ErrorTimeout, "Host reageert niet"),
        (ErrorProtocol, "De andere kant spreekt een ander protocol"),
        (ErrorNoDecoder, "Geen decoder voor dit formaat"),
        (TipBitrate, "Bovengrens van de bitrate. Bij beweging gebruikt de encoder alles; op andermans netwerk liever 25 tot 50."),
        (TipFps, "Gewenste framerate. Meer dan het scherm van de Mac levert, kan niet."),
        (TipGaming, "Vaker keyframes en minder toegestane achterstand: rustiger bij beweging, kost wat bitrate."),
        (TipSound, "Geluid meesturen. Uit bespaart zo'n 3 Mbit/s; de host stuurt dan geen geluid."),
        (TipCodec, "Codec van de host, wisselt tijdens gebruik; het beeld staat even stil. \"omgezet\" kost één stap extra."),
        (TipFullscreen, "Randloos volledig scherm. In een venster wordt het beeld ingepast."),
        (TipPixelExact, "Beeld 1:1 zonder schalen. Is het venster kleiner, dan zie je een uitsnede."),
        (TipShowOverlay, "Statistieken linksboven tonen. Welke regels, staat rechts."),
        (TipNerdMode, "Uitgebreide statistieken: vertragingsketen als balk, belasting van host en client."),
        (TipStatRows, "Welke regels de statistieken tonen."),
        (TipDecoderAuto, "Videokaart als die de codec aankan, anders software."),
        (TipDecoderCpu, "Decoderen op de processor. Werkt overal, kost rekentijd."),
        (TipDecoderGpu, "Decoderen op de videokaart. Lukt dat niet, dan valt de client terug op software en zegt waarom."),
        (TipDisconnect, "Verbinding beëindigen, terug naar het startscherm."),
        (TabShortcuts, "Sneltoetsen"),
        (ShortcutMenu, "Menu openen (deze ESC komt nooit bij de Mac aan)"),
        (ShortcutBack, "Terug naar het startscherm"),
        (ShortcutWinKey, "Windows-toets = Command-toets van de Mac"),
        (ShortcutOthers, "Alle andere toetsen gaan naar de Mac. Verzonden wordt de positie van de toets, niet het teken – accenten en AltGr kloppen vanzelf."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Starten"),
        (BenchAbort, "Annuleren"),
        (BenchApply, "Toepassen"),
        (BenchDuration, "Duur per stap"),
        (BenchTestPattern, "Testbeeld"),
        (BenchStep, "Stap {n} van {m}"),
        (BenchPhaseSettings, "instellingen worden gezet"),
        (BenchPhaseSettle, "stabiliseren"),
        (BenchPhaseMeasure, "meten"),
        (BenchFailed, "mislukt"),
        (BenchDone, "Klaar"),
        (BenchAborted, "Geannuleerd"),
        (BenchMeasured, "gemeten"),
        (BenchChain, "Keten"),
        (BenchColFps, "fps"),
        (BenchColDropped, "verloren"),
        (BenchColHostCpu, "Host-CPU"),
        (BenchRecommendation, "Aanbeveling"),
        (BenchNoRecommendation, "Geen enkele stap is geslaagd. Probeer lagere bitrates of framerates."),
        (BenchHint, "Gemeten wordt wat er nu op de Mac gebeurt. Stappen zijn alleen vergelijkbaar als er iets beweegt – een lopende video is genoeg."),
        (BenchHintPattern, "Met testbeeld ziet elke stap dezelfde bewegende inhoud – op de Mac hoeft niets te draaien."),
        (TipBenchStart, "Meet alle combinaties van de gekozen codecs, framerates en bitrates na elkaar, elk voor de ingestelde duur. Het beeld loopt door en het menu mag open blijven."),
        (TipBenchApply, "Aanbevolen codec en instellingen zetten en opslaan voor deze host."),
        (TipBenchDuration, "Meettijd per stap. Langer is rustiger; 5 s is meestal genoeg."),
        (TipBenchHint, "Een stap slaagt als de keten binnen anderhalf beeld blijft, minstens 95 % van de beelden aankomt, er geen verloren gaat en de encoder binnen zijn beeldbudget blijft. Aanbevolen wordt de beste kleurkwaliteit die slaagt bij de hoogste framerate, met de hoogste bitrate waarbij ze nog slaagt."),
        (TipBenchTestPattern, "Voor de duur van de run toont de host een vast bewegend patroon in plaats van het scherm – elke stap meet dezelfde inhoud."),
    ],
};
