// Westeuropaeische Sprachen: Franzoesisch, Spanisch, Italienisch,
// Portugiesisch (Portugal) und Niederlaendisch.
//
// Ein Eintrag je Schluessel aus strings.rs, gleiche Reihenfolge wie dort.

use crate::strings::{Key::*, Lang};

pub static FR: Lang = Lang {
    code: "fr",
    name: "Français",
    table: &[
        (AppSubtitle, "Bureau à distance sans perte de couleur"),
        (Connect, "Se connecter"),
        (Disconnect, "Se déconnecter"),
        (HostAddress, "Adresse de l'hôte"),
        (SearchingHosts, "Recherche d'hôtes"),
        (NoHostsFound, "Aucun hôte trouvé"),
        (FoundHosts, "Hôtes trouvés"),
        (Settings, "Paramètres"),
        (Language, "Langue"),
        (Quit, "Quitter"),
        (Connecting, "Connexion en cours"),
        (Connected, "Connecté"),
        (ConnectionLost, "Connexion perdue"),
        (Reconnecting, "Reconnexion"),
        (Fullscreen, "Plein écran"),
        (PixelExact, "Pixel par pixel"),
        (Stretch, "Ajuster à la fenêtre"),
        (ShowOverlay, "Afficher les statistiques"),
        (Fps, "Images par seconde"),
        (DecodeTime, "Temps de décodage"),
        (Bitrate, "Débit"),
        (Resolution, "Résolution"),
        (Codec, "Codec"),
        (Latency, "Latence"),
        (EncodeTime, "Encodage"),
        (NetworkTime, "Réseau"),
        (AudioBuffer, "Tampon audio"),
        (Dropped, "Images perdues"),
        (MaxBitrate, "Débit maximal"),
        (MaxFps, "Fréquence d'images max"),
        (ExpertMode, "Mode expert"),
        (GamingMode, "Mode jeu"),
        (FixedRate, "Fréquence d'images fixe"),
        (FixedRateHint, "Maintient la fréquence même quand rien ne bouge. Charge permanente sur l'hôte."),
        (Sound, "Son"),
        (HoldEscHint, "Maintenez ESC pour le menu"),
        (NerdMode, "Mode geek"),
        (More, "Plus"),
        (Back, "Retour"),
        (SavedForHost, "Enregistré pour cet hôte"),
        (Queue, "Capture & attente"),
        (OneFrame, "Une image"),
        (Bottleneck, "Goulot d'étranglement"),
        (TabPicture, "Image"),
        (TabDisplay, "Affichage"),
        (CodecConverted, "converti"),
        (CodecSwitching, "Changement de codec"),
        (HostCpu, "CPU de l'hôte"),
        (HostGpu, "GPU de l'hôte"),
        (HostRam, "Mémoire de l'hôte"),
        (NoDisplay, "L'hôte n'a pas d'écran pour le moment"),
        (Encryption, "Chiffrement"),
        (EncryptionOn, "activé"),
        (EncryptionOff, "désactivé"),
        (AudioEnabled, "Son"),
        (ClipboardEnabled, "Presse-papiers"),
        (DecoderLabel, "Décodeur"),
        (RoleAuto, "Automatique"),
        (RoleCpu, "Processeur"),
        (RoleGpu, "Carte graphique"),
        (RoleGpuN, "Carte graphique {n}"),
        (RoleIntegrated, "Intégrée"),
        (NextStartHint, "prend effet au prochain démarrage"),
        (AdapterWithOutput, "avec sortie écran"),
        (AdapterNoOutput, "sans sortie écran"),
        (TipOnly420, "Seulement 4:2:0 et H.264 (D3D11VA) ; en 4:4:4, le client repasse sur le processeur – changer le codec dans l'onglet Image."),
        (DisplayLabel, "Affichage"),
        (DisplayStage, "Affichage"),
        (ClientCpu, "CPU du client"),
        (Monitor, "Moniteur"),
        (Skipped, "sautées"),
        (SecuredWith, "Sécurisé · code de vérification"),
        (HostFingerprint, "Empreinte de l'hôte"),
        (ErrorConnectRefused, "L'hôte a refusé la connexion"),
        (ErrorTimeout, "L'hôte ne répond pas"),
        (ErrorProtocol, "L'autre poste utilise un autre protocole"),
        (ErrorNoDecoder, "Aucun décodeur pour ce format"),
        (SessionTakenOver, "Un autre appareil a repris la session."),
        (KeyFileDamaged, "Le fichier de clé {p} est endommagé et a été laissé tel quel. Vérifiez-le ou supprimez-le – une nouvelle clé sera alors créée, et l'appareil devra de nouveau être autorisé avec le mot de passe."),
        (FileUnreadable, "Impossible de lire {p} – pas de connexion."),
        (FileNotUtf8, "{p} n'est pas enregistré en UTF-8 – pas de connexion."),
        (FileNotWritable, "Impossible d'écrire dans {p} – pas de connexion."),
        (StorageUnavailable, "Le dossier des clés et des paramètres n'est pas disponible – pas de connexion."),
        (ErrorAddress, "Impossible de résoudre l'adresse {n}"),
        (ErrorNoConnection, "Pas de connexion à l'hôte"),
        (ErrorHandshake, "La connexion sécurisée n'a pas pu être établie"),
        (ErrorFfmpegStart, "Impossible de démarrer FFmpeg"),
        (ErrorSound, "Son indisponible"),
        (ErrorGpuDisplay, "Carte graphique inutilisable, affichage en mode logiciel"),
        (ErrorGpuLost, "Carte graphique perdue – veuillez redémarrer avec --anzeige cpu"),
        (ErrorPixelFormat, "Le décodeur fournit des images que ce client ne peut pas afficher"),
        (DecoderFallback, "La carte graphique choisie ne décode pas – le décodeur logiciel prend le relais"),
        (TipBitrate, "Limite supérieure du débit. L'encodeur l'utilise entièrement dès que ça bouge ; sur un réseau qui n'est pas le vôtre, préférez 25 à 50."),
        (TipFps, "Fréquence d'images visée. Impossible d'aller au-delà de ce que fournit l'écran du Mac."),
        (TipGaming, "Images clés plus fréquentes et moins de retard toléré : plus régulier quand ça bouge, coûte un peu de débit."),
        (TipSound, "Transmettre le son. Désactivé, économise environ 3 Mbit/s ; l'hôte n'envoie alors aucun son."),
        (TipCodec, "Codec de l'hôte, changé à chaud ; l'image se fige un instant. « converti » coûte une passe de plus."),
        (TipFullscreen, "Plein écran sans bordure. En fenêtre, l'image est ajustée."),
        (TipPixelExact, "Image 1:1 sans mise à l'échelle. Si la fenêtre est plus petite, seule une partie est visible."),
        (TipShowOverlay, "Afficher les statistiques en haut à gauche. Le choix des lignes se fait à droite."),
        (TipNerdMode, "Statistiques étendues : chaîne de latence en barre, charge de l'hôte et du client."),
        (TipStatRows, "Lignes affichées dans les statistiques."),
        (TipDecoderAuto, "NVDEC sur une carte NVIDIA ; sinon D3D11VA sur la carte qui dessine (seulement 4:2:0 et H.264) ; sinon le processeur."),
        (TipDecoderCpu, "Décodage sur le processeur. Fonctionne partout, coûte du temps de calcul."),
        (TipDecoderGpu, "Décodage sur la carte graphique. Si elle n'y arrive pas, le client repasse sur le processeur et en indique la raison."),
        (TipDecoderIntegrated, "Décodage sur la carte graphique intégrée (D3D11VA). Si elle n'y arrive pas, le client repasse sur le processeur et en indique la raison."),
        (TipDisplayAuto, "Direct3D 11 sur la première carte avec sortie écran, sinon la première carte NVIDIA, sinon la première trouvée. Sans carte : le processeur. Prend effet au prochain démarrage."),
        (TipDisplayGpu, "Dessiner avec Direct3D 11 sur cette carte. Prend effet au prochain démarrage."),
        (TipDisplayIntegrated, "Dessiner avec Direct3D 11 sur la carte graphique intégrée – celle à laquelle l'écran est généralement branché. Prend effet au prochain démarrage."),
        (TipDisplayCpu, "Dessiner sur le processeur, sans Direct3D. Fonctionne partout, coûte du temps de calcul. Prend effet au prochain démarrage."),
        (TipDisconnect, "Terminer la connexion, retour à l'écran d'accueil."),
        (TabShortcuts, "Raccourcis"),
        (ShortcutMenu, "Ouvrir le menu (cet ESC n'atteint jamais le Mac)"),
        (ShortcutBack, "Retour à l'écran d'accueil"),
        (ShortcutWinKey, "Touche Windows = touche Commande du Mac"),
        (ShortcutOthers, "Toutes les autres touches vont au Mac. C'est la position de la touche qui est transmise, pas le caractère – accents et AltGr fonctionnent d'eux-mêmes."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Démarrer"),
        (BenchAbort, "Annuler"),
        (BenchApply, "Appliquer"),
        (BenchDuration, "Durée par étape"),
        (BenchTestPattern, "Mire"),
        (BenchStep, "Étape {n} sur {m}"),
        (BenchPhaseSettings, "réglages en cours"),
        (BenchPhaseSettle, "stabilisation"),
        (BenchPhaseMeasure, "mesure"),
        (BenchFailed, "échec"),
        (BenchDone, "Terminé"),
        (BenchAborted, "Annulé"),
        (BenchMeasured, "mesuré"),
        (BenchChain, "Chaîne"),
        (BenchColFps, "ips"),
        (BenchColDropped, "perdues"),
        (BenchColHostCpu, "CPU hôte"),
        (BenchRecommendation, "Recommandation"),
        (BenchNoRecommendation, "Aucune étape n'a réussi : chaîne au-delà de 30 ms ou trop peu d'images. Essayez des fréquences d'images ou des débits plus bas."),
        (BenchHint, "La mesure reflète ce qui se passe sur le Mac en ce moment. Les étapes ne sont comparables que si quelque chose bouge – une vidéo en lecture suffit."),
        (BenchHintPattern, "Avec la mire, chaque étape voit le même contenu animé – rien n'a besoin de tourner sur le Mac."),
        (TipBenchStart, "Mesure tour à tour toutes les combinaisons des codecs, fréquences d'images et débits choisis, chacune pendant la durée réglée. L'image continue et le menu peut rester ouvert."),
        (TipBenchApply, "Régler le codec et les paramètres recommandés et les enregistrer pour cet hôte."),
        (TipBenchDuration, "Temps de mesure par étape. Plus long est plus stable ; 5 s suffisent en général."),
        (TipBenchHint, "Une étape réussit si au moins 95 % de la fréquence d'images cible arrivent, si moins de 1 % des images sont perdues et si toute la chaîne reste sous 30 ms – quelle que soit la fréquence d'images. Le temps d'encodage de l'hôte est affiché mais pas évalué. Recommandé : la meilleure qualité de couleur qui réussit à la fréquence d'images la plus élevée, au débit le plus élevé."),
        (TipBenchTestPattern, "Pendant toute la durée du test, l'hôte affiche un motif animé fixe à la place de l'écran – chaque étape mesure le même contenu."),
        (DesktopShortcut, "Raccourci bureau"),
        (TipDesktopShortcut, "Crée sur le bureau un raccourci vers cet hôte. Un double-clic dessus établit aussitôt la connexion."),
        (DesktopShortcutCreated, "Raccourci créé sur le bureau : {n}"),
        (DesktopShortcutFailed, "Raccourci non créé : {n}"),
        (DesktopShortcutDescription, "QuadChroma : se connecter à {n} ({m})"),
        (FilesSending, "Envoi des fichiers : {n} sur {m}"),
        (FilesReceiving, "Réception des fichiers : {n} sur {m}"),
        (FilesReady, "Fichiers prêts à coller : {n}"),
        (FilesSent, "Fichiers transférés : {n}"),
        (FilesAborted, "Transfert de fichiers interrompu : {n}"),
        (FilesTooLarge, "Fichiers non transférés : plus de 4 GB ou de 10 000 éléments"),
        (FilesPeerOld, "L'autre côté ne peut pas encore recevoir de fichiers."),
        (TrayOpen, "Ouvrir"),
        (TrayConnect, "Se connecter : {n}"),
        (TrayQuit, "Quitter"),
        (TrayStillRunning, "QuadChroma continue de fonctionner dans la zone de notification."),
        (TrayStillRunningMac, "QuadChroma continue de fonctionner dans la barre des menus."),
        (FilesAbortLocal, "par cet appareil"),
        (FilesAbortPeer, "par l'autre côté"),
        (FilesAbortConnection, "connexion interrompue"),
        (FilesAbortTimeout, "délai dépassé, aucun progrès"),
        (FilesAbortNoSpace, "espace disque insuffisant"),
        (FilesAbortInvalid, "données non valides"),
        (FilesAbortRead, "erreur de lecture"),
        (FilesAbortWrite, "erreur d'écriture"),
        (FilesAbortClipboard, "presse-papiers indisponible"),
        (ScreenLabel, "Écran de l'hôte"),
        (ScreenAuto, "Automatique"),
        (TipScreen, "Quel écran de l'hôte tu vois. Automatique suit l'écran principal ; un écran fixe reste valable jusqu'à ce que tu choisisses autre chose."),
        (ScreenSwitching, "Changement d'écran …"),
        (ScreenFallback, "{n} non connecté – écran de repli : {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Mot de passe pour {n}"),
        (AccessText, "{n} ne connaît pas encore cet appareil. Saisissez le mot de passe affiché dans le menu QuadChroma sur {n}."),
        (AccessOrAllow, "Ou demandez à une personne devant {n} de cliquer sur « Autoriser »."),
        (AccessCode, "Code : {c}"),
        (AccessPassword, "Mot de passe"),
        (AccessShow, "Afficher"),
        (AccessCancel, "Annuler"),
        (AccessChecking, "Vérification …"),
        (AccessWrong, "Mot de passe incorrect."),
        (AccessWait, "Trop de tentatives. Réessayez dans {s} s."),
        (AccessNewIdentity, "L'appareil à cette adresse a une nouvelle identité (ID {i})."),
        (MsgRefused, "{n} a refusé la connexion."),
        (MsgNoAnswer, "Pas de réponse de {n}. Veuillez réessayer."),
        (MsgTooManyAttempts, "Trop de tentatives. Patientez un instant, puis réessayez."),
        (MsgHostOutdated, "{n} utilise une version plus ancienne de QuadChroma. Veuillez la mettre à jour sur {n}."),
        (MsgHostProofBad, "{n} n'a pas pu confirmer le mot de passe. Par sécurité, la connexion a été interrompue."),
        (MsgOtherDevice, "Un autre appareil répond à cette adresse."),
        (MsgIdNotFound, "Aucun appareil avec l'ID {i} trouvé sur le réseau."),
        (StartId, "ID {i}"),
        (StartShare, "Partager ce PC"),
        (StartSharing, "Partage actif"),
        (HostReady, "Prêt pour les connexions"),
        (HostConnected, "Connecté : {n}"),
        (HostDeviceId, "ID de l'appareil : {i}"),
        (HostPassword, "Mot de passe : {p}"),
        (HostCopied, "Copié"),
        (HostChangePassword, "Changer le mot de passe …"),
        (HostRandomPassword, "Nouveau mot de passe aléatoire"),
        (HostNewPassword, "Nouveau mot de passe (au moins 8 caractères)"),
        (HostRepeatPassword, "Répéter le mot de passe"),
        (HostPasswordsDiffer, "Les mots de passe ne correspondent pas."),
        (HostPasswordShort, "Veuillez saisir au moins 8 caractères."),
        (HostPasswordSaved, "Mot de passe enregistré."),
        (HostPasswordUnreadable, "Fichier du mot de passe illisible – nouveaux appareils uniquement via « Autoriser »."),
        (HostDevices, "Appareils autorisés"),
        (HostNoDevices, "Aucun appareil pour l'instant"),
        (HostDeviceLine, "{n} – ID {i} – depuis le {d}"),
        (HostRemove, "Retirer"),
        (HostRemoveAll, "Retirer tous les appareils …"),
        (HostRemoveAllAsk, "Retirer tous les appareils autorisés ? Ils auront de nouveau besoin du mot de passe."),
        (HostListDamaged, "Liste des appareils endommagée"),
        (HostListReset, "Réinitialiser la liste des appareils"),
        (HostRequest, "{n} (ID {i}) souhaite contrôler cet ordinateur."),
        (HostAllow, "Autoriser"),
        (HostDeny, "Refuser"),
        (HostStartLogin, "Lancer à l'ouverture de session"),
        (HostStartWindows, "Démarrer avec Windows"),
        (HostMoveToApps, "Déplacez d'abord QuadChroma dans Applications"),
        (HostScreenMissing, "Enregistrement de l'écran non autorisé – ouvrir Réglages Système …"),
        (HostAccessMissing, "Accessibilité non autorisée – ouvrir Réglages Système …"),
        (HostPortBusy, "Le port {p} est utilisé par un autre programme"),
        (HostQuit, "Quitter QuadChroma"),
        (HostStopSharing, "Arrêter le partage"),
        (HostTooltip, "QuadChroma – ce PC est partagé (ID {i})"),
        (HostOk, "OK"),
        (AccessHide, "Masquer"),
        (MsgShareFailed, "Impossible de démarrer le partage de ce PC."),
        (MsgDeviceRemoved, "{n} ne connaît plus cet appareil. Reconnectez-vous et saisissez le mot de passe."),
        (HostPasswordNotSaved, "Le mot de passe n'a pas pu être enregistré."),
        (HostPasswordInvalid, "Le mot de passe contient des caractères non autorisés."),
        (HostPasswordTitle, "Changer le mot de passe"),
        (MsgHostUnverified, "{n} n'a pas prouvé son identité. Par sécurité, la connexion a été interrompue."),
        (MsgHostQuit, "QuadChroma a été fermé sur {n}."),
        (MsgHostSharingOff, "{n} a arrêté le partage."),
        (MsgHostRemovedYou, "{n} a supprimé cet appareil."),
        (MsgSelf, "Il s'agit de cet ordinateur."),
        (TrayOpenApp, "Ouvrir QuadChroma"),
        (HostSharingIsOff, "Partage désactivé"),
        (DeviceNameChange, "Modifier le nom de l'appareil …"),
        (DeviceNameTitle, "Nom de l'appareil"),
        (DeviceNameLabel, "Les autres appareils voient cet ordinateur sous ce nom :"),
        (DeviceNameHint, "Laissez vide pour utiliser le nom de l'ordinateur ({n})."),
        (DeviceNameTooLong, "Le nom est trop long (40 octets au maximum)."),
        (DeviceNameInvalid, "Le nom contient des caractères non autorisés."),
        (ThisComputer, "Cet ordinateur : {n} · {i}"),
        (DeviceNameRename, "Renommer"),
        (PreventSleep, "Empêcher la mise en veille tant que QuadChroma fonctionne"),
        (TipDecoderAutoMac, "VideoToolbox dans le moteur multimédia du Mac (HEVC 4:4:4 compris) ; sinon le processeur."),
        (TipDisplayAutoMac, "Metal sur la puce graphique du Mac. Sans Metal : le processeur. Prend effet au prochain démarrage."),
        (TipDisplayCpuMac, "Dessiner sur le processeur, sans Metal. Fonctionne partout, coûte du temps de calcul. Prend effet au prochain démarrage."),
        (StartShareMac, "Partager ce Mac"),
        (TabComputers, "Ordinateurs"),
        (ComputersHint, "Cliquez sur un ordinateur pour y passer. Cette session se termine alors."),
        (AccessDeviceKeyChanged, "QuadChroma utilise désormais une seule clé par ordinateur dans les deux sens. Si {n} connaissait déjà cet ordinateur, l'accès est redemandé une fois."),
        (ShareFailedKey, "Le partage n'a pas pu démarrer : host.key ou son dossier est inutilisable."),
        (ShareFailedSwitch, "Le partage n'a pas pu démarrer : {s} est inutilisable. Désactivez puis réactivez le partage pour réessayer."),
        (PreventSleepRefused, "Inactif : refusé par le système ({c})"),
        (CloseWindow, "Fermer la fenêtre"),
        (InputBlocked, "Une fenêtre sur le PC Windows attend une confirmation de Windows lui-même – le contrôle y est momentanément impossible."),
        (AutostartInstalled, "Installé dans {n} – QuadChroma démarre depuis cet emplacement avec Windows."),
        (AutostartFailed, "Impossible de modifier « Démarrer avec Windows ». Les détails figurent dans protokoll.txt."),
        (AutostartNeedsAdmin, "Uniquement avec un compte administrateur"),
        (TipHdr, "HDR10 dès que les deux côtés le peuvent : l'écran de l'hôte et cet écran affichent le HDR. Désactivé : toujours SDR. Enregistré pour cet hôte."),
        (HdrActive, "actif des deux côtés"),
        (HdrMapped, "cet écran l'affiche en SDR"),
        (HdrOff, "désactivé – toujours SDR"),
        (HdrWhyClientSdr, "cet écran est SDR"),
        (HdrWhyCodec, "uniquement en HEVC 10 bits"),
        (HdrWhyHostScreen, "l'écran de l'hôte est SDR"),
        (HdrWhyHostCannot, "l'hôte ne peut pas envoyer de HDR"),
        (HdrWhyClientCannot, "cet affichage ne peut pas montrer le HDR"),
        (HdrWhySwitchFailed, "le passage en HDR a échoué"),
        (HdrWhyNegotiating, "négociation …"),
        (HdrWhyOldHost, "l'hôte ne connaît pas le HDR (ancienne version)"),
        (StatColor, "Couleur"),
        (ShortcutMouseCapture, "Capturer ou libérer la souris (jeux)"),
        (MouseCapturedHint, "Souris capturée · F8 la libère"),
    ],
};

pub static ES: Lang = Lang {
    code: "es",
    name: "Español",
    table: &[
        (AppSubtitle, "Escritorio remoto sin pérdida de color"),
        (Connect, "Conectar"),
        (Disconnect, "Desconectar"),
        (HostAddress, "Dirección del host"),
        (SearchingHosts, "Buscando hosts"),
        (NoHostsFound, "No se encontraron hosts"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Ajustes"),
        (Language, "Idioma"),
        (Quit, "Salir"),
        (Connecting, "Conectando"),
        (Connected, "Conectado"),
        (ConnectionLost, "Conexión perdida"),
        (Reconnecting, "Reconectando"),
        (Fullscreen, "Pantalla completa"),
        (PixelExact, "Píxel a píxel"),
        (Stretch, "Ajustar a la ventana"),
        (ShowOverlay, "Mostrar estadísticas"),
        (Fps, "Fotogramas por segundo"),
        (DecodeTime, "Decodificación"),
        (Bitrate, "Tasa de bits"),
        (Resolution, "Resolución"),
        (Codec, "Códec"),
        (Latency, "Latencia"),
        (EncodeTime, "Codificación"),
        (NetworkTime, "Red"),
        (AudioBuffer, "Búfer de audio"),
        (Dropped, "Fotogramas perdidos"),
        (MaxBitrate, "Tasa de bits máxima"),
        (MaxFps, "Tasa de fotogramas máxima"),
        (ExpertMode, "Modo experto"),
        (GamingMode, "Modo juego"),
        (FixedRate, "Tasa de fotogramas fija"),
        (FixedRateHint, "Mantiene la tasa aunque no se mueva nada. Carga permanente en el host."),
        (Sound, "Sonido"),
        (HoldEscHint, "Mantén ESC para el menú"),
        (NerdMode, "Modo nerd"),
        (More, "Más"),
        (Back, "Atrás"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura y espera"),
        (OneFrame, "Un fotograma"),
        (Bottleneck, "Cuello de botella"),
        (TabPicture, "Imagen"),
        (TabDisplay, "Pantalla"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "Cambiando de códec"),
        (HostCpu, "CPU del host"),
        (HostGpu, "GPU del host"),
        (HostRam, "Memoria del host"),
        (NoDisplay, "El host no tiene pantalla en este momento"),
        (Encryption, "Cifrado"),
        (EncryptionOn, "activado"),
        (EncryptionOff, "desactivado"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Portapapeles"),
        (DecoderLabel, "Decodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Procesador"),
        (RoleGpu, "Tarjeta gráfica"),
        (RoleGpuN, "Tarjeta gráfica {n}"),
        (RoleIntegrated, "Integrada"),
        (NextStartHint, "se aplica desde el próximo inicio"),
        (AdapterWithOutput, "con salida de pantalla"),
        (AdapterNoOutput, "sin salida de pantalla"),
        (TipOnly420, "Solo 4:2:0 y H.264 (D3D11VA); con 4:4:4 el cliente vuelve al procesador – cambiar el códec en la pestaña Imagen."),
        (DisplayLabel, "Pantalla"),
        (DisplayStage, "Pantalla"),
        (ClientCpu, "CPU del cliente"),
        (Monitor, "Monitor"),
        (Skipped, "omitidos"),
        (SecuredWith, "Protegido · código de verificación"),
        (HostFingerprint, "Huella del host"),
        (ErrorConnectRefused, "El host rechazó la conexión"),
        (ErrorTimeout, "El host no responde"),
        (ErrorProtocol, "El otro extremo usa otro protocolo"),
        (ErrorNoDecoder, "No hay decodificador para este formato"),
        (SessionTakenOver, "Otro dispositivo ha tomado el control de la sesión."),
        (KeyFileDamaged, "El archivo de clave {p} está dañado y se ha dejado tal cual. Revísalo o bórralo – entonces se crea una clave nueva y habrá que volver a permitir este dispositivo con la contraseña."),
        (FileUnreadable, "No se puede leer {p} – no se conectará."),
        (FileNotUtf8, "{p} no está guardado en UTF-8 – no se conectará."),
        (FileNotWritable, "No se puede escribir en {p} – no se conectará."),
        (StorageUnavailable, "La carpeta de claves y ajustes no está disponible – no se conectará."),
        (ErrorAddress, "No se puede resolver la dirección {n}"),
        (ErrorNoConnection, "Sin conexión con el host"),
        (ErrorHandshake, "No se pudo establecer la conexión segura"),
        (ErrorFfmpegStart, "No se pudo iniciar FFmpeg"),
        (ErrorSound, "El sonido no está disponible"),
        (ErrorGpuDisplay, "Tarjeta gráfica inutilizable, la imagen se muestra por software"),
        (ErrorGpuLost, "Tarjeta gráfica perdida – reinicia con --anzeige cpu"),
        (ErrorPixelFormat, "El decodificador entrega imágenes que este cliente no puede mostrar"),
        (DecoderFallback, "La tarjeta gráfica elegida no decodifica – se usa el decodificador por software"),
        (TipBitrate, "Límite superior de la tasa de bits. Con movimiento el codificador la usa entera; en redes ajenas, mejor entre 25 y 50."),
        (TipFps, "Tasa de fotogramas objetivo. No puede superar lo que entrega la pantalla del Mac."),
        (TipGaming, "Fotogramas clave más frecuentes y menos retraso permitido: más estable con movimiento, cuesta algo de tasa de bits."),
        (TipSound, "Transmitir el sonido. Desactivado ahorra unos 3 Mbit/s; el host entonces no envía sonido."),
        (TipCodec, "Códec del host, se cambia en marcha; la imagen se detiene un momento. \"convertido\" cuesta una pasada más."),
        (TipFullscreen, "Pantalla completa sin bordes. En ventana, la imagen se ajusta."),
        (TipPixelExact, "Imagen 1:1 sin escalar. Si la ventana es más pequeña, se ve un recorte."),
        (TipShowOverlay, "Mostrar las estadísticas arriba a la izquierda. Qué filas, a la derecha."),
        (TipNerdMode, "Estadísticas ampliadas: cadena de latencia como barra, carga del host y del cliente."),
        (TipStatRows, "Qué filas muestran las estadísticas."),
        (TipDecoderAuto, "NVDEC en una tarjeta NVIDIA; si no, D3D11VA en la tarjeta que dibuja (solo 4:2:0 y H.264); si no, el procesador."),
        (TipDecoderCpu, "Decodificar en el procesador. Funciona en todas partes, cuesta tiempo de CPU."),
        (TipDecoderGpu, "Decodificar en la tarjeta gráfica. Si no puede, el cliente vuelve al procesador y dice por qué."),
        (TipDecoderIntegrated, "Decodificar en la gráfica integrada (D3D11VA). Si no puede, el cliente vuelve al procesador y dice por qué."),
        (TipDisplayAuto, "Direct3D 11 en la primera tarjeta con salida de pantalla; si no, la primera NVIDIA; si no, la primera que haya. Sin tarjeta: el procesador. Se aplica desde el próximo inicio."),
        (TipDisplayGpu, "Dibujar con Direct3D 11 en esta tarjeta. Se aplica desde el próximo inicio."),
        (TipDisplayIntegrated, "Dibujar con Direct3D 11 en la gráfica integrada – a la que suele estar conectada la pantalla. Se aplica desde el próximo inicio."),
        (TipDisplayCpu, "Dibujar en el procesador, sin Direct3D. Funciona en todas partes, cuesta tiempo de CPU. Se aplica desde el próximo inicio."),
        (TipDisconnect, "Terminar la conexión, volver a la pantalla de inicio."),
        (TabShortcuts, "Atajos"),
        (ShortcutMenu, "Abrir el menú (este ESC nunca llega al Mac)"),
        (ShortcutBack, "Volver a la pantalla de inicio"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando del Mac"),
        (ShortcutOthers, "Todas las demás teclas van al Mac. Se transmite la posición de la tecla, no el carácter: acentos y AltGr funcionan por sí solos."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duración por paso"),
        (BenchTestPattern, "Patrón de prueba"),
        (BenchStep, "Paso {n} de {m}"),
        (BenchPhaseSettings, "aplicando ajustes"),
        (BenchPhaseSettle, "estabilizando"),
        (BenchPhaseMeasure, "midiendo"),
        (BenchFailed, "fallido"),
        (BenchDone, "Terminado"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidos"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendación"),
        (BenchNoRecommendation, "Ningún paso ha pasado: cadena por encima de 30 ms o muy pocos fotogramas. Prueba tasas de fotogramas o de bits más bajas."),
        (BenchHint, "Se mide lo que ocurre en el Mac ahora mismo. Los pasos solo son comparables si algo se mueve: basta con un vídeo en reproducción."),
        (BenchHintPattern, "Con el patrón de prueba, cada paso ve el mismo contenido en movimiento: no hace falta que nada corra en el Mac."),
        (TipBenchStart, "Mide una tras otra todas las combinaciones de los códecs, tasas de fotogramas y tasas de bits elegidos, cada una durante el tiempo fijado. La imagen sigue en marcha y el menú puede quedar abierto."),
        (TipBenchApply, "Aplicar el códec y los ajustes recomendados y guardarlos para este host."),
        (TipBenchDuration, "Tiempo de medición por paso. Más largo es más estable; 5 s suelen bastar."),
        (TipBenchHint, "Un paso pasa si llega al menos el 95 % de la tasa de fotogramas objetivo, se pierde menos del 1 % de los fotogramas y toda la cadena se mantiene dentro de 30 ms, sea cual sea la tasa de fotogramas. El tiempo del codificador del host se muestra, pero no se evalúa. Recomendado: la mejor calidad de color que pasa a la tasa de fotogramas más alta, con la tasa de bits más alta."),
        (TipBenchTestPattern, "Durante la prueba, el host muestra un patrón fijo en movimiento en lugar de la pantalla: cada paso mide el mismo contenido."),
        (DesktopShortcut, "Acceso directo"),
        (TipDesktopShortcut, "Crea en el escritorio un acceso directo a este host. Con un doble clic se conecta al instante."),
        (DesktopShortcutCreated, "Acceso directo creado en el escritorio: {n}"),
        (DesktopShortcutFailed, "No se creó el acceso directo: {n}"),
        (DesktopShortcutDescription, "QuadChroma: conectar con {n} ({m})"),
        (FilesSending, "Enviando archivos: {n} de {m}"),
        (FilesReceiving, "Recibiendo archivos: {n} de {m}"),
        (FilesReady, "Archivos listos para pegar: {n}"),
        (FilesSent, "Archivos transferidos: {n}"),
        (FilesAborted, "Transferencia de archivos cancelada: {n}"),
        (FilesTooLarge, "Archivos no transferidos: más de 4 GB o 10 000 elementos"),
        (FilesPeerOld, "El otro lado todavía no puede recibir archivos."),
        (TrayOpen, "Abrir"),
        (TrayConnect, "Conectar: {n}"),
        (TrayQuit, "Salir"),
        (TrayStillRunning, "QuadChroma sigue ejecutándose en el área de notificación."),
        (TrayStillRunningMac, "QuadChroma sigue ejecutándose en la barra de menús."),
        (FilesAbortLocal, "por este dispositivo"),
        (FilesAbortPeer, "por el otro lado"),
        (FilesAbortConnection, "conexión interrumpida"),
        (FilesAbortTimeout, "tiempo agotado sin progreso"),
        (FilesAbortNoSpace, "espacio en disco insuficiente"),
        (FilesAbortInvalid, "datos no válidos"),
        (FilesAbortRead, "error de lectura"),
        (FilesAbortWrite, "error de escritura"),
        (FilesAbortClipboard, "portapapeles no disponible"),
        (ScreenLabel, "Pantalla del host"),
        (ScreenAuto, "Automático"),
        (TipScreen, "Qué pantalla del host ves. Automático sigue la pantalla principal; una pantalla fija vale hasta que elijas otra cosa."),
        (ScreenSwitching, "Cambiando de pantalla …"),
        (ScreenFallback, "{n} no conectada – alternativa: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Contraseña de {n}"),
        (AccessText, "{n} aún no conoce este dispositivo. Introduce la contraseña que aparece en el menú de QuadChroma en {n}."),
        (AccessOrAllow, "O pide a alguien junto a {n} que haga clic en \"Permitir\"."),
        (AccessCode, "Código: {c}"),
        (AccessPassword, "Contraseña"),
        (AccessShow, "Mostrar"),
        (AccessCancel, "Cancelar"),
        (AccessChecking, "Comprobando …"),
        (AccessWrong, "Contraseña incorrecta."),
        (AccessWait, "Demasiados intentos. Vuelve a intentarlo en {s} s."),
        (AccessNewIdentity, "El dispositivo de esta dirección tiene una identidad nueva (ID {i})."),
        (MsgRefused, "{n} ha rechazado la conexión."),
        (MsgNoAnswer, "Sin respuesta de {n}. Inténtalo de nuevo."),
        (MsgTooManyAttempts, "Demasiados intentos. Espera un momento y vuelve a intentarlo."),
        (MsgHostOutdated, "{n} usa una versión anterior de QuadChroma. Actualízala en {n}."),
        (MsgHostProofBad, "{n} no ha podido confirmar la contraseña. Por seguridad, se ha cortado la conexión."),
        (MsgOtherDevice, "En esta dirección responde otro dispositivo."),
        (MsgIdNotFound, "No se ha encontrado ningún dispositivo con el ID {i} en la red."),
        (StartId, "ID {i}"),
        (StartShare, "Compartir este PC"),
        (StartSharing, "Uso compartido activo"),
        (HostReady, "Listo para conexiones"),
        (HostConnected, "Conectado: {n}"),
        (HostDeviceId, "ID del dispositivo: {i}"),
        (HostPassword, "Contraseña: {p}"),
        (HostCopied, "Copiado"),
        (HostChangePassword, "Cambiar contraseña …"),
        (HostRandomPassword, "Nueva contraseña aleatoria"),
        (HostNewPassword, "Nueva contraseña (mínimo 8 caracteres)"),
        (HostRepeatPassword, "Repetir contraseña"),
        (HostPasswordsDiffer, "Las contraseñas no coinciden."),
        (HostPasswordShort, "Usa al menos 8 caracteres."),
        (HostPasswordSaved, "Contraseña guardada."),
        (HostPasswordUnreadable, "Archivo de contraseña ilegible – dispositivos nuevos solo mediante \"Permitir\"."),
        (HostDevices, "Dispositivos permitidos"),
        (HostNoDevices, "Aún no hay dispositivos"),
        (HostDeviceLine, "{n} – ID {i} – desde el {d}"),
        (HostRemove, "Quitar"),
        (HostRemoveAll, "Quitar todos los dispositivos …"),
        (HostRemoveAllAsk, "¿Quitar todos los dispositivos permitidos? Volverán a necesitar la contraseña."),
        (HostListDamaged, "Lista de dispositivos dañada"),
        (HostListReset, "Restablecer lista de dispositivos"),
        (HostRequest, "{n} (ID {i}) quiere controlar este ordenador."),
        (HostAllow, "Permitir"),
        (HostDeny, "Rechazar"),
        (HostStartLogin, "Abrir al iniciar sesión"),
        (HostStartWindows, "Iniciar con Windows"),
        (HostMoveToApps, "Mueve primero QuadChroma a Aplicaciones"),
        (HostScreenMissing, "Grabación de pantalla no permitida – abrir Configuración del Sistema …"),
        (HostAccessMissing, "Accesibilidad no permitida – abrir Configuración del Sistema …"),
        (HostPortBusy, "El puerto {p} lo está usando otro programa"),
        (HostQuit, "Salir de QuadChroma"),
        (HostStopSharing, "Dejar de compartir"),
        (HostTooltip, "QuadChroma – este PC está compartido (ID {i})"),
        (HostOk, "Aceptar"),
        (AccessHide, "Ocultar"),
        (MsgShareFailed, "No se ha podido iniciar el uso compartido de este PC."),
        (MsgDeviceRemoved, "{n} ya no conoce este dispositivo. Vuelve a conectarte e introduce la contraseña."),
        (HostPasswordNotSaved, "No se ha podido guardar la contraseña."),
        (HostPasswordInvalid, "La contraseña contiene caracteres no permitidos."),
        (HostPasswordTitle, "Cambiar contraseña"),
        (MsgHostUnverified, "{n} no ha demostrado su identidad. Por seguridad, se ha cortado la conexión."),
        (MsgHostQuit, "Se ha cerrado QuadChroma en {n}."),
        (MsgHostSharingOff, "{n} ha dejado de compartir."),
        (MsgHostRemovedYou, "{n} ha eliminado este dispositivo."),
        (MsgSelf, "Se trata de este mismo ordenador."),
        (TrayOpenApp, "Abrir QuadChroma"),
        (HostSharingIsOff, "Uso compartido desactivado"),
        (DeviceNameChange, "Cambiar nombre del dispositivo …"),
        (DeviceNameTitle, "Nombre del dispositivo"),
        (DeviceNameLabel, "Otros dispositivos ven este ordenador con este nombre:"),
        (DeviceNameHint, "Déjalo vacío para usar el nombre del equipo ({n})."),
        (DeviceNameTooLong, "El nombre es demasiado largo (máximo 40 bytes)."),
        (DeviceNameInvalid, "El nombre contiene caracteres no permitidos."),
        (ThisComputer, "Este ordenador: {n} · {i}"),
        (DeviceNameRename, "Renombrar"),
        (PreventSleep, "Evitar la suspensión mientras QuadChroma se ejecuta"),
        (TipDecoderAutoMac, "VideoToolbox en el motor multimedia del Mac (también HEVC 4:4:4); si no, el procesador."),
        (TipDisplayAutoMac, "Metal en el chip gráfico del Mac. Sin Metal: el procesador. Se aplica desde el próximo inicio."),
        (TipDisplayCpuMac, "Dibujar en el procesador, sin Metal. Funciona en todas partes, cuesta tiempo de CPU. Se aplica desde el próximo inicio."),
        (StartShareMac, "Compartir este Mac"),
        (TabComputers, "Ordenadores"),
        (ComputersHint, "Haz clic en un ordenador para cambiar a él. Esta sesión termina."),
        (AccessDeviceKeyChanged, "QuadChroma usa ahora una sola clave por ordenador en ambas direcciones. Si {n} ya conocía este ordenador, vuelve a pedir acceso una vez."),
        (ShareFailedKey, "No se pudo iniciar el uso compartido: host.key o su carpeta no se pueden usar."),
        (ShareFailedSwitch, "No se pudo iniciar el uso compartido: {s} no se puede usar. Desactívalo y vuelve a activarlo para reintentarlo."),
        (PreventSleepRefused, "No activo: rechazado por el sistema ({c})"),
        (CloseWindow, "Cerrar ventana"),
        (InputBlocked, "Una ventana en el PC con Windows necesita la propia confirmación de Windows – el control no es posible ahí por un momento."),
        (AutostartInstalled, "Instalado en {n} – QuadChroma se inicia desde allí con Windows."),
        (AutostartFailed, "No se pudo cambiar \"Iniciar con Windows\". Los detalles están en protokoll.txt."),
        (AutostartNeedsAdmin, "Solo con una cuenta de administrador"),
        (TipHdr, "HDR10 en cuanto ambos lados pueden: la pantalla del host y esta pantalla muestran HDR. Desactivado: siempre SDR. Guardado para este host."),
        (HdrActive, "activo en ambos lados"),
        (HdrMapped, "esta pantalla lo muestra en SDR"),
        (HdrOff, "desactivado – siempre SDR"),
        (HdrWhyClientSdr, "esta pantalla es SDR"),
        (HdrWhyCodec, "solo con HEVC 10 bits"),
        (HdrWhyHostScreen, "la pantalla del host es SDR"),
        (HdrWhyHostCannot, "el host no puede enviar HDR"),
        (HdrWhyClientCannot, "esta visualización no puede mostrar HDR"),
        (HdrWhySwitchFailed, "falló el cambio a HDR"),
        (HdrWhyNegotiating, "negociando …"),
        (HdrWhyOldHost, "el host no admite HDR (versión anterior)"),
        (StatColor, "Color"),
        (ShortcutMouseCapture, "Capturar o liberar el ratón (juegos)"),
        (MouseCapturedHint, "Ratón capturado · F8 lo libera"),
    ],
};

pub static IT: Lang = Lang {
    code: "it",
    name: "Italiano",
    table: &[
        (AppSubtitle, "Desktop remoto senza perdita di colore"),
        (Connect, "Connetti"),
        (Disconnect, "Disconnetti"),
        (HostAddress, "Indirizzo dell'host"),
        (SearchingHosts, "Ricerca host"),
        (NoHostsFound, "Nessun host trovato"),
        (FoundHosts, "Host trovati"),
        (Settings, "Impostazioni"),
        (Language, "Lingua"),
        (Quit, "Esci"),
        (Connecting, "Connessione in corso"),
        (Connected, "Connesso"),
        (ConnectionLost, "Connessione persa"),
        (Reconnecting, "Riconnessione"),
        (Fullscreen, "Schermo intero"),
        (PixelExact, "Pixel per pixel"),
        (Stretch, "Adatta alla finestra"),
        (ShowOverlay, "Mostra statistiche"),
        (Fps, "Fotogrammi al secondo"),
        (DecodeTime, "Tempo di decodifica"),
        (Bitrate, "Bitrate"),
        (Resolution, "Risoluzione"),
        (Codec, "Codec"),
        (Latency, "Latenza"),
        (EncodeTime, "Codifica"),
        (NetworkTime, "Rete"),
        (AudioBuffer, "Buffer audio"),
        (Dropped, "Fotogrammi persi"),
        (MaxBitrate, "Bitrate massimo"),
        (MaxFps, "Frequenza massima"),
        (ExpertMode, "Modalità esperto"),
        (GamingMode, "Modalità gioco"),
        (FixedRate, "Frequenza fissa"),
        (FixedRateHint, "Mantiene la frequenza anche quando nulla si muove. Carico continuo sull'host."),
        (Sound, "Audio"),
        (HoldEscHint, "Tieni premuto ESC per il menu"),
        (NerdMode, "Modalità nerd"),
        (More, "Altro"),
        (Back, "Indietro"),
        (SavedForHost, "Salvato per questo host"),
        (Queue, "Cattura e attesa"),
        (OneFrame, "Un fotogramma"),
        (Bottleneck, "Collo di bottiglia"),
        (TabPicture, "Immagine"),
        (TabDisplay, "Schermo"),
        (CodecConverted, "convertito"),
        (CodecSwitching, "Cambio codec in corso"),
        (HostCpu, "CPU dell'host"),
        (HostGpu, "GPU dell'host"),
        (HostRam, "Memoria dell'host"),
        (NoDisplay, "L'host al momento non ha uno schermo"),
        (Encryption, "Crittografia"),
        (EncryptionOn, "attivata"),
        (EncryptionOff, "disattivata"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Appunti"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatico"),
        (RoleCpu, "Processore"),
        (RoleGpu, "Scheda grafica"),
        (RoleGpuN, "Scheda grafica {n}"),
        (RoleIntegrated, "Integrata"),
        (NextStartHint, "vale dal prossimo avvio"),
        (AdapterWithOutput, "con uscita video"),
        (AdapterNoOutput, "senza uscita video"),
        (TipOnly420, "Solo 4:2:0 e H.264 (D3D11VA); con 4:4:4 il client torna al processore – cambiare il codec nella scheda Immagine."),
        (DisplayLabel, "Schermo"),
        (DisplayStage, "Schermo"),
        (ClientCpu, "CPU del client"),
        (Monitor, "Monitor"),
        (Skipped, "saltati"),
        (SecuredWith, "Protetto · codice di verifica"),
        (HostFingerprint, "Impronta dell'host"),
        (ErrorConnectRefused, "L'host ha rifiutato la connessione"),
        (ErrorTimeout, "L'host non risponde"),
        (ErrorProtocol, "La controparte usa un altro protocollo"),
        (ErrorNoDecoder, "Nessun decoder per questo formato"),
        (SessionTakenOver, "Un altro dispositivo ha preso il controllo della sessione."),
        (KeyFileDamaged, "Il file della chiave {p} è danneggiato ed è stato lasciato com'è. Controllalo o eliminalo – verrà creata una nuova chiave e il dispositivo dovrà essere di nuovo consentito con la password."),
        (FileUnreadable, "Impossibile leggere {p} – nessuna connessione."),
        (FileNotUtf8, "{p} non è salvato in UTF-8 – nessuna connessione."),
        (FileNotWritable, "Impossibile scrivere {p} – nessuna connessione."),
        (StorageUnavailable, "La cartella per chiavi e impostazioni non è disponibile – nessuna connessione."),
        (ErrorAddress, "Impossibile risolvere l'indirizzo {n}"),
        (ErrorNoConnection, "Nessuna connessione all'host"),
        (ErrorHandshake, "Impossibile stabilire la connessione sicura"),
        (ErrorFfmpegStart, "Impossibile avviare FFmpeg"),
        (ErrorSound, "Audio non disponibile"),
        (ErrorGpuDisplay, "Scheda grafica non utilizzabile, visualizzazione via software"),
        (ErrorGpuLost, "Scheda grafica persa – riavvia con --anzeige cpu"),
        (ErrorPixelFormat, "Il decoder fornisce immagini che questo client non può visualizzare"),
        (DecoderFallback, "La scheda grafica scelta non decodifica – è in uso il decoder software"),
        (TipBitrate, "Limite superiore del bitrate. Con il movimento l'encoder lo usa tutto; su reti non tue meglio da 25 a 50."),
        (TipFps, "Frequenza fotogrammi desiderata. Non può superare quella dello schermo del Mac."),
        (TipGaming, "Keyframe più frequenti e meno arretrato consentito: più fluido con il movimento, costa un po' di bitrate."),
        (TipSound, "Trasmettere l'audio. Spento risparmia circa 3 Mbit/s; l'host allora non invia audio."),
        (TipCodec, "Codec dell'host, cambiato al volo; l'immagine si ferma un attimo. \"convertito\" costa un passaggio in più."),
        (TipFullscreen, "Schermo intero senza bordi. In finestra l'immagine viene adattata."),
        (TipPixelExact, "Immagine 1:1 senza ridimensionamento. Se la finestra è più piccola, si vede solo una parte."),
        (TipShowOverlay, "Mostra le statistiche in alto a sinistra. Quali righe, a destra."),
        (TipNerdMode, "Statistiche estese: catena di latenza come barra, carico di host e client."),
        (TipStatRows, "Quali righe mostrano le statistiche."),
        (TipDecoderAuto, "NVDEC su una scheda NVIDIA; altrimenti D3D11VA sulla scheda che disegna (solo 4:2:0 e H.264); altrimenti il processore."),
        (TipDecoderCpu, "Decodifica sul processore. Funziona ovunque, costa tempo di calcolo."),
        (TipDecoderGpu, "Decodifica sulla scheda grafica. Se non ci riesce, il client torna al processore e spiega perché."),
        (TipDecoderIntegrated, "Decodifica sulla grafica integrata (D3D11VA). Se non ci riesce, il client torna al processore e spiega perché."),
        (TipDisplayAuto, "Direct3D 11 sulla prima scheda con uscita video, altrimenti la prima NVIDIA, altrimenti la prima che c'è. Senza scheda: il processore. Vale dal prossimo avvio."),
        (TipDisplayGpu, "Disegnare con Direct3D 11 su questa scheda. Vale dal prossimo avvio."),
        (TipDisplayIntegrated, "Disegnare con Direct3D 11 sulla grafica integrata – quella a cui di solito è collegato lo schermo. Vale dal prossimo avvio."),
        (TipDisplayCpu, "Disegnare sul processore, senza Direct3D. Funziona ovunque, costa tempo di calcolo. Vale dal prossimo avvio."),
        (TipDisconnect, "Chiudere la connessione, tornare alla schermata iniziale."),
        (TabShortcuts, "Scorciatoie"),
        (ShortcutMenu, "Apri il menu (questo ESC non arriva mai al Mac)"),
        (ShortcutBack, "Torna alla schermata iniziale"),
        (ShortcutWinKey, "Tasto Windows = tasto Comando del Mac"),
        (ShortcutOthers, "Tutti gli altri tasti vanno al Mac. Viene trasmessa la posizione del tasto, non il carattere: accenti e AltGr funzionano da soli."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Avvia"),
        (BenchAbort, "Annulla"),
        (BenchApply, "Applica"),
        (BenchDuration, "Durata per passo"),
        (BenchTestPattern, "Immagine di test"),
        (BenchStep, "Passo {n} di {m}"),
        (BenchPhaseSettings, "impostazioni in corso"),
        (BenchPhaseSettle, "assestamento"),
        (BenchPhaseMeasure, "misurazione"),
        (BenchFailed, "fallito"),
        (BenchDone, "Finito"),
        (BenchAborted, "Annullato"),
        (BenchMeasured, "misurato"),
        (BenchChain, "Catena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "persi"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Raccomandazione"),
        (BenchNoRecommendation, "Nessun passo superato: catena oltre 30 ms o troppo pochi fotogrammi. Prova frequenze fotogrammi o bitrate più bassi."),
        (BenchHint, "Si misura ciò che accade sul Mac in questo momento. I passi sono confrontabili solo se qualcosa si muove: basta un video in riproduzione."),
        (BenchHintPattern, "Con l'immagine di test ogni passo vede lo stesso contenuto in movimento: sul Mac non deve girare nulla."),
        (TipBenchStart, "Misura una dopo l'altra tutte le combinazioni di codec, frequenze fotogrammi e bitrate scelti, ciascuna per la durata impostata. L'immagine continua e il menu può restare aperto."),
        (TipBenchApply, "Impostare codec e impostazioni consigliati e salvarli per questo host."),
        (TipBenchDuration, "Tempo di misura per passo. Più lungo è più stabile; 5 s di solito bastano."),
        (TipBenchHint, "Un passo è superato se arriva almeno il 95 % della frequenza fotogrammi obiettivo, meno dell'1 % dei fotogrammi viene perso e l'intera catena resta entro 30 ms, indipendentemente dalla frequenza fotogrammi. Il tempo dell'encoder dell'host viene mostrato ma non valutato. Consigliata: la migliore qualità colore che supera alla frequenza fotogrammi più alta, con il bitrate più alto."),
        (TipBenchTestPattern, "Per la durata del test l'host mostra un motivo fisso in movimento al posto dello schermo: ogni passo misura lo stesso contenuto."),
        (DesktopShortcut, "Collegamento"),
        (TipDesktopShortcut, "Crea sul desktop un collegamento a questo host. Con un doppio clic si connette subito."),
        (DesktopShortcutCreated, "Collegamento creato sul desktop: {n}"),
        (DesktopShortcutFailed, "Collegamento non creato: {n}"),
        (DesktopShortcutDescription, "QuadChroma: connettersi a {n} ({m})"),
        (FilesSending, "Invio dei file: {n} di {m}"),
        (FilesReceiving, "Ricezione dei file: {n} di {m}"),
        (FilesReady, "File pronti da incollare: {n}"),
        (FilesSent, "File trasferiti: {n}"),
        (FilesAborted, "Trasferimento dei file interrotto: {n}"),
        (FilesTooLarge, "File non trasferiti: più di 4 GB o 10.000 elementi"),
        (FilesPeerOld, "L'altro lato non può ancora ricevere file."),
        (TrayOpen, "Apri"),
        (TrayConnect, "Connetti: {n}"),
        (TrayQuit, "Esci"),
        (TrayStillRunning, "QuadChroma continua a funzionare nell'area di notifica."),
        (TrayStillRunningMac, "QuadChroma continua a funzionare nella barra dei menu."),
        (FilesAbortLocal, "da questo dispositivo"),
        (FilesAbortPeer, "dall'altro lato"),
        (FilesAbortConnection, "connessione interrotta"),
        (FilesAbortTimeout, "tempo scaduto senza progressi"),
        (FilesAbortNoSpace, "spazio su disco insufficiente"),
        (FilesAbortInvalid, "dati non validi"),
        (FilesAbortRead, "errore di lettura"),
        (FilesAbortWrite, "errore di scrittura"),
        (FilesAbortClipboard, "appunti non disponibili"),
        (ScreenLabel, "Schermo dell'host"),
        (ScreenAuto, "Automatico"),
        (TipScreen, "Quale schermo dell'host vedi. Automatico segue lo schermo principale; uno schermo fisso vale finché non scegli altro."),
        (ScreenSwitching, "Cambio schermo in corso …"),
        (ScreenFallback, "{n} non collegato – ripiego: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Password per {n}"),
        (AccessText, "{n} non conosce ancora questo dispositivo. Inserisci la password che compare nel menu di QuadChroma su {n}."),
        (AccessOrAllow, "Oppure chiedi a qualcuno davanti a {n} di fare clic su \"Consenti\"."),
        (AccessCode, "Codice: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Mostra"),
        (AccessCancel, "Annulla"),
        (AccessChecking, "Verifica in corso …"),
        (AccessWrong, "Password errata."),
        (AccessWait, "Troppi tentativi. Riprova tra {s} s."),
        (AccessNewIdentity, "Il dispositivo a questo indirizzo ha una nuova identità (ID {i})."),
        (MsgRefused, "{n} ha rifiutato la connessione."),
        (MsgNoAnswer, "Nessuna risposta da {n}. Riprova."),
        (MsgTooManyAttempts, "Troppi tentativi. Attendi un momento e riprova."),
        (MsgHostOutdated, "{n} usa una versione precedente di QuadChroma. Aggiornala su {n}."),
        (MsgHostProofBad, "{n} non ha potuto confermare la password. Per sicurezza la connessione è stata interrotta."),
        (MsgOtherDevice, "A questo indirizzo risponde un altro dispositivo."),
        (MsgIdNotFound, "Nessun dispositivo con ID {i} trovato nella rete."),
        (StartId, "ID {i}"),
        (StartShare, "Condividi questo PC"),
        (StartSharing, "Condivisione attiva"),
        (HostReady, "Pronto per le connessioni"),
        (HostConnected, "Connesso: {n}"),
        (HostDeviceId, "ID dispositivo: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copiato"),
        (HostChangePassword, "Cambia password …"),
        (HostRandomPassword, "Nuova password casuale"),
        (HostNewPassword, "Nuova password (almeno 8 caratteri)"),
        (HostRepeatPassword, "Ripeti password"),
        (HostPasswordsDiffer, "Le password non coincidono."),
        (HostPasswordShort, "Servono almeno 8 caratteri."),
        (HostPasswordSaved, "Password salvata."),
        (HostPasswordUnreadable, "File della password illeggibile – nuovi dispositivi solo tramite \"Consenti\"."),
        (HostDevices, "Dispositivi consentiti"),
        (HostNoDevices, "Ancora nessun dispositivo"),
        (HostDeviceLine, "{n} – ID {i} – dal {d}"),
        (HostRemove, "Rimuovi"),
        (HostRemoveAll, "Rimuovi tutti i dispositivi …"),
        (HostRemoveAllAsk, "Rimuovere tutti i dispositivi consentiti? Avranno di nuovo bisogno della password."),
        (HostListDamaged, "Elenco dispositivi danneggiato"),
        (HostListReset, "Reimposta elenco dispositivi"),
        (HostRequest, "{n} (ID {i}) vuole controllare questo computer."),
        (HostAllow, "Consenti"),
        (HostDeny, "Rifiuta"),
        (HostStartLogin, "Avvia al login"),
        (HostStartWindows, "Avvia con Windows"),
        (HostMoveToApps, "Sposta prima QuadChroma in Applicazioni"),
        (HostScreenMissing, "Registrazione schermo non consentita – apri Impostazioni di Sistema …"),
        (HostAccessMissing, "Accessibilità non consentita – apri Impostazioni di Sistema …"),
        (HostPortBusy, "La porta {p} è usata da un altro programma"),
        (HostQuit, "Esci da QuadChroma"),
        (HostStopSharing, "Interrompi condivisione"),
        (HostTooltip, "QuadChroma – questo PC è condiviso (ID {i})"),
        (HostOk, "OK"),
        (AccessHide, "Nascondi"),
        (MsgShareFailed, "Impossibile avviare la condivisione di questo PC."),
        (MsgDeviceRemoved, "{n} non conosce più questo dispositivo. Connettiti di nuovo e inserisci la password."),
        (HostPasswordNotSaved, "Impossibile salvare la password."),
        (HostPasswordInvalid, "La password contiene caratteri non consentiti."),
        (HostPasswordTitle, "Cambia password"),
        (MsgHostUnverified, "{n} non ha dimostrato la propria identità. Per sicurezza la connessione è stata interrotta."),
        (MsgHostQuit, "QuadChroma è stato chiuso su {n}."),
        (MsgHostSharingOff, "{n} ha interrotto la condivisione."),
        (MsgHostRemovedYou, "{n} ha rimosso questo dispositivo."),
        (MsgSelf, "Si tratta di questo computer."),
        (TrayOpenApp, "Apri QuadChroma"),
        (HostSharingIsOff, "Condivisione disattivata"),
        (DeviceNameChange, "Cambia nome del dispositivo …"),
        (DeviceNameTitle, "Nome del dispositivo"),
        (DeviceNameLabel, "Gli altri dispositivi vedono questo computer con questo nome:"),
        (DeviceNameHint, "Lascia vuoto per usare il nome del computer ({n})."),
        (DeviceNameTooLong, "Il nome è troppo lungo (al massimo 40 byte)."),
        (DeviceNameInvalid, "Il nome contiene caratteri non consentiti."),
        (ThisComputer, "Questo computer: {n} · {i}"),
        (DeviceNameRename, "Rinomina"),
        (PreventSleep, "Impedisci la sospensione mentre QuadChroma è in esecuzione"),
        (TipDecoderAutoMac, "VideoToolbox nel motore multimediale del Mac (anche HEVC 4:4:4); altrimenti il processore."),
        (TipDisplayAutoMac, "Metal sul chip grafico del Mac. Senza Metal: il processore. Vale dal prossimo avvio."),
        (TipDisplayCpuMac, "Disegnare sul processore, senza Metal. Funziona ovunque, costa tempo di calcolo. Vale dal prossimo avvio."),
        (StartShareMac, "Condividi questo Mac"),
        (TabComputers, "Computer"),
        (ComputersHint, "Fai clic su un computer per passare a quello. Questa sessione termina."),
        (AccessDeviceKeyChanged, "QuadChroma ora usa una sola chiave per computer in entrambe le direzioni. Se {n} conosceva già questo computer, chiede di nuovo l'accesso una volta."),
        (ShareFailedKey, "Impossibile avviare la condivisione: host.key o la sua cartella non sono utilizzabili."),
        (ShareFailedSwitch, "Impossibile avviare la condivisione: {s} non è utilizzabile. Disattivala e riattivala per riprovare."),
        (PreventSleepRefused, "Non attivo: rifiutato dal sistema ({c})"),
        (CloseWindow, "Chiudi finestra"),
        (InputBlocked, "Una finestra sul PC Windows richiede la conferma di Windows stesso – lì il controllo non è possibile per un momento."),
        (AutostartInstalled, "Installato in {n} – QuadChroma si avvia da lì con Windows."),
        (AutostartFailed, "Impossibile modificare \"Avvia con Windows\". I dettagli sono in protokoll.txt."),
        (AutostartNeedsAdmin, "Solo con un account amministratore"),
        (TipHdr, "HDR10 non appena entrambi i lati possono: lo schermo dell'host e questo schermo mostrano l'HDR. Spento: sempre SDR. Salvato per questo host."),
        (HdrActive, "attivo su entrambi i lati"),
        (HdrMapped, "questo schermo lo mostra in SDR"),
        (HdrOff, "spento – sempre SDR"),
        (HdrWhyClientSdr, "questo schermo è SDR"),
        (HdrWhyCodec, "solo con HEVC 10 bit"),
        (HdrWhyHostScreen, "lo schermo dell'host è SDR"),
        (HdrWhyHostCannot, "l'host non può inviare HDR"),
        (HdrWhyClientCannot, "questa visualizzazione non può mostrare l'HDR"),
        (HdrWhySwitchFailed, "passaggio a HDR non riuscito"),
        (HdrWhyNegotiating, "negoziazione …"),
        (HdrWhyOldHost, "l'host non supporta l'HDR (versione precedente)"),
        (StatColor, "Colore"),
        (ShortcutMouseCapture, "Cattura o rilascia il mouse (giochi)"),
        (MouseCapturedHint, "Mouse catturato · F8 lo rilascia"),
    ],
};

pub static PT: Lang = Lang {
    code: "pt",
    name: "Português",
    table: &[
        (AppSubtitle, "Acesso remoto sem perda de cor"),
        (Connect, "Ligar"),
        (Disconnect, "Terminar ligação"),
        (HostAddress, "Endereço do host"),
        (SearchingHosts, "A procurar hosts"),
        (NoHostsFound, "Nenhum host encontrado"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Definições"),
        (Language, "Idioma"),
        (Quit, "Sair"),
        (Connecting, "A ligar"),
        (Connected, "Ligado"),
        (ConnectionLost, "Ligação perdida"),
        (Reconnecting, "A ligar novamente"),
        (Fullscreen, "Ecrã inteiro"),
        (PixelExact, "Pixel a pixel"),
        (Stretch, "Ajustar à janela"),
        (ShowOverlay, "Mostrar estatísticas"),
        (Fps, "Imagens por segundo"),
        (DecodeTime, "Descodificação"),
        (Bitrate, "Taxa de bits"),
        (Resolution, "Resolução"),
        (Codec, "Codec"),
        (Latency, "Latência"),
        (EncodeTime, "Codificação"),
        (NetworkTime, "Rede"),
        (AudioBuffer, "Buffer de áudio"),
        (Dropped, "Imagens perdidas"),
        (MaxBitrate, "Taxa de bits máxima"),
        (MaxFps, "Taxa de imagens máxima"),
        (ExpertMode, "Modo avançado"),
        (GamingMode, "Modo de jogo"),
        (FixedRate, "Taxa de imagens fixa"),
        (FixedRateHint, "Mantém a taxa mesmo quando nada se move. Carga permanente no host."),
        (Sound, "Som"),
        (HoldEscHint, "Mantenha ESC para o menu"),
        (NerdMode, "Modo nerd"),
        (More, "Mais"),
        (Back, "Voltar"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura e espera"),
        (OneFrame, "Uma imagem"),
        (Bottleneck, "Estrangulamento"),
        (TabPicture, "Imagem"),
        (TabDisplay, "Ecrã"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "A mudar de codec"),
        (HostCpu, "CPU do host"),
        (HostGpu, "GPU do host"),
        (HostRam, "Memória do host"),
        (NoDisplay, "O host não tem ecrã neste momento"),
        (Encryption, "Encriptação"),
        (EncryptionOn, "ativada"),
        (EncryptionOff, "desativada"),
        (AudioEnabled, "Áudio"),
        (ClipboardEnabled, "Área de transferência"),
        (DecoderLabel, "Descodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Processador"),
        (RoleGpu, "Placa gráfica"),
        (RoleGpuN, "Placa gráfica {n}"),
        (RoleIntegrated, "Integrada"),
        (NextStartHint, "aplica-se a partir do próximo arranque"),
        (AdapterWithOutput, "com saída de ecrã"),
        (AdapterNoOutput, "sem saída de ecrã"),
        (TipOnly420, "Só 4:2:0 e H.264 (D3D11VA); com 4:4:4 o cliente recorre ao processador – mudar o codec no separador Imagem."),
        (DisplayLabel, "Ecrã"),
        (DisplayStage, "Ecrã"),
        (ClientCpu, "CPU do cliente"),
        (Monitor, "Monitor"),
        (Skipped, "saltadas"),
        (SecuredWith, "Protegido · código de verificação"),
        (HostFingerprint, "Impressão digital do host"),
        (ErrorConnectRefused, "O host recusou a ligação"),
        (ErrorTimeout, "O host não responde"),
        (ErrorProtocol, "O outro lado usa outro protocolo"),
        (ErrorNoDecoder, "Sem descodificador para este formato"),
        (SessionTakenOver, "Outro dispositivo assumiu a sessão."),
        (KeyFileDamaged, "O ficheiro de chave {p} está danificado e foi deixado como está. Verifique-o ou apague-o – é então criada uma chave nova, e o dispositivo terá de ser novamente permitido com a palavra-passe."),
        (FileUnreadable, "Não é possível ler {p} – não é feita a ligação."),
        (FileNotUtf8, "{p} não está guardado em UTF-8 – não é feita a ligação."),
        (FileNotWritable, "Não é possível escrever em {p} – não é feita a ligação."),
        (StorageUnavailable, "A pasta para chaves e definições não está disponível – não é feita a ligação."),
        (ErrorAddress, "Não é possível resolver o endereço {n}"),
        (ErrorNoConnection, "Sem ligação ao host"),
        (ErrorHandshake, "Não foi possível estabelecer a ligação segura"),
        (ErrorFfmpegStart, "Não foi possível iniciar o FFmpeg"),
        (ErrorSound, "Som indisponível"),
        (ErrorGpuDisplay, "Placa gráfica inutilizável, a imagem é mostrada por software"),
        (ErrorGpuLost, "Placa gráfica perdida – reinicie com --anzeige cpu"),
        (ErrorPixelFormat, "O descodificador entrega imagens que este cliente não consegue mostrar"),
        (DecoderFallback, "A placa gráfica escolhida não descodifica – está a ser usado o descodificador por software"),
        (TipBitrate, "Limite superior da taxa de bits. Com movimento o codificador usa-a toda; em redes alheias, melhor entre 25 e 50."),
        (TipFps, "Taxa de imagens pretendida. Não pode exceder a que o ecrã do Mac fornece."),
        (TipGaming, "Imagens-chave mais frequentes e menos atraso tolerado: mais estável com movimento, custa alguma taxa de bits."),
        (TipSound, "Transmitir o som. Desligado poupa cerca de 3 Mbit/s; o host deixa então de enviar som."),
        (TipCodec, "Codec do host, mudado em funcionamento; a imagem para por um instante. \"convertido\" custa uma passagem a mais."),
        (TipFullscreen, "Ecrã inteiro sem margens. Em janela, a imagem é ajustada."),
        (TipPixelExact, "Imagem 1:1 sem redimensionar. Se a janela for mais pequena, vê-se apenas uma parte."),
        (TipShowOverlay, "Mostrar as estatísticas no canto superior esquerdo. Quais as linhas, à direita."),
        (TipNerdMode, "Estatísticas alargadas: cadeia de latência em barra, carga do host e do cliente."),
        (TipStatRows, "Que linhas as estatísticas mostram."),
        (TipDecoderAuto, "NVDEC numa placa NVIDIA; senão D3D11VA na placa que desenha (só 4:2:0 e H.264); senão o processador."),
        (TipDecoderCpu, "Descodificar no processador. Funciona em todo o lado, custa tempo de CPU."),
        (TipDecoderGpu, "Descodificar na placa gráfica. Se não conseguir, o cliente recorre ao processador e diz porquê."),
        (TipDecoderIntegrated, "Descodificar na gráfica integrada (D3D11VA). Se não conseguir, o cliente recorre ao processador e diz porquê."),
        (TipDisplayAuto, "Direct3D 11 na primeira placa com saída de ecrã, senão a primeira NVIDIA, senão a primeira que houver. Sem placa: o processador. Aplica-se a partir do próximo arranque."),
        (TipDisplayGpu, "Desenhar com Direct3D 11 nesta placa. Aplica-se a partir do próximo arranque."),
        (TipDisplayIntegrated, "Desenhar com Direct3D 11 na gráfica integrada – aquela a que o ecrã normalmente está ligado. Aplica-se a partir do próximo arranque."),
        (TipDisplayCpu, "Desenhar no processador, sem Direct3D. Funciona em todo o lado, custa tempo de CPU. Aplica-se a partir do próximo arranque."),
        (TipDisconnect, "Terminar a ligação, voltar ao ecrã inicial."),
        (TabShortcuts, "Atalhos"),
        (ShortcutMenu, "Abrir o menu (este ESC nunca chega ao Mac)"),
        (ShortcutBack, "Voltar ao ecrã inicial"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando do Mac"),
        (ShortcutOthers, "Todas as outras teclas vão para o Mac. Transmite-se a posição da tecla, não o carácter: acentos e AltGr funcionam por si."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duração por passo"),
        (BenchTestPattern, "Padrão de teste"),
        (BenchStep, "Passo {n} de {m}"),
        (BenchPhaseSettings, "a aplicar definições"),
        (BenchPhaseSettle, "a estabilizar"),
        (BenchPhaseMeasure, "a medir"),
        (BenchFailed, "falhou"),
        (BenchDone, "Concluído"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadeia"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidas"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendação"),
        (BenchNoRecommendation, "Nenhum passo passou: cadeia acima de 30 ms ou imagens a menos. Experimente taxas de imagens ou de bits mais baixas."),
        (BenchHint, "Mede-se o que acontece no Mac neste momento. Os passos só são comparáveis se algo se mover: basta um vídeo em reprodução."),
        (BenchHintPattern, "Com o padrão de teste, cada passo vê o mesmo conteúdo em movimento: nada precisa de correr no Mac."),
        (TipBenchStart, "Mede uma a uma todas as combinações dos codecs, taxas de imagens e taxas de bits escolhidos, cada uma durante o tempo definido. A imagem continua e o menu pode ficar aberto."),
        (TipBenchApply, "Definir o codec e as definições recomendados e guardá-los para este host."),
        (TipBenchDuration, "Tempo de medição por passo. Mais longo é mais estável; 5 s costumam chegar."),
        (TipBenchHint, "Um passo passa se chegarem pelo menos 95 % da taxa de imagens alvo, se se perder menos de 1 % das imagens e se toda a cadeia se mantiver dentro de 30 ms, independentemente da taxa de imagens. O tempo do codificador do host é mostrado, mas não avaliado. Recomendado: a melhor qualidade de cor que passa à taxa de imagens mais alta, com a taxa de bits mais alta."),
        (TipBenchTestPattern, "Durante o teste, o host mostra um padrão fixo em movimento em vez do ecrã: cada passo mede o mesmo conteúdo."),
        (DesktopShortcut, "Criar atalho"),
        (TipDesktopShortcut, "Cria no ambiente de trabalho um atalho para este host. Um duplo clique liga de imediato."),
        (DesktopShortcutCreated, "Atalho criado no ambiente de trabalho: {n}"),
        (DesktopShortcutFailed, "Atalho não criado: {n}"),
        (DesktopShortcutDescription, "QuadChroma: ligar a {n} ({m})"),
        (FilesSending, "A enviar ficheiros: {n} de {m}"),
        (FilesReceiving, "A receber ficheiros: {n} de {m}"),
        (FilesReady, "Ficheiros prontos a colar: {n}"),
        (FilesSent, "Ficheiros transferidos: {n}"),
        (FilesAborted, "Transferência de ficheiros interrompida: {n}"),
        (FilesTooLarge, "Ficheiros não transferidos: mais de 4 GB ou 10 000 elementos"),
        (FilesPeerOld, "O outro lado ainda não pode receber ficheiros."),
        (TrayOpen, "Abrir"),
        (TrayConnect, "Ligar: {n}"),
        (TrayQuit, "Sair"),
        (TrayStillRunning, "O QuadChroma continua em execução na área de notificação."),
        (TrayStillRunningMac, "O QuadChroma continua em execução na barra de menus."),
        (FilesAbortLocal, "por este dispositivo"),
        (FilesAbortPeer, "pelo outro lado"),
        (FilesAbortConnection, "ligação interrompida"),
        (FilesAbortTimeout, "tempo esgotado sem progresso"),
        (FilesAbortNoSpace, "espaço em disco insuficiente"),
        (FilesAbortInvalid, "dados inválidos"),
        (FilesAbortRead, "erro de leitura"),
        (FilesAbortWrite, "erro de escrita"),
        (FilesAbortClipboard, "área de transferência indisponível"),
        (ScreenLabel, "Ecrã do host"),
        (ScreenAuto, "Automático"),
        (TipScreen, "Que ecrã do host vês. Automático segue o ecrã principal; um ecrã fixo vale até escolheres outra coisa."),
        (ScreenSwitching, "A mudar de ecrã …"),
        (ScreenFallback, "{n} não ligado – alternativa: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Palavra-passe de {n}"),
        (AccessText, "{n} ainda não conhece este dispositivo. Introduza a palavra-passe indicada no menu do QuadChroma em {n}."),
        (AccessOrAllow, "Ou peça a alguém junto de {n} que clique em \"Permitir\"."),
        (AccessCode, "Código: {c}"),
        (AccessPassword, "Palavra-passe"),
        (AccessShow, "Mostrar"),
        (AccessCancel, "Cancelar"),
        (AccessChecking, "A verificar …"),
        (AccessWrong, "Palavra-passe incorreta."),
        (AccessWait, "Demasiadas tentativas. Tente novamente dentro de {s} s."),
        (AccessNewIdentity, "O dispositivo neste endereço tem uma nova identidade (ID {i})."),
        (MsgRefused, "{n} recusou a ligação."),
        (MsgNoAnswer, "Sem resposta de {n}. Tente novamente."),
        (MsgTooManyAttempts, "Demasiadas tentativas. Aguarde um momento e tente novamente."),
        (MsgHostOutdated, "{n} usa uma versão anterior do QuadChroma. Atualize-a em {n}."),
        (MsgHostProofBad, "{n} não conseguiu confirmar a palavra-passe. Por segurança, a ligação foi terminada."),
        (MsgOtherDevice, "Neste endereço responde outro dispositivo."),
        (MsgIdNotFound, "Nenhum dispositivo com o ID {i} encontrado na rede."),
        (StartId, "ID {i}"),
        (StartShare, "Partilhar este PC"),
        (StartSharing, "Partilha ativa"),
        (HostReady, "Pronto para ligações"),
        (HostConnected, "Ligado: {n}"),
        (HostDeviceId, "ID do dispositivo: {i}"),
        (HostPassword, "Palavra-passe: {p}"),
        (HostCopied, "Copiado"),
        (HostChangePassword, "Alterar palavra-passe …"),
        (HostRandomPassword, "Nova palavra-passe aleatória"),
        (HostNewPassword, "Nova palavra-passe (pelo menos 8 caracteres)"),
        (HostRepeatPassword, "Repetir palavra-passe"),
        (HostPasswordsDiffer, "As palavras-passe não coincidem."),
        (HostPasswordShort, "Utilize pelo menos 8 caracteres."),
        (HostPasswordSaved, "Palavra-passe guardada."),
        (HostPasswordUnreadable, "Ficheiro da palavra-passe ilegível – novos dispositivos só através de \"Permitir\"."),
        (HostDevices, "Dispositivos permitidos"),
        (HostNoDevices, "Ainda sem dispositivos"),
        (HostDeviceLine, "{n} – ID {i} – desde {d}"),
        (HostRemove, "Remover"),
        (HostRemoveAll, "Remover todos os dispositivos …"),
        (HostRemoveAllAsk, "Remover todos os dispositivos permitidos? Voltarão a precisar da palavra-passe."),
        (HostListDamaged, "Lista de dispositivos danificada"),
        (HostListReset, "Repor lista de dispositivos"),
        (HostRequest, "{n} (ID {i}) pretende controlar este computador."),
        (HostAllow, "Permitir"),
        (HostDeny, "Recusar"),
        (HostStartLogin, "Abrir ao iniciar sessão"),
        (HostStartWindows, "Iniciar com o Windows"),
        (HostMoveToApps, "Mova primeiro o QuadChroma para Aplicações"),
        (HostScreenMissing, "Gravação do ecrã não permitida – abrir Definições do Sistema …"),
        (HostAccessMissing, "Acessibilidade não permitida – abrir Definições do Sistema …"),
        (HostPortBusy, "A porta {p} está a ser usada por outro programa"),
        (HostQuit, "Sair do QuadChroma"),
        (HostStopSharing, "Parar a partilha"),
        (HostTooltip, "QuadChroma – este PC está partilhado (ID {i})"),
        (HostOk, "OK"),
        (AccessHide, "Ocultar"),
        (MsgShareFailed, "Não foi possível iniciar a partilha deste PC."),
        (MsgDeviceRemoved, "{n} já não conhece este dispositivo. Ligue-se novamente e introduza a palavra-passe."),
        (HostPasswordNotSaved, "Não foi possível guardar a palavra-passe."),
        (HostPasswordInvalid, "A palavra-passe contém caracteres não permitidos."),
        (HostPasswordTitle, "Alterar palavra-passe"),
        (MsgHostUnverified, "{n} não comprovou a sua identidade. Por segurança, a ligação foi terminada."),
        (MsgHostQuit, "O QuadChroma foi fechado em {n}."),
        (MsgHostSharingOff, "{n} deixou de partilhar."),
        (MsgHostRemovedYou, "{n} removeu este dispositivo."),
        (MsgSelf, "Trata-se deste computador."),
        (TrayOpenApp, "Abrir QuadChroma"),
        (HostSharingIsOff, "Partilha desativada"),
        (DeviceNameChange, "Alterar nome do dispositivo …"),
        (DeviceNameTitle, "Nome do dispositivo"),
        (DeviceNameLabel, "Os outros dispositivos veem este computador com este nome:"),
        (DeviceNameHint, "Deixe vazio para usar o nome do computador ({n})."),
        (DeviceNameTooLong, "O nome é demasiado longo (no máximo 40 bytes)."),
        (DeviceNameInvalid, "O nome contém caracteres não permitidos."),
        (ThisComputer, "Este computador: {n} · {i}"),
        (DeviceNameRename, "Mudar o nome"),
        (PreventSleep, "Impedir a suspensão enquanto o QuadChroma estiver em execução"),
        (TipDecoderAutoMac, "VideoToolbox no motor multimédia do Mac (também HEVC 4:4:4); senão o processador."),
        (TipDisplayAutoMac, "Metal no chip gráfico do Mac. Sem Metal: o processador. Aplica-se a partir do próximo arranque."),
        (TipDisplayCpuMac, "Desenhar no processador, sem Metal. Funciona em todo o lado, custa tempo de CPU. Aplica-se a partir do próximo arranque."),
        (StartShareMac, "Partilhar este Mac"),
        (TabComputers, "Computadores"),
        (ComputersHint, "Clique num computador para mudar para ele. Esta sessão termina."),
        (AccessDeviceKeyChanged, "O QuadChroma usa agora uma única chave por computador nos dois sentidos. Se {n} já conhecia este computador, volta a pedir acesso uma vez."),
        (ShareFailedKey, "Não foi possível iniciar a partilha: não é possível usar o host.key nem a respetiva pasta."),
        (ShareFailedSwitch, "Não foi possível iniciar a partilha: {s} não pode ser usado. Desative e volte a ativar a partilha para tentar de novo."),
        (PreventSleepRefused, "Inativo: recusado pelo sistema ({c})"),
        (CloseWindow, "Fechar janela"),
        (InputBlocked, "Uma janela no PC com Windows precisa da própria confirmação do Windows – o controlo não é possível aí por um momento."),
        (AutostartInstalled, "Instalado em {n} – o QuadChroma inicia a partir daí com o Windows."),
        (AutostartFailed, "Não foi possível alterar \"Iniciar com o Windows\". Os detalhes estão em protokoll.txt."),
        (AutostartNeedsAdmin, "Só com uma conta de administrador"),
        (TipHdr, "HDR10 assim que ambos os lados conseguem: o ecrã do host e este ecrã mostram HDR. Desligado: sempre SDR. Guardado para este host."),
        (HdrActive, "ativo nos dois lados"),
        (HdrMapped, "este ecrã mostra-o em SDR"),
        (HdrOff, "desligado – sempre SDR"),
        (HdrWhyClientSdr, "este ecrã é SDR"),
        (HdrWhyCodec, "só com HEVC 10 bits"),
        (HdrWhyHostScreen, "o ecrã do host é SDR"),
        (HdrWhyHostCannot, "o host não consegue enviar HDR"),
        (HdrWhyClientCannot, "esta visualização não consegue mostrar HDR"),
        (HdrWhySwitchFailed, "a mudança para HDR falhou"),
        (HdrWhyNegotiating, "a negociar …"),
        (HdrWhyOldHost, "o host não suporta HDR (versão anterior)"),
        (StatColor, "Cor"),
        (ShortcutMouseCapture, "Capturar ou libertar o rato (jogos)"),
        (MouseCapturedHint, "Rato capturado · F8 liberta-o"),
    ],
};

pub static NL: Lang = Lang {
    code: "nl",
    name: "Nederlands",
    table: &[
        (AppSubtitle, "Extern bureaublad zonder kleurverlies"),
        (Connect, "Verbinden"),
        (Disconnect, "Verbinding verbreken"),
        (HostAddress, "Adres van de host"),
        (SearchingHosts, "Zoeken naar hosts"),
        (NoHostsFound, "Geen hosts gevonden"),
        (FoundHosts, "Gevonden hosts"),
        (Settings, "Instellingen"),
        (Language, "Taal"),
        (Quit, "Afsluiten"),
        (Connecting, "Bezig met verbinden"),
        (Connected, "Verbonden"),
        (ConnectionLost, "Verbinding verbroken"),
        (Reconnecting, "Opnieuw verbinden"),
        (Fullscreen, "Volledig scherm"),
        (PixelExact, "Pixel voor pixel"),
        (Stretch, "Aan venster aanpassen"),
        (ShowOverlay, "Statistieken tonen"),
        (Fps, "Beelden per seconde"),
        (DecodeTime, "Decodeertijd"),
        (Bitrate, "Bitrate"),
        (Resolution, "Resolutie"),
        (Codec, "Codec"),
        (Latency, "Vertraging"),
        (EncodeTime, "Encodeertijd"),
        (NetworkTime, "Netwerk"),
        (AudioBuffer, "Audiobuffer"),
        (Dropped, "Verloren beelden"),
        (MaxBitrate, "Maximale bitrate"),
        (MaxFps, "Maximale framerate"),
        (ExpertMode, "Expertmodus"),
        (GamingMode, "Spelmodus"),
        (FixedRate, "Vaste framerate"),
        (FixedRateHint, "Houdt de framerate vast, ook als er niets beweegt. Constante belasting op de host."),
        (Sound, "Geluid"),
        (HoldEscHint, "Houd ESC vast voor het menu"),
        (NerdMode, "Nerdmodus"),
        (More, "Meer"),
        (Back, "Terug"),
        (SavedForHost, "Opgeslagen voor deze host"),
        (Queue, "Opname & wachten"),
        (OneFrame, "Eén beeld"),
        (Bottleneck, "Knelpunt"),
        (TabPicture, "Beeld"),
        (TabDisplay, "Weergave"),
        (CodecConverted, "omgezet"),
        (CodecSwitching, "Codec wordt gewisseld"),
        (HostCpu, "Host-CPU"),
        (HostGpu, "Host-GPU"),
        (HostRam, "Hostgeheugen"),
        (NoDisplay, "De host heeft momenteel geen beeldscherm"),
        (Encryption, "Versleuteling"),
        (EncryptionOn, "aan"),
        (EncryptionOff, "uit"),
        (AudioEnabled, "Geluid"),
        (ClipboardEnabled, "Klembord"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatisch"),
        (RoleCpu, "Processor"),
        (RoleGpu, "Videokaart"),
        (RoleGpuN, "Videokaart {n}"),
        (RoleIntegrated, "Geïntegreerd"),
        (NextStartHint, "geldt vanaf de volgende start"),
        (AdapterWithOutput, "met beeldschermuitgang"),
        (AdapterNoOutput, "zonder beeldschermuitgang"),
        (TipOnly420, "Alleen 4:2:0 en H.264 (D3D11VA); bij 4:4:4 valt de client terug op de processor – codec omzetten op het tabblad Beeld."),
        (DisplayLabel, "Weergave"),
        (DisplayStage, "Weergave"),
        (ClientCpu, "Client-CPU"),
        (Monitor, "Monitor"),
        (Skipped, "overgeslagen"),
        (SecuredWith, "Beveiligd · verificatiecode"),
        (HostFingerprint, "Vingerafdruk van de host"),
        (ErrorConnectRefused, "Host heeft de verbinding geweigerd"),
        (ErrorTimeout, "Host reageert niet"),
        (ErrorProtocol, "De andere kant spreekt een ander protocol"),
        (ErrorNoDecoder, "Geen decoder voor dit formaat"),
        (SessionTakenOver, "Een ander apparaat heeft de sessie overgenomen."),
        (KeyFileDamaged, "Het sleutelbestand {p} is beschadigd en is ongewijzigd gelaten. Controleer of verwijder het – dan wordt een nieuwe sleutel gemaakt en moet dit apparaat opnieuw worden toegestaan met het wachtwoord."),
        (FileUnreadable, "{p} kan niet worden gelezen – geen verbinding."),
        (FileNotUtf8, "{p} is niet als UTF-8 opgeslagen – geen verbinding."),
        (FileNotWritable, "{p} kan niet worden geschreven – geen verbinding."),
        (StorageUnavailable, "De map voor sleutels en instellingen is niet beschikbaar – geen verbinding."),
        (ErrorAddress, "Het adres {n} kan niet worden omgezet"),
        (ErrorNoConnection, "Geen verbinding met de host"),
        (ErrorHandshake, "De beveiligde verbinding kwam niet tot stand"),
        (ErrorFfmpegStart, "FFmpeg kon niet worden gestart"),
        (ErrorSound, "Geluid niet beschikbaar"),
        (ErrorGpuDisplay, "Videokaart niet bruikbaar, weergave via software"),
        (ErrorGpuLost, "Videokaart verloren – start opnieuw met --anzeige cpu"),
        (ErrorPixelFormat, "De decoder levert beelden die deze client niet kan weergeven"),
        (DecoderFallback, "De gekozen videokaart decodeert niet – softwaredecoder actief"),
        (TipBitrate, "Bovengrens van de bitrate. Bij beweging gebruikt de encoder alles; op andermans netwerk liever 25 tot 50."),
        (TipFps, "Gewenste framerate. Meer dan het scherm van de Mac levert, kan niet."),
        (TipGaming, "Vaker keyframes en minder toegestane achterstand: rustiger bij beweging, kost wat bitrate."),
        (TipSound, "Geluid meesturen. Uit bespaart zo'n 3 Mbit/s; de host stuurt dan geen geluid."),
        (TipCodec, "Codec van de host, wisselt tijdens gebruik; het beeld staat even stil. \"omgezet\" kost één stap extra."),
        (TipFullscreen, "Randloos volledig scherm. In een venster wordt het beeld ingepast."),
        (TipPixelExact, "Beeld 1:1 zonder schalen. Is het venster kleiner, dan zie je een uitsnede."),
        (TipShowOverlay, "Statistieken linksboven tonen. Welke regels, staat rechts."),
        (TipNerdMode, "Uitgebreide statistieken: vertragingsketen als balk, belasting van host en client."),
        (TipStatRows, "Welke regels de statistieken tonen."),
        (TipDecoderAuto, "NVDEC op een NVIDIA-kaart; anders D3D11VA op de kaart die tekent (alleen 4:2:0 en H.264); anders de processor."),
        (TipDecoderCpu, "Decoderen op de processor. Werkt overal, kost rekentijd."),
        (TipDecoderGpu, "Decoderen op de videokaart. Lukt dat niet, dan valt de client terug op de processor en zegt waarom."),
        (TipDecoderIntegrated, "Decoderen op de geïntegreerde grafische kaart (D3D11VA). Lukt dat niet, dan valt de client terug op de processor en zegt waarom."),
        (TipDisplayAuto, "Direct3D 11 op de eerste kaart met beeldschermuitgang, anders de eerste NVIDIA-kaart, anders de eerste die er is. Zonder kaart: de processor. Geldt vanaf de volgende start."),
        (TipDisplayGpu, "Tekenen met Direct3D 11 op deze kaart. Geldt vanaf de volgende start."),
        (TipDisplayIntegrated, "Tekenen met Direct3D 11 op de geïntegreerde grafische kaart – waar het beeldscherm meestal aan hangt. Geldt vanaf de volgende start."),
        (TipDisplayCpu, "Tekenen op de processor, zonder Direct3D. Werkt overal, kost rekentijd. Geldt vanaf de volgende start."),
        (TipDisconnect, "Verbinding beëindigen, terug naar het startscherm."),
        (TabShortcuts, "Sneltoetsen"),
        (ShortcutMenu, "Menu openen (deze ESC komt nooit bij de Mac aan)"),
        (ShortcutBack, "Terug naar het startscherm"),
        (ShortcutWinKey, "Windows-toets = Command-toets van de Mac"),
        (ShortcutOthers, "Alle andere toetsen gaan naar de Mac. Verzonden wordt de positie van de toets, niet het teken – accenten en AltGr kloppen vanzelf."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Starten"),
        (BenchAbort, "Annuleren"),
        (BenchApply, "Toepassen"),
        (BenchDuration, "Duur per stap"),
        (BenchTestPattern, "Testbeeld"),
        (BenchStep, "Stap {n} van {m}"),
        (BenchPhaseSettings, "instellingen worden gezet"),
        (BenchPhaseSettle, "stabiliseren"),
        (BenchPhaseMeasure, "meten"),
        (BenchFailed, "mislukt"),
        (BenchDone, "Klaar"),
        (BenchAborted, "Geannuleerd"),
        (BenchMeasured, "gemeten"),
        (BenchChain, "Keten"),
        (BenchColFps, "fps"),
        (BenchColDropped, "verloren"),
        (BenchColHostCpu, "Host-CPU"),
        (BenchRecommendation, "Aanbeveling"),
        (BenchNoRecommendation, "Geen enkele stap is geslaagd: keten boven 30 ms of te weinig beelden. Probeer lagere framerates of bitrates."),
        (BenchHint, "Gemeten wordt wat er nu op de Mac gebeurt. Stappen zijn alleen vergelijkbaar als er iets beweegt – een lopende video is genoeg."),
        (BenchHintPattern, "Met testbeeld ziet elke stap dezelfde bewegende inhoud – op de Mac hoeft niets te draaien."),
        (TipBenchStart, "Meet alle combinaties van de gekozen codecs, framerates en bitrates na elkaar, elk voor de ingestelde duur. Het beeld loopt door en het menu mag open blijven."),
        (TipBenchApply, "Aanbevolen codec en instellingen zetten en opslaan voor deze host."),
        (TipBenchDuration, "Meettijd per stap. Langer is rustiger; 5 s is meestal genoeg."),
        (TipBenchHint, "Een stap slaagt als minstens 95 % van de doelframerate aankomt, minder dan 1 % van de beelden verloren gaat en de hele keten binnen 30 ms blijft – ongeacht de framerate. De encodertijd van de host wordt getoond maar niet beoordeeld. Aanbevolen: de beste kleurkwaliteit die slaagt bij de hoogste framerate, met de hoogste bitrate."),
        (TipBenchTestPattern, "Voor de duur van de run toont de host een vast bewegend patroon in plaats van het scherm – elke stap meet dezelfde inhoud."),
        (DesktopShortcut, "Snelkoppeling"),
        (TipDesktopShortcut, "Maakt op het bureaublad een snelkoppeling naar deze host. Dubbelklikken maakt meteen verbinding."),
        (DesktopShortcutCreated, "Snelkoppeling op het bureaublad gemaakt: {n}"),
        (DesktopShortcutFailed, "Snelkoppeling niet gemaakt: {n}"),
        (DesktopShortcutDescription, "QuadChroma: verbinden met {n} ({m})"),
        (FilesSending, "Bestanden worden verzonden: {n} van {m}"),
        (FilesReceiving, "Bestanden worden ontvangen: {n} van {m}"),
        (FilesReady, "Bestanden klaar om te plakken: {n}"),
        (FilesSent, "Bestanden overgedragen: {n}"),
        (FilesAborted, "Bestandsoverdracht afgebroken: {n}"),
        (FilesTooLarge, "Bestanden niet overgedragen: meer dan 4 GB of 10.000 items"),
        (FilesPeerOld, "De andere kant kan nog geen bestanden ontvangen."),
        (TrayOpen, "Openen"),
        (TrayConnect, "Verbinden: {n}"),
        (TrayQuit, "Afsluiten"),
        (TrayStillRunning, "QuadChroma blijft actief in het systeemvak."),
        (TrayStillRunningMac, "QuadChroma blijft actief in de menubalk."),
        (FilesAbortLocal, "door dit apparaat"),
        (FilesAbortPeer, "door de andere kant"),
        (FilesAbortConnection, "verbinding onderbroken"),
        (FilesAbortTimeout, "time-out zonder voortgang"),
        (FilesAbortNoSpace, "onvoldoende schijfruimte"),
        (FilesAbortInvalid, "ongeldige gegevens"),
        (FilesAbortRead, "leesfout"),
        (FilesAbortWrite, "schrijffout"),
        (FilesAbortClipboard, "klembord niet beschikbaar"),
        (ScreenLabel, "Scherm van de host"),
        (ScreenAuto, "Automatisch"),
        (TipScreen, "Welk scherm van de host je ziet. Automatisch volgt het hoofdscherm; een vast scherm geldt tot je iets anders kiest."),
        (ScreenSwitching, "Scherm wordt gewisseld …"),
        (ScreenFallback, "{n} niet aangesloten – uitwijk: {m}"),
        // Zugang (Spezifikation Pairing v1, Abschnitt 14)
        (AccessTitle, "Wachtwoord voor {n}"),
        (AccessText, "{n} kent dit apparaat nog niet. Voer het wachtwoord in dat in het QuadChroma-menu op {n} staat."),
        (AccessOrAllow, "Of vraag iemand bij {n} om op \"Toestaan\" te klikken."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Wachtwoord"),
        (AccessShow, "Tonen"),
        (AccessCancel, "Annuleren"),
        (AccessChecking, "Controleren …"),
        (AccessWrong, "Onjuist wachtwoord."),
        (AccessWait, "Te veel pogingen. Probeer het over {s} s opnieuw."),
        (AccessNewIdentity, "Het apparaat op dit adres heeft een nieuwe identiteit (ID {i})."),
        (MsgRefused, "{n} heeft de verbinding geweigerd."),
        (MsgNoAnswer, "Geen antwoord van {n}. Probeer het opnieuw."),
        (MsgTooManyAttempts, "Te veel pogingen. Wacht even en probeer het opnieuw."),
        (MsgHostOutdated, "{n} gebruikt een oudere versie van QuadChroma. Werk die bij op {n}."),
        (MsgHostProofBad, "{n} kon het wachtwoord niet bevestigen. Voor de veiligheid is de verbinding verbroken."),
        (MsgOtherDevice, "Op dit adres antwoordt een ander apparaat."),
        (MsgIdNotFound, "Geen apparaat met ID {i} gevonden in het netwerk."),
        (StartId, "ID {i}"),
        (StartShare, "Deze pc delen"),
        (StartSharing, "Delen is actief"),
        (HostReady, "Klaar voor verbindingen"),
        (HostConnected, "Verbonden: {n}"),
        (HostDeviceId, "Apparaat-ID: {i}"),
        (HostPassword, "Wachtwoord: {p}"),
        (HostCopied, "Gekopieerd"),
        (HostChangePassword, "Wachtwoord wijzigen …"),
        (HostRandomPassword, "Nieuw willekeurig wachtwoord"),
        (HostNewPassword, "Nieuw wachtwoord (minstens 8 tekens)"),
        (HostRepeatPassword, "Wachtwoord herhalen"),
        (HostPasswordsDiffer, "De wachtwoorden komen niet overeen."),
        (HostPasswordShort, "Gebruik minstens 8 tekens."),
        (HostPasswordSaved, "Wachtwoord opgeslagen."),
        (HostPasswordUnreadable, "Wachtwoordbestand onleesbaar – nieuwe apparaten alleen via \"Toestaan\"."),
        (HostDevices, "Toegestane apparaten"),
        (HostNoDevices, "Nog geen apparaten"),
        (HostDeviceLine, "{n} – ID {i} – sinds {d}"),
        (HostRemove, "Verwijderen"),
        (HostRemoveAll, "Alle apparaten verwijderen …"),
        (HostRemoveAllAsk, "Alle toegestane apparaten verwijderen? Ze hebben dan opnieuw het wachtwoord nodig."),
        (HostListDamaged, "Apparatenlijst beschadigd"),
        (HostListReset, "Apparatenlijst opnieuw instellen"),
        (HostRequest, "{n} (ID {i}) wil deze computer bedienen."),
        (HostAllow, "Toestaan"),
        (HostDeny, "Weigeren"),
        (HostStartLogin, "Starten bij inloggen"),
        (HostStartWindows, "Starten met Windows"),
        (HostMoveToApps, "Verplaats QuadChroma eerst naar Programma's"),
        (HostScreenMissing, "Schermopname niet toegestaan – Systeeminstellingen openen …"),
        (HostAccessMissing, "Toegankelijkheid niet toegestaan – Systeeminstellingen openen …"),
        (HostPortBusy, "Poort {p} wordt door een ander programma gebruikt"),
        (HostQuit, "QuadChroma afsluiten"),
        (HostStopSharing, "Delen stoppen"),
        (HostTooltip, "QuadChroma – deze pc wordt gedeeld (ID {i})"),
        (HostOk, "OK"),
        (AccessHide, "Verbergen"),
        (MsgShareFailed, "Het delen van deze pc kon niet worden gestart."),
        (MsgDeviceRemoved, "{n} kent dit apparaat niet meer. Maak opnieuw verbinding en voer het wachtwoord in."),
        (HostPasswordNotSaved, "Het wachtwoord kon niet worden opgeslagen."),
        (HostPasswordInvalid, "Het wachtwoord bevat tekens die niet zijn toegestaan."),
        (HostPasswordTitle, "Wachtwoord wijzigen"),
        (MsgHostUnverified, "{n} heeft zijn identiteit niet aangetoond. Voor de veiligheid is de verbinding verbroken."),
        (MsgHostQuit, "QuadChroma op {n} is afgesloten."),
        (MsgHostSharingOff, "{n} is gestopt met delen."),
        (MsgHostRemovedYou, "{n} heeft dit apparaat verwijderd."),
        (MsgSelf, "Dit is deze computer."),
        (TrayOpenApp, "QuadChroma openen"),
        (HostSharingIsOff, "Delen is uit"),
        (DeviceNameChange, "Apparaatnaam wijzigen …"),
        (DeviceNameTitle, "Apparaatnaam"),
        (DeviceNameLabel, "Onder deze naam zien andere apparaten deze computer:"),
        (DeviceNameHint, "Laat leeg voor de computernaam ({n})."),
        (DeviceNameTooLong, "De naam is te lang (maximaal 40 bytes)."),
        (DeviceNameInvalid, "De naam bevat tekens die niet zijn toegestaan."),
        (ThisComputer, "Deze computer: {n} · {i}"),
        (DeviceNameRename, "Hernoemen"),
        (PreventSleep, "Slaapstand voorkomen zolang QuadChroma draait"),
        (TipDecoderAutoMac, "VideoToolbox in de media-engine van de Mac (ook HEVC 4:4:4); anders de processor."),
        (TipDisplayAutoMac, "Metal op de grafische chip van de Mac. Zonder Metal: de processor. Geldt vanaf de volgende start."),
        (TipDisplayCpuMac, "Tekenen op de processor, zonder Metal. Werkt overal, kost rekentijd. Geldt vanaf de volgende start."),
        (StartShareMac, "Deze Mac delen"),
        (TabComputers, "Computers"),
        (ComputersHint, "Klik op een computer om ernaar over te schakelen. Deze sessie eindigt dan."),
        (AccessDeviceKeyChanged, "QuadChroma gebruikt nu één sleutel per computer voor beide richtingen. Als {n} deze computer al kende, vraagt het nog één keer om toegang."),
        (ShareFailedKey, "Delen kon niet starten: host.key of de map ervan is niet bruikbaar."),
        (ShareFailedSwitch, "Delen kon niet starten: {s} is niet bruikbaar. Zet delen uit en weer aan om het opnieuw te proberen."),
        (PreventSleepRefused, "Niet actief: geweigerd door het systeem ({c})"),
        (CloseWindow, "Venster sluiten"),
        (InputBlocked, "Een venster op de Windows-pc vereist Windows' eigen bevestiging – besturing is daar even niet mogelijk."),
        (AutostartInstalled, "Geïnstalleerd in {n} – QuadChroma start van daaruit met Windows."),
        (AutostartFailed, "\"Starten met Windows\" kon niet worden gewijzigd. Details staan in protokoll.txt."),
        (AutostartNeedsAdmin, "Alleen met een beheerdersaccount"),
        (TipHdr, "HDR10 zodra beide kanten het kunnen: het scherm van de host en dit scherm tonen HDR. Uit: altijd SDR. Opgeslagen voor deze host."),
        (HdrActive, "actief aan beide kanten"),
        (HdrMapped, "dit scherm toont het als SDR"),
        (HdrOff, "uit – altijd SDR"),
        (HdrWhyClientSdr, "dit scherm is SDR"),
        (HdrWhyCodec, "alleen met HEVC 10 bit"),
        (HdrWhyHostScreen, "het scherm van de host is SDR"),
        (HdrWhyHostCannot, "de host kan geen HDR sturen"),
        (HdrWhyClientCannot, "deze weergave kan geen HDR tonen"),
        (HdrWhySwitchFailed, "overschakelen naar HDR mislukt"),
        (HdrWhyNegotiating, "wordt afgestemd …"),
        (HdrWhyOldHost, "de host kent geen HDR (oudere versie)"),
        (StatColor, "Kleur"),
        (ShortcutMouseCapture, "Muis vangen of vrijgeven (games)"),
        (MouseCapturedHint, "Muis gevangen · F8 geeft hem vrij"),
    ],
};
