// Nordische Sprachen: Schwedisch, Daenisch, Norwegisch (Bokmal), Finnisch,
// Islaendisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static SV: Lang = Lang {
    code: "sv",
    name: "Svenska",
    table: &[
        (AppSubtitle, "Fjärrskrivbord med full färgupplösning"),
        (Connect, "Anslut"),
        (Disconnect, "Koppla från"),
        (HostAddress, "Värdadress"),
        (SearchingHosts, "Söker efter värdar"),
        (NoHostsFound, "Inga värdar hittades"),
        (FoundHosts, "Hittade värdar"),
        (Settings, "Inställningar"),
        (Language, "Språk"),
        (Quit, "Avsluta"),
        (Connecting, "Ansluter"),
        (Connected, "Ansluten"),
        (ConnectionLost, "Anslutningen bröts"),
        (Reconnecting, "Återansluter"),
        (Fullscreen, "Helskärm"),
        (PixelExact, "Pixelexakt"),
        (Stretch, "Anpassa till fönster"),
        (ShowOverlay, "Visa statistik"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Avkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplösning"),
        (Codec, "Codec"),
        (Latency, "Latens"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Överföring"),
        (AudioBuffer, "Ljudbuffert"),
        (Dropped, "Tappade bilder"),
        (MaxBitrate, "Högsta bitrate"),
        (MaxFps, "Högsta bildfrekvens"),
        (ExpertMode, "Expertläge"),
        (GamingMode, "Spelläge"),
        (FixedRate, "Fast bildfrekvens"),
        (FixedRateHint, "Håller bildfrekvensen även när inget rör sig. Konstant belastning på värden."),
        (Sound, "Ljud"),
        (HoldEscHint, "Håll kvar ESC för menyn"),
        (NerdMode, "Nördläge"),
        (More, "Mer"),
        (Back, "Tillbaka"),
        (SavedForHost, "Sparat för den här värden"),
        (Queue, "Infångning & kö"),
        (OneFrame, "En bild"),
        (Bottleneck, "Flaskhals"),
        (TabPicture, "Bild"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverterad"),
        (CodecSwitching, "Byter codec"),
        (HostCpu, "Värdens processor"),
        (HostGpu, "Värdens grafik"),
        (HostRam, "Värdens minne"),
        (NoDisplay, "Värden har ingen skärm just nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Ljud"),
        (ClipboardEnabled, "Urklipp"),
        (DecoderLabel, "Avkodare"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Mjukvara"),
        (DecoderNvidia, "Grafikkort"),
        (PairingTitle, "Parkoppla med värd"),
        (PairingHint, "Ange koden som visas på värden"),
        (PairingCode, "Parkopplingskod"),
        (PairingWrong, "Fel kod"),
        (PairingOk, "Parkopplad"),
        (SecuredWith, "Skyddad · verifieringskod"),
        (HostFingerprint, "Värdens fingeravtryck"),
        (NotPaired, "Den här värden känner inte till din enhet ännu. Starta värden med --pair och anslut igen."),
        (FirstContact, "Första kontakten med den här värden. Jämför koden med den på värden."),
        (ErrorConnectRefused, "Värden nekade anslutningen"),
        (ErrorTimeout, "Värden svarar inte"),
        (ErrorProtocol, "Motparten använder ett annat protokoll"),
        (ErrorNoDecoder, "Ingen avkodare för det här formatet"),
    ],
};

pub static DA: Lang = Lang {
    code: "da",
    name: "Dansk",
    table: &[
        (AppSubtitle, "Fjernskrivebord med fuld farveopløsning"),
        (Connect, "Forbind"),
        (Disconnect, "Afbryd"),
        (HostAddress, "Værtsadresse"),
        (SearchingHosts, "Søger efter værter"),
        (NoHostsFound, "Ingen værter fundet"),
        (FoundHosts, "Fundne værter"),
        (Settings, "Indstillinger"),
        (Language, "Sprog"),
        (Quit, "Afslut"),
        (Connecting, "Forbinder"),
        (Connected, "Forbundet"),
        (ConnectionLost, "Forbindelsen blev afbrudt"),
        (Reconnecting, "Forbinder igen"),
        (Fullscreen, "Fuld skærm"),
        (PixelExact, "Pixelnøjagtig"),
        (Stretch, "Tilpas til vindue"),
        (ShowOverlay, "Vis statistik"),
        (Fps, "Billeder pr. sekund"),
        (DecodeTime, "Afkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Opløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Overførsel"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tabte billeder"),
        (MaxBitrate, "Højeste bitrate"),
        (MaxFps, "Højeste billedfrekvens"),
        (ExpertMode, "Eksperttilstand"),
        (GamingMode, "Spiltilstand"),
        (FixedRate, "Fast billedfrekvens"),
        (FixedRateHint, "Holder billedfrekvensen, også når intet bevæger sig. Konstant belastning på værten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menuen"),
        (NerdMode, "Nørdtilstand"),
        (More, "Mere"),
        (Back, "Tilbage"),
        (SavedForHost, "Gemt for denne vært"),
        (Queue, "Optagelse & kø"),
        (OneFrame, "Ét billede"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Billede"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverteret"),
        (CodecSwitching, "Skifter codec"),
        (HostCpu, "Værtens processor"),
        (HostGpu, "Værtens grafik"),
        (HostRam, "Værtens hukommelse"),
        (NoDisplay, "Værten har ingen skærm lige nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "til"),
        (EncryptionOff, "fra"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Udklipsholder"),
        (DecoderLabel, "Afkoder"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Software"),
        (DecoderNvidia, "Grafikkort"),
        (PairingTitle, "Par med vært"),
        (PairingHint, "Indtast koden, der vises på værten"),
        (PairingCode, "Parringskode"),
        (PairingWrong, "Forkert kode"),
        (PairingOk, "Parret"),
        (SecuredWith, "Sikret · bekræftelseskode"),
        (HostFingerprint, "Værtens fingeraftryk"),
        (NotPaired, "Denne vært kender ikke din enhed endnu. Start værten med --pair, og forbind igen."),
        (FirstContact, "Første kontakt med denne vært. Sammenlign koden med den på værten."),
        (ErrorConnectRefused, "Værten afviste forbindelsen"),
        (ErrorTimeout, "Værten svarer ikke"),
        (ErrorProtocol, "Modparten bruger en anden protokol"),
        (ErrorNoDecoder, "Ingen afkoder til dette format"),
    ],
};

pub static NB: Lang = Lang {
    code: "nb",
    name: "Norsk bokmål",
    table: &[
        (AppSubtitle, "Fjernskrivebord med full fargeoppløsning"),
        (Connect, "Koble til"),
        (Disconnect, "Koble fra"),
        (HostAddress, "Vertsadresse"),
        (SearchingHosts, "Søker etter verter"),
        (NoHostsFound, "Fant ingen verter"),
        (FoundHosts, "Funne verter"),
        (Settings, "Innstillinger"),
        (Language, "Språk"),
        (Quit, "Avslutt"),
        (Connecting, "Kobler til"),
        (Connected, "Tilkoblet"),
        (ConnectionLost, "Mistet forbindelsen"),
        (Reconnecting, "Kobler til på nytt"),
        (Fullscreen, "Fullskjerm"),
        (PixelExact, "Pikselnøyaktig"),
        (Stretch, "Tilpass til vindu"),
        (ShowOverlay, "Vis statistikk"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Dekodingstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Oppløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodingstid"),
        (NetworkTime, "Overføring"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tapte bilder"),
        (MaxBitrate, "Høyeste bitrate"),
        (MaxFps, "Høyeste bildefrekvens"),
        (ExpertMode, "Ekspertmodus"),
        (GamingMode, "Spillmodus"),
        (FixedRate, "Fast bildefrekvens"),
        (FixedRateHint, "Holder bildefrekvensen, også når ingenting beveger seg. Konstant belastning på verten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menyen"),
        (NerdMode, "Nerdemodus"),
        (More, "Mer"),
        (Back, "Tilbake"),
        (SavedForHost, "Lagret for denne verten"),
        (Queue, "Opptak & kø"),
        (OneFrame, "Ett bilde"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Bilde"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konvertert"),
        (CodecSwitching, "Bytter codec"),
        (HostCpu, "Vertens prosessor"),
        (HostGpu, "Vertens grafikk"),
        (HostRam, "Vertens minne"),
        (NoDisplay, "Verten har ingen skjerm akkurat nå"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Utklippstavle"),
        (DecoderLabel, "Dekoder"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Programvare"),
        (DecoderNvidia, "Grafikkort"),
        (PairingTitle, "Parkoble med vert"),
        (PairingHint, "Skriv inn koden som vises på verten"),
        (PairingCode, "Parkoblingskode"),
        (PairingWrong, "Feil kode"),
        (PairingOk, "Parkoblet"),
        (SecuredWith, "Sikret · bekreftelseskode"),
        (HostFingerprint, "Vertens fingeravtrykk"),
        (NotPaired, "Denne verten kjenner ikke enheten din ennå. Start verten med --pair og koble til på nytt."),
        (FirstContact, "Første kontakt med denne verten. Sammenlign koden med den på verten."),
        (ErrorConnectRefused, "Verten avviste tilkoblingen"),
        (ErrorTimeout, "Verten svarer ikke"),
        (ErrorProtocol, "Motparten bruker en annen protokoll"),
        (ErrorNoDecoder, "Ingen dekoder for dette formatet"),
    ],
};

pub static FI: Lang = Lang {
    code: "fi",
    name: "Suomi",
    table: &[
        (AppSubtitle, "Etätyöpöytä täydellä väritarkkuudella"),
        (Connect, "Yhdistä"),
        (Disconnect, "Katkaise yhteys"),
        (HostAddress, "Isäntäkoneen osoite"),
        (SearchingHosts, "Etsitään isäntäkoneita"),
        (NoHostsFound, "Isäntäkoneita ei löytynyt"),
        (FoundHosts, "Löydetyt isäntäkoneet"),
        (Settings, "Asetukset"),
        (Language, "Kieli"),
        (Quit, "Lopeta"),
        (Connecting, "Yhdistetään"),
        (Connected, "Yhdistetty"),
        (ConnectionLost, "Yhteys katkesi"),
        (Reconnecting, "Yhdistetään uudelleen"),
        (Fullscreen, "Koko näyttö"),
        (PixelExact, "Pikselintarkka"),
        (Stretch, "Sovita ikkunaan"),
        (ShowOverlay, "Näytä tilastot"),
        (Fps, "Kuvaa sekunnissa"),
        (DecodeTime, "Dekoodausaika"),
        (Bitrate, "Bitrate"),
        (Resolution, "Tarkkuus"),
        (Codec, "Codec"),
        (Latency, "Viive"),
        (EncodeTime, "Koodausaika"),
        (NetworkTime, "Siirtoaika"),
        (AudioBuffer, "Äänipuskuri"),
        (Dropped, "Pudonneet kuvat"),
        (MaxBitrate, "Suurin bitrate"),
        (MaxFps, "Suurin kuvataajuus"),
        (ExpertMode, "Asiantuntijatila"),
        (GamingMode, "Pelitila"),
        (FixedRate, "Kiinteä kuvataajuus"),
        (FixedRateHint, "Pitää kuvataajuuden ennallaan, vaikka mikään ei liiku. Jatkuva kuormitus isäntäkoneelle."),
        (Sound, "Ääni"),
        (HoldEscHint, "Pidä ESC pohjassa valikkoa varten"),
        (NerdMode, "Nörttitila"),
        (More, "Lisää"),
        (Back, "Takaisin"),
        (SavedForHost, "Tallennettu tälle isäntäkoneelle"),
        (Queue, "Kaappaus & jono"),
        (OneFrame, "Yksi kuva"),
        (Bottleneck, "Pullonkaula"),
        (TabPicture, "Kuva"),
        (TabDisplay, "Näyttö"),
        (CodecConverted, "muunnettu"),
        (CodecSwitching, "Codec vaihtuu"),
        (HostCpu, "Isäntäkoneen suoritin"),
        (HostGpu, "Isäntäkoneen näytönohjain"),
        (HostRam, "Isäntäkoneen muisti"),
        (NoDisplay, "Isäntäkoneella ei ole näyttöä juuri nyt"),
        (Encryption, "Salaus"),
        (EncryptionOn, "päällä"),
        (EncryptionOff, "pois"),
        (AudioEnabled, "Ääni"),
        (ClipboardEnabled, "Leikepöytä"),
        (DecoderLabel, "Purkaja"),
        (DecoderAuto, "Automaattinen"),
        (DecoderSoftware, "Ohjelmisto"),
        (DecoderNvidia, "Näytönohjain"),
        (PairingTitle, "Muodosta laitepari"),
        (PairingHint, "Syötä isäntäkoneella näkyvä koodi"),
        (PairingCode, "Parikoodi"),
        (PairingWrong, "Väärä koodi"),
        (PairingOk, "Pari muodostettu"),
        (SecuredWith, "Suojattu · vahvistuskoodi"),
        (HostFingerprint, "Isäntäkoneen sormenjälki"),
        (NotPaired, "Tämä isäntäkone ei vielä tunne laitettasi. Käynnistä isäntäkone valitsimella --pair ja yhdistä uudelleen."),
        (FirstContact, "Ensimmäinen yhteys tähän isäntäkoneeseen. Vertaa koodia isäntäkoneella näkyvään koodiin."),
        (ErrorConnectRefused, "Isäntäkone hylkäsi yhteyden"),
        (ErrorTimeout, "Isäntäkone ei vastaa"),
        (ErrorProtocol, "Vastapuoli käyttää eri protokollaa"),
        (ErrorNoDecoder, "Ei purkajaa tälle muodolle"),
    ],
};

pub static IS: Lang = Lang {
    code: "is",
    name: "Íslenska",
    table: &[
        (AppSubtitle, "Fjartengt skjáborð með fullri litupplausn"),
        (Connect, "Tengjast"),
        (Disconnect, "Aftengja"),
        (HostAddress, "Vistfang hýsils"),
        (SearchingHosts, "Leita að hýslum"),
        (NoHostsFound, "Enginn hýsill fannst"),
        (FoundHosts, "Hýslar sem fundust"),
        (Settings, "Stillingar"),
        (Language, "Tungumál"),
        (Quit, "Hætta"),
        (Connecting, "Tengist"),
        (Connected, "Tengt"),
        (ConnectionLost, "Tenging rofnaði"),
        (Reconnecting, "Tengist aftur"),
        (Fullscreen, "Allur skjárinn"),
        (PixelExact, "Dílanákvæmt"),
        (Stretch, "Laga að glugga"),
        (ShowOverlay, "Sýna tölfræði"),
        (Fps, "Rammar á sekúndu"),
        (DecodeTime, "Afkóðunartími"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplausn"),
        (Codec, "Codec"),
        (Latency, "Biðtími"),
        (EncodeTime, "Kóðunartími"),
        (NetworkTime, "Flutningstími"),
        (AudioBuffer, "Hljóðbiðminni"),
        (Dropped, "Týndir rammar"),
        (MaxBitrate, "Hámarks bitrate"),
        (MaxFps, "Hámarks rammatíðni"),
        (ExpertMode, "Sérfræðihamur"),
        (GamingMode, "Leikjahamur"),
        (FixedRate, "Föst rammatíðni"),
        (FixedRateHint, "Heldur rammatíðninni þótt ekkert hreyfist. Stöðugt álag á hýsilinn."),
        (Sound, "Hljóð"),
        (HoldEscHint, "Haltu ESC inni fyrir valmyndina"),
        (NerdMode, "Nördahamur"),
        (More, "Meira"),
        (Back, "Til baka"),
        (SavedForHost, "Vistað fyrir þennan hýsil"),
        (Queue, "Upptaka & bið"),
        (OneFrame, "Einn rammi"),
        (Bottleneck, "Flöskuháls"),
        (TabPicture, "Mynd"),
        (TabDisplay, "Birting"),
        (CodecConverted, "umbreytt"),
        (CodecSwitching, "Skiptir um codec"),
        (HostCpu, "Örgjörvi hýsils"),
        (HostGpu, "Skjákort hýsils"),
        (HostRam, "Minni hýsils"),
        (NoDisplay, "Hýsillinn hefur engan skjá í augnablikinu"),
        (Encryption, "Dulkóðun"),
        (EncryptionOn, "kveikt"),
        (EncryptionOff, "slökkt"),
        (AudioEnabled, "Hljóð"),
        (ClipboardEnabled, "Klippiborð"),
        (DecoderLabel, "Afkóðari"),
        (DecoderAuto, "Sjálfvirkt"),
        (DecoderSoftware, "Hugbúnaður"),
        (DecoderNvidia, "Skjákort"),
        (PairingTitle, "Para við hýsil"),
        (PairingHint, "Sláðu inn kóðann sem birtist á hýslinum"),
        (PairingCode, "Pörunarkóði"),
        (PairingWrong, "Rangur kóði"),
        (PairingOk, "Parað"),
        (SecuredWith, "Öruggt · staðfestingarkóði"),
        (HostFingerprint, "Fingrafar hýsilsins"),
        (NotPaired, "Þessi hýsill þekkir ekki tækið þitt enn. Ræstu hýsilinn með --pair og tengdu aftur."),
        (FirstContact, "Fyrsta tenging við þennan hýsil. Berðu kóðann saman við þann sem birtist á hýslinum."),
        (ErrorConnectRefused, "Hýsillinn hafnaði tengingunni"),
        (ErrorTimeout, "Hýsillinn svarar ekki"),
        (ErrorProtocol, "Hinn endinn notar annan samskiptastaðal"),
        (ErrorNoDecoder, "Enginn afkóðari fyrir þetta snið"),
    ],
};
