// Nordische Sprachen: Schwedisch, Daenisch, Norwegisch (Bokmal), Finnisch,
// Islaendisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static SV: Lang = Lang {
    code: "sv",
    name: "Svenska",
    table: &[
        (AppSubtitle, "Fjärrskrivbord med full färgupplösning"),
        (Connect, "Anslut"),
        (Disconnect, "Koppla från"),
        (HostAddress, "Värdadress"),
        (SearchingHosts, "Söker efter värdar"),
        (NoHostsFound, "Inga värdar hittades"),
        (FoundHosts, "Hittade värdar"),
        (Settings, "Inställningar"),
        (Language, "Språk"),
        (Quit, "Avsluta"),
        (Connecting, "Ansluter"),
        (Connected, "Ansluten"),
        (ConnectionLost, "Anslutningen bröts"),
        (Reconnecting, "Återansluter"),
        (Fullscreen, "Helskärm"),
        (PixelExact, "Pixelexakt"),
        (Stretch, "Anpassa till fönster"),
        (ShowOverlay, "Visa statistik"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Avkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplösning"),
        (Codec, "Codec"),
        (Latency, "Latens"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Överföring"),
        (AudioBuffer, "Ljudbuffert"),
        (Dropped, "Tappade bilder"),
        (MaxBitrate, "Högsta bitrate"),
        (MaxFps, "Högsta bildfrekvens"),
        (ExpertMode, "Expertläge"),
        (GamingMode, "Spelläge"),
        (FixedRate, "Fast bildfrekvens"),
        (FixedRateHint, "Håller bildfrekvensen även när inget rör sig. Konstant belastning på värden."),
        (Sound, "Ljud"),
        (HoldEscHint, "Håll kvar ESC för menyn"),
        (NerdMode, "Nördläge"),
        (More, "Mer"),
        (Back, "Tillbaka"),
        (SavedForHost, "Sparat för den här värden"),
        (Queue, "Infångning & kö"),
        (OneFrame, "En bild"),
        (Bottleneck, "Flaskhals"),
        (TabPicture, "Bild"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverterad"),
        (CodecSwitching, "Byter codec"),
        (HostCpu, "Värdens processor"),
        (HostGpu, "Värdens grafik"),
        (HostRam, "Värdens minne"),
        (NoDisplay, "Värden har ingen skärm just nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Ljud"),
        (ClipboardEnabled, "Urklipp"),
        (DecoderLabel, "Avkodare"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Mjukvara"),
        (DecoderNvidia, "Grafikkort"),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens processor"),
        (Monitor, "Bildskärm"),
        (Skipped, "överhoppade"),
        (PairingTitle, "Parkoppla med värd"),
        (PairingHint, "Ange koden som visas på värden"),
        (PairingCode, "Parkopplingskod"),
        (PairingWrong, "Fel kod"),
        (PairingOk, "Parkopplad"),
        (SecuredWith, "Skyddad · verifieringskod"),
        (HostFingerprint, "Värdens fingeravtryck"),
        (NotPaired, "Den här värden känner inte till din enhet ännu. Starta värden med --pair och anslut igen."),
        (FirstContact, "Första kontakten med den här värden. Jämför koden med den på värden."),
        (ErrorConnectRefused, "Värden nekade anslutningen"),
        (ErrorTimeout, "Värden svarar inte"),
        (ErrorProtocol, "Motparten använder ett annat protokoll"),
        (ErrorNoDecoder, "Ingen avkodare för det här formatet"),
        (TipBitrate, "Övre gräns för bitrate. Vid rörelse använder kodaren allt; i andras nätverk hellre 25 till 50."),
        (TipFps, "Önskad bildfrekvens. Mer än Macens skärm levererar går inte."),
        (TipGaming, "Tätare nyckelbilder och mindre tillåten eftersläpning: jämnare vid rörelse, kostar lite bitrate."),
        (TipSound, "Skicka ljud. Av sparar cirka 3 Mbit/s; värden skickar då inget ljud."),
        (TipCodec, "Värdens codec, byts under drift; bilden står stilla ett ögonblick. \"konverterad\" kostar ett steg till."),
        (TipFullscreen, "Kantlös helskärm. I fönster passas bilden in."),
        (TipPixelExact, "Bilden 1:1 utan skalning. Är fönstret mindre visas ett utsnitt."),
        (TipShowOverlay, "Visa statistiken uppe till vänster. Vilka rader, se till höger."),
        (TipNerdMode, "Utökad statistik: latenskedjan som stapel, belastning på värd och klient."),
        (TipStatRows, "Vilka rader statistiken visar."),
        (TipDecoderAuto, "Grafikkort om det klarar codecen, annars mjukvara."),
        (TipDecoderSoftware, "Avkoda på processorn. Fungerar överallt, kostar processortid."),
        (TipDecoderGpu, "Avkoda på grafikkortet. Klarar det inte det faller klienten tillbaka på mjukvara och säger varför."),
        (TipDisconnect, "Avsluta anslutningen, tillbaka till startskärmen."),
        (TabShortcuts, "Kortkommandon"),
        (ShortcutMenu, "Öppna menyn (detta ESC når aldrig Macen)"),
        (ShortcutBack, "Tillbaka till startskärmen"),
        (ShortcutWinKey, "Windows-tangenten = Macens kommandotangent"),
        (ShortcutOthers, "Alla andra tangenter går till Macen. Det som skickas är tangentens position, inte tecknet – å, ä, ö och AltGr fungerar av sig själva."),
    ],
};

pub static DA: Lang = Lang {
    code: "da",
    name: "Dansk",
    table: &[
        (AppSubtitle, "Fjernskrivebord med fuld farveopløsning"),
        (Connect, "Forbind"),
        (Disconnect, "Afbryd"),
        (HostAddress, "Værtsadresse"),
        (SearchingHosts, "Søger efter værter"),
        (NoHostsFound, "Ingen værter fundet"),
        (FoundHosts, "Fundne værter"),
        (Settings, "Indstillinger"),
        (Language, "Sprog"),
        (Quit, "Afslut"),
        (Connecting, "Forbinder"),
        (Connected, "Forbundet"),
        (ConnectionLost, "Forbindelsen blev afbrudt"),
        (Reconnecting, "Forbinder igen"),
        (Fullscreen, "Fuld skærm"),
        (PixelExact, "Pixelnøjagtig"),
        (Stretch, "Tilpas til vindue"),
        (ShowOverlay, "Vis statistik"),
        (Fps, "Billeder pr. sekund"),
        (DecodeTime, "Afkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Opløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Overførsel"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tabte billeder"),
        (MaxBitrate, "Højeste bitrate"),
        (MaxFps, "Højeste billedfrekvens"),
        (ExpertMode, "Eksperttilstand"),
        (GamingMode, "Spiltilstand"),
        (FixedRate, "Fast billedfrekvens"),
        (FixedRateHint, "Holder billedfrekvensen, også når intet bevæger sig. Konstant belastning på værten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menuen"),
        (NerdMode, "Nørdtilstand"),
        (More, "Mere"),
        (Back, "Tilbage"),
        (SavedForHost, "Gemt for denne vært"),
        (Queue, "Optagelse & kø"),
        (OneFrame, "Ét billede"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Billede"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverteret"),
        (CodecSwitching, "Skifter codec"),
        (HostCpu, "Værtens processor"),
        (HostGpu, "Værtens grafik"),
        (HostRam, "Værtens hukommelse"),
        (NoDisplay, "Værten har ingen skærm lige nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "til"),
        (EncryptionOff, "fra"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Udklipsholder"),
        (DecoderLabel, "Afkoder"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Software"),
        (DecoderNvidia, "Grafikkort"),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens processor"),
        (Monitor, "Skærm"),
        (Skipped, "sprunget over"),
        (PairingTitle, "Par med vært"),
        (PairingHint, "Indtast koden, der vises på værten"),
        (PairingCode, "Parringskode"),
        (PairingWrong, "Forkert kode"),
        (PairingOk, "Parret"),
        (SecuredWith, "Sikret · bekræftelseskode"),
        (HostFingerprint, "Værtens fingeraftryk"),
        (NotPaired, "Denne vært kender ikke din enhed endnu. Start værten med --pair, og forbind igen."),
        (FirstContact, "Første kontakt med denne vært. Sammenlign koden med den på værten."),
        (ErrorConnectRefused, "Værten afviste forbindelsen"),
        (ErrorTimeout, "Værten svarer ikke"),
        (ErrorProtocol, "Modparten bruger en anden protokol"),
        (ErrorNoDecoder, "Ingen afkoder til dette format"),
        (TipBitrate, "Øvre grænse for bitrate. Ved bevægelse bruger encoderen det hele; på fremmede netværk hellere 25 til 50."),
        (TipFps, "Ønsket billedfrekvens. Mere end Mac'ens skærm leverer, kan ikke lade sig gøre."),
        (TipGaming, "Hyppigere nøglebilleder og mindre tilladt efterslæb: mere jævnt ved bevægelse, koster lidt bitrate."),
        (TipSound, "Send lyd. Fra sparer cirka 3 Mbit/s; værten sender så ingen lyd."),
        (TipCodec, "Værtens codec, skiftes under drift; billedet står stille et øjeblik. \"konverteret\" koster et trin mere."),
        (TipFullscreen, "Kantløs fuld skærm. I vindue tilpasses billedet."),
        (TipPixelExact, "Billedet 1:1 uden skalering. Er vinduet mindre, vises et udsnit."),
        (TipShowOverlay, "Vis statistikken øverst til venstre. Hvilke rækker, se til højre."),
        (TipNerdMode, "Udvidet statistik: forsinkelseskæden som søjle, belastning på vært og klient."),
        (TipStatRows, "Hvilke rækker statistikken viser."),
        (TipDecoderAuto, "Grafikkort, hvis det kan klare codec'en, ellers software."),
        (TipDecoderSoftware, "Afkod på processoren. Virker overalt, koster regnetid."),
        (TipDecoderGpu, "Afkod på grafikkortet. Kan det ikke, falder klienten tilbage på software og siger hvorfor."),
        (TipDisconnect, "Afslut forbindelsen, tilbage til startskærmen."),
        (TabShortcuts, "Genveje"),
        (ShortcutMenu, "Åbn menuen (denne ESC når aldrig Mac'en)"),
        (ShortcutBack, "Tilbage til startskærmen"),
        (ShortcutWinKey, "Windows-tasten = Mac'ens kommandotast"),
        (ShortcutOthers, "Alle andre taster går til Mac'en. Det er tastens position, der sendes, ikke tegnet – æ, ø, å og AltGr virker af sig selv."),
    ],
};

pub static NB: Lang = Lang {
    code: "nb",
    name: "Norsk bokmål",
    table: &[
        (AppSubtitle, "Fjernskrivebord med full fargeoppløsning"),
        (Connect, "Koble til"),
        (Disconnect, "Koble fra"),
        (HostAddress, "Vertsadresse"),
        (SearchingHosts, "Søker etter verter"),
        (NoHostsFound, "Fant ingen verter"),
        (FoundHosts, "Funne verter"),
        (Settings, "Innstillinger"),
        (Language, "Språk"),
        (Quit, "Avslutt"),
        (Connecting, "Kobler til"),
        (Connected, "Tilkoblet"),
        (ConnectionLost, "Mistet forbindelsen"),
        (Reconnecting, "Kobler til på nytt"),
        (Fullscreen, "Fullskjerm"),
        (PixelExact, "Pikselnøyaktig"),
        (Stretch, "Tilpass til vindu"),
        (ShowOverlay, "Vis statistikk"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Dekodingstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Oppløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodingstid"),
        (NetworkTime, "Overføring"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tapte bilder"),
        (MaxBitrate, "Høyeste bitrate"),
        (MaxFps, "Høyeste bildefrekvens"),
        (ExpertMode, "Ekspertmodus"),
        (GamingMode, "Spillmodus"),
        (FixedRate, "Fast bildefrekvens"),
        (FixedRateHint, "Holder bildefrekvensen, også når ingenting beveger seg. Konstant belastning på verten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menyen"),
        (NerdMode, "Nerdemodus"),
        (More, "Mer"),
        (Back, "Tilbake"),
        (SavedForHost, "Lagret for denne verten"),
        (Queue, "Opptak & kø"),
        (OneFrame, "Ett bilde"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Bilde"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konvertert"),
        (CodecSwitching, "Bytter codec"),
        (HostCpu, "Vertens prosessor"),
        (HostGpu, "Vertens grafikk"),
        (HostRam, "Vertens minne"),
        (NoDisplay, "Verten har ingen skjerm akkurat nå"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Utklippstavle"),
        (DecoderLabel, "Dekoder"),
        (DecoderAuto, "Automatisk"),
        (DecoderSoftware, "Programvare"),
        (DecoderNvidia, "Grafikkort"),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens prosessor"),
        (Monitor, "Skjerm"),
        (Skipped, "hoppet over"),
        (PairingTitle, "Parkoble med vert"),
        (PairingHint, "Skriv inn koden som vises på verten"),
        (PairingCode, "Parkoblingskode"),
        (PairingWrong, "Feil kode"),
        (PairingOk, "Parkoblet"),
        (SecuredWith, "Sikret · bekreftelseskode"),
        (HostFingerprint, "Vertens fingeravtrykk"),
        (NotPaired, "Denne verten kjenner ikke enheten din ennå. Start verten med --pair og koble til på nytt."),
        (FirstContact, "Første kontakt med denne verten. Sammenlign koden med den på verten."),
        (ErrorConnectRefused, "Verten avviste tilkoblingen"),
        (ErrorTimeout, "Verten svarer ikke"),
        (ErrorProtocol, "Motparten bruker en annen protokoll"),
        (ErrorNoDecoder, "Ingen dekoder for dette formatet"),
        (TipBitrate, "Øvre grense for bitrate. Ved bevegelse bruker enkoderen alt; på fremmede nettverk heller 25 til 50."),
        (TipFps, "Ønsket bildefrekvens. Mer enn Mac-ens skjerm leverer, går ikke."),
        (TipGaming, "Hyppigere nøkkelbilder og mindre tillatt etterslep: jevnere ved bevegelse, koster litt bitrate."),
        (TipSound, "Send lyd. Av sparer omtrent 3 Mbit/s; verten sender da ingen lyd."),
        (TipCodec, "Vertens codec, byttes under drift; bildet står stille et øyeblikk. \"konvertert\" koster ett trinn til."),
        (TipFullscreen, "Kantløs fullskjerm. I vindu tilpasses bildet."),
        (TipPixelExact, "Bildet 1:1 uten skalering. Er vinduet mindre, vises et utsnitt."),
        (TipShowOverlay, "Vis statistikken øverst til venstre. Hvilke rader, se til høyre."),
        (TipNerdMode, "Utvidet statistikk: forsinkelseskjeden som stolpe, belastning på vert og klient."),
        (TipStatRows, "Hvilke rader statistikken viser."),
        (TipDecoderAuto, "Grafikkort hvis det håndterer codecen, ellers programvare."),
        (TipDecoderSoftware, "Dekod på prosessoren. Virker overalt, koster regnetid."),
        (TipDecoderGpu, "Dekod på grafikkortet. Klarer det ikke, faller klienten tilbake på programvare og sier hvorfor."),
        (TipDisconnect, "Avslutt forbindelsen, tilbake til startskjermen."),
        (TabShortcuts, "Snarveier"),
        (ShortcutMenu, "Åpne menyen (denne ESC når aldri Mac-en)"),
        (ShortcutBack, "Tilbake til startskjermen"),
        (ShortcutWinKey, "Windows-tasten = Mac-ens kommandotast"),
        (ShortcutOthers, "Alle andre taster går til Mac-en. Det er tastens posisjon som sendes, ikke tegnet – æ, ø, å og AltGr virker av seg selv."),
    ],
};

pub static FI: Lang = Lang {
    code: "fi",
    name: "Suomi",
    table: &[
        (AppSubtitle, "Etätyöpöytä täydellä väritarkkuudella"),
        (Connect, "Yhdistä"),
        (Disconnect, "Katkaise yhteys"),
        (HostAddress, "Isäntäkoneen osoite"),
        (SearchingHosts, "Etsitään isäntäkoneita"),
        (NoHostsFound, "Isäntäkoneita ei löytynyt"),
        (FoundHosts, "Löydetyt isäntäkoneet"),
        (Settings, "Asetukset"),
        (Language, "Kieli"),
        (Quit, "Lopeta"),
        (Connecting, "Yhdistetään"),
        (Connected, "Yhdistetty"),
        (ConnectionLost, "Yhteys katkesi"),
        (Reconnecting, "Yhdistetään uudelleen"),
        (Fullscreen, "Koko näyttö"),
        (PixelExact, "Pikselintarkka"),
        (Stretch, "Sovita ikkunaan"),
        (ShowOverlay, "Näytä tilastot"),
        (Fps, "Kuvaa sekunnissa"),
        (DecodeTime, "Dekoodausaika"),
        (Bitrate, "Bitrate"),
        (Resolution, "Tarkkuus"),
        (Codec, "Codec"),
        (Latency, "Viive"),
        (EncodeTime, "Koodausaika"),
        (NetworkTime, "Siirtoaika"),
        (AudioBuffer, "Äänipuskuri"),
        (Dropped, "Pudonneet kuvat"),
        (MaxBitrate, "Suurin bitrate"),
        (MaxFps, "Suurin kuvataajuus"),
        (ExpertMode, "Asiantuntijatila"),
        (GamingMode, "Pelitila"),
        (FixedRate, "Kiinteä kuvataajuus"),
        (FixedRateHint, "Pitää kuvataajuuden ennallaan, vaikka mikään ei liiku. Jatkuva kuormitus isäntäkoneelle."),
        (Sound, "Ääni"),
        (HoldEscHint, "Pidä ESC pohjassa valikkoa varten"),
        (NerdMode, "Nörttitila"),
        (More, "Lisää"),
        (Back, "Takaisin"),
        (SavedForHost, "Tallennettu tälle isäntäkoneelle"),
        (Queue, "Kaappaus & jono"),
        (OneFrame, "Yksi kuva"),
        (Bottleneck, "Pullonkaula"),
        (TabPicture, "Kuva"),
        (TabDisplay, "Näyttö"),
        (CodecConverted, "muunnettu"),
        (CodecSwitching, "Codec vaihtuu"),
        (HostCpu, "Isäntäkoneen suoritin"),
        (HostGpu, "Isäntäkoneen näytönohjain"),
        (HostRam, "Isäntäkoneen muisti"),
        (NoDisplay, "Isäntäkoneella ei ole näyttöä juuri nyt"),
        (Encryption, "Salaus"),
        (EncryptionOn, "päällä"),
        (EncryptionOff, "pois"),
        (AudioEnabled, "Ääni"),
        (ClipboardEnabled, "Leikepöytä"),
        (DecoderLabel, "Purkaja"),
        (DecoderAuto, "Automaattinen"),
        (DecoderSoftware, "Ohjelmisto"),
        (DecoderNvidia, "Näytönohjain"),
        (DisplayLabel, "Näyttö"),
        (DisplayStage, "Näyttö"),
        (ClientCpu, "Asiakaskoneen suoritin"),
        (Monitor, "Monitori"),
        (Skipped, "ohitettu"),
        (PairingTitle, "Muodosta laitepari"),
        (PairingHint, "Syötä isäntäkoneella näkyvä koodi"),
        (PairingCode, "Parikoodi"),
        (PairingWrong, "Väärä koodi"),
        (PairingOk, "Pari muodostettu"),
        (SecuredWith, "Suojattu · vahvistuskoodi"),
        (HostFingerprint, "Isäntäkoneen sormenjälki"),
        (NotPaired, "Tämä isäntäkone ei vielä tunne laitettasi. Käynnistä isäntäkone valitsimella --pair ja yhdistä uudelleen."),
        (FirstContact, "Ensimmäinen yhteys tähän isäntäkoneeseen. Vertaa koodia isäntäkoneella näkyvään koodiin."),
        (ErrorConnectRefused, "Isäntäkone hylkäsi yhteyden"),
        (ErrorTimeout, "Isäntäkone ei vastaa"),
        (ErrorProtocol, "Vastapuoli käyttää eri protokollaa"),
        (ErrorNoDecoder, "Ei purkajaa tälle muodolle"),
        (TipBitrate, "Bitraten yläraja. Liikkeessä enkooderi käyttää sen kokonaan; vieraissa verkoissa mieluummin 25–50."),
        (TipFps, "Tavoitekuvataajuus. Enempää kuin Macin näyttö tuottaa ei voi saada."),
        (TipGaming, "Tiheämmin avainkuvia ja vähemmän sallittua jonoa: tasaisempi liikkeessä, maksaa hieman bitratea."),
        (TipSound, "Lähetä ääni. Pois päältä säästää noin 3 Mbit/s; isäntäkone ei silloin lähetä ääntä lainkaan."),
        (TipCodec, "Isäntäkoneen codec, vaihtuu lennossa; kuva pysähtyy hetkeksi. \"muunnettu\" maksaa yhden ylimääräisen vaiheen."),
        (TipFullscreen, "Reunaton koko näyttö. Ikkunassa kuva sovitetaan."),
        (TipPixelExact, "Kuva 1:1 ilman skaalausta. Jos ikkuna on pienempi, näkyy vain osa."),
        (TipShowOverlay, "Näytä tilastot vasemmassa yläkulmassa. Mitkä rivit, valitaan oikealta."),
        (TipNerdMode, "Laajennetut tilastot: viiveketju palkkina, isäntäkoneen ja asiakaskoneen kuormitus."),
        (TipStatRows, "Mitkä rivit tilastoissa näytetään."),
        (TipDecoderAuto, "Näytönohjain, jos se osaa codecin, muuten ohjelmisto."),
        (TipDecoderSoftware, "Purku suorittimella. Toimii kaikkialla, vie laskenta-aikaa."),
        (TipDecoderGpu, "Purku näytönohjaimella. Jos se ei onnistu, asiakas palaa ohjelmistoon ja kertoo syyn."),
        (TipDisconnect, "Katkaise yhteys, takaisin aloitusnäyttöön."),
        (TabShortcuts, "Pikanäppäimet"),
        (ShortcutMenu, "Avaa valikko (tämä ESC ei koskaan mene Macille)"),
        (ShortcutBack, "Takaisin aloitusnäyttöön"),
        (ShortcutWinKey, "Windows-näppäin = Macin komentonäppäin"),
        (ShortcutOthers, "Kaikki muut näppäimet menevät Macille. Välitetään näppäimen sijainti, ei merkkiä – ä, ö ja AltGr toimivat itsestään."),
    ],
};

pub static IS: Lang = Lang {
    code: "is",
    name: "Íslenska",
    table: &[
        (AppSubtitle, "Fjartengt skjáborð með fullri litupplausn"),
        (Connect, "Tengjast"),
        (Disconnect, "Aftengja"),
        (HostAddress, "Vistfang hýsils"),
        (SearchingHosts, "Leita að hýslum"),
        (NoHostsFound, "Enginn hýsill fannst"),
        (FoundHosts, "Hýslar sem fundust"),
        (Settings, "Stillingar"),
        (Language, "Tungumál"),
        (Quit, "Hætta"),
        (Connecting, "Tengist"),
        (Connected, "Tengt"),
        (ConnectionLost, "Tenging rofnaði"),
        (Reconnecting, "Tengist aftur"),
        (Fullscreen, "Allur skjárinn"),
        (PixelExact, "Dílanákvæmt"),
        (Stretch, "Laga að glugga"),
        (ShowOverlay, "Sýna tölfræði"),
        (Fps, "Rammar á sekúndu"),
        (DecodeTime, "Afkóðunartími"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplausn"),
        (Codec, "Codec"),
        (Latency, "Biðtími"),
        (EncodeTime, "Kóðunartími"),
        (NetworkTime, "Flutningstími"),
        (AudioBuffer, "Hljóðbiðminni"),
        (Dropped, "Týndir rammar"),
        (MaxBitrate, "Hámarks bitrate"),
        (MaxFps, "Hámarks rammatíðni"),
        (ExpertMode, "Sérfræðihamur"),
        (GamingMode, "Leikjahamur"),
        (FixedRate, "Föst rammatíðni"),
        (FixedRateHint, "Heldur rammatíðninni þótt ekkert hreyfist. Stöðugt álag á hýsilinn."),
        (Sound, "Hljóð"),
        (HoldEscHint, "Haltu ESC inni fyrir valmyndina"),
        (NerdMode, "Nördahamur"),
        (More, "Meira"),
        (Back, "Til baka"),
        (SavedForHost, "Vistað fyrir þennan hýsil"),
        (Queue, "Upptaka & bið"),
        (OneFrame, "Einn rammi"),
        (Bottleneck, "Flöskuháls"),
        (TabPicture, "Mynd"),
        (TabDisplay, "Birting"),
        (CodecConverted, "umbreytt"),
        (CodecSwitching, "Skiptir um codec"),
        (HostCpu, "Örgjörvi hýsils"),
        (HostGpu, "Skjákort hýsils"),
        (HostRam, "Minni hýsils"),
        (NoDisplay, "Hýsillinn hefur engan skjá í augnablikinu"),
        (Encryption, "Dulkóðun"),
        (EncryptionOn, "kveikt"),
        (EncryptionOff, "slökkt"),
        (AudioEnabled, "Hljóð"),
        (ClipboardEnabled, "Klippiborð"),
        (DecoderLabel, "Afkóðari"),
        (DecoderAuto, "Sjálfvirkt"),
        (DecoderSoftware, "Hugbúnaður"),
        (DecoderNvidia, "Skjákort"),
        (DisplayLabel, "Birting"),
        (DisplayStage, "Birting"),
        (ClientCpu, "Örgjörvi biðlara"),
        (Monitor, "Skjár"),
        (Skipped, "sleppt"),
        (PairingTitle, "Para við hýsil"),
        (PairingHint, "Sláðu inn kóðann sem birtist á hýslinum"),
        (PairingCode, "Pörunarkóði"),
        (PairingWrong, "Rangur kóði"),
        (PairingOk, "Parað"),
        (SecuredWith, "Öruggt · staðfestingarkóði"),
        (HostFingerprint, "Fingrafar hýsilsins"),
        (NotPaired, "Þessi hýsill þekkir ekki tækið þitt enn. Ræstu hýsilinn með --pair og tengdu aftur."),
        (FirstContact, "Fyrsta tenging við þennan hýsil. Berðu kóðann saman við þann sem birtist á hýslinum."),
        (ErrorConnectRefused, "Hýsillinn hafnaði tengingunni"),
        (ErrorTimeout, "Hýsillinn svarar ekki"),
        (ErrorProtocol, "Hinn endinn notar annan samskiptastaðal"),
        (ErrorNoDecoder, "Enginn afkóðari fyrir þetta snið"),
        (TipBitrate, "Efri mörk bitrate. Við hreyfingu nýtir kóðarinn þau öll; á ókunnum netum frekar 25 til 50."),
        (TipFps, "Æskileg rammatíðni. Meira en skjár Macsins skilar er ekki hægt."),
        (TipGaming, "Tíðari lykilrammar og minni leyfð uppsöfnun: jafnara við hreyfingu, kostar dálítið bitrate."),
        (TipSound, "Senda hljóð. Slökkt sparar um 3 Mbit/s; hýsillinn sendir þá ekkert hljóð."),
        (TipCodec, "Codec hýsilsins, skipt í gangi; myndin stöðvast augnablik. \"umbreytt\" kostar eina umferð til viðbótar."),
        (TipFullscreen, "Allur skjárinn án ramma. Í glugga er myndin löguð að."),
        (TipPixelExact, "Mynd 1:1 án skölunar. Sé glugginn minni sést aðeins hluti."),
        (TipShowOverlay, "Sýna tölfræðina efst til vinstri. Hvaða línur, sjá til hægri."),
        (TipNerdMode, "Ítarleg tölfræði: biðtímakeðjan sem súla, álag á hýsil og biðlara."),
        (TipStatRows, "Hvaða línur tölfræðin sýnir."),
        (TipDecoderAuto, "Skjákort ef það ræður við codecinn, annars hugbúnaður."),
        (TipDecoderSoftware, "Afkóða á örgjörvanum. Virkar alls staðar, kostar reiknitíma."),
        (TipDecoderGpu, "Afkóða á skjákortinu. Ráði það ekki við það fellur biðlarinn aftur á hugbúnað og segir hvers vegna."),
        (TipDisconnect, "Slíta tengingu, aftur á upphafsskjá."),
        (TabShortcuts, "Flýtilyklar"),
        (ShortcutMenu, "Opna valmyndina (þetta ESC berst aldrei til Macsins)"),
        (ShortcutBack, "Aftur á upphafsskjá"),
        (ShortcutWinKey, "Windows-lykill = skipanalykill Macsins"),
        (ShortcutOthers, "Allir aðrir lyklar fara til Macsins. Staða lykilsins er send, ekki táknið – broddstafir og AltGr virka af sjálfu sér."),
    ],
};
