// Sprachtabellen Ost- und Suedosteuropa:
// Polnisch, Tschechisch, Slowakisch, Ungarisch, Rumaenisch, Bulgarisch, Griechisch.

use crate::strings::{Key::*, Lang};

pub static PL: Lang = Lang {
    code: "pl",
    name: "Polski",
    table: &[
        (AppSubtitle, "Zdalny pulpit z pełnym odwzorowaniem kolorów"),
        (Connect, "Połącz"),
        (Disconnect, "Rozłącz"),
        (HostAddress, "Adres hosta"),
        (SearchingHosts, "Wyszukiwanie hostów"),
        (NoHostsFound, "Nie znaleziono hostów"),
        (FoundHosts, "Znalezione hosty"),
        (Settings, "Ustawienia"),
        (Language, "Język"),
        (Quit, "Zakończ"),
        (Connecting, "Łączenie"),
        (Connected, "Połączono"),
        (ConnectionLost, "Utracono połączenie"),
        (Reconnecting, "Ponowne łączenie"),
        (Fullscreen, "Pełny ekran"),
        (PixelExact, "Piksel w piksel"),
        (Stretch, "Dopasuj do okna"),
        (ShowOverlay, "Pokaż statystyki"),
        (Fps, "Klatki na sekundę"),
        (DecodeTime, "Czas dekodowania"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozdzielczość"),
        (Codec, "Kodek"),
        (Latency, "Opóźnienie"),
        (EncodeTime, "Czas kodowania"),
        (NetworkTime, "Czas transmisji"),
        (AudioBuffer, "Bufor dźwięku"),
        (Dropped, "Pominięte klatki"),
        (MaxBitrate, "Maksymalny bitrate"),
        (MaxFps, "Maksymalna liczba klatek"),
        (ExpertMode, "Tryb eksperta"),
        (GamingMode, "Tryb gry"),
        (FixedRate, "Stała liczba klatek"),
        (FixedRateHint, "Utrzymuje liczbę klatek, nawet gdy nic się nie porusza. Stałe obciążenie hosta."),
        (Sound, "Dźwięk"),
        (HoldEscHint, "Trzymaj ESC, aby otworzyć menu"),
        (NerdMode, "Tryb nerda"),
        (More, "Więcej"),
        (Back, "Wstecz"),
        (SavedForHost, "Zapisano dla tego hosta"),
        (Queue, "Przechwyt i kolejka"),
        (OneFrame, "Jedna klatka"),
        (Bottleneck, "Wąskie gardło"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Ekran"),
        (CodecConverted, "z konwersją"),
        (CodecSwitching, "Zmiana kodeka"),
        (HostCpu, "Procesor hosta"),
        (HostGpu, "Grafika hosta"),
        (HostRam, "Pamięć hosta"),
        (NoDisplay, "Host chwilowo nie ma ekranu"),
        (Encryption, "Szyfrowanie"),
        (EncryptionOn, "wł."),
        (EncryptionOff, "wył."),
        (AudioEnabled, "Dźwięk"),
        (ClipboardEnabled, "Schowek"),
        (DecoderLabel, "Dekoder"),
        (DecoderAuto, "Automatyczny"),
        (DecoderSoftware, "Programowy"),
        (DecoderNvidia, "Karta graficzna"),
        (DisplayLabel, "Ekran"),
        (DisplayStage, "Ekran"),
        (ClientCpu, "Procesor klienta"),
        (Monitor, "Monitor"),
        (Skipped, "opuszczone"),
        (PairingTitle, "Parowanie z hostem"),
        (PairingHint, "Wpisz kod wyświetlony na hoście"),
        (PairingCode, "Kod parowania"),
        (PairingWrong, "Błędny kod"),
        (PairingOk, "Sparowano"),
        (SecuredWith, "Zabezpieczone · kod weryfikacyjny"),
        (HostFingerprint, "Odcisk klucza hosta"),
        (NotPaired, "Ten host jeszcze nie zna twojego urządzenia. Uruchom hosta z opcją --pair i połącz się ponownie."),
        (FirstContact, "Pierwszy kontakt z tym hostem. Porównaj kod z tym na hoście."),
        (ErrorConnectRefused, "Host odrzucił połączenie"),
        (ErrorTimeout, "Host nie odpowiada"),
        (ErrorProtocol, "Druga strona używa innego protokołu"),
        (ErrorNoDecoder, "Brak dekodera dla tego formatu"),
        (TipBitrate, "Górna granica bitrate'u. Przy ruchu enkoder wykorzystuje ją w całości; w obcych sieciach lepiej 25 do 50."),
        (TipFps, "Docelowa liczba klatek. Nie da się więcej, niż daje ekran Maca."),
        (TipGaming, "Częstsze klatki kluczowe i mniejsze dopuszczalne zaległości: płynniej przy ruchu, kosztuje trochę bitrate'u."),
        (TipSound, "Przesyłanie dźwięku. Wyłączone oszczędza około 3 Mbit/s; host nie wysyła wtedy dźwięku."),
        (TipCodec, "Kodek hosta, zmiana w trakcie pracy; obraz na chwilę zamiera. \"z konwersją\" kosztuje jeden przebieg więcej."),
        (TipFullscreen, "Pełny ekran bez ramki. W oknie obraz jest dopasowywany."),
        (TipPixelExact, "Obraz 1:1 bez skalowania. Jeśli okno jest mniejsze, widać wycinek."),
        (TipShowOverlay, "Pokaż statystyki w lewym górnym rogu. Które wiersze – po prawej."),
        (TipNerdMode, "Rozszerzone statystyki: łańcuch opóźnień jako pasek, obciążenie hosta i klienta."),
        (TipStatRows, "Które wiersze pokazują statystyki."),
        (TipDecoderAuto, "Karta graficzna, jeśli obsługuje kodek, inaczej programowo."),
        (TipDecoderSoftware, "Dekodowanie na procesorze. Działa wszędzie, kosztuje czas obliczeń."),
        (TipDecoderGpu, "Dekodowanie na karcie graficznej. Jeśli nie da rady, klient wraca do dekodowania programowego i mówi dlaczego."),
        (TipDisconnect, "Zakończ połączenie, wróć do ekranu startowego."),
        (TabShortcuts, "Skróty"),
        (ShortcutMenu, "Otwórz menu (ten ESC nigdy nie dociera do Maca)"),
        (ShortcutBack, "Powrót do ekranu startowego"),
        (ShortcutWinKey, "Klawisz Windows = klawisz Command Maca"),
        (ShortcutOthers, "Wszystkie pozostałe klawisze idą do Maca. Przesyłana jest pozycja klawisza, nie znak – polskie znaki i AltGr działają same."),
    ],
};

pub static CS: Lang = Lang {
    code: "cs",
    name: "Čeština",
    table: &[
        (AppSubtitle, "Vzdálená plocha s plným barevným podáním"),
        (Connect, "Připojit"),
        (Disconnect, "Odpojit"),
        (HostAddress, "Adresa hostitele"),
        (SearchingHosts, "Hledání hostitelů"),
        (NoHostsFound, "Žádný hostitel nenalezen"),
        (FoundHosts, "Nalezení hostitelé"),
        (Settings, "Nastavení"),
        (Language, "Jazyk"),
        (Quit, "Ukončit"),
        (Connecting, "Připojování"),
        (Connected, "Připojeno"),
        (ConnectionLost, "Spojení přerušeno"),
        (Reconnecting, "Obnovování spojení"),
        (Fullscreen, "Celá obrazovka"),
        (PixelExact, "Přesně na pixel"),
        (Stretch, "Přizpůsobit oknu"),
        (ShowOverlay, "Zobrazit statistiky"),
        (Fps, "Snímky za sekundu"),
        (DecodeTime, "Doba dekódování"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozlišení"),
        (Codec, "Kodek"),
        (Latency, "Latence"),
        (EncodeTime, "Doba kódování"),
        (NetworkTime, "Doba přenosu"),
        (AudioBuffer, "Zvukový buffer"),
        (Dropped, "Zahozené snímky"),
        (MaxBitrate, "Maximální bitrate"),
        (MaxFps, "Maximální snímková frekvence"),
        (ExpertMode, "Expertní režim"),
        (GamingMode, "Herní režim"),
        (FixedRate, "Pevná snímková frekvence"),
        (FixedRateHint, "Udržuje snímkovou frekvenci, i když se nic nehýbe. Trvalá zátěž hostitele."),
        (Sound, "Zvuk"),
        (HoldEscHint, "Držte ESC pro nabídku"),
        (NerdMode, "Nerdovský režim"),
        (More, "Více"),
        (Back, "Zpět"),
        (SavedForHost, "Uloženo pro tohoto hostitele"),
        (Queue, "Snímání a fronta"),
        (OneFrame, "Jeden snímek"),
        (Bottleneck, "Úzké hrdlo"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Zobrazení"),
        (CodecConverted, "s převodem"),
        (CodecSwitching, "Přepínání kodeku"),
        (HostCpu, "Procesor hostitele"),
        (HostGpu, "Grafika hostitele"),
        (HostRam, "Paměť hostitele"),
        (NoDisplay, "Hostitel momentálně nemá obrazovku"),
        (Encryption, "Šifrování"),
        (EncryptionOn, "zap."),
        (EncryptionOff, "vyp."),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Schránka"),
        (DecoderLabel, "Dekodér"),
        (DecoderAuto, "Automatický"),
        (DecoderSoftware, "Softwarový"),
        (DecoderNvidia, "Grafická karta"),
        (DisplayLabel, "Zobrazení"),
        (DisplayStage, "Zobrazení"),
        (ClientCpu, "Procesor klienta"),
        (Monitor, "Monitor"),
        (Skipped, "vynecháno"),
        (PairingTitle, "Spárovat s hostitelem"),
        (PairingHint, "Zadejte kód zobrazený na hostiteli"),
        (PairingCode, "Párovací kód"),
        (PairingWrong, "Špatný kód"),
        (PairingOk, "Spárováno"),
        (SecuredWith, "Zabezpečeno · ověřovací kód"),
        (HostFingerprint, "Otisk klíče hostitele"),
        (NotPaired, "Tento hostitel zatím nezná vaše zařízení. Spusťte hostitele s volbou --pair a připojte se znovu."),
        (FirstContact, "První kontakt s tímto hostitelem. Porovnejte kód s tím na hostiteli."),
        (ErrorConnectRefused, "Hostitel odmítl spojení"),
        (ErrorTimeout, "Hostitel neodpovídá"),
        (ErrorProtocol, "Protistrana používá jiný protokol"),
        (ErrorNoDecoder, "Pro tento formát chybí dekodér"),
        (TipBitrate, "Horní hranice bitrate. Při pohybu ji enkodér využije celou; v cizích sítích raději 25 až 50."),
        (TipFps, "Cílová snímková frekvence. Víc, než dává obrazovka Macu, nejde."),
        (TipGaming, "Častější klíčové snímky a menší povolený skluz: plynulejší při pohybu, stojí trochu bitrate."),
        (TipSound, "Přenášet zvuk. Vypnuto ušetří asi 3 Mbit/s; hostitel pak zvuk vůbec neposílá."),
        (TipCodec, "Kodek hostitele, přepíná se za běhu; obraz se na chvíli zastaví. \"s převodem\" stojí jeden průchod navíc."),
        (TipFullscreen, "Celá obrazovka bez okrajů. V okně se obraz přizpůsobí."),
        (TipPixelExact, "Obraz 1:1 bez škálování. Je-li okno menší, vidíte výřez."),
        (TipShowOverlay, "Zobrazit statistiky vlevo nahoře. Které řádky, nastavíte vpravo."),
        (TipNerdMode, "Rozšířené statistiky: řetězec latence jako sloupec, zátěž hostitele a klienta."),
        (TipStatRows, "Které řádky statistiky zobrazují."),
        (TipDecoderAuto, "Grafická karta, pokud kodek zvládne, jinak softwarově."),
        (TipDecoderSoftware, "Dekódování na procesoru. Funguje všude, stojí výpočetní čas."),
        (TipDecoderGpu, "Dekódování na grafické kartě. Pokud to nezvládne, klient se vrátí k softwaru a řekne proč."),
        (TipDisconnect, "Ukončit spojení, zpět na úvodní obrazovku."),
        (TabShortcuts, "Zkratky"),
        (ShortcutMenu, "Otevřít nabídku (tento ESC se na Mac nikdy nedostane)"),
        (ShortcutBack, "Zpět na úvodní obrazovku"),
        (ShortcutWinKey, "Klávesa Windows = klávesa Command na Macu"),
        (ShortcutOthers, "Všechny ostatní klávesy jdou na Mac. Přenáší se poloha klávesy, ne znak – háčky, čárky a AltGr fungují samy."),
    ],
};

pub static SK: Lang = Lang {
    code: "sk",
    name: "Slovenčina",
    table: &[
        (AppSubtitle, "Vzdialená plocha s plným podaním farieb"),
        (Connect, "Pripojiť"),
        (Disconnect, "Odpojiť"),
        (HostAddress, "Adresa hostiteľa"),
        (SearchingHosts, "Hľadanie hostiteľov"),
        (NoHostsFound, "Nenašiel sa žiadny hostiteľ"),
        (FoundHosts, "Nájdení hostitelia"),
        (Settings, "Nastavenia"),
        (Language, "Jazyk"),
        (Quit, "Ukončiť"),
        (Connecting, "Pripájanie"),
        (Connected, "Pripojené"),
        (ConnectionLost, "Spojenie prerušené"),
        (Reconnecting, "Obnovovanie spojenia"),
        (Fullscreen, "Celá obrazovka"),
        (PixelExact, "Presne na pixel"),
        (Stretch, "Prispôsobiť oknu"),
        (ShowOverlay, "Zobraziť štatistiky"),
        (Fps, "Snímky za sekundu"),
        (DecodeTime, "Čas dekódovania"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozlíšenie"),
        (Codec, "Kodek"),
        (Latency, "Latencia"),
        (EncodeTime, "Čas kódovania"),
        (NetworkTime, "Čas prenosu"),
        (AudioBuffer, "Zvukový buffer"),
        (Dropped, "Zahodené snímky"),
        (MaxBitrate, "Maximálny bitrate"),
        (MaxFps, "Maximálna snímková frekvencia"),
        (ExpertMode, "Expertný režim"),
        (GamingMode, "Herný režim"),
        (FixedRate, "Pevná snímková frekvencia"),
        (FixedRateHint, "Udržiava snímkovú frekvenciu, aj keď sa nič nehýbe. Trvalá záťaž hostiteľa."),
        (Sound, "Zvuk"),
        (HoldEscHint, "Držte ESC pre ponuku"),
        (NerdMode, "Nerdovský režim"),
        (More, "Viac"),
        (Back, "Späť"),
        (SavedForHost, "Uložené pre tohto hostiteľa"),
        (Queue, "Snímanie a fronta"),
        (OneFrame, "Jeden snímok"),
        (Bottleneck, "Úzke hrdlo"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Zobrazenie"),
        (CodecConverted, "s prevodom"),
        (CodecSwitching, "Prepínanie kodeku"),
        (HostCpu, "Procesor hostiteľa"),
        (HostGpu, "Grafika hostiteľa"),
        (HostRam, "Pamäť hostiteľa"),
        (NoDisplay, "Hostiteľ momentálne nemá obrazovku"),
        (Encryption, "Šifrovanie"),
        (EncryptionOn, "zap."),
        (EncryptionOff, "vyp."),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Schránka"),
        (DecoderLabel, "Dekodér"),
        (DecoderAuto, "Automatický"),
        (DecoderSoftware, "Softvérový"),
        (DecoderNvidia, "Grafická karta"),
        (DisplayLabel, "Zobrazenie"),
        (DisplayStage, "Zobrazenie"),
        (ClientCpu, "Procesor klienta"),
        (Monitor, "Monitor"),
        (Skipped, "vynechané"),
        (PairingTitle, "Spárovať s hostiteľom"),
        (PairingHint, "Zadajte kód zobrazený na hostiteľovi"),
        (PairingCode, "Párovací kód"),
        (PairingWrong, "Nesprávny kód"),
        (PairingOk, "Spárované"),
        (SecuredWith, "Zabezpečené · overovací kód"),
        (HostFingerprint, "Odtlačok kľúča hostiteľa"),
        (NotPaired, "Tento hostiteľ zatiaľ nepozná vaše zariadenie. Spustite hostiteľa s voľbou --pair a pripojte sa znova."),
        (FirstContact, "Prvý kontakt s týmto hostiteľom. Porovnajte kód s tým na hostiteľovi."),
        (ErrorConnectRefused, "Hostiteľ odmietol spojenie"),
        (ErrorTimeout, "Hostiteľ neodpovedá"),
        (ErrorProtocol, "Druhá strana používa iný protokol"),
        (ErrorNoDecoder, "Pre tento formát chýba dekodér"),
        (TipBitrate, "Horná hranica bitrate. Pri pohybe ju enkodér využije celú; v cudzích sieťach radšej 25 až 50."),
        (TipFps, "Cieľová snímková frekvencia. Viac, než dáva obrazovka Macu, sa nedá."),
        (TipGaming, "Častejšie kľúčové snímky a menší povolený sklz: plynulejšie pri pohybe, stojí trochu bitrate."),
        (TipSound, "Prenášať zvuk. Vypnuté ušetrí asi 3 Mbit/s; hostiteľ potom zvuk vôbec neposiela."),
        (TipCodec, "Kodek hostiteľa, prepína sa za behu; obraz sa na chvíľu zastaví. \"s prevodom\" stojí jeden prechod navyše."),
        (TipFullscreen, "Celá obrazovka bez okrajov. V okne sa obraz prispôsobí."),
        (TipPixelExact, "Obraz 1:1 bez škálovania. Ak je okno menšie, vidíte výrez."),
        (TipShowOverlay, "Zobraziť štatistiky vľavo hore. Ktoré riadky, nastavíte vpravo."),
        (TipNerdMode, "Rozšírené štatistiky: reťazec latencie ako stĺpec, záťaž hostiteľa a klienta."),
        (TipStatRows, "Ktoré riadky štatistiky zobrazujú."),
        (TipDecoderAuto, "Grafická karta, ak kodek zvládne, inak softvérovo."),
        (TipDecoderSoftware, "Dekódovanie na procesore. Funguje všade, stojí výpočtový čas."),
        (TipDecoderGpu, "Dekódovanie na grafickej karte. Ak to nezvládne, klient sa vráti k softvéru a povie prečo."),
        (TipDisconnect, "Ukončiť spojenie, späť na úvodnú obrazovku."),
        (TabShortcuts, "Skratky"),
        (ShortcutMenu, "Otvoriť ponuku (tento ESC sa na Mac nikdy nedostane)"),
        (ShortcutBack, "Späť na úvodnú obrazovku"),
        (ShortcutWinKey, "Kláves Windows = kláves Command na Macu"),
        (ShortcutOthers, "Všetky ostatné klávesy idú na Mac. Prenáša sa poloha klávesu, nie znak – mäkčene, dĺžne a AltGr fungujú samy."),
    ],
};

pub static HU: Lang = Lang {
    code: "hu",
    name: "Magyar",
    table: &[
        (AppSubtitle, "Távoli asztal teljes színhűséggel"),
        (Connect, "Csatlakozás"),
        (Disconnect, "Kapcsolat bontása"),
        (HostAddress, "Gazdagép címe"),
        (SearchingHosts, "Gazdagépek keresése"),
        (NoHostsFound, "Nem található gazdagép"),
        (FoundHosts, "Megtalált gazdagépek"),
        (Settings, "Beállítások"),
        (Language, "Nyelv"),
        (Quit, "Kilépés"),
        (Connecting, "Kapcsolódás"),
        (Connected, "Csatlakozva"),
        (ConnectionLost, "A kapcsolat megszakadt"),
        (Reconnecting, "Újracsatlakozás"),
        (Fullscreen, "Teljes képernyő"),
        (PixelExact, "Pixelpontos"),
        (Stretch, "Ablakhoz igazítás"),
        (ShowOverlay, "Statisztika mutatása"),
        (Fps, "Képkocka/másodperc"),
        (DecodeTime, "Dekódolási idő"),
        (Bitrate, "Bitráta"),
        (Resolution, "Felbontás"),
        (Codec, "Kodek"),
        (Latency, "Késleltetés"),
        (EncodeTime, "Kódolási idő"),
        (NetworkTime, "Átviteli idő"),
        (AudioBuffer, "Hangpuffer"),
        (Dropped, "Eldobott képkockák"),
        (MaxBitrate, "Maximális bitráta"),
        (MaxFps, "Maximális képkockaszám"),
        (ExpertMode, "Szakértői mód"),
        (GamingMode, "Játékmód"),
        (FixedRate, "Állandó képkockaszám"),
        (FixedRateHint, "Tartja a képkockaszámot akkor is, ha semmi nem mozog. Folyamatos terhelés a gazdagépen."),
        (Sound, "Hang"),
        (HoldEscHint, "Tartsa nyomva az ESC-et a menühöz"),
        (NerdMode, "Nerd mód"),
        (More, "Több"),
        (Back, "Vissza"),
        (SavedForHost, "Mentve ehhez a gazdagéphez"),
        (Queue, "Rögzítés és sor"),
        (OneFrame, "Egy képkocka"),
        (Bottleneck, "Szűk keresztmetszet"),
        (TabPicture, "Kép"),
        (TabDisplay, "Megjelenítés"),
        (CodecConverted, "átalakítva"),
        (CodecSwitching, "Kodekváltás"),
        (HostCpu, "Gazdagép CPU-ja"),
        (HostGpu, "Gazdagép GPU-ja"),
        (HostRam, "Gazdagép memóriája"),
        (NoDisplay, "A gazdagépnek jelenleg nincs képernyője"),
        (Encryption, "Titkosítás"),
        (EncryptionOn, "be"),
        (EncryptionOff, "ki"),
        (AudioEnabled, "Hang"),
        (ClipboardEnabled, "Vágólap"),
        (DecoderLabel, "Dekóder"),
        (DecoderAuto, "Automatikus"),
        (DecoderSoftware, "Szoftveres"),
        (DecoderNvidia, "Videokártya"),
        (DisplayLabel, "Megjelenítés"),
        (DisplayStage, "Megjelenítés"),
        (ClientCpu, "Kliens CPU-ja"),
        (Monitor, "Monitor"),
        (Skipped, "kihagyva"),
        (PairingTitle, "Párosítás a gazdagéppel"),
        (PairingHint, "Írja be a gazdagépen látható kódot"),
        (PairingCode, "Párosítási kód"),
        (PairingWrong, "Hibás kód"),
        (PairingOk, "Párosítva"),
        (SecuredWith, "Védett · ellenőrző kód"),
        (HostFingerprint, "Gazdagép ujjlenyomata"),
        (NotPaired, "Ez a gazdagép még nem ismeri az eszközét. Indítsa el a gazdagépet a --pair kapcsolóval, és csatlakozzon újra."),
        (FirstContact, "Első kapcsolat ezzel a gazdagéppel. Hasonlítsa össze a kódot a gazdagépen láthatóval."),
        (ErrorConnectRefused, "A gazdagép elutasította a kapcsolatot"),
        (ErrorTimeout, "A gazdagép nem válaszol"),
        (ErrorProtocol, "A túloldal más protokollt használ"),
        (ErrorNoDecoder, "Nincs dekóder ehhez a formátumhoz"),
        (TipBitrate, "A bitráta felső határa. Mozgásnál a kódoló teljesen kihasználja; idegen hálózaton inkább 25–50."),
        (TipFps, "Cél képkockaszám. A Mac kijelzőjénél többet nem lehet."),
        (TipGaming, "Gyakoribb kulcskockák és kevesebb megengedett lemaradás: egyenletesebb mozgásnál, kis bitrátába kerül."),
        (TipSound, "Hang átvitele. Kikapcsolva kb. 3 Mbit/s-ot spórol; a gazdagép ilyenkor nem küld hangot."),
        (TipCodec, "A gazdagép kodeke, menet közben váltható; a kép egy pillanatra megáll. Az \"átalakítva\" egy plusz menetbe kerül."),
        (TipFullscreen, "Keret nélküli teljes képernyő. Ablakban a kép beillesztve jelenik meg."),
        (TipPixelExact, "Kép 1:1, nagyítás nélkül. Ha az ablak kisebb, csak egy részlet látszik."),
        (TipShowOverlay, "Statisztika a bal felső sarokban. Hogy mely sorok, jobbra állítható."),
        (TipNerdMode, "Bővített statisztika: késleltetési lánc sávként, gazdagép és kliens terhelése."),
        (TipStatRows, "Mely sorokat mutatja a statisztika."),
        (TipDecoderAuto, "Videokártya, ha kezeli a kodeket, különben szoftveres."),
        (TipDecoderSoftware, "Dekódolás a processzoron. Mindenhol működik, számítási időbe kerül."),
        (TipDecoderGpu, "Dekódolás a videokártyán. Ha nem megy, a kliens szoftveresre vált, és megmondja, miért."),
        (TipDisconnect, "Kapcsolat bontása, vissza a kezdőképernyőre."),
        (TabShortcuts, "Gyorsbillentyűk"),
        (ShortcutMenu, "Menü megnyitása (ez az ESC sosem jut el a Machez)"),
        (ShortcutBack, "Vissza a kezdőképernyőre"),
        (ShortcutWinKey, "Windows billentyű = a Mac Command billentyűje"),
        (ShortcutOthers, "Minden más billentyű a Machez megy. A billentyű helye kerül átvitelre, nem a karakter – ékezetek és AltGr maguktól működnek."),
    ],
};

pub static RO: Lang = Lang {
    code: "ro",
    name: "Română",
    table: &[
        (AppSubtitle, "Desktop la distanță cu culori complete"),
        (Connect, "Conectare"),
        (Disconnect, "Deconectare"),
        (HostAddress, "Adresa gazdei"),
        (SearchingHosts, "Se caută gazde"),
        (NoHostsFound, "Nicio gazdă găsită"),
        (FoundHosts, "Gazde găsite"),
        (Settings, "Setări"),
        (Language, "Limbă"),
        (Quit, "Ieșire"),
        (Connecting, "Se conectează"),
        (Connected, "Conectat"),
        (ConnectionLost, "Conexiune pierdută"),
        (Reconnecting, "Se reconectează"),
        (Fullscreen, "Ecran complet"),
        (PixelExact, "Exact pe pixel"),
        (Stretch, "Potrivire la fereastră"),
        (ShowOverlay, "Afișează statisticile"),
        (Fps, "Cadre pe secundă"),
        (DecodeTime, "Timp de decodare"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rezoluție"),
        (Codec, "Codec"),
        (Latency, "Latență"),
        (EncodeTime, "Codare"),
        (NetworkTime, "Transfer"),
        (AudioBuffer, "Buffer audio"),
        (Dropped, "Pierdute"),
        (MaxBitrate, "Bitrate maxim"),
        (MaxFps, "Rată maximă de cadre"),
        (ExpertMode, "Mod expert"),
        (GamingMode, "Mod joc"),
        (FixedRate, "Rată fixă de cadre"),
        (FixedRateHint, "Menține rata chiar și când nimic nu se mișcă. Încărcare continuă pe gazdă."),
        (Sound, "Sunet"),
        (HoldEscHint, "Țineți ESC apăsat pentru meniu"),
        (NerdMode, "Mod nerd"),
        (More, "Mai multe"),
        (Back, "Înapoi"),
        (SavedForHost, "Salvat pentru această gazdă"),
        (Queue, "Captură și coadă"),
        (OneFrame, "Un cadru"),
        (Bottleneck, "Gâtuire"),
        (TabPicture, "Imagine"),
        (TabDisplay, "Afișare"),
        (CodecConverted, "cu conversie"),
        (CodecSwitching, "Se schimbă codecul"),
        (HostCpu, "Procesorul gazdei"),
        (HostGpu, "Grafica gazdei"),
        (HostRam, "Memoria gazdei"),
        (NoDisplay, "Gazda momentan nu are ecran"),
        (Encryption, "Criptare"),
        (EncryptionOn, "pornită"),
        (EncryptionOff, "oprită"),
        (AudioEnabled, "Sunet"),
        (ClipboardEnabled, "Clipboard"),
        (DecoderLabel, "Decodor"),
        (DecoderAuto, "Automat"),
        (DecoderSoftware, "Software"),
        (DecoderNvidia, "Placă video"),
        (DisplayLabel, "Afișare"),
        (DisplayStage, "Afișare"),
        (ClientCpu, "Procesorul clientului"),
        (Monitor, "Monitor"),
        (Skipped, "sărite"),
        (PairingTitle, "Asociere cu gazda"),
        (PairingHint, "Introduceți codul afișat pe gazdă"),
        (PairingCode, "Cod de asociere"),
        (PairingWrong, "Cod greșit"),
        (PairingOk, "Asociat"),
        (SecuredWith, "Securizat · cod de verificare"),
        (HostFingerprint, "Amprenta gazdei"),
        (NotPaired, "Această gazdă nu cunoaște încă dispozitivul dvs. Porniți gazda cu --pair și conectați-vă din nou."),
        (FirstContact, "Primul contact cu această gazdă. Comparați codul cu cel afișat pe gazdă."),
        (ErrorConnectRefused, "Gazda a refuzat conexiunea"),
        (ErrorTimeout, "Gazda nu răspunde"),
        (ErrorProtocol, "Cealaltă parte folosește alt protocol"),
        (ErrorNoDecoder, "Nu există decodor pentru acest format"),
        (TipBitrate, "Limita superioară a bitrate-ului. La mișcare encoderul o folosește toată; în rețele străine mai bine 25–50."),
        (TipFps, "Rata de cadre țintă. Mai mult decât livrează ecranul Mac-ului nu se poate."),
        (TipGaming, "Cadre-cheie mai dese și mai puțină întârziere permisă: mai uniform la mișcare, costă ceva bitrate."),
        (TipSound, "Transmite sunetul. Oprit economisește cam 3 Mbit/s; gazda nu mai trimite atunci sunet."),
        (TipCodec, "Codecul gazdei, schimbat din mers; imaginea se oprește o clipă. \"cu conversie\" costă o trecere în plus."),
        (TipFullscreen, "Ecran complet fără margini. În fereastră imaginea este potrivită."),
        (TipPixelExact, "Imagine 1:1 fără scalare. Dacă fereastra e mai mică, se vede un decupaj."),
        (TipShowOverlay, "Afișează statisticile în stânga sus. Ce rânduri, se alege în dreapta."),
        (TipNerdMode, "Statistici extinse: lanțul de latență ca bară, încărcarea gazdei și a clientului."),
        (TipStatRows, "Ce rânduri arată statisticile."),
        (TipDecoderAuto, "Placa video dacă suportă codecul, altfel software."),
        (TipDecoderSoftware, "Decodare pe procesor. Merge oriunde, costă timp de calcul."),
        (TipDecoderGpu, "Decodare pe placa video. Dacă nu poate, clientul revine la software și spune de ce."),
        (TipDisconnect, "Încheie conexiunea, înapoi la ecranul de start."),
        (TabShortcuts, "Scurtături"),
        (ShortcutMenu, "Deschide meniul (acest ESC nu ajunge niciodată la Mac)"),
        (ShortcutBack, "Înapoi la ecranul de start"),
        (ShortcutWinKey, "Tasta Windows = tasta Command a Mac-ului"),
        (ShortcutOthers, "Toate celelalte taste merg la Mac. Se transmite poziția tastei, nu caracterul – diacriticele și AltGr merg de la sine."),
    ],
};

pub static BG: Lang = Lang {
    code: "bg",
    name: "Български",
    table: &[
        (AppSubtitle, "Отдалечен работен плот с пълни цветове"),
        (Connect, "Свързване"),
        (Disconnect, "Прекъсване"),
        (HostAddress, "Адрес на хоста"),
        (SearchingHosts, "Търсене на хостове"),
        (NoHostsFound, "Няма намерени хостове"),
        (FoundHosts, "Намерени хостове"),
        (Settings, "Настройки"),
        (Language, "Език"),
        (Quit, "Изход"),
        (Connecting, "Свързва се"),
        (Connected, "Свързано"),
        (ConnectionLost, "Връзката прекъсна"),
        (Reconnecting, "Повторно свързване"),
        (Fullscreen, "Цял екран"),
        (PixelExact, "Точно по пиксели"),
        (Stretch, "Побиране в прозореца"),
        (ShowOverlay, "Показване на статистика"),
        (Fps, "Кадри в секунда"),
        (DecodeTime, "Време за декодиране"),
        (Bitrate, "Битрейт"),
        (Resolution, "Резолюция"),
        (Codec, "Кодек"),
        (Latency, "Закъснение"),
        (EncodeTime, "Кодиране"),
        (NetworkTime, "Пренос"),
        (AudioBuffer, "Аудио буфер"),
        (Dropped, "Пропуснати"),
        (MaxBitrate, "Максимален битрейт"),
        (MaxFps, "Максимални кадри в секунда"),
        (ExpertMode, "Експертен режим"),
        (GamingMode, "Игрови режим"),
        (FixedRate, "Постоянни кадри в секунда"),
        (FixedRateHint, "Запазва честотата, дори когато нищо не се движи. Постоянно натоварване на хоста."),
        (Sound, "Звук"),
        (HoldEscHint, "Задръжте ESC за менюто"),
        (NerdMode, "Режим за маниаци"),
        (More, "Още"),
        (Back, "Назад"),
        (SavedForHost, "Запазено за този хост"),
        (Queue, "Заснемане и чакане"),
        (OneFrame, "Един кадър"),
        (Bottleneck, "Тясно място"),
        (TabPicture, "Картина"),
        (TabDisplay, "Екран"),
        (CodecConverted, "с преобразуване"),
        (CodecSwitching, "Сменя се кодекът"),
        (HostCpu, "Процесор на хоста"),
        (HostGpu, "Графика на хоста"),
        (HostRam, "Памет на хоста"),
        (NoDisplay, "Хостът в момента няма екран"),
        (Encryption, "Шифроване"),
        (EncryptionOn, "вкл."),
        (EncryptionOff, "изкл."),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Клипборд"),
        (DecoderLabel, "Декодер"),
        (DecoderAuto, "Автоматично"),
        (DecoderSoftware, "Софтуерно"),
        (DecoderNvidia, "Видеокарта"),
        (DisplayLabel, "Екран"),
        (DisplayStage, "Екран"),
        (ClientCpu, "Процесор на клиента"),
        (Monitor, "Монитор"),
        (Skipped, "прескочени"),
        (PairingTitle, "Сдвояване с хоста"),
        (PairingHint, "Въведете кода, показан на хоста"),
        (PairingCode, "Код за сдвояване"),
        (PairingWrong, "Грешен код"),
        (PairingOk, "Сдвоено"),
        (SecuredWith, "Защитено · код за проверка"),
        (HostFingerprint, "Отпечатък на хоста"),
        (NotPaired, "Този хост още не познава устройството ви. Стартирайте хоста с --pair и се свържете отново."),
        (FirstContact, "Първи контакт с този хост. Сравнете кода с този на хоста."),
        (ErrorConnectRefused, "Хостът отказа връзката"),
        (ErrorTimeout, "Хостът не отговаря"),
        (ErrorProtocol, "Отсрещната страна използва друг протокол"),
        (ErrorNoDecoder, "Няма декодер за този формат"),
        (TipBitrate, "Горна граница на битрейта. При движение енкодерът я използва докрай; в чужди мрежи по-добре 25 до 50."),
        (TipFps, "Целева честота на кадрите. Повече, отколкото дава екранът на Mac, не е възможно."),
        (TipGaming, "По-чести ключови кадри и по-малко допустимо изоставане: по-равномерно при движение, струва малко битрейт."),
        (TipSound, "Пренасяне на звука. Изключено пести около 3 Mbit/s; хостът тогава не изпраща звук."),
        (TipCodec, "Кодекът на хоста, сменя се в движение; картината спира за миг. \"с преобразуване\" струва един допълнителен проход."),
        (TipFullscreen, "Цял екран без рамка. В прозорец картината се побира."),
        (TipPixelExact, "Картина 1:1 без мащабиране. Ако прозорецът е по-малък, се вижда изрезка."),
        (TipShowOverlay, "Показване на статистиката горе вляво. Кои редове – вдясно."),
        (TipNerdMode, "Разширена статистика: веригата на закъснението като лента, натоварване на хоста и клиента."),
        (TipStatRows, "Кои редове показва статистиката."),
        (TipDecoderAuto, "Видеокарта, ако поддържа кодека, иначе софтуерно."),
        (TipDecoderSoftware, "Декодиране на процесора. Работи навсякъде, струва процесорно време."),
        (TipDecoderGpu, "Декодиране на видеокартата. Ако не може, клиентът минава на софтуерно и казва защо."),
        (TipDisconnect, "Прекъсване на връзката, обратно към началния екран."),
        (TabShortcuts, "Клавиши"),
        (ShortcutMenu, "Отваря менюто (този ESC никога не стига до Mac)"),
        (ShortcutBack, "Обратно към началния екран"),
        (ShortcutWinKey, "Клавиш Windows = клавишът Command на Mac"),
        (ShortcutOthers, "Всички други клавиши отиват към Mac. Предава се позицията на клавиша, не знакът – кирилица и AltGr работят от само себе си."),
    ],
};

pub static EL: Lang = Lang {
    code: "el",
    name: "Ελληνικά",
    table: &[
        (AppSubtitle, "Απομακρυσμένη επιφάνεια με πλήρη χρώματα"),
        (Connect, "Σύνδεση"),
        (Disconnect, "Αποσύνδεση"),
        (HostAddress, "Διεύθυνση host"),
        (SearchingHosts, "Αναζήτηση host"),
        (NoHostsFound, "Δεν βρέθηκαν host"),
        (FoundHosts, "Host που βρέθηκαν"),
        (Settings, "Ρυθμίσεις"),
        (Language, "Γλώσσα"),
        (Quit, "Έξοδος"),
        (Connecting, "Γίνεται σύνδεση"),
        (Connected, "Συνδεδεμένο"),
        (ConnectionLost, "Η σύνδεση χάθηκε"),
        (Reconnecting, "Επανασύνδεση"),
        (Fullscreen, "Πλήρης οθόνη"),
        (PixelExact, "Ακριβώς σε pixel"),
        (Stretch, "Προσαρμογή στο παράθυρο"),
        (ShowOverlay, "Εμφάνιση στατιστικών"),
        (Fps, "Καρέ ανά δευτερόλεπτο"),
        (DecodeTime, "Χρόνος αποκωδικοποίησης"),
        (Bitrate, "Bitrate"),
        (Resolution, "Ανάλυση"),
        (Codec, "Codec"),
        (Latency, "Καθυστέρηση"),
        (EncodeTime, "Κωδικοποίηση"),
        (NetworkTime, "Μετάδοση"),
        (AudioBuffer, "Buffer ήχου"),
        (Dropped, "Χαμένα"),
        (MaxBitrate, "Μέγιστο bitrate"),
        (MaxFps, "Μέγιστος ρυθμός καρέ"),
        (ExpertMode, "Λειτουργία για προχωρημένους"),
        (GamingMode, "Λειτουργία παιχνιδιού"),
        (FixedRate, "Σταθερός ρυθμός καρέ"),
        (FixedRateHint, "Διατηρεί τον ρυθμό ακόμη και όταν δεν κινείται τίποτα. Συνεχής φόρτος στον host."),
        (Sound, "Ήχος"),
        (HoldEscHint, "Κρατήστε το ESC για το μενού"),
        (NerdMode, "Λειτουργία nerd"),
        (More, "Περισσότερα"),
        (Back, "Πίσω"),
        (SavedForHost, "Αποθηκεύτηκε για αυτόν τον host"),
        (Queue, "Λήψη και αναμονή"),
        (OneFrame, "Ένα καρέ"),
        (Bottleneck, "Σημείο συμφόρησης"),
        (TabPicture, "Εικόνα"),
        (TabDisplay, "Προβολή"),
        (CodecConverted, "με μετατροπή"),
        (CodecSwitching, "Γίνεται αλλαγή codec"),
        (HostCpu, "CPU host"),
        (HostGpu, "GPU host"),
        (HostRam, "Μνήμη host"),
        (NoDisplay, "Ο host δεν έχει οθόνη αυτή τη στιγμή"),
        (Encryption, "Κρυπτογράφηση"),
        (EncryptionOn, "ενεργή"),
        (EncryptionOff, "ανενεργή"),
        (AudioEnabled, "Ήχος"),
        (ClipboardEnabled, "Πρόχειρο"),
        (DecoderLabel, "Decoder"),
        (DecoderAuto, "Αυτόματα"),
        (DecoderSoftware, "Λογισμικό"),
        (DecoderNvidia, "Κάρτα γραφικών"),
        (DisplayLabel, "Προβολή"),
        (DisplayStage, "Προβολή"),
        (ClientCpu, "CPU client"),
        (Monitor, "Οθόνη"),
        (Skipped, "παραλείφθηκαν"),
        (PairingTitle, "Σύζευξη με τον host"),
        (PairingHint, "Εισαγάγετε τον κωδικό που δείχνει ο host"),
        (PairingCode, "Κωδικός σύζευξης"),
        (PairingWrong, "Λάθος κωδικός"),
        (PairingOk, "Έγινε σύζευξη"),
        (SecuredWith, "Ασφαλές · κωδικός επαλήθευσης"),
        (HostFingerprint, "Αποτύπωμα του host"),
        (NotPaired, "Αυτός ο host δεν γνωρίζει ακόμη τη συσκευή σας. Εκκινήστε τον host με --pair και συνδεθείτε ξανά."),
        (FirstContact, "Πρώτη επαφή με αυτόν τον host. Συγκρίνετε τον κωδικό με αυτόν στον host."),
        (ErrorConnectRefused, "Ο host απέρριψε τη σύνδεση"),
        (ErrorTimeout, "Ο host δεν απαντά"),
        (ErrorProtocol, "Η άλλη πλευρά χρησιμοποιεί άλλο πρωτόκολλο"),
        (ErrorNoDecoder, "Δεν υπάρχει decoder για αυτή τη μορφή"),
        (TipBitrate, "Άνω όριο του bitrate. Με κίνηση ο encoder το αξιοποιεί όλο· σε ξένα δίκτυα καλύτερα 25 έως 50."),
        (TipFps, "Επιθυμητός ρυθμός καρέ. Δεν μπορεί να ξεπεράσει όσα δίνει η οθόνη του Mac."),
        (TipGaming, "Συχνότερα keyframes και λιγότερη ανεκτή καθυστέρηση: πιο σταθερό με κίνηση, κοστίζει λίγο bitrate."),
        (TipSound, "Μετάδοση ήχου. Απενεργοποιημένο εξοικονομεί περίπου 3 Mbit/s· ο host τότε δεν στέλνει ήχο."),
        (TipCodec, "Codec του host, αλλάζει εν λειτουργία· η εικόνα παγώνει για μια στιγμή. Το \"με μετατροπή\" κοστίζει ένα πέρασμα παραπάνω."),
        (TipFullscreen, "Πλήρης οθόνη χωρίς πλαίσιο. Σε παράθυρο η εικόνα προσαρμόζεται."),
        (TipPixelExact, "Εικόνα 1:1 χωρίς κλιμάκωση. Αν το παράθυρο είναι μικρότερο, βλέπετε ένα τμήμα."),
        (TipShowOverlay, "Εμφάνιση στατιστικών πάνω αριστερά. Ποιες γραμμές, δεξιά."),
        (TipNerdMode, "Εκτεταμένα στατιστικά: αλυσίδα καθυστέρησης ως μπάρα, φόρτος host και client."),
        (TipStatRows, "Ποιες γραμμές δείχνουν τα στατιστικά."),
        (TipDecoderAuto, "Κάρτα γραφικών αν υποστηρίζει το codec, αλλιώς λογισμικό."),
        (TipDecoderSoftware, "Αποκωδικοποίηση στον επεξεργαστή. Δουλεύει παντού, κοστίζει χρόνο CPU."),
        (TipDecoderGpu, "Αποκωδικοποίηση στην κάρτα γραφικών. Αν δεν μπορεί, ο client επιστρέφει σε λογισμικό και λέει γιατί."),
        (TipDisconnect, "Τερματισμός σύνδεσης, επιστροφή στην αρχική οθόνη."),
        (TabShortcuts, "Συντομεύσεις"),
        (ShortcutMenu, "Άνοιγμα μενού (αυτό το ESC δεν φτάνει ποτέ στο Mac)"),
        (ShortcutBack, "Επιστροφή στην αρχική οθόνη"),
        (ShortcutWinKey, "Πλήκτρο Windows = πλήκτρο Command του Mac"),
        (ShortcutOthers, "Όλα τα άλλα πλήκτρα πάνε στο Mac. Μεταδίδεται η θέση του πλήκτρου, όχι ο χαρακτήρας – τόνοι και AltGr δουλεύουν από μόνα τους."),
    ],
};
