// Sprachtabellen: Estnisch, Lettisch, Litauisch, Slowenisch, Kroatisch,
// Ukrainisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static ET: Lang = Lang {
    code: "et",
    name: "Eesti",
    table: &[
        (AppSubtitle, "Kaugtöölaud täieliku värvitäpsusega"),
        (Connect, "Ühenda"),
        (Disconnect, "Katkesta ühendus"),
        (HostAddress, "Hosti aadress"),
        (SearchingHosts, "Otsin hoste"),
        (NoHostsFound, "Hoste ei leitud"),
        (FoundHosts, "Leitud hostid"),
        (Settings, "Sätted"),
        (Language, "Keel"),
        (Quit, "Välju"),
        (Connecting, "Ühendan"),
        (Connected, "Ühendatud"),
        (ConnectionLost, "Ühendus katkes"),
        (Reconnecting, "Ühendan uuesti"),
        (Fullscreen, "Täisekraan"),
        (PixelExact, "Pikslitäpne"),
        (Stretch, "Sobita aknasse"),
        (ShowOverlay, "Näita statistikat"),
        (Fps, "Kaadrit sekundis"),
        (DecodeTime, "Dekodeerimisaeg"),
        (Bitrate, "Bitikiirus"),
        (Resolution, "Eraldusvõime"),
        (Codec, "Koodek"),
        (Latency, "Viivitus"),
        (EncodeTime, "Kodeerimisaeg"),
        (NetworkTime, "Ülekandeaeg"),
        (AudioBuffer, "Helipuhver"),
        (Dropped, "Vahelejäänud"),
        (MaxBitrate, "Suurim bitikiirus"),
        (MaxFps, "Suurim kaadrisagedus"),
        (ExpertMode, "Eksperdirežiim"),
        (GamingMode, "Mängurežiim"),
        (FixedRate, "Püsiv kaadrisagedus"),
        (FixedRateHint, "Hoiab kaadrisagedust ka siis, kui miski ei liigu. Pidev koormus hostile."),
        (Sound, "Heli"),
        (HoldEscHint, "Hoia ESC all menüü avamiseks"),
        (NerdMode, "Tehniline vaade"),
        (More, "Veel"),
        (Back, "Tagasi"),
        (SavedForHost, "Salvestatud selle hosti jaoks"),
        (Queue, "Hõive ja ootamine"),
        (OneFrame, "Üks kaader"),
        (Bottleneck, "Kitsaskoht"),
        (TabPicture, "Pilt"),
        (TabDisplay, "Kuva"),
        (CodecConverted, "teisendatud"),
        (CodecSwitching, "Vahetan koodekit"),
        (HostCpu, "Hosti protsessor"),
        (HostGpu, "Hosti graafika"),
        (HostRam, "Hosti mälu"),
        (NoDisplay, "Hostil pole praegu ekraani"),
        (Encryption, "Krüptimine"),
        (EncryptionOn, "sees"),
        (EncryptionOff, "väljas"),
        (AudioEnabled, "Heli"),
        (ClipboardEnabled, "Lõikelaud"),
        (DecoderLabel, "Dekooder"),
        (RoleAuto, "Automaatne"),
        (RoleCpu, "Protsessor"),
        (RoleGpu, "Graafikakaart"),
        (RoleGpuN, "Graafikakaart {n}"),
        (RoleIntegrated, "Integreeritud"),
        (NextStartHint, "kehtib alates järgmisest käivitusest"),
        (AdapterWithOutput, "ekraaniväljundiga"),
        (AdapterNoOutput, "ilma ekraaniväljundita"),
        (TipOnly420, "Ainult 4:2:0 ja H.264 (D3D11VA); 4:4:4 korral läheb klient protsessorile üle – vaheta koodek vahekaardil Pilt."),
        (DisplayLabel, "Kuva"),
        (DisplayStage, "Kuva"),
        (ClientCpu, "Kliendi protsessor"),
        (Monitor, "Monitor"),
        (Skipped, "esitamata"),
        (PairingTitle, "Seo hostiga"),
        (PairingHint, "Sisesta hostis kuvatud kood"),
        (PairingCode, "Sidumiskood"),
        (PairingWrong, "Vale kood"),
        (PairingOk, "Seotud"),
        (SecuredWith, "Turvatud · kontrollkood"),
        (HostFingerprint, "Hosti sõrmejälg"),
        (NotPaired, "See host ei tunne veel sinu seadet. Käivita host võtmega --pair ja ühenda uuesti."),
        (FirstContact, "Esimene kontakt selle hostiga. Võrdle koodi hostis kuvatuga."),
        (ErrorConnectRefused, "Host keeldus ühendusest"),
        (ErrorTimeout, "Host ei vastanud"),
        (ErrorProtocol, "Teine pool kasutab teist protokolli"),
        (ErrorNoDecoder, "Selle vormingu jaoks pole dekoodrit"),
        (SessionTakenOver, "Teine seade võttis seansi üle."),
        (HostKeyChanged, "Hosti {n} sõrmejälg on muutunud (nüüd {m}). Ühendusest keelduti. Kui host paigaldati uuesti, kustuta selle rida failist {p}."),
        (KeyFileDamaged, "Võtmefail {p} on rikutud ja jäeti muutmata. Kontrolli seda või kustuta see – siis luuakse uus võti ja host peab selle seadme uuesti siduma."),
        (FileUnreadable, "Faili {p} ei saa lugeda – ühendust ei looda."),
        (FileNotUtf8, "Fail {p} pole salvestatud UTF-8 kodeeringus – ühendust ei looda."),
        (FileNotWritable, "Faili {p} ei saa kirjutada – ühendust ei looda."),
        (StorageUnavailable, "Võtmete ja sätete kaust pole saadaval – ühendust ei looda."),
        (ErrorAddress, "Aadressi {n} ei saa lahendada"),
        (ErrorNoConnection, "Hostiga puudub ühendus"),
        (ErrorHandshake, "Turvalist ühendust ei õnnestunud luua"),
        (ErrorFfmpegStart, "FFmpegi ei õnnestunud käivitada"),
        (ErrorSound, "Heli pole saadaval"),
        (ErrorGpuDisplay, "Graafikakaart pole kasutatav, kuva töötab tarkvaraliselt"),
        (ErrorGpuLost, "Graafikakaart kadus – käivita uuesti võtmega --anzeige cpu"),
        (ErrorPixelFormat, "Dekooder annab pilte, mida see klient kuvada ei suuda"),
        (DecoderFallback, "Valitud graafikakaart ei dekodeeri – töötab tarkvaraline dekooder"),
        (TipBitrate, "Bitikiiruse ülempiir. Liikumise korral kasutab kooder selle täielikult ära; võõras võrgus pigem 25 kuni 50."),
        (TipFps, "Sihtkaadrisagedus. Rohkem, kui Maci ekraan annab, ei saa."),
        (TipGaming, "Sagedamad võtmekaadrid ja väiksem lubatud mahajäämus: ühtlasem liikumisel, maksab veidi bitikiirust."),
        (TipSound, "Heli edastamine. Väljas säästab umbes 3 Mbit/s; host ei saada siis heli."),
        (TipCodec, "Hosti koodek, vahetatakse töö ajal; pilt seisab hetkeks. \"teisendatud\" maksab ühe lisakäigu."),
        (TipFullscreen, "Raamita täisekraan. Aknas pilt sobitatakse."),
        (TipPixelExact, "Pilt 1:1 ilma skaleerimata. Kui aken on väiksem, näed väljalõiget."),
        (TipShowOverlay, "Näita statistikat üleval vasakul. Millised read, vali paremalt."),
        (TipNerdMode, "Laiendatud statistika: viivitusahel tulbana, hosti ja kliendi koormus."),
        (TipStatRows, "Millised read statistikas kuvatakse."),
        (TipDecoderAuto, "NVDEC NVIDIA kaardil; muidu D3D11VA kaardil, mis joonistab (ainult 4:2:0 ja H.264); muidu protsessor."),
        (TipDecoderCpu, "Dekodeerimine protsessoril. Töötab kõikjal, maksab arvutusaega."),
        (TipDecoderGpu, "Dekodeerimine graafikakaardil. Kui see ei õnnestu, läheb klient protsessorile üle ja ütleb, miks."),
        (TipDecoderIntegrated, "Dekodeerimine integreeritud graafikal (D3D11VA). Kui see ei õnnestu, läheb klient protsessorile üle ja ütleb, miks."),
        (TipDisplayAuto, "Direct3D 11 esimesel ekraaniväljundiga kaardil, muidu esimesel NVIDIA kaardil, muidu esimesel, mis leidub. Ilma kaardita: protsessor. Kehtib alates järgmisest käivitusest."),
        (TipDisplayGpu, "Joonistamine Direct3D 11-ga sellel kaardil. Kehtib alates järgmisest käivitusest."),
        (TipDisplayIntegrated, "Joonistamine Direct3D 11-ga integreeritud graafikal – selle küljes on tavaliselt ekraan. Kehtib alates järgmisest käivitusest."),
        (TipDisplayCpu, "Joonistamine protsessoril, ilma Direct3D-ta. Töötab kõikjal, maksab arvutusaega. Kehtib alates järgmisest käivitusest."),
        (TipDisconnect, "Lõpeta ühendus, tagasi avakuvale."),
        (TabShortcuts, "Kiirklahvid"),
        (ShortcutMenu, "Ava menüü (see ESC ei jõua kunagi Macini)"),
        (ShortcutBack, "Tagasi avakuvale"),
        (ShortcutWinKey, "Windowsi klahv = Maci Command-klahv"),
        (ShortcutOthers, "Kõik teised klahvid lähevad Macile. Edastatakse klahvi asukoht, mitte märk – täpitähed ja AltGr töötavad iseenesest."),
        // Benchmark
        (TabBenchmark, "Jõudlustest"),
        (BenchStart, "Alusta"),
        (BenchAbort, "Katkesta"),
        (BenchApply, "Rakenda"),
        (BenchDuration, "Kestus sammu kohta"),
        (BenchTestPattern, "Testpilt"),
        (BenchStep, "Samm {n}/{m}"),
        (BenchPhaseSettings, "sätete rakendamine"),
        (BenchPhaseSettle, "stabiliseerumine"),
        (BenchPhaseMeasure, "mõõtmine"),
        (BenchFailed, "ebaõnnestus"),
        (BenchDone, "Valmis"),
        (BenchAborted, "Katkestatud"),
        (BenchMeasured, "mõõdetud"),
        (BenchChain, "Ahel"),
        (BenchColFps, "fps"),
        (BenchColDropped, "vahelejäänud"),
        (BenchColHostCpu, "Hosti CPU"),
        (BenchRecommendation, "Soovitus"),
        (BenchNoRecommendation, "Ükski samm ei läbinud: ahel üle 30 ms või liiga vähe kaadreid. Proovi madalamat kaadrisagedust või bitikiirust."),
        (BenchHint, "Mõõdetakse seda, mis Macil praegu toimub. Sammud on võrreldavad ainult siis, kui miski liigub – piisab mängivast videost."),
        (BenchHintPattern, "Testpildiga näeb iga samm sama liikuvat sisu – Macil ei pea midagi töötama."),
        (TipBenchStart, "Mõõdab järjest kõik valitud koodekite, kaadrisageduste ja bitikiiruste kombinatsioonid, iga seatud kestuse jooksul. Pilt jookseb edasi ja menüü võib jääda lahti."),
        (TipBenchApply, "Sea soovitatud koodek ja sätted ning salvesta need selle hosti jaoks."),
        (TipBenchDuration, "Mõõteaeg sammu kohta. Pikem on stabiilsem; 5 s on enamasti küllalt."),
        (TipBenchHint, "Samm läbib, kui kohale jõuab vähemalt 95 % sihtkaadrisagedusest, vahele jääb alla 1 % kaadritest ja kogu ahel püsib 30 ms sees – kaadrisagedusest sõltumata. Hosti kooderi aega näidatakse, kuid ei hinnata. Soovitus: parim värvikvaliteet, mis läbib kõrgeimal kaadrisagedusel, kõrgeima bitikiirusega."),
        (TipBenchTestPattern, "Jooksu ajaks näitab host ekraani asemel kindlat liikuvat mustrit – iga samm mõõdab sama sisu."),
        (DesktopShortcut, "Otsetee"),
        (TipDesktopShortcut, "Loob töölauale otsetee selle hostini. Topeltklõps loob kohe ühenduse."),
        (DesktopShortcutCreated, "Otsetee loodud töölauale: {n}"),
        (DesktopShortcutFailed, "Otseteed ei loodud: {n}"),
        (DesktopShortcutDescription, "QuadChroma: ühenda hostiga {n} ({m})"),
        (FilesSending, "Failide saatmine: {n} / {m}"),
        (FilesReceiving, "Failide vastuvõtmine: {n} / {m}"),
        (FilesReady, "Failid on kleepimiseks valmis: {n}"),
        (FilesSent, "Failid edastatud: {n}"),
        (FilesAborted, "Failide edastamine katkestati: {n}"),
        (FilesTooLarge, "Faile ei edastatud: üle 4 GB või 10 000 kirje"),
        (FilesPeerOld, "Teine pool ei saa veel faile vastu võtta."),
        (TrayOpen, "Ava"),
        (TrayConnect, "Ühenda: {n}"),
        (TrayQuit, "Välju"),
        (TrayStillRunning, "QuadChroma töötab edasi teavitusalal."),
        (TrayStillRunningMac, "QuadChroma töötab edasi menüüribal."),
        (FilesAbortLocal, "selle seadme poolt"),
        (FilesAbortPeer, "teise poole poolt"),
        (FilesAbortConnection, "ühendus katkes"),
        (FilesAbortTimeout, "ajalõpp, edenemist pole"),
        (FilesAbortNoSpace, "kettaruumi pole piisavalt"),
        (FilesAbortInvalid, "vigased andmed"),
        (FilesAbortRead, "lugemisviga"),
        (FilesAbortWrite, "kirjutamisviga"),
        (FilesAbortClipboard, "lõikelaud pole saadaval"),
        (ScreenLabel, "Hosti ekraan"),
        (ScreenAuto, "Automaatne"),
        (TipScreen, "Millist hosti ekraani sa näed. Automaatne järgib põhiekraani; kindel ekraan kehtib, kuni valid midagi muud."),
        (ScreenSwitching, "Vahetan ekraani …"),
        (ScreenFallback, "{n} pole ühendatud – asendus: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};

pub static LV: Lang = Lang {
    code: "lv",
    name: "Latviešu",
    table: &[
        (AppSubtitle, "Attālā darbvirsma ar pilnu krāsu detalizāciju"),
        (Connect, "Savienot"),
        (Disconnect, "Atvienot"),
        (HostAddress, "Hosta adrese"),
        (SearchingHosts, "Meklē hostus"),
        (NoHostsFound, "Hosti nav atrasti"),
        (FoundHosts, "Atrastie hosti"),
        (Settings, "Iestatījumi"),
        (Language, "Valoda"),
        (Quit, "Iziet"),
        (Connecting, "Savienojas"),
        (Connected, "Savienots"),
        (ConnectionLost, "Savienojums pārtrūka"),
        (Reconnecting, "Savienojas atkārtoti"),
        (Fullscreen, "Pilnekrāns"),
        (PixelExact, "Pikseļu precizitāte"),
        (Stretch, "Ietilpināt logā"),
        (ShowOverlay, "Rādīt statistiku"),
        (Fps, "Kadri sekundē"),
        (DecodeTime, "Dekodēšanas laiks"),
        (Bitrate, "Bitu ātrums"),
        (Resolution, "Izšķirtspēja"),
        (Codec, "Kodeks"),
        (Latency, "Aizkave"),
        (EncodeTime, "Kodēšanas laiks"),
        (NetworkTime, "Pārraides laiks"),
        (AudioBuffer, "Audio buferis"),
        (Dropped, "Izlaisti"),
        (MaxBitrate, "Maksimālais bitu ātrums"),
        (MaxFps, "Maksimālais kadru ātrums"),
        (ExpertMode, "Eksperta režīms"),
        (GamingMode, "Spēļu režīms"),
        (FixedRate, "Fiksēts kadru ātrums"),
        (FixedRateHint, "Uztur kadru ātrumu arī tad, kad nekas nekustas. Pastāvīga slodze hostam."),
        (Sound, "Skaņa"),
        (HoldEscHint, "Turiet ESC, lai atvērtu izvēlni"),
        (NerdMode, "Nerda režīms"),
        (More, "Vairāk"),
        (Back, "Atpakaļ"),
        (SavedForHost, "Saglabāts šim hostam"),
        (Queue, "Uzņemšana un rinda"),
        (OneFrame, "Viens kadrs"),
        (Bottleneck, "Šaurā vieta"),
        (TabPicture, "Attēls"),
        (TabDisplay, "Ekrāns"),
        (CodecConverted, "konvertēts"),
        (CodecSwitching, "Pārslēdz kodeku"),
        (HostCpu, "Hosta procesors"),
        (HostGpu, "Hosta grafika"),
        (HostRam, "Hosta atmiņa"),
        (NoDisplay, "Hostam pašlaik nav ekrāna"),
        (Encryption, "Šifrēšana"),
        (EncryptionOn, "ieslēgta"),
        (EncryptionOff, "izslēgta"),
        (AudioEnabled, "Skaņa"),
        (ClipboardEnabled, "Starpliktuve"),
        (DecoderLabel, "Dekoders"),
        (RoleAuto, "Automātiski"),
        (RoleCpu, "Procesors"),
        (RoleGpu, "Videokarte"),
        (RoleGpuN, "Videokarte {n}"),
        (RoleIntegrated, "Integrētā"),
        (NextStartHint, "stājas spēkā no nākamās palaišanas"),
        (AdapterWithOutput, "ar ekrāna izeju"),
        (AdapterNoOutput, "bez ekrāna izejas"),
        (TipOnly420, "Tikai 4:2:0 un H.264 (D3D11VA); ar 4:4:4 klients pāriet uz procesoru – nomainiet kodeku cilnē Attēls."),
        (DisplayLabel, "Ekrāns"),
        (DisplayStage, "Ekrāns"),
        (ClientCpu, "Klienta procesors"),
        (Monitor, "Monitors"),
        (Skipped, "nerādīti"),
        (PairingTitle, "Savienot pārī ar hostu"),
        (PairingHint, "Ievadiet hostā redzamo kodu"),
        (PairingCode, "Savienošanas kods"),
        (PairingWrong, "Nepareizs kods"),
        (PairingOk, "Savienots pārī"),
        (SecuredWith, "Aizsargāts · pārbaudes kods"),
        (HostFingerprint, "Hosta atslēgas nospiedums"),
        (NotPaired, "Šis hosts vēl nepazīst jūsu ierīci. Palaidiet hostu ar --pair un savienojiet vēlreiz."),
        (FirstContact, "Pirmais kontakts ar šo hostu. Salīdziniet kodu ar to, kas redzams hostā."),
        (ErrorConnectRefused, "Hosts noraidīja savienojumu"),
        (ErrorTimeout, "Hosts neatbildēja"),
        (ErrorProtocol, "Otra puse lieto citu protokolu"),
        (ErrorNoDecoder, "Šim formātam nav dekodera"),
        (SessionTakenOver, "Sesiju pārņēma cita ierīce."),
        (HostKeyChanged, "Hosta {n} atslēgas nospiedums ir mainījies (tagad {m}). Savienojums noraidīts. Ja hosts ir pārinstalēts, izdzēsiet tā rindu failā {p}."),
        (KeyFileDamaged, "Atslēgas fails {p} ir bojāts un atstāts nemainīts. Pārbaudiet vai izdzēsiet to – tad tiks izveidota jauna atslēga, un hostam šī ierīce būs atkārtoti jāsavieno pārī."),
        (FileUnreadable, "Failu {p} nevar nolasīt – savienojums netiek veidots."),
        (FileNotUtf8, "Fails {p} nav saglabāts UTF-8 kodējumā – savienojums netiek veidots."),
        (FileNotWritable, "Failā {p} nevar ierakstīt – savienojums netiek veidots."),
        (StorageUnavailable, "Mape atslēgām un iestatījumiem nav pieejama – savienojums netiek veidots."),
        (ErrorAddress, "Adresi {n} nevar atrisināt"),
        (ErrorNoConnection, "Nav savienojuma ar hostu"),
        (ErrorHandshake, "Drošo savienojumu neizdevās izveidot"),
        (ErrorFfmpegStart, "FFmpeg neizdevās palaist"),
        (ErrorSound, "Skaņa nav pieejama"),
        (ErrorGpuDisplay, "Videokarte nav izmantojama, attēlošana notiek programmatūrā"),
        (ErrorGpuLost, "Videokarte zaudēta – palaidiet no jauna ar --anzeige cpu"),
        (ErrorPixelFormat, "Dekoders piegādā attēlus, kurus šis klients nevar parādīt"),
        (DecoderFallback, "Izvēlētā videokarte nedekodē – darbojas programmatūras dekoders"),
        (TipBitrate, "Bitu ātruma augšējā robeža. Kustībā kodētājs to izmanto pilnībā; svešos tīklos labāk 25 līdz 50."),
        (TipFps, "Mērķa kadru ātrums. Vairāk, nekā dod Mac ekrāns, nav iespējams."),
        (TipGaming, "Biežāki atslēgkadri un mazāka pieļaujamā atpalikšana: vienmērīgāk kustībā, maksā nedaudz bitu ātruma."),
        (TipSound, "Pārraidīt skaņu. Izslēgts ietaupa apmēram 3 Mbit/s; hosts tad skaņu nesūta."),
        (TipCodec, "Hosta kodeks, maināms darbības laikā; attēls uz brīdi apstājas. \"konvertēts\" maksā vienu papildu soli."),
        (TipFullscreen, "Pilnekrāns bez malām. Logā attēls tiek ietilpināts."),
        (TipPixelExact, "Attēls 1:1 bez mērogošanas. Ja logs ir mazāks, redzams izgriezums."),
        (TipShowOverlay, "Rādīt statistiku augšā pa kreisi. Kuras rindas – pa labi."),
        (TipNerdMode, "Paplašināta statistika: aizkaves ķēde kā josla, hosta un klienta slodze."),
        (TipStatRows, "Kuras rindas statistika rāda."),
        (TipDecoderAuto, "NVDEC uz NVIDIA kartes; citādi D3D11VA uz kartes, kas zīmē (tikai 4:2:0 un H.264); citādi procesors."),
        (TipDecoderCpu, "Dekodēšana uz procesora. Darbojas visur, maksā skaitļošanas laiku."),
        (TipDecoderGpu, "Dekodēšana uz videokartes. Ja tā nevar, klients pāriet uz procesoru un pasaka, kāpēc."),
        (TipDecoderIntegrated, "Dekodēšana uz integrētās grafikas (D3D11VA). Ja tā nevar, klients pāriet uz procesoru un pasaka, kāpēc."),
        (TipDisplayAuto, "Direct3D 11 uz pirmās kartes ar ekrāna izeju, citādi uz pirmās NVIDIA kartes, citādi uz pirmās, kas ir. Bez kartes: procesors. Stājas spēkā no nākamās palaišanas."),
        (TipDisplayGpu, "Zīmēšana ar Direct3D 11 uz šīs kartes. Stājas spēkā no nākamās palaišanas."),
        (TipDisplayIntegrated, "Zīmēšana ar Direct3D 11 uz integrētās grafikas – pie tās parasti pieslēgts ekrāns. Stājas spēkā no nākamās palaišanas."),
        (TipDisplayCpu, "Zīmēšana uz procesora, bez Direct3D. Darbojas visur, maksā skaitļošanas laiku. Stājas spēkā no nākamās palaišanas."),
        (TipDisconnect, "Beigt savienojumu, atpakaļ uz sākuma ekrānu."),
        (TabShortcuts, "Īsinājumtaustiņi"),
        (ShortcutMenu, "Atvērt izvēlni (šis ESC nekad nenonāk līdz Mac)"),
        (ShortcutBack, "Atpakaļ uz sākuma ekrānu"),
        (ShortcutWinKey, "Windows taustiņš = Mac Command taustiņš"),
        (ShortcutOthers, "Visi pārējie taustiņi iet uz Mac. Tiek pārraidīta taustiņa pozīcija, nevis rakstzīme – garumzīmes, mīkstinājumi un AltGr darbojas paši."),
        // Benchmark
        (TabBenchmark, "Veiktspējas tests"),
        (BenchStart, "Sākt"),
        (BenchAbort, "Atcelt"),
        (BenchApply, "Lietot"),
        (BenchDuration, "Ilgums vienam solim"),
        (BenchTestPattern, "Testa attēls"),
        (BenchStep, "{n}. solis no {m}"),
        (BenchPhaseSettings, "iestatījumi tiek lietoti"),
        (BenchPhaseSettle, "stabilizācija"),
        (BenchPhaseMeasure, "mērīšana"),
        (BenchFailed, "neizdevās"),
        (BenchDone, "Pabeigts"),
        (BenchAborted, "Atcelts"),
        (BenchMeasured, "izmērīts"),
        (BenchChain, "Ķēde"),
        (BenchColFps, "fps"),
        (BenchColDropped, "izlaisti"),
        (BenchColHostCpu, "Hosta CPU"),
        (BenchRecommendation, "Ieteikums"),
        (BenchNoRecommendation, "Neviens solis neizturēja: ķēde virs 30 ms vai par maz kadru. Mēģiniet zemāku kadru ātrumu vai bitu ātrumu."),
        (BenchHint, "Mērīts tiek tas, kas šobrīd notiek Mac. Soļi ir salīdzināmi tikai tad, ja kaut kas kustas – pietiek ar atskaņotu video."),
        (BenchHintPattern, "Ar testa attēlu katrs solis redz vienu un to pašu kustīgo saturu – Mac nekam nav jādarbojas."),
        (TipBenchStart, "Pēc kārtas izmēra visas izvēlēto kodeku, kadru ātrumu un bitu ātrumu kombinācijas, katru iestatīto laiku. Attēls turpina darboties, un izvēlne var palikt atvērta."),
        (TipBenchApply, "Iestatīt ieteikto kodeku un iestatījumus un saglabāt tos šim hostam."),
        (TipBenchDuration, "Mērīšanas laiks vienam solim. Ilgāks ir stabilāks; 5 s parasti pietiek."),
        (TipBenchHint, "Solis iztur, ja pienāk vismaz 95 % no mērķa kadru ātruma, izlaisti ir mazāk nekā 1 % kadru un visa ķēde iekļaujas 30 ms – neatkarīgi no kadru ātruma. Hosta kodētāja laiks tiek rādīts, bet netiek vērtēts. Ieteicams: labākā krāsu kvalitāte, kas iztur pie augstākā kadru ātruma, ar augstāko bitu ātrumu."),
        (TipBenchTestPattern, "Testa laikā hosts ekrāna vietā rāda fiksētu kustīgu rakstu – katrs solis mēra vienu un to pašu saturu."),
        (DesktopShortcut, "Saīsne"),
        (TipDesktopShortcut, "Izveido darbvirsmā saīsni uz šo hostu. Dubultklikšķis uzreiz izveido savienojumu."),
        (DesktopShortcutCreated, "Saīsne izveidota darbvirsmā: {n}"),
        (DesktopShortcutFailed, "Saīsne netika izveidota: {n}"),
        (DesktopShortcutDescription, "QuadChroma: savienoties ar {n} ({m})"),
        (FilesSending, "Failu sūtīšana: {n} no {m}"),
        (FilesReceiving, "Failu saņemšana: {n} no {m}"),
        (FilesReady, "Faili gatavi ielīmēšanai: {n}"),
        (FilesSent, "Faili pārsūtīti: {n}"),
        (FilesAborted, "Failu pārsūtīšana pārtraukta: {n}"),
        (FilesTooLarge, "Faili netika pārsūtīti: vairāk nekā 4 GB vai 10 000 vienumu"),
        (FilesPeerOld, "Otra puse vēl nevar saņemt failus."),
        (TrayOpen, "Atvērt"),
        (TrayConnect, "Savienot: {n}"),
        (TrayQuit, "Iziet"),
        (TrayStillRunning, "QuadChroma turpina darboties paziņojumu apgabalā."),
        (TrayStillRunningMac, "QuadChroma turpina darboties izvēļņu joslā."),
        (FilesAbortLocal, "šajā ierīcē"),
        (FilesAbortPeer, "otrā pusē"),
        (FilesAbortConnection, "savienojums pārtrūka"),
        (FilesAbortTimeout, "noildze bez progresa"),
        (FilesAbortNoSpace, "nepietiek vietas diskā"),
        (FilesAbortInvalid, "nederīgi dati"),
        (FilesAbortRead, "lasīšanas kļūda"),
        (FilesAbortWrite, "rakstīšanas kļūda"),
        (FilesAbortClipboard, "starpliktuve nav pieejama"),
        (ScreenLabel, "Hosta ekrāns"),
        (ScreenAuto, "Automātiski"),
        (TipScreen, "Kuru hosta ekrānu tu redzi. Automātiski seko galvenajam ekrānam; fiksēts ekrāns ir spēkā, līdz izvēlies ko citu."),
        (ScreenSwitching, "Pārslēdz ekrānu …"),
        (ScreenFallback, "{n} nav pievienots – rezerve: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};

pub static LT: Lang = Lang {
    code: "lt",
    name: "Lietuvių",
    table: &[
        (AppSubtitle, "Nuotolinis darbalaukis su visa spalvų raiška"),
        (Connect, "Prisijungti"),
        (Disconnect, "Atsijungti"),
        (HostAddress, "Hosto adresas"),
        (SearchingHosts, "Ieškoma hostų"),
        (NoHostsFound, "Hostų nerasta"),
        (FoundHosts, "Rasti hostai"),
        (Settings, "Nustatymai"),
        (Language, "Kalba"),
        (Quit, "Išeiti"),
        (Connecting, "Jungiamasi"),
        (Connected, "Prisijungta"),
        (ConnectionLost, "Ryšys nutrūko"),
        (Reconnecting, "Jungiamasi iš naujo"),
        (Fullscreen, "Visas ekranas"),
        (PixelExact, "Pikselių tikslumas"),
        (Stretch, "Pritaikyti prie lango"),
        (ShowOverlay, "Rodyti statistiką"),
        (Fps, "Kadrai per sekundę"),
        (DecodeTime, "Dekodavimo laikas"),
        (Bitrate, "Bitų sparta"),
        (Resolution, "Skiriamoji geba"),
        (Codec, "Kodekas"),
        (Latency, "Delsa"),
        (EncodeTime, "Kodavimo laikas"),
        (NetworkTime, "Perdavimo laikas"),
        (AudioBuffer, "Garso buferis"),
        (Dropped, "Praleista"),
        (MaxBitrate, "Didžiausia bitų sparta"),
        (MaxFps, "Didžiausias kadrų dažnis"),
        (ExpertMode, "Eksperto režimas"),
        (GamingMode, "Žaidimų režimas"),
        (FixedRate, "Pastovus kadrų dažnis"),
        (FixedRateHint, "Išlaiko kadrų dažnį, net kai niekas nejuda. Nuolatinė hosto apkrova."),
        (Sound, "Garsas"),
        (HoldEscHint, "Laikykite ESC, kad atsidarytų meniu"),
        (NerdMode, "Nerdo režimas"),
        (More, "Daugiau"),
        (Back, "Atgal"),
        (SavedForHost, "Įrašyta šiam hostui"),
        (Queue, "Fiksavimas ir eilė"),
        (OneFrame, "Vienas kadras"),
        (Bottleneck, "Siauroji vieta"),
        (TabPicture, "Vaizdas"),
        (TabDisplay, "Ekranas"),
        (CodecConverted, "konvertuota"),
        (CodecSwitching, "Keičiamas kodekas"),
        (HostCpu, "Hosto procesorius"),
        (HostGpu, "Hosto grafika"),
        (HostRam, "Hosto atmintis"),
        (NoDisplay, "Hostas šiuo metu neturi ekrano"),
        (Encryption, "Šifravimas"),
        (EncryptionOn, "įjungtas"),
        (EncryptionOff, "išjungtas"),
        (AudioEnabled, "Garsas"),
        (ClipboardEnabled, "Iškarpinė"),
        (DecoderLabel, "Dekoderis"),
        (RoleAuto, "Automatinis"),
        (RoleCpu, "Procesorius"),
        (RoleGpu, "Vaizdo plokštė"),
        (RoleGpuN, "Vaizdo plokštė {n}"),
        (RoleIntegrated, "Integruota"),
        (NextStartHint, "galioja nuo kito paleidimo"),
        (AdapterWithOutput, "su ekrano išvestimi"),
        (AdapterNoOutput, "be ekrano išvesties"),
        (TipOnly420, "Tik 4:2:0 ir H.264 (D3D11VA); su 4:4:4 klientas grįžta prie procesoriaus – pakeiskite kodeką skirtuke Vaizdas."),
        (DisplayLabel, "Ekranas"),
        (DisplayStage, "Ekranas"),
        (ClientCpu, "Kliento procesorius"),
        (Monitor, "Monitorius"),
        (Skipped, "nerodyta"),
        (PairingTitle, "Susieti su hostu"),
        (PairingHint, "Įveskite hoste rodomą kodą"),
        (PairingCode, "Susiejimo kodas"),
        (PairingWrong, "Neteisingas kodas"),
        (PairingOk, "Susieta"),
        (SecuredWith, "Apsaugota · patvirtinimo kodas"),
        (HostFingerprint, "Hosto rakto atspaudas"),
        (NotPaired, "Šis hostas dar nepažįsta jūsų įrenginio. Paleiskite hostą su --pair ir prisijunkite iš naujo."),
        (FirstContact, "Pirmas kontaktas su šiuo hostu. Palyginkite kodą su rodomu hoste."),
        (ErrorConnectRefused, "Hostas atmetė ryšį"),
        (ErrorTimeout, "Hostas neatsakė"),
        (ErrorProtocol, "Kita pusė naudoja kitą protokolą"),
        (ErrorNoDecoder, "Šiam formatui nėra dekoderio"),
        (SessionTakenOver, "Seansą perėmė kitas įrenginys."),
        (HostKeyChanged, "Hosto {n} rakto atspaudas pasikeitė (dabar {m}). Ryšys atmestas. Jei hostas buvo įdiegtas iš naujo, ištrinkite jo eilutę faile {p}."),
        (KeyFileDamaged, "Rakto failas {p} sugadintas ir paliktas nepakeistas. Patikrinkite arba ištrinkite jį – tada bus sukurtas naujas raktas, o hostas turės iš naujo susieti šį įrenginį."),
        (FileUnreadable, "Failo {p} nepavyksta perskaityti – ryšys neužmezgamas."),
        (FileNotUtf8, "Failas {p} neįrašytas UTF-8 koduote – ryšys neužmezgamas."),
        (FileNotWritable, "Į failą {p} nepavyksta įrašyti – ryšys neužmezgamas."),
        (StorageUnavailable, "Raktų ir nustatymų aplankas nepasiekiamas – ryšys neužmezgamas."),
        (ErrorAddress, "Adreso {n} nepavyksta išspręsti"),
        (ErrorNoConnection, "Nėra ryšio su hostu"),
        (ErrorHandshake, "Nepavyko užmegzti saugaus ryšio"),
        (ErrorFfmpegStart, "Nepavyko paleisti FFmpeg"),
        (ErrorSound, "Garsas nepasiekiamas"),
        (ErrorGpuDisplay, "Vaizdo plokštė netinkama naudoti, vaizdas rodomas programiškai"),
        (ErrorGpuLost, "Vaizdo plokštė prarasta – paleiskite iš naujo su --anzeige cpu"),
        (ErrorPixelFormat, "Dekoderis pateikia vaizdus, kurių šis klientas negali parodyti"),
        (DecoderFallback, "Pasirinkta vaizdo plokštė nedekoduoja – veikia programinis dekoderis"),
        (TipBitrate, "Viršutinė bitų spartos riba. Judant koderis ją išnaudoja visą; svetimuose tinkluose geriau 25–50."),
        (TipFps, "Tikslinis kadrų dažnis. Daugiau, nei duoda Mac ekranas, neįmanoma."),
        (TipGaming, "Dažnesni raktiniai kadrai ir mažesnis leidžiamas atsilikimas: tolygiau judant, kainuoja šiek tiek bitų spartos."),
        (TipSound, "Perduoti garsą. Išjungus sutaupoma apie 3 Mbit/s; hostas tada garso nesiunčia."),
        (TipCodec, "Hosto kodekas, keičiamas darbo metu; vaizdas akimirkai sustoja. \"konvertuota\" kainuoja vieną papildomą žingsnį."),
        (TipFullscreen, "Visas ekranas be rėmelių. Lange vaizdas pritaikomas."),
        (TipPixelExact, "Vaizdas 1:1 be mastelio. Jei langas mažesnis, matoma tik dalis."),
        (TipShowOverlay, "Rodyti statistiką viršuje kairėje. Kurias eilutes – dešinėje."),
        (TipNerdMode, "Išplėsta statistika: delsos grandinė kaip juosta, hosto ir kliento apkrova."),
        (TipStatRows, "Kurias eilutes rodo statistika."),
        (TipDecoderAuto, "NVDEC NVIDIA plokštėje; kitaip D3D11VA plokštėje, kuri piešia (tik 4:2:0 ir H.264); kitaip procesorius."),
        (TipDecoderCpu, "Dekodavimas procesoriuje. Veikia visur, kainuoja skaičiavimo laiko."),
        (TipDecoderGpu, "Dekodavimas vaizdo plokštėje. Jei nepavyksta, klientas grįžta prie procesoriaus ir pasako, kodėl."),
        (TipDecoderIntegrated, "Dekodavimas integruotoje grafikoje (D3D11VA). Jei nepavyksta, klientas grįžta prie procesoriaus ir pasako, kodėl."),
        (TipDisplayAuto, "Direct3D 11 pirmoje plokštėje su ekrano išvestimi, kitaip pirmoje NVIDIA plokštėje, kitaip pirmoje, kokia yra. Be plokštės: procesorius. Galioja nuo kito paleidimo."),
        (TipDisplayGpu, "Piešimas su Direct3D 11 šioje plokštėje. Galioja nuo kito paleidimo."),
        (TipDisplayIntegrated, "Piešimas su Direct3D 11 integruotoje grafikoje – prie jos paprastai prijungtas ekranas. Galioja nuo kito paleidimo."),
        (TipDisplayCpu, "Piešimas procesoriuje, be Direct3D. Veikia visur, kainuoja skaičiavimo laiko. Galioja nuo kito paleidimo."),
        (TipDisconnect, "Baigti ryšį, grįžti į pradinį ekraną."),
        (TabShortcuts, "Spartieji klavišai"),
        (ShortcutMenu, "Atidaryti meniu (šis ESC niekada nepasiekia Mac)"),
        (ShortcutBack, "Grįžti į pradinį ekraną"),
        (ShortcutWinKey, "Windows klavišas = Mac Command klavišas"),
        (ShortcutOthers, "Visi kiti klavišai keliauja į Mac. Perduodama klavišo padėtis, o ne simbolis – lietuviškos raidės ir AltGr veikia savaime."),
        // Benchmark
        (TabBenchmark, "Našumo testas"),
        (BenchStart, "Pradėti"),
        (BenchAbort, "Atšaukti"),
        (BenchApply, "Taikyti"),
        (BenchDuration, "Trukmė vienam žingsniui"),
        (BenchTestPattern, "Bandomasis vaizdas"),
        (BenchStep, "Žingsnis {n} iš {m}"),
        (BenchPhaseSettings, "taikomi nustatymai"),
        (BenchPhaseSettle, "stabilizuojasi"),
        (BenchPhaseMeasure, "matuojama"),
        (BenchFailed, "nepavyko"),
        (BenchDone, "Baigta"),
        (BenchAborted, "Atšaukta"),
        (BenchMeasured, "išmatuota"),
        (BenchChain, "Grandinė"),
        (BenchColFps, "fps"),
        (BenchColDropped, "praleista"),
        (BenchColHostCpu, "Hosto CPU"),
        (BenchRecommendation, "Rekomendacija"),
        (BenchNoRecommendation, "Nė vienas žingsnis nepraėjo: grandinė viršija 30 ms arba per mažai kadrų. Pabandykite mažesnį kadrų dažnį arba bitų spartą."),
        (BenchHint, "Matuojama tai, kas dabar vyksta Mac. Žingsniai palyginami tik tada, kai kas nors juda – pakanka grojamo vaizdo įrašo."),
        (BenchHintPattern, "Su bandomuoju vaizdu kiekvienas žingsnis mato tą patį judantį turinį – Mac nieko nereikia paleisti."),
        (TipBenchStart, "Iš eilės išmatuoja visas pasirinktų kodekų, kadrų dažnių ir bitų spartų kombinacijas, kiekvieną nustatytą laiką. Vaizdas rodomas toliau, meniu gali likti atidarytas."),
        (TipBenchApply, "Nustatyti rekomenduojamą kodeką ir nustatymus ir įrašyti juos šiam hostui."),
        (TipBenchDuration, "Matavimo laikas vienam žingsniui. Ilgesnis stabilesnis; 5 s paprastai pakanka."),
        (TipBenchHint, "Žingsnis praeina, kai atkeliauja bent 95 % tikslinio kadrų dažnio, praleidžiama mažiau nei 1 % kadrų ir visa grandinė telpa į 30 ms – nepriklausomai nuo kadrų dažnio. Hosto koderio laikas rodomas, bet nevertinamas. Rekomenduojama: geriausia spalvų kokybė, kuri praeina esant didžiausiam kadrų dažniui, su didžiausia bitų sparta."),
        (TipBenchTestPattern, "Testo metu hostas vietoj ekrano rodo fiksuotą judantį raštą – kiekvienas žingsnis matuoja tą patį turinį."),
        (DesktopShortcut, "Nuoroda"),
        (TipDesktopShortcut, "Sukuria darbalaukyje nuorodą į šį hostą. Dukart spustelėjus iš karto prisijungiama."),
        (DesktopShortcutCreated, "Nuoroda sukurta darbalaukyje: {n}"),
        (DesktopShortcutFailed, "Nuoroda nesukurta: {n}"),
        (DesktopShortcutDescription, "QuadChroma: prisijungti prie {n} ({m})"),
        (FilesSending, "Siunčiami failai: {n} iš {m}"),
        (FilesReceiving, "Gaunami failai: {n} iš {m}"),
        (FilesReady, "Failai paruošti įklijuoti: {n}"),
        (FilesSent, "Failai perduoti: {n}"),
        (FilesAborted, "Failų perdavimas nutrauktas: {n}"),
        (FilesTooLarge, "Failai neperduoti: daugiau nei 4 GB arba 10 000 elementų"),
        (FilesPeerOld, "Kita pusė dar negali priimti failų."),
        (TrayOpen, "Atidaryti"),
        (TrayConnect, "Prisijungti: {n}"),
        (TrayQuit, "Išeiti"),
        (TrayStillRunning, "QuadChroma toliau veikia pranešimų srityje."),
        (TrayStillRunningMac, "QuadChroma toliau veikia meniu juostoje."),
        (FilesAbortLocal, "šiame įrenginyje"),
        (FilesAbortPeer, "kitoje pusėje"),
        (FilesAbortConnection, "ryšys nutrūko"),
        (FilesAbortTimeout, "baigėsi laikas be pažangos"),
        (FilesAbortNoSpace, "nepakanka vietos diske"),
        (FilesAbortInvalid, "neteisingi duomenys"),
        (FilesAbortRead, "skaitymo klaida"),
        (FilesAbortWrite, "rašymo klaida"),
        (FilesAbortClipboard, "iškarpinė nepasiekiama"),
        (ScreenLabel, "Hosto ekranas"),
        (ScreenAuto, "Automatiškai"),
        (TipScreen, "Kurį hosto ekraną matai. Automatiškai seka pagrindinį ekraną; fiksuotas ekranas galioja, kol pasirinksi ką nors kita."),
        (ScreenSwitching, "Keičiamas ekranas …"),
        (ScreenFallback, "{n} neprijungtas – atsarginis: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};

pub static SL: Lang = Lang {
    code: "sl",
    name: "Slovenščina",
    table: &[
        (AppSubtitle, "Oddaljeno namizje s polno barvno ločljivostjo"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini povezavo"),
        (HostAddress, "Naslov gostitelja"),
        (SearchingHosts, "Iskanje gostiteljev"),
        (NoHostsFound, "Ni najdenih gostiteljev"),
        (FoundHosts, "Najdeni gostitelji"),
        (Settings, "Nastavitve"),
        (Language, "Jezik"),
        (Quit, "Končaj"),
        (Connecting, "Povezovanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Povezava prekinjena"),
        (Reconnecting, "Ponovno povezovanje"),
        (Fullscreen, "Celozaslonsko"),
        (PixelExact, "Pikselna natančnost"),
        (Stretch, "Prilagodi oknu"),
        (ShowOverlay, "Prikaži statistiko"),
        (Fps, "Sličic na sekundo"),
        (DecodeTime, "Čas dekodiranja"),
        (Bitrate, "Bitna hitrost"),
        (Resolution, "Ločljivost"),
        (Codec, "Kodek"),
        (Latency, "Zakasnitev"),
        (EncodeTime, "Čas kodiranja"),
        (NetworkTime, "Čas prenosa"),
        (AudioBuffer, "Zvočni medpomnilnik"),
        (Dropped, "Izpuščene"),
        (MaxBitrate, "Največja bitna hitrost"),
        (MaxFps, "Največja hitrost sličic"),
        (ExpertMode, "Strokovni način"),
        (GamingMode, "Igralni način"),
        (FixedRate, "Stalna hitrost sličic"),
        (FixedRateHint, "Ohranja hitrost sličic tudi, ko se nič ne premika. Stalna obremenitev gostitelja."),
        (Sound, "Zvok"),
        (HoldEscHint, "Držite ESC za meni"),
        (NerdMode, "Nerdovski način"),
        (More, "Več"),
        (Back, "Nazaj"),
        (SavedForHost, "Shranjeno za tega gostitelja"),
        (Queue, "Zajem in čakanje"),
        (OneFrame, "Ena sličica"),
        (Bottleneck, "Ozko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbo"),
        (CodecSwitching, "Menjava kodeka"),
        (HostCpu, "Procesor gostitelja"),
        (HostGpu, "Grafika gostitelja"),
        (HostRam, "Pomnilnik gostitelja"),
        (NoDisplay, "Gostitelj trenutno nima zaslona"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "vklopljeno"),
        (EncryptionOff, "izklopljeno"),
        (AudioEnabled, "Zvok"),
        (ClipboardEnabled, "Odložišče"),
        (DecoderLabel, "Dekodirnik"),
        (RoleAuto, "Samodejno"),
        (RoleCpu, "Procesor"),
        (RoleGpu, "Grafična kartica"),
        (RoleGpuN, "Grafična kartica {n}"),
        (RoleIntegrated, "Vgrajena"),
        (NextStartHint, "velja od naslednjega zagona"),
        (AdapterWithOutput, "z izhodom za zaslon"),
        (AdapterNoOutput, "brez izhoda za zaslon"),
        (TipOnly420, "Samo 4:2:0 in H.264 (D3D11VA); pri 4:4:4 se odjemalec vrne na procesor – kodek zamenjajte na zavihku Slika."),
        (DisplayLabel, "Prikaz"),
        (DisplayStage, "Prikaz"),
        (ClientCpu, "Procesor odjemalca"),
        (Monitor, "Monitor"),
        (Skipped, "preskočene"),
        (PairingTitle, "Seznanitev z gostiteljem"),
        (PairingHint, "Vnesite kodo, prikazano na gostitelju"),
        (PairingCode, "Koda za seznanitev"),
        (PairingWrong, "Napačna koda"),
        (PairingOk, "Seznanjeno"),
        (SecuredWith, "Zavarovano · overitvena koda"),
        (HostFingerprint, "Prstni odtis gostitelja"),
        (NotPaired, "Ta gostitelj še ne pozna vaše naprave. Zaženite gostitelja z --pair in se znova povežite."),
        (FirstContact, "Prvi stik s tem gostiteljem. Primerjajte kodo s tisto na gostitelju."),
        (ErrorConnectRefused, "Gostitelj je zavrnil povezavo"),
        (ErrorTimeout, "Gostitelj se ni odzval"),
        (ErrorProtocol, "Nasprotna stran uporablja drug protokol"),
        (ErrorNoDecoder, "Za to obliko ni dekodirnika"),
        (SessionTakenOver, "Sejo je prevzela druga naprava."),
        (HostKeyChanged, "Prstni odtis gostitelja {n} se je spremenil (zdaj {m}). Povezava zavrnjena. Če je bil gostitelj na novo nameščen, izbrišite njegovo vrstico v {p}."),
        (KeyFileDamaged, "Datoteka s ključem {p} je poškodovana in je ostala nespremenjena. Preverite jo ali jo izbrišite – nato se ustvari nov ključ in gostitelj mora to napravo znova seznaniti."),
        (FileUnreadable, "Datoteke {p} ni mogoče prebrati – povezava ne bo vzpostavljena."),
        (FileNotUtf8, "Datoteka {p} ni shranjena kot UTF-8 – povezava ne bo vzpostavljena."),
        (FileNotWritable, "V datoteko {p} ni mogoče pisati – povezava ne bo vzpostavljena."),
        (StorageUnavailable, "Mapa za ključe in nastavitve ni na voljo – povezava ne bo vzpostavljena."),
        (ErrorAddress, "Naslova {n} ni mogoče razrešiti"),
        (ErrorNoConnection, "Ni povezave z gostiteljem"),
        (ErrorHandshake, "Zavarovane povezave ni bilo mogoče vzpostaviti"),
        (ErrorFfmpegStart, "FFmpeg ni bilo mogoče zagnati"),
        (ErrorSound, "Zvok ni na voljo"),
        (ErrorGpuDisplay, "Grafične kartice ni mogoče uporabiti, prikaz teče programsko"),
        (ErrorGpuLost, "Grafična kartica izgubljena – znova zaženite z --anzeige cpu"),
        (ErrorPixelFormat, "Dekodirnik daje slike, ki jih ta odjemalec ne more prikazati"),
        (DecoderFallback, "Izbrana grafična kartica ne dekodira – teče programski dekodirnik"),
        (TipBitrate, "Zgornja meja bitne hitrosti. Ob gibanju jo kodirnik izkoristi v celoti; v tujih omrežjih raje 25 do 50."),
        (TipFps, "Ciljna hitrost sličic. Več, kot daje zaslon Maca, ni mogoče."),
        (TipGaming, "Pogostejše ključne sličice in manj dovoljenega zaostanka: enakomerneje ob gibanju, stane nekaj bitne hitrosti."),
        (TipSound, "Prenašaj zvok. Izklopljeno prihrani okoli 3 Mbit/s; gostitelj takrat zvoka ne pošilja."),
        (TipCodec, "Kodek gostitelja, menjava med delovanjem; slika se za hip ustavi. \"s pretvorbo\" stane en prehod več."),
        (TipFullscreen, "Celozaslonsko brez robov. V oknu se slika prilagodi."),
        (TipPixelExact, "Slika 1:1 brez skaliranja. Če je okno manjše, vidite izrez."),
        (TipShowOverlay, "Prikaži statistiko zgoraj levo. Katere vrstice, nastavite desno."),
        (TipNerdMode, "Razširjena statistika: veriga zakasnitve kot stolpec, obremenitev gostitelja in odjemalca."),
        (TipStatRows, "Katere vrstice statistika prikazuje."),
        (TipDecoderAuto, "NVDEC na kartici NVIDIA; sicer D3D11VA na kartici, ki riše (samo 4:2:0 in H.264); sicer procesor."),
        (TipDecoderCpu, "Dekodiranje na procesorju. Deluje povsod, stane računski čas."),
        (TipDecoderGpu, "Dekodiranje na grafični kartici. Če ne gre, se odjemalec vrne na procesor in pove, zakaj."),
        (TipDecoderIntegrated, "Dekodiranje na vgrajeni grafiki (D3D11VA). Če ne gre, se odjemalec vrne na procesor in pove, zakaj."),
        (TipDisplayAuto, "Direct3D 11 na prvi kartici z izhodom za zaslon, sicer na prvi kartici NVIDIA, sicer na prvi, ki je. Brez kartice: procesor. Velja od naslednjega zagona."),
        (TipDisplayGpu, "Risanje z Direct3D 11 na tej kartici. Velja od naslednjega zagona."),
        (TipDisplayIntegrated, "Risanje z Direct3D 11 na vgrajeni grafiki – nanjo je navadno priključen zaslon. Velja od naslednjega zagona."),
        (TipDisplayCpu, "Risanje na procesorju, brez Direct3D. Deluje povsod, stane računski čas. Velja od naslednjega zagona."),
        (TipDisconnect, "Prekini povezavo, nazaj na začetni zaslon."),
        (TabShortcuts, "Bližnjice"),
        (ShortcutMenu, "Odpri meni (ta ESC nikoli ne pride do Maca)"),
        (ShortcutBack, "Nazaj na začetni zaslon"),
        (ShortcutWinKey, "Tipka Windows = tipka Command na Macu"),
        (ShortcutOthers, "Vse druge tipke gredo na Mac. Prenaša se položaj tipke, ne znak – šumniki in AltGr delujejo sami od sebe."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Zaženi"),
        (BenchAbort, "Prekliči"),
        (BenchApply, "Uporabi"),
        (BenchDuration, "Trajanje na korak"),
        (BenchTestPattern, "Preizkusna slika"),
        (BenchStep, "Korak {n} od {m}"),
        (BenchPhaseSettings, "nastavljanje"),
        (BenchPhaseSettle, "umirjanje"),
        (BenchPhaseMeasure, "merjenje"),
        (BenchFailed, "ni uspel"),
        (BenchDone, "Končano"),
        (BenchAborted, "Preklicano"),
        (BenchMeasured, "izmerjeno"),
        (BenchChain, "Veriga"),
        (BenchColFps, "fps"),
        (BenchColDropped, "izpuščene"),
        (BenchColHostCpu, "CPU gostitelja"),
        (BenchRecommendation, "Priporočilo"),
        (BenchNoRecommendation, "Noben korak ni uspel: veriga nad 30 ms ali premalo sličic. Poskusite nižjo hitrost sličic ali bitno hitrost."),
        (BenchHint, "Meri se to, kar se trenutno dogaja na Macu. Koraki so primerljivi le, ko se kaj premika – dovolj je predvajan video."),
        (BenchHintPattern, "S preizkusno sliko vsak korak vidi isto gibljivo vsebino – na Macu ni treba, da kaj teče."),
        (TipBenchStart, "Po vrsti izmeri vse kombinacije izbranih kodekov, hitrosti sličic in bitnih hitrosti, vsako za nastavljeni čas. Slika teče naprej, meni lahko ostane odprt."),
        (TipBenchApply, "Nastavi priporočeni kodek in nastavitve ter jih shrani za tega gostitelja."),
        (TipBenchDuration, "Čas merjenja na korak. Daljši je mirnejši; 5 s običajno zadostuje."),
        (TipBenchHint, "Korak uspe, če prispe vsaj 95 % ciljne hitrosti sličic, izpuščenih je manj kot 1 % sličic in celotna veriga ostane znotraj 30 ms – ne glede na hitrost sličic. Čas kodirnika gostitelja je prikazan, a se ne ocenjuje. Priporočeno: najboljša barvna kakovost, ki uspe pri najvišji hitrosti sličic, z najvišjo bitno hitrostjo."),
        (TipBenchTestPattern, "Med izvajanjem gostitelj namesto zaslona kaže stalen gibljiv vzorec – vsak korak meri isto vsebino."),
        (DesktopShortcut, "Ustvari bližnjico"),
        (TipDesktopShortcut, "Na namizju ustvari bližnjico do tega gostitelja. Dvoklik takoj vzpostavi povezavo."),
        (DesktopShortcutCreated, "Bližnjica ustvarjena na namizju: {n}"),
        (DesktopShortcutFailed, "Bližnjica ni bila ustvarjena: {n}"),
        (DesktopShortcutDescription, "QuadChroma: poveži se z {n} ({m})"),
        (FilesSending, "Pošiljanje datotek: {n} od {m}"),
        (FilesReceiving, "Prejemanje datotek: {n} od {m}"),
        (FilesReady, "Datoteke, pripravljene za lepljenje: {n}"),
        (FilesSent, "Datoteke prenesene: {n}"),
        (FilesAborted, "Prenos datotek je bil prekinjen: {n}"),
        (FilesTooLarge, "Datoteke niso bile prenesene: več kot 4 GB ali 10.000 elementov"),
        (FilesPeerOld, "Druga stran še ne more prejemati datotek."),
        (TrayOpen, "Odpri"),
        (TrayConnect, "Poveži: {n}"),
        (TrayQuit, "Končaj"),
        (TrayStillRunning, "QuadChroma še naprej teče v območju za obvestila."),
        (TrayStillRunningMac, "QuadChroma še naprej teče v menijski vrstici."),
        (FilesAbortLocal, "na tej napravi"),
        (FilesAbortPeer, "na drugi strani"),
        (FilesAbortConnection, "povezava prekinjena"),
        (FilesAbortTimeout, "časovna omejitev brez napredka"),
        (FilesAbortNoSpace, "premalo prostora na disku"),
        (FilesAbortInvalid, "neveljavni podatki"),
        (FilesAbortRead, "napaka pri branju"),
        (FilesAbortWrite, "napaka pri pisanju"),
        (FilesAbortClipboard, "odložišče ni na voljo"),
        (ScreenLabel, "Zaslon gostitelja"),
        (ScreenAuto, "Samodejno"),
        (TipScreen, "Kateri zaslon gostitelja vidiš. Samodejno sledi glavnemu zaslonu; stalni zaslon velja, dokler ne izbereš česa drugega."),
        (ScreenSwitching, "Menjava zaslona …"),
        (ScreenFallback, "{n} ni priključen – nadomestni: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};

pub static HR: Lang = Lang {
    code: "hr",
    name: "Hrvatski",
    table: &[
        (AppSubtitle, "Udaljena radna površina s punim detaljima boje"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini vezu"),
        (HostAddress, "Adresa hosta"),
        (SearchingHosts, "Traženje hostova"),
        (NoHostsFound, "Nema pronađenih hostova"),
        (FoundHosts, "Pronađeni hostovi"),
        (Settings, "Postavke"),
        (Language, "Jezik"),
        (Quit, "Izlaz"),
        (Connecting, "Povezivanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Veza prekinuta"),
        (Reconnecting, "Ponovno povezivanje"),
        (Fullscreen, "Cijeli zaslon"),
        (PixelExact, "Pikselna točnost"),
        (Stretch, "Prilagodi prozoru"),
        (ShowOverlay, "Prikaži statistiku"),
        (Fps, "Sličica u sekundi"),
        (DecodeTime, "Vrijeme dekodiranja"),
        (Bitrate, "Brzina prijenosa"),
        (Resolution, "Razlučivost"),
        (Codec, "Kodek"),
        (Latency, "Kašnjenje"),
        (EncodeTime, "Vrijeme kodiranja"),
        (NetworkTime, "Vrijeme prijenosa"),
        (AudioBuffer, "Međuspremnik zvuka"),
        (Dropped, "Ispušteno"),
        (MaxBitrate, "Najveća brzina prijenosa"),
        (MaxFps, "Najveći broj sličica"),
        (ExpertMode, "Stručni način"),
        (GamingMode, "Način za igre"),
        (FixedRate, "Stalan broj sličica"),
        (FixedRateHint, "Održava broj sličica i kad se ništa ne miče. Stalno opterećenje hosta."),
        (Sound, "Zvuk"),
        (HoldEscHint, "Držite ESC za izbornik"),
        (NerdMode, "Način za nerdove"),
        (More, "Više"),
        (Back, "Natrag"),
        (SavedForHost, "Spremljeno za ovaj host"),
        (Queue, "Snimanje i čekanje"),
        (OneFrame, "Jedna sličica"),
        (Bottleneck, "Usko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbom"),
        (CodecSwitching, "Promjena kodeka"),
        (HostCpu, "Procesor hosta"),
        (HostGpu, "Grafika hosta"),
        (HostRam, "Memorija hosta"),
        (NoDisplay, "Host trenutno nema zaslon"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "uključeno"),
        (EncryptionOff, "isključeno"),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Međuspremnik"),
        (DecoderLabel, "Dekoder"),
        (RoleAuto, "Automatski"),
        (RoleCpu, "Procesor"),
        (RoleGpu, "Grafička kartica"),
        (RoleGpuN, "Grafička kartica {n}"),
        (RoleIntegrated, "Integrirana"),
        (NextStartHint, "vrijedi od sljedećeg pokretanja"),
        (AdapterWithOutput, "s izlazom za zaslon"),
        (AdapterNoOutput, "bez izlaza za zaslon"),
        (TipOnly420, "Samo 4:2:0 i H.264 (D3D11VA); kod 4:4:4 klijent se vraća na procesor – promijenite kodek na kartici Slika."),
        (DisplayLabel, "Prikaz"),
        (DisplayStage, "Prikaz"),
        (ClientCpu, "Procesor klijenta"),
        (Monitor, "Monitor"),
        (Skipped, "preskočeno"),
        (PairingTitle, "Uparivanje s hostom"),
        (PairingHint, "Unesite kod prikazan na hostu"),
        (PairingCode, "Kod za uparivanje"),
        (PairingWrong, "Netočan kod"),
        (PairingOk, "Upareno"),
        (SecuredWith, "Zaštićeno · kod za provjeru"),
        (HostFingerprint, "Otisak ključa hosta"),
        (NotPaired, "Ovaj host još ne poznaje vaš uređaj. Pokrenite host s --pair i povežite se ponovno."),
        (FirstContact, "Prvi kontakt s ovim hostom. Usporedite kod s onim na hostu."),
        (ErrorConnectRefused, "Host je odbio vezu"),
        (ErrorTimeout, "Host nije odgovorio"),
        (ErrorProtocol, "Druga strana koristi drugi protokol"),
        (ErrorNoDecoder, "Nema dekodera za ovaj format"),
        (SessionTakenOver, "Sesiju je preuzeo drugi uređaj."),
        (HostKeyChanged, "Otisak ključa hosta {n} se promijenio (sada {m}). Veza odbijena. Ako je host ponovno instaliran, izbrišite njegov redak u {p}."),
        (KeyFileDamaged, "Datoteka ključa {p} je oštećena i ostavljena je nepromijenjena. Provjerite je ili izbrišite – tada nastaje novi ključ, a host mora ponovno upariti ovaj uređaj."),
        (FileUnreadable, "Datoteku {p} nije moguće pročitati – veza se ne uspostavlja."),
        (FileNotUtf8, "Datoteka {p} nije spremljena kao UTF-8 – veza se ne uspostavlja."),
        (FileNotWritable, "U datoteku {p} nije moguće pisati – veza se ne uspostavlja."),
        (StorageUnavailable, "Mapa za ključeve i postavke nije dostupna – veza se ne uspostavlja."),
        (ErrorAddress, "Adresu {n} nije moguće razriješiti"),
        (ErrorNoConnection, "Nema veze s hostom"),
        (ErrorHandshake, "Zaštićenu vezu nije bilo moguće uspostaviti"),
        (ErrorFfmpegStart, "FFmpeg nije bilo moguće pokrenuti"),
        (ErrorSound, "Zvuk nije dostupan"),
        (ErrorGpuDisplay, "Grafička kartica nije upotrebljiva, prikaz radi softverski"),
        (ErrorGpuLost, "Grafička kartica izgubljena – ponovno pokrenite s --anzeige cpu"),
        (ErrorPixelFormat, "Dekoder isporučuje slike koje ovaj klijent ne može prikazati"),
        (DecoderFallback, "Odabrana grafička kartica ne dekodira – radi softverski dekoder"),
        (TipBitrate, "Gornja granica brzine prijenosa. Pri pokretu enkoder je iskoristi u cijelosti; u tuđim mrežama radije 25 do 50."),
        (TipFps, "Ciljani broj sličica. Više nego što daje zaslon Maca nije moguće."),
        (TipGaming, "Češće ključne sličice i manje dopuštenog zaostatka: ujednačenije pri pokretu, košta nešto brzine prijenosa."),
        (TipSound, "Prenosi zvuk. Isključeno štedi oko 3 Mbit/s; host tada ne šalje zvuk."),
        (TipCodec, "Kodek hosta, mijenja se u radu; slika na trenutak stane. \"s pretvorbom\" košta jedan prolaz više."),
        (TipFullscreen, "Cijeli zaslon bez rubova. U prozoru se slika prilagođava."),
        (TipPixelExact, "Slika 1:1 bez skaliranja. Ako je prozor manji, vidi se isječak."),
        (TipShowOverlay, "Prikaži statistiku gore lijevo. Koji redci, odabire se desno."),
        (TipNerdMode, "Proširena statistika: lanac kašnjenja kao traka, opterećenje hosta i klijenta."),
        (TipStatRows, "Koje retke statistika prikazuje."),
        (TipDecoderAuto, "NVDEC na NVIDIA kartici; inače D3D11VA na kartici koja crta (samo 4:2:0 i H.264); inače procesor."),
        (TipDecoderCpu, "Dekodiranje na procesoru. Radi svugdje, košta računsko vrijeme."),
        (TipDecoderGpu, "Dekodiranje na grafičkoj kartici. Ako ne može, klijent se vraća na procesor i kaže zašto."),
        (TipDecoderIntegrated, "Dekodiranje na integriranoj grafici (D3D11VA). Ako ne može, klijent se vraća na procesor i kaže zašto."),
        (TipDisplayAuto, "Direct3D 11 na prvoj kartici s izlazom za zaslon, inače na prvoj NVIDIA kartici, inače na prvoj koja postoji. Bez kartice: procesor. Vrijedi od sljedećeg pokretanja."),
        (TipDisplayGpu, "Crtanje s Direct3D 11 na ovoj kartici. Vrijedi od sljedećeg pokretanja."),
        (TipDisplayIntegrated, "Crtanje s Direct3D 11 na integriranoj grafici – na nju je obično spojen zaslon. Vrijedi od sljedećeg pokretanja."),
        (TipDisplayCpu, "Crtanje na procesoru, bez Direct3D. Radi svugdje, košta računsko vrijeme. Vrijedi od sljedećeg pokretanja."),
        (TipDisconnect, "Prekini vezu, natrag na početni zaslon."),
        (TabShortcuts, "Prečaci"),
        (ShortcutMenu, "Otvori izbornik (ovaj ESC nikad ne stiže do Maca)"),
        (ShortcutBack, "Natrag na početni zaslon"),
        (ShortcutWinKey, "Tipka Windows = tipka Command na Macu"),
        (ShortcutOthers, "Sve ostale tipke idu na Mac. Prenosi se položaj tipke, ne znak – č, ć, š, ž i AltGr rade sami od sebe."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Pokreni"),
        (BenchAbort, "Odustani"),
        (BenchApply, "Primijeni"),
        (BenchDuration, "Trajanje po koraku"),
        (BenchTestPattern, "Testna slika"),
        (BenchStep, "Korak {n} od {m}"),
        (BenchPhaseSettings, "postavljanje"),
        (BenchPhaseSettle, "smirivanje"),
        (BenchPhaseMeasure, "mjerenje"),
        (BenchFailed, "neuspješan"),
        (BenchDone, "Gotovo"),
        (BenchAborted, "Prekinuto"),
        (BenchMeasured, "izmjereno"),
        (BenchChain, "Lanac"),
        (BenchColFps, "fps"),
        (BenchColDropped, "ispušteno"),
        (BenchColHostCpu, "CPU hosta"),
        (BenchRecommendation, "Preporuka"),
        (BenchNoRecommendation, "Nijedan korak nije prošao: lanac iznad 30 ms ili premalo sličica. Pokušajte s manjim brojem sličica ili nižom brzinom prijenosa."),
        (BenchHint, "Mjeri se ono što se trenutno događa na Macu. Koraci su usporedivi samo kad se nešto miče – dovoljan je video koji se reproducira."),
        (BenchHintPattern, "S testnom slikom svaki korak vidi isti pokretni sadržaj – na Macu ne mora ništa raditi."),
        (TipBenchStart, "Redom mjeri sve kombinacije odabranih kodeka, brojeva sličica i brzina prijenosa, svaku tijekom postavljenog vremena. Slika teče dalje, a izbornik može ostati otvoren."),
        (TipBenchApply, "Postavi preporučeni kodek i postavke te ih spremi za ovaj host."),
        (TipBenchDuration, "Vrijeme mjerenja po koraku. Dulje je stabilnije; 5 s obično je dovoljno."),
        (TipBenchHint, "Korak prolazi ako stigne barem 95 % ciljnog broja sličica, ispušteno je manje od 1 % sličica i cijeli lanac ostane unutar 30 ms – neovisno o broju sličica. Vrijeme enkodera hosta se prikazuje, ali ne ocjenjuje. Preporučeno: najbolja kvaliteta boje koja prolazi pri najvećem broju sličica, s najvećom brzinom prijenosa."),
        (TipBenchTestPattern, "Za vrijeme izvođenja host umjesto zaslona prikazuje fiksni pokretni uzorak – svaki korak mjeri isti sadržaj."),
        (DesktopShortcut, "Stvori prečac"),
        (TipDesktopShortcut, "Stvara na radnoj površini prečac do ovog hosta. Dvostrukim klikom odmah se povezuje."),
        (DesktopShortcutCreated, "Prečac stvoren na radnoj površini: {n}"),
        (DesktopShortcutFailed, "Prečac nije stvoren: {n}"),
        (DesktopShortcutDescription, "QuadChroma: poveži se s {n} ({m})"),
        (FilesSending, "Slanje datoteka: {n} od {m}"),
        (FilesReceiving, "Primanje datoteka: {n} od {m}"),
        (FilesReady, "Datoteke spremne za lijepljenje: {n}"),
        (FilesSent, "Datoteke prenesene: {n}"),
        (FilesAborted, "Prijenos datoteka prekinut: {n}"),
        (FilesTooLarge, "Datoteke nisu prenesene: više od 4 GB ili 10.000 stavki"),
        (FilesPeerOld, "Druga strana još ne može primati datoteke."),
        (TrayOpen, "Otvori"),
        (TrayConnect, "Poveži: {n}"),
        (TrayQuit, "Izlaz"),
        (TrayStillRunning, "QuadChroma i dalje radi u području obavijesti."),
        (TrayStillRunningMac, "QuadChroma i dalje radi u traci izbornika."),
        (FilesAbortLocal, "na ovom uređaju"),
        (FilesAbortPeer, "na drugoj strani"),
        (FilesAbortConnection, "veza prekinuta"),
        (FilesAbortTimeout, "isteklo vrijeme bez napretka"),
        (FilesAbortNoSpace, "nedovoljno prostora na disku"),
        (FilesAbortInvalid, "nevaljani podaci"),
        (FilesAbortRead, "pogreška čitanja"),
        (FilesAbortWrite, "pogreška pisanja"),
        (FilesAbortClipboard, "međuspremnik nije dostupan"),
        (ScreenLabel, "Zaslon hosta"),
        (ScreenAuto, "Automatski"),
        (TipScreen, "Koji zaslon hosta vidiš. Automatski prati glavni zaslon; fiksni zaslon vrijedi dok ne odabereš nešto drugo."),
        (ScreenSwitching, "Promjena zaslona …"),
        (ScreenFallback, "{n} nije priključen – zamjenski: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};

pub static UK: Lang = Lang {
    code: "uk",
    name: "Українська",
    table: &[
        (AppSubtitle, "Віддалений робочий стіл з повною деталізацією кольору"),
        (Connect, "Підключитися"),
        (Disconnect, "Відключитися"),
        (HostAddress, "Адреса хоста"),
        (SearchingHosts, "Пошук хостів"),
        (NoHostsFound, "Хостів не знайдено"),
        (FoundHosts, "Знайдені хости"),
        (Settings, "Налаштування"),
        (Language, "Мова"),
        (Quit, "Вийти"),
        (Connecting, "Підключення"),
        (Connected, "Підключено"),
        (ConnectionLost, "З'єднання втрачено"),
        (Reconnecting, "Повторне підключення"),
        (Fullscreen, "Повний екран"),
        (PixelExact, "Піксельна точність"),
        (Stretch, "Вписати у вікно"),
        (ShowOverlay, "Показати статистику"),
        (Fps, "Кадрів за секунду"),
        (DecodeTime, "Час декодування"),
        (Bitrate, "Бітрейт"),
        (Resolution, "Роздільність"),
        (Codec, "Кодек"),
        (Latency, "Затримка"),
        (EncodeTime, "Час кодування"),
        (NetworkTime, "Час передачі"),
        (AudioBuffer, "Буфер звуку"),
        (Dropped, "Пропущено"),
        (MaxBitrate, "Максимальний бітрейт"),
        (MaxFps, "Максимальна частота кадрів"),
        (ExpertMode, "Режим експерта"),
        (GamingMode, "Ігровий режим"),
        (FixedRate, "Стала частота кадрів"),
        (FixedRateHint, "Утримує частоту кадрів, навіть коли нічого не рухається. Постійне навантаження на хост."),
        (Sound, "Звук"),
        (HoldEscHint, "Утримуйте ESC для меню"),
        (NerdMode, "Режим нерда"),
        (More, "Більше"),
        (Back, "Назад"),
        (SavedForHost, "Збережено для цього хоста"),
        (Queue, "Захоплення і черга"),
        (OneFrame, "Один кадр"),
        (Bottleneck, "Вузьке місце"),
        (TabPicture, "Зображення"),
        (TabDisplay, "Екран"),
        (CodecConverted, "з перетворенням"),
        (CodecSwitching, "Зміна кодека"),
        (HostCpu, "Процесор хоста"),
        (HostGpu, "Графіка хоста"),
        (HostRam, "Пам'ять хоста"),
        (NoDisplay, "У хоста зараз немає екрана"),
        (Encryption, "Шифрування"),
        (EncryptionOn, "увімкнено"),
        (EncryptionOff, "вимкнено"),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Буфер обміну"),
        (DecoderLabel, "Декодер"),
        (RoleAuto, "Автоматично"),
        (RoleCpu, "Процесор"),
        (RoleGpu, "Відеокарта"),
        (RoleGpuN, "Відеокарта {n}"),
        (RoleIntegrated, "Вбудована"),
        (NextStartHint, "діє з наступного запуску"),
        (AdapterWithOutput, "з виходом на екран"),
        (AdapterNoOutput, "без виходу на екран"),
        (TipOnly420, "Лише 4:2:0 і H.264 (D3D11VA); при 4:4:4 клієнт повертається до процесора – змініть кодек на вкладці Зображення."),
        (DisplayLabel, "Екран"),
        (DisplayStage, "Екран"),
        (ClientCpu, "Процесор клієнта"),
        (Monitor, "Монітор"),
        (Skipped, "не показано"),
        (PairingTitle, "Створення пари з хостом"),
        (PairingHint, "Введіть код, показаний на хості"),
        (PairingCode, "Код підключення"),
        (PairingWrong, "Неправильний код"),
        (PairingOk, "Пару створено"),
        (SecuredWith, "Захищено · код підтвердження"),
        (HostFingerprint, "Відбиток ключа хоста"),
        (NotPaired, "Цей хост ще не знає вашого пристрою. Запустіть хост із --pair і підключіться знову."),
        (FirstContact, "Перший контакт із цим хостом. Порівняйте код із тим, що на хості."),
        (ErrorConnectRefused, "Хост відхилив з'єднання"),
        (ErrorTimeout, "Хост не відповів"),
        (ErrorProtocol, "Інша сторона використовує інший протокол"),
        (ErrorNoDecoder, "Немає декодера для цього формату"),
        (SessionTakenOver, "Сеанс перейшов до іншого пристрою."),
        (HostKeyChanged, "Відбиток ключа хоста {n} змінився (тепер {m}). З'єднання відхилено. Якщо хост було встановлено заново, видаліть його рядок у {p}."),
        (KeyFileDamaged, "Файл ключа {p} пошкоджено, його залишено без змін. Перевірте або видаліть його – тоді буде створено новий ключ, і хосту доведеться знову створити пару з цим пристроєм."),
        (FileUnreadable, "Не вдається прочитати {p} – з'єднання не встановлюється."),
        (FileNotUtf8, "{p} збережено не в UTF-8 – з'єднання не встановлюється."),
        (FileNotWritable, "Не вдається записати {p} – з'єднання не встановлюється."),
        (StorageUnavailable, "Тека для ключів і налаштувань недоступна – з'єднання не встановлюється."),
        (ErrorAddress, "Не вдається розпізнати адресу {n}"),
        (ErrorNoConnection, "Немає з'єднання з хостом"),
        (ErrorHandshake, "Не вдалося встановити захищене з'єднання"),
        (ErrorFfmpegStart, "Не вдалося запустити FFmpeg"),
        (ErrorSound, "Звук недоступний"),
        (ErrorGpuDisplay, "Відеокарта непридатна, відображення працює програмно"),
        (ErrorGpuLost, "Відеокарту втрачено – перезапустіть із --anzeige cpu"),
        (ErrorPixelFormat, "Декодер видає зображення, які цей клієнт не може показати"),
        (DecoderFallback, "Вибрана відеокарта не декодує – працює програмний декодер"),
        (TipBitrate, "Верхня межа бітрейту. Під час руху кодер використовує її повністю; в чужих мережах краще 25–50."),
        (TipFps, "Цільова частота кадрів. Більше, ніж дає екран Mac, не вийде."),
        (TipGaming, "Частіші ключові кадри й менше допустиме відставання: рівніше під час руху, коштує трохи бітрейту."),
        (TipSound, "Передавати звук. Вимкнено заощаджує близько 3 Мбіт/с; хост тоді звук не надсилає."),
        (TipCodec, "Кодек хоста, перемикається на ходу; зображення на мить завмирає. \"з перетворенням\" коштує один додатковий прохід."),
        (TipFullscreen, "Повний екран без рамки. У вікні зображення вписується."),
        (TipPixelExact, "Зображення 1:1 без масштабування. Якщо вікно менше, видно лише частину."),
        (TipShowOverlay, "Показувати статистику вгорі ліворуч. Які рядки – праворуч."),
        (TipNerdMode, "Розширена статистика: ланцюжок затримки як смуга, навантаження хоста і клієнта."),
        (TipStatRows, "Які рядки показує статистика."),
        (TipDecoderAuto, "NVDEC на карті NVIDIA; інакше D3D11VA на карті, яка малює (лише 4:2:0 і H.264); інакше процесор."),
        (TipDecoderCpu, "Декодування на процесорі. Працює всюди, коштує процесорного часу."),
        (TipDecoderGpu, "Декодування на відеокарті. Якщо не вдається, клієнт повертається до процесора і каже чому."),
        (TipDecoderIntegrated, "Декодування на вбудованій графіці (D3D11VA). Якщо не вдається, клієнт повертається до процесора і каже чому."),
        (TipDisplayAuto, "Direct3D 11 на першій карті з виходом на екран, інакше на першій карті NVIDIA, інакше на першій, яка є. Без карти: процесор. Діє з наступного запуску."),
        (TipDisplayGpu, "Малювання через Direct3D 11 на цій карті. Діє з наступного запуску."),
        (TipDisplayIntegrated, "Малювання через Direct3D 11 на вбудованій графіці – до неї зазвичай підключено екран. Діє з наступного запуску."),
        (TipDisplayCpu, "Малювання на процесорі, без Direct3D. Працює всюди, коштує процесорного часу. Діє з наступного запуску."),
        (TipDisconnect, "Завершити з'єднання, назад до початкового екрана."),
        (TabShortcuts, "Клавіші"),
        (ShortcutMenu, "Відкрити меню (цей ESC ніколи не доходить до Mac)"),
        (ShortcutBack, "Назад до початкового екрана"),
        (ShortcutWinKey, "Клавіша Windows = клавіша Command на Mac"),
        (ShortcutOthers, "Усі інші клавіші йдуть на Mac. Передається положення клавіші, а не символ – кирилиця та AltGr працюють самі собою."),
        // Benchmark
        (TabBenchmark, "Бенчмарк"),
        (BenchStart, "Старт"),
        (BenchAbort, "Скасувати"),
        (BenchApply, "Застосувати"),
        (BenchDuration, "Тривалість кроку"),
        (BenchTestPattern, "Тестове зображення"),
        (BenchStep, "Крок {n} з {m}"),
        (BenchPhaseSettings, "застосування налаштувань"),
        (BenchPhaseSettle, "стабілізація"),
        (BenchPhaseMeasure, "вимірювання"),
        (BenchFailed, "невдалий"),
        (BenchDone, "Готово"),
        (BenchAborted, "Скасовано"),
        (BenchMeasured, "виміряно"),
        (BenchChain, "Ланцюжок"),
        (BenchColFps, "fps"),
        (BenchColDropped, "пропущено"),
        (BenchColHostCpu, "CPU хоста"),
        (BenchRecommendation, "Рекомендація"),
        (BenchNoRecommendation, "Жоден крок не пройшов: ланцюжок понад 30 ms або замало кадрів. Спробуйте нижчу частоту кадрів або бітрейт."),
        (BenchHint, "Вимірюється те, що зараз відбувається на Mac. Кроки можна порівнювати лише тоді, коли щось рухається – достатньо відео, що відтворюється."),
        (BenchHintPattern, "З тестовим зображенням кожен крок бачить той самий рухомий вміст – на Mac нічого не має працювати."),
        (TipBenchStart, "По черзі вимірює всі комбінації вибраних кодеків, частот кадрів і бітрейтів, кожну протягом заданого часу. Зображення йде далі, меню може лишатися відкритим."),
        (TipBenchApply, "Установити рекомендований кодек і налаштування та зберегти їх для цього хоста."),
        (TipBenchDuration, "Час вимірювання на крок. Довше – стабільніше; 5 с зазвичай достатньо."),
        (TipBenchHint, "Крок проходить, якщо надходить щонайменше 95 % цільової частоти кадрів, пропущено менше ніж 1 % кадрів і весь ланцюжок вкладається в 30 ms – незалежно від частоти кадрів. Час кодера хоста показується, але не оцінюється. Рекомендується: найкраща якість кольору, яка проходить на найвищій частоті кадрів, із найвищим бітрейтом."),
        (TipBenchTestPattern, "На час вимірювання хост показує замість екрана фіксований рухомий візерунок – кожен крок вимірює той самий вміст."),
        (DesktopShortcut, "Ярлик"),
        (TipDesktopShortcut, "Створює на робочому столі ярлик до цього хоста. Подвійне клацання одразу підключає."),
        (DesktopShortcutCreated, "Ярлик створено на робочому столі: {n}"),
        (DesktopShortcutFailed, "Ярлик не створено: {n}"),
        (DesktopShortcutDescription, "QuadChroma: підключитися до {n} ({m})"),
        (FilesSending, "Надсилання файлів: {n} з {m}"),
        (FilesReceiving, "Отримання файлів: {n} з {m}"),
        (FilesReady, "Файли готові до вставлення: {n}"),
        (FilesSent, "Файли передано: {n}"),
        (FilesAborted, "Передавання файлів перервано: {n}"),
        (FilesTooLarge, "Файли не передано: понад 4 GB або 10 000 елементів"),
        (FilesPeerOld, "Інша сторона ще не може отримувати файли."),
        (TrayOpen, "Відкрити"),
        (TrayConnect, "Підключитися: {n}"),
        (TrayQuit, "Вийти"),
        (TrayStillRunning, "QuadChroma і далі працює в області сповіщень."),
        (TrayStillRunningMac, "QuadChroma і далі працює в рядку меню."),
        (FilesAbortLocal, "цим пристроєм"),
        (FilesAbortPeer, "іншою стороною"),
        (FilesAbortConnection, "з'єднання перервано"),
        (FilesAbortTimeout, "час очікування вичерпано без поступу"),
        (FilesAbortNoSpace, "недостатньо місця на диску"),
        (FilesAbortInvalid, "недійсні дані"),
        (FilesAbortRead, "помилка читання"),
        (FilesAbortWrite, "помилка запису"),
        (FilesAbortClipboard, "буфер обміну недоступний"),
        (ScreenLabel, "Екран хоста"),
        (ScreenAuto, "Автоматично"),
        (TipScreen, "Який екран хоста ти бачиш. Автоматично слідує за головним екраном; фіксований екран діє, доки ти не обереш щось інше."),
        (ScreenSwitching, "Зміна екрана …"),
        (ScreenFallback, "{n} не підключено – запасний: {m}"),
        // Zugang: vorerst englisch - Paket P6 uebersetzt.
        (AccessTitle, "Password for {n}"),
        (AccessText, "{n} does not know this device yet. Enter the password shown in the QuadChroma menu on {n}."),
        (AccessOrAllow, "Or ask someone at {n} to click \"Allow\"."),
        (AccessCode, "Code: {c}"),
        (AccessPassword, "Password"),
        (AccessShow, "Show"),
        (AccessCancel, "Cancel"),
        (AccessChecking, "Checking ..."),
        (AccessWrong, "Wrong password."),
        (AccessWait, "Too many attempts. Try again in {s} s."),
        (AccessNewIdentity, "The device at this address has a new identity (ID {i})."),
        (MsgRefused, "{n} refused the connection."),
        (MsgNoAnswer, "No answer from {n}. Please try again."),
        (MsgTooManyAttempts, "Too many attempts. Please wait a moment and try again."),
        (MsgHostOutdated, "{n} uses an older QuadChroma version. Please update it there."),
        (MsgHostProofBad, "{n} could not confirm the password. The connection was stopped for safety."),
        (MsgOtherDevice, "A different device answers at this address."),
        (MsgIdNotFound, "No device with ID {i} found in the network."),
        (StartId, "ID {i}"),
        (StartShare, "Share this PC"),
        (StartSharing, "Sharing is on"),
        (HostReady, "Ready for connections"),
        (HostConnected, "Connected: {n}"),
        (HostDeviceId, "Device ID: {i}"),
        (HostPassword, "Password: {p}"),
        (HostCopied, "Copied"),
        (HostChangePassword, "Change password ..."),
        (HostRandomPassword, "New random password"),
        (HostNewPassword, "New password (at least 8 characters)"),
        (HostRepeatPassword, "Repeat password"),
        (HostPasswordsDiffer, "The passwords do not match."),
        (HostPasswordShort, "At least 8 characters, please."),
        (HostPasswordSaved, "Password saved."),
        (HostPasswordUnreadable, "Password file unreadable - new devices only via \"Allow\"."),
        (HostDevices, "Allowed devices"),
        (HostNoDevices, "No devices yet"),
        (HostDeviceLine, "{n} - ID {i} - since {d}"),
        (HostRemove, "Remove"),
        (HostRemoveAll, "Remove all devices ..."),
        (HostRemoveAllAsk, "Remove all allowed devices? They will need the password again."),
        (HostListDamaged, "Device list damaged"),
        (HostListReset, "Reset device list"),
        (HostRequest, "{n} (ID {i}) wants to control this computer."),
        (HostAllow, "Allow"),
        (HostDeny, "Deny"),
        (HostStartLogin, "Start at login"),
        (HostStartWindows, "Start with Windows"),
        (HostMoveToApps, "Move QuadChroma to Applications first"),
        (HostScreenMissing, "Screen Recording not allowed - open System Settings ..."),
        (HostAccessMissing, "Accessibility not allowed - open System Settings ..."),
        (HostPortBusy, "Port {p} is used by another program"),
        (HostQuit, "Quit QuadChroma"),
        (HostStopSharing, "Stop sharing"),
        (HostTooltip, "QuadChroma - sharing this PC (ID {i})"),
        (HostOk, "OK"),
    ],
};
