// Westeuropaeische Sprachen: Franzoesisch, Spanisch, Italienisch,
// Portugiesisch (Portugal) und Niederlaendisch.
//
// Ein Eintrag je Schluessel aus strings.rs, gleiche Reihenfolge wie dort.

use crate::strings::{Key::*, Lang};

pub static FR: Lang = Lang {
    code: "fr",
    name: "Français",
    table: &[
        (AppSubtitle, "Bureau à distance sans perte de couleur"),
        (Connect, "Se connecter"),
        (Disconnect, "Se déconnecter"),
        (HostAddress, "Adresse de l'hôte"),
        (SearchingHosts, "Recherche d'hôtes"),
        (NoHostsFound, "Aucun hôte trouvé"),
        (FoundHosts, "Hôtes trouvés"),
        (Settings, "Paramètres"),
        (Language, "Langue"),
        (Quit, "Quitter"),
        (Connecting, "Connexion en cours"),
        (Connected, "Connecté"),
        (ConnectionLost, "Connexion perdue"),
        (Reconnecting, "Reconnexion"),
        (Fullscreen, "Plein écran"),
        (PixelExact, "Pixel par pixel"),
        (Stretch, "Ajuster à la fenêtre"),
        (ShowOverlay, "Afficher les statistiques"),
        (Fps, "Images par seconde"),
        (DecodeTime, "Temps de décodage"),
        (Bitrate, "Débit"),
        (Resolution, "Résolution"),
        (Codec, "Codec"),
        (Latency, "Latence"),
        (EncodeTime, "Encodage"),
        (NetworkTime, "Réseau"),
        (AudioBuffer, "Tampon audio"),
        (Dropped, "Images perdues"),
        (MaxBitrate, "Débit maximal"),
        (MaxFps, "Fréquence d'images max"),
        (ExpertMode, "Mode expert"),
        (GamingMode, "Mode jeu"),
        (FixedRate, "Fréquence d'images fixe"),
        (FixedRateHint, "Maintient la fréquence même quand rien ne bouge. Charge permanente sur l'hôte."),
        (Sound, "Son"),
        (HoldEscHint, "Maintenez ESC pour le menu"),
        (NerdMode, "Mode geek"),
        (More, "Plus"),
        (Back, "Retour"),
        (SavedForHost, "Enregistré pour cet hôte"),
        (Queue, "Capture & attente"),
        (OneFrame, "Une image"),
        (Bottleneck, "Goulot d'étranglement"),
        (TabPicture, "Image"),
        (TabDisplay, "Affichage"),
        (CodecConverted, "converti"),
        (CodecSwitching, "Changement de codec"),
        (HostCpu, "CPU de l'hôte"),
        (HostGpu, "GPU de l'hôte"),
        (HostRam, "Mémoire de l'hôte"),
        (NoDisplay, "L'hôte n'a pas d'écran pour le moment"),
        (Encryption, "Chiffrement"),
        (EncryptionOn, "activé"),
        (EncryptionOff, "désactivé"),
        (AudioEnabled, "Son"),
        (ClipboardEnabled, "Presse-papiers"),
        (DecoderLabel, "Décodeur"),
        (RoleAuto, "Automatique"),
        (RoleCpu, "Processeur"),
        (RoleGpu, "Carte graphique"),
        (RoleGpuN, "Carte graphique {n}"),
        (RoleIntegrated, "Intégrée"),
        (NextStartHint, "prend effet au prochain démarrage"),
        (AdapterWithOutput, "avec sortie écran"),
        (AdapterNoOutput, "sans sortie écran"),
        (TipOnly420, "Seulement 4:2:0 et H.264 (D3D11VA) ; en 4:4:4, le client repasse sur le processeur – changer le codec dans l'onglet Image."),
        (DisplayLabel, "Affichage"),
        (DisplayStage, "Affichage"),
        (ClientCpu, "CPU du client"),
        (Monitor, "Moniteur"),
        (Skipped, "sautées"),
        (PairingTitle, "Associer à l'hôte"),
        (PairingHint, "Saisissez le code affiché sur l'hôte"),
        (PairingCode, "Code d'association"),
        (PairingWrong, "Code incorrect"),
        (PairingOk, "Associé"),
        (SecuredWith, "Sécurisé · code de vérification"),
        (HostFingerprint, "Empreinte de l'hôte"),
        (NotPaired, "Cet hôte ne connaît pas encore votre appareil. Démarrez l'hôte avec --pair et reconnectez-vous."),
        (FirstContact, "Premier contact avec cet hôte. Comparez le code avec celui affiché sur l'hôte."),
        (ErrorConnectRefused, "L'hôte a refusé la connexion"),
        (ErrorTimeout, "L'hôte ne répond pas"),
        (ErrorProtocol, "L'autre poste utilise un autre protocole"),
        (ErrorNoDecoder, "Aucun décodeur pour ce format"),
        (SessionTakenOver, "Un autre appareil a repris la session."),
        (HostKeyChanged, "L'empreinte de l'hôte {n} a changé (désormais {m}). Connexion refusée. Si l'hôte a été réinstallé, supprimez sa ligne dans {p}."),
        (KeyFileDamaged, "Le fichier de clé {p} est endommagé et a été laissé tel quel. Vérifiez-le ou supprimez-le – une nouvelle clé sera alors créée, et l'hôte devra de nouveau associer cet appareil."),
        (FileUnreadable, "Impossible de lire {p} – pas de connexion."),
        (FileNotUtf8, "{p} n'est pas enregistré en UTF-8 – pas de connexion."),
        (FileNotWritable, "Impossible d'écrire dans {p} – pas de connexion."),
        (StorageUnavailable, "Le dossier des clés et des paramètres n'est pas disponible – pas de connexion."),
        (ErrorAddress, "Impossible de résoudre l'adresse {n}"),
        (ErrorNoConnection, "Pas de connexion à l'hôte"),
        (ErrorHandshake, "La connexion sécurisée n'a pas pu être établie"),
        (ErrorFfmpegStart, "Impossible de démarrer FFmpeg"),
        (ErrorSound, "Son indisponible"),
        (ErrorGpuDisplay, "Carte graphique inutilisable, affichage en mode logiciel"),
        (ErrorGpuLost, "Carte graphique perdue – veuillez redémarrer avec --anzeige cpu"),
        (ErrorPixelFormat, "Le décodeur fournit des images que ce client ne peut pas afficher"),
        (DecoderFallback, "La carte graphique choisie ne décode pas – le décodeur logiciel prend le relais"),
        (TipBitrate, "Limite supérieure du débit. L'encodeur l'utilise entièrement dès que ça bouge ; sur un réseau qui n'est pas le vôtre, préférez 25 à 50."),
        (TipFps, "Fréquence d'images visée. Impossible d'aller au-delà de ce que fournit l'écran du Mac."),
        (TipGaming, "Images clés plus fréquentes et moins de retard toléré : plus régulier quand ça bouge, coûte un peu de débit."),
        (TipSound, "Transmettre le son. Désactivé, économise environ 3 Mbit/s ; l'hôte n'envoie alors aucun son."),
        (TipCodec, "Codec de l'hôte, changé à chaud ; l'image se fige un instant. « converti » coûte une passe de plus."),
        (TipFullscreen, "Plein écran sans bordure. En fenêtre, l'image est ajustée."),
        (TipPixelExact, "Image 1:1 sans mise à l'échelle. Si la fenêtre est plus petite, seule une partie est visible."),
        (TipShowOverlay, "Afficher les statistiques en haut à gauche. Le choix des lignes se fait à droite."),
        (TipNerdMode, "Statistiques étendues : chaîne de latence en barre, charge de l'hôte et du client."),
        (TipStatRows, "Lignes affichées dans les statistiques."),
        (TipDecoderAuto, "NVDEC sur une carte NVIDIA ; sinon D3D11VA sur la carte qui dessine (seulement 4:2:0 et H.264) ; sinon le processeur."),
        (TipDecoderCpu, "Décodage sur le processeur. Fonctionne partout, coûte du temps de calcul."),
        (TipDecoderGpu, "Décodage sur la carte graphique. Si elle n'y arrive pas, le client repasse sur le processeur et en indique la raison."),
        (TipDecoderIntegrated, "Décodage sur la carte graphique intégrée (D3D11VA). Si elle n'y arrive pas, le client repasse sur le processeur et en indique la raison."),
        (TipDisplayAuto, "Direct3D 11 sur la première carte avec sortie écran, sinon la première carte NVIDIA, sinon la première trouvée. Sans carte : le processeur. Prend effet au prochain démarrage."),
        (TipDisplayGpu, "Dessiner avec Direct3D 11 sur cette carte. Prend effet au prochain démarrage."),
        (TipDisplayIntegrated, "Dessiner avec Direct3D 11 sur la carte graphique intégrée – celle à laquelle l'écran est généralement branché. Prend effet au prochain démarrage."),
        (TipDisplayCpu, "Dessiner sur le processeur, sans Direct3D. Fonctionne partout, coûte du temps de calcul. Prend effet au prochain démarrage."),
        (TipDisconnect, "Terminer la connexion, retour à l'écran d'accueil."),
        (TabShortcuts, "Raccourcis"),
        (ShortcutMenu, "Ouvrir le menu (cet ESC n'atteint jamais le Mac)"),
        (ShortcutBack, "Retour à l'écran d'accueil"),
        (ShortcutWinKey, "Touche Windows = touche Commande du Mac"),
        (ShortcutOthers, "Toutes les autres touches vont au Mac. C'est la position de la touche qui est transmise, pas le caractère – accents et AltGr fonctionnent d'eux-mêmes."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Démarrer"),
        (BenchAbort, "Annuler"),
        (BenchApply, "Appliquer"),
        (BenchDuration, "Durée par étape"),
        (BenchTestPattern, "Mire"),
        (BenchStep, "Étape {n} sur {m}"),
        (BenchPhaseSettings, "réglages en cours"),
        (BenchPhaseSettle, "stabilisation"),
        (BenchPhaseMeasure, "mesure"),
        (BenchFailed, "échec"),
        (BenchDone, "Terminé"),
        (BenchAborted, "Annulé"),
        (BenchMeasured, "mesuré"),
        (BenchChain, "Chaîne"),
        (BenchColFps, "ips"),
        (BenchColDropped, "perdues"),
        (BenchColHostCpu, "CPU hôte"),
        (BenchRecommendation, "Recommandation"),
        (BenchNoRecommendation, "Aucune étape n'a réussi : chaîne au-delà de 30 ms ou trop peu d'images. Essayez des fréquences d'images ou des débits plus bas."),
        (BenchHint, "La mesure reflète ce qui se passe sur le Mac en ce moment. Les étapes ne sont comparables que si quelque chose bouge – une vidéo en lecture suffit."),
        (BenchHintPattern, "Avec la mire, chaque étape voit le même contenu animé – rien n'a besoin de tourner sur le Mac."),
        (TipBenchStart, "Mesure tour à tour toutes les combinaisons des codecs, fréquences d'images et débits choisis, chacune pendant la durée réglée. L'image continue et le menu peut rester ouvert."),
        (TipBenchApply, "Régler le codec et les paramètres recommandés et les enregistrer pour cet hôte."),
        (TipBenchDuration, "Temps de mesure par étape. Plus long est plus stable ; 5 s suffisent en général."),
        (TipBenchHint, "Une étape réussit si au moins 95 % de la fréquence d'images cible arrivent, si moins de 1 % des images sont perdues et si toute la chaîne reste sous 30 ms – quelle que soit la fréquence d'images. Le temps d'encodage de l'hôte est affiché mais pas évalué. Recommandé : la meilleure qualité de couleur qui réussit à la fréquence d'images la plus élevée, au débit le plus élevé."),
        (TipBenchTestPattern, "Pendant toute la durée du test, l'hôte affiche un motif animé fixe à la place de l'écran – chaque étape mesure le même contenu."),
    ],
};

pub static ES: Lang = Lang {
    code: "es",
    name: "Español",
    table: &[
        (AppSubtitle, "Escritorio remoto sin pérdida de color"),
        (Connect, "Conectar"),
        (Disconnect, "Desconectar"),
        (HostAddress, "Dirección del host"),
        (SearchingHosts, "Buscando hosts"),
        (NoHostsFound, "No se encontraron hosts"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Ajustes"),
        (Language, "Idioma"),
        (Quit, "Salir"),
        (Connecting, "Conectando"),
        (Connected, "Conectado"),
        (ConnectionLost, "Conexión perdida"),
        (Reconnecting, "Reconectando"),
        (Fullscreen, "Pantalla completa"),
        (PixelExact, "Píxel a píxel"),
        (Stretch, "Ajustar a la ventana"),
        (ShowOverlay, "Mostrar estadísticas"),
        (Fps, "Fotogramas por segundo"),
        (DecodeTime, "Decodificación"),
        (Bitrate, "Tasa de bits"),
        (Resolution, "Resolución"),
        (Codec, "Códec"),
        (Latency, "Latencia"),
        (EncodeTime, "Codificación"),
        (NetworkTime, "Red"),
        (AudioBuffer, "Búfer de audio"),
        (Dropped, "Fotogramas perdidos"),
        (MaxBitrate, "Tasa de bits máxima"),
        (MaxFps, "Tasa de fotogramas máxima"),
        (ExpertMode, "Modo experto"),
        (GamingMode, "Modo juego"),
        (FixedRate, "Tasa de fotogramas fija"),
        (FixedRateHint, "Mantiene la tasa aunque no se mueva nada. Carga permanente en el host."),
        (Sound, "Sonido"),
        (HoldEscHint, "Mantén ESC para el menú"),
        (NerdMode, "Modo nerd"),
        (More, "Más"),
        (Back, "Atrás"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura y espera"),
        (OneFrame, "Un fotograma"),
        (Bottleneck, "Cuello de botella"),
        (TabPicture, "Imagen"),
        (TabDisplay, "Pantalla"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "Cambiando de códec"),
        (HostCpu, "CPU del host"),
        (HostGpu, "GPU del host"),
        (HostRam, "Memoria del host"),
        (NoDisplay, "El host no tiene pantalla en este momento"),
        (Encryption, "Cifrado"),
        (EncryptionOn, "activado"),
        (EncryptionOff, "desactivado"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Portapapeles"),
        (DecoderLabel, "Decodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Procesador"),
        (RoleGpu, "Tarjeta gráfica"),
        (RoleGpuN, "Tarjeta gráfica {n}"),
        (RoleIntegrated, "Integrada"),
        (NextStartHint, "se aplica desde el próximo inicio"),
        (AdapterWithOutput, "con salida de pantalla"),
        (AdapterNoOutput, "sin salida de pantalla"),
        (TipOnly420, "Solo 4:2:0 y H.264 (D3D11VA); con 4:4:4 el cliente vuelve al procesador – cambiar el códec en la pestaña Imagen."),
        (DisplayLabel, "Pantalla"),
        (DisplayStage, "Pantalla"),
        (ClientCpu, "CPU del cliente"),
        (Monitor, "Monitor"),
        (Skipped, "omitidos"),
        (PairingTitle, "Emparejar con el host"),
        (PairingHint, "Introduce el código que aparece en el host"),
        (PairingCode, "Código de emparejamiento"),
        (PairingWrong, "Código incorrecto"),
        (PairingOk, "Emparejado"),
        (SecuredWith, "Protegido · código de verificación"),
        (HostFingerprint, "Huella del host"),
        (NotPaired, "Este host aún no conoce tu dispositivo. Inicia el host con --pair y vuelve a conectar."),
        (FirstContact, "Primer contacto con este host. Compara el código con el que aparece en el host."),
        (ErrorConnectRefused, "El host rechazó la conexión"),
        (ErrorTimeout, "El host no responde"),
        (ErrorProtocol, "El otro extremo usa otro protocolo"),
        (ErrorNoDecoder, "No hay decodificador para este formato"),
        (SessionTakenOver, "Otro dispositivo ha tomado el control de la sesión."),
        (HostKeyChanged, "La huella del host {n} ha cambiado (ahora {m}). Conexión rechazada. Si el host se ha reinstalado, borra su línea en {p}."),
        (KeyFileDamaged, "El archivo de clave {p} está dañado y se ha dejado tal cual. Revísalo o bórralo – entonces se crea una clave nueva y el host tendrá que volver a emparejar este dispositivo."),
        (FileUnreadable, "No se puede leer {p} – no se conectará."),
        (FileNotUtf8, "{p} no está guardado en UTF-8 – no se conectará."),
        (FileNotWritable, "No se puede escribir en {p} – no se conectará."),
        (StorageUnavailable, "La carpeta de claves y ajustes no está disponible – no se conectará."),
        (ErrorAddress, "No se puede resolver la dirección {n}"),
        (ErrorNoConnection, "Sin conexión con el host"),
        (ErrorHandshake, "No se pudo establecer la conexión segura"),
        (ErrorFfmpegStart, "No se pudo iniciar FFmpeg"),
        (ErrorSound, "El sonido no está disponible"),
        (ErrorGpuDisplay, "Tarjeta gráfica inutilizable, la imagen se muestra por software"),
        (ErrorGpuLost, "Tarjeta gráfica perdida – reinicia con --anzeige cpu"),
        (ErrorPixelFormat, "El decodificador entrega imágenes que este cliente no puede mostrar"),
        (DecoderFallback, "La tarjeta gráfica elegida no decodifica – se usa el decodificador por software"),
        (TipBitrate, "Límite superior de la tasa de bits. Con movimiento el codificador la usa entera; en redes ajenas, mejor entre 25 y 50."),
        (TipFps, "Tasa de fotogramas objetivo. No puede superar lo que entrega la pantalla del Mac."),
        (TipGaming, "Fotogramas clave más frecuentes y menos retraso permitido: más estable con movimiento, cuesta algo de tasa de bits."),
        (TipSound, "Transmitir el sonido. Desactivado ahorra unos 3 Mbit/s; el host entonces no envía sonido."),
        (TipCodec, "Códec del host, se cambia en marcha; la imagen se detiene un momento. \"convertido\" cuesta una pasada más."),
        (TipFullscreen, "Pantalla completa sin bordes. En ventana, la imagen se ajusta."),
        (TipPixelExact, "Imagen 1:1 sin escalar. Si la ventana es más pequeña, se ve un recorte."),
        (TipShowOverlay, "Mostrar las estadísticas arriba a la izquierda. Qué filas, a la derecha."),
        (TipNerdMode, "Estadísticas ampliadas: cadena de latencia como barra, carga del host y del cliente."),
        (TipStatRows, "Qué filas muestran las estadísticas."),
        (TipDecoderAuto, "NVDEC en una tarjeta NVIDIA; si no, D3D11VA en la tarjeta que dibuja (solo 4:2:0 y H.264); si no, el procesador."),
        (TipDecoderCpu, "Decodificar en el procesador. Funciona en todas partes, cuesta tiempo de CPU."),
        (TipDecoderGpu, "Decodificar en la tarjeta gráfica. Si no puede, el cliente vuelve al procesador y dice por qué."),
        (TipDecoderIntegrated, "Decodificar en la gráfica integrada (D3D11VA). Si no puede, el cliente vuelve al procesador y dice por qué."),
        (TipDisplayAuto, "Direct3D 11 en la primera tarjeta con salida de pantalla; si no, la primera NVIDIA; si no, la primera que haya. Sin tarjeta: el procesador. Se aplica desde el próximo inicio."),
        (TipDisplayGpu, "Dibujar con Direct3D 11 en esta tarjeta. Se aplica desde el próximo inicio."),
        (TipDisplayIntegrated, "Dibujar con Direct3D 11 en la gráfica integrada – a la que suele estar conectada la pantalla. Se aplica desde el próximo inicio."),
        (TipDisplayCpu, "Dibujar en el procesador, sin Direct3D. Funciona en todas partes, cuesta tiempo de CPU. Se aplica desde el próximo inicio."),
        (TipDisconnect, "Terminar la conexión, volver a la pantalla de inicio."),
        (TabShortcuts, "Atajos"),
        (ShortcutMenu, "Abrir el menú (este ESC nunca llega al Mac)"),
        (ShortcutBack, "Volver a la pantalla de inicio"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando del Mac"),
        (ShortcutOthers, "Todas las demás teclas van al Mac. Se transmite la posición de la tecla, no el carácter: acentos y AltGr funcionan por sí solos."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duración por paso"),
        (BenchTestPattern, "Patrón de prueba"),
        (BenchStep, "Paso {n} de {m}"),
        (BenchPhaseSettings, "aplicando ajustes"),
        (BenchPhaseSettle, "estabilizando"),
        (BenchPhaseMeasure, "midiendo"),
        (BenchFailed, "fallido"),
        (BenchDone, "Terminado"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidos"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendación"),
        (BenchNoRecommendation, "Ningún paso ha pasado: cadena por encima de 30 ms o muy pocos fotogramas. Prueba tasas de fotogramas o de bits más bajas."),
        (BenchHint, "Se mide lo que ocurre en el Mac ahora mismo. Los pasos solo son comparables si algo se mueve: basta con un vídeo en reproducción."),
        (BenchHintPattern, "Con el patrón de prueba, cada paso ve el mismo contenido en movimiento: no hace falta que nada corra en el Mac."),
        (TipBenchStart, "Mide una tras otra todas las combinaciones de los códecs, tasas de fotogramas y tasas de bits elegidos, cada una durante el tiempo fijado. La imagen sigue en marcha y el menú puede quedar abierto."),
        (TipBenchApply, "Aplicar el códec y los ajustes recomendados y guardarlos para este host."),
        (TipBenchDuration, "Tiempo de medición por paso. Más largo es más estable; 5 s suelen bastar."),
        (TipBenchHint, "Un paso pasa si llega al menos el 95 % de la tasa de fotogramas objetivo, se pierde menos del 1 % de los fotogramas y toda la cadena se mantiene dentro de 30 ms, sea cual sea la tasa de fotogramas. El tiempo del codificador del host se muestra, pero no se evalúa. Recomendado: la mejor calidad de color que pasa a la tasa de fotogramas más alta, con la tasa de bits más alta."),
        (TipBenchTestPattern, "Durante la prueba, el host muestra un patrón fijo en movimiento en lugar de la pantalla: cada paso mide el mismo contenido."),
    ],
};

pub static IT: Lang = Lang {
    code: "it",
    name: "Italiano",
    table: &[
        (AppSubtitle, "Desktop remoto senza perdita di colore"),
        (Connect, "Connetti"),
        (Disconnect, "Disconnetti"),
        (HostAddress, "Indirizzo dell'host"),
        (SearchingHosts, "Ricerca host"),
        (NoHostsFound, "Nessun host trovato"),
        (FoundHosts, "Host trovati"),
        (Settings, "Impostazioni"),
        (Language, "Lingua"),
        (Quit, "Esci"),
        (Connecting, "Connessione in corso"),
        (Connected, "Connesso"),
        (ConnectionLost, "Connessione persa"),
        (Reconnecting, "Riconnessione"),
        (Fullscreen, "Schermo intero"),
        (PixelExact, "Pixel per pixel"),
        (Stretch, "Adatta alla finestra"),
        (ShowOverlay, "Mostra statistiche"),
        (Fps, "Fotogrammi al secondo"),
        (DecodeTime, "Tempo di decodifica"),
        (Bitrate, "Bitrate"),
        (Resolution, "Risoluzione"),
        (Codec, "Codec"),
        (Latency, "Latenza"),
        (EncodeTime, "Codifica"),
        (NetworkTime, "Rete"),
        (AudioBuffer, "Buffer audio"),
        (Dropped, "Fotogrammi persi"),
        (MaxBitrate, "Bitrate massimo"),
        (MaxFps, "Frequenza massima"),
        (ExpertMode, "Modalità esperto"),
        (GamingMode, "Modalità gioco"),
        (FixedRate, "Frequenza fissa"),
        (FixedRateHint, "Mantiene la frequenza anche quando nulla si muove. Carico continuo sull'host."),
        (Sound, "Audio"),
        (HoldEscHint, "Tieni premuto ESC per il menu"),
        (NerdMode, "Modalità nerd"),
        (More, "Altro"),
        (Back, "Indietro"),
        (SavedForHost, "Salvato per questo host"),
        (Queue, "Cattura e attesa"),
        (OneFrame, "Un fotogramma"),
        (Bottleneck, "Collo di bottiglia"),
        (TabPicture, "Immagine"),
        (TabDisplay, "Schermo"),
        (CodecConverted, "convertito"),
        (CodecSwitching, "Cambio codec in corso"),
        (HostCpu, "CPU dell'host"),
        (HostGpu, "GPU dell'host"),
        (HostRam, "Memoria dell'host"),
        (NoDisplay, "L'host al momento non ha uno schermo"),
        (Encryption, "Crittografia"),
        (EncryptionOn, "attivata"),
        (EncryptionOff, "disattivata"),
        (AudioEnabled, "Audio"),
        (ClipboardEnabled, "Appunti"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatico"),
        (RoleCpu, "Processore"),
        (RoleGpu, "Scheda grafica"),
        (RoleGpuN, "Scheda grafica {n}"),
        (RoleIntegrated, "Integrata"),
        (NextStartHint, "vale dal prossimo avvio"),
        (AdapterWithOutput, "con uscita video"),
        (AdapterNoOutput, "senza uscita video"),
        (TipOnly420, "Solo 4:2:0 e H.264 (D3D11VA); con 4:4:4 il client torna al processore – cambiare il codec nella scheda Immagine."),
        (DisplayLabel, "Schermo"),
        (DisplayStage, "Schermo"),
        (ClientCpu, "CPU del client"),
        (Monitor, "Monitor"),
        (Skipped, "saltati"),
        (PairingTitle, "Associa all'host"),
        (PairingHint, "Inserisci il codice mostrato sull'host"),
        (PairingCode, "Codice di associazione"),
        (PairingWrong, "Codice errato"),
        (PairingOk, "Associato"),
        (SecuredWith, "Protetto · codice di verifica"),
        (HostFingerprint, "Impronta dell'host"),
        (NotPaired, "Questo host non conosce ancora il tuo dispositivo. Avvia l'host con --pair e riconnettiti."),
        (FirstContact, "Primo contatto con questo host. Confronta il codice con quello mostrato sull'host."),
        (ErrorConnectRefused, "L'host ha rifiutato la connessione"),
        (ErrorTimeout, "L'host non risponde"),
        (ErrorProtocol, "La controparte usa un altro protocollo"),
        (ErrorNoDecoder, "Nessun decoder per questo formato"),
        (SessionTakenOver, "Un altro dispositivo ha preso il controllo della sessione."),
        (HostKeyChanged, "L'impronta dell'host {n} è cambiata (ora {m}). Connessione rifiutata. Se l'host è stato reinstallato, elimina la sua riga in {p}."),
        (KeyFileDamaged, "Il file della chiave {p} è danneggiato ed è stato lasciato com'è. Controllalo o eliminalo – verrà creata una nuova chiave e l'host dovrà associare di nuovo questo dispositivo."),
        (FileUnreadable, "Impossibile leggere {p} – nessuna connessione."),
        (FileNotUtf8, "{p} non è salvato in UTF-8 – nessuna connessione."),
        (FileNotWritable, "Impossibile scrivere {p} – nessuna connessione."),
        (StorageUnavailable, "La cartella per chiavi e impostazioni non è disponibile – nessuna connessione."),
        (ErrorAddress, "Impossibile risolvere l'indirizzo {n}"),
        (ErrorNoConnection, "Nessuna connessione all'host"),
        (ErrorHandshake, "Impossibile stabilire la connessione sicura"),
        (ErrorFfmpegStart, "Impossibile avviare FFmpeg"),
        (ErrorSound, "Audio non disponibile"),
        (ErrorGpuDisplay, "Scheda grafica non utilizzabile, visualizzazione via software"),
        (ErrorGpuLost, "Scheda grafica persa – riavvia con --anzeige cpu"),
        (ErrorPixelFormat, "Il decoder fornisce immagini che questo client non può visualizzare"),
        (DecoderFallback, "La scheda grafica scelta non decodifica – è in uso il decoder software"),
        (TipBitrate, "Limite superiore del bitrate. Con il movimento l'encoder lo usa tutto; su reti non tue meglio da 25 a 50."),
        (TipFps, "Frequenza fotogrammi desiderata. Non può superare quella dello schermo del Mac."),
        (TipGaming, "Keyframe più frequenti e meno arretrato consentito: più fluido con il movimento, costa un po' di bitrate."),
        (TipSound, "Trasmettere l'audio. Spento risparmia circa 3 Mbit/s; l'host allora non invia audio."),
        (TipCodec, "Codec dell'host, cambiato al volo; l'immagine si ferma un attimo. \"convertito\" costa un passaggio in più."),
        (TipFullscreen, "Schermo intero senza bordi. In finestra l'immagine viene adattata."),
        (TipPixelExact, "Immagine 1:1 senza ridimensionamento. Se la finestra è più piccola, si vede solo una parte."),
        (TipShowOverlay, "Mostra le statistiche in alto a sinistra. Quali righe, a destra."),
        (TipNerdMode, "Statistiche estese: catena di latenza come barra, carico di host e client."),
        (TipStatRows, "Quali righe mostrano le statistiche."),
        (TipDecoderAuto, "NVDEC su una scheda NVIDIA; altrimenti D3D11VA sulla scheda che disegna (solo 4:2:0 e H.264); altrimenti il processore."),
        (TipDecoderCpu, "Decodifica sul processore. Funziona ovunque, costa tempo di calcolo."),
        (TipDecoderGpu, "Decodifica sulla scheda grafica. Se non ci riesce, il client torna al processore e spiega perché."),
        (TipDecoderIntegrated, "Decodifica sulla grafica integrata (D3D11VA). Se non ci riesce, il client torna al processore e spiega perché."),
        (TipDisplayAuto, "Direct3D 11 sulla prima scheda con uscita video, altrimenti la prima NVIDIA, altrimenti la prima che c'è. Senza scheda: il processore. Vale dal prossimo avvio."),
        (TipDisplayGpu, "Disegnare con Direct3D 11 su questa scheda. Vale dal prossimo avvio."),
        (TipDisplayIntegrated, "Disegnare con Direct3D 11 sulla grafica integrata – quella a cui di solito è collegato lo schermo. Vale dal prossimo avvio."),
        (TipDisplayCpu, "Disegnare sul processore, senza Direct3D. Funziona ovunque, costa tempo di calcolo. Vale dal prossimo avvio."),
        (TipDisconnect, "Chiudere la connessione, tornare alla schermata iniziale."),
        (TabShortcuts, "Scorciatoie"),
        (ShortcutMenu, "Apri il menu (questo ESC non arriva mai al Mac)"),
        (ShortcutBack, "Torna alla schermata iniziale"),
        (ShortcutWinKey, "Tasto Windows = tasto Comando del Mac"),
        (ShortcutOthers, "Tutti gli altri tasti vanno al Mac. Viene trasmessa la posizione del tasto, non il carattere: accenti e AltGr funzionano da soli."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Avvia"),
        (BenchAbort, "Annulla"),
        (BenchApply, "Applica"),
        (BenchDuration, "Durata per passo"),
        (BenchTestPattern, "Immagine di test"),
        (BenchStep, "Passo {n} di {m}"),
        (BenchPhaseSettings, "impostazioni in corso"),
        (BenchPhaseSettle, "assestamento"),
        (BenchPhaseMeasure, "misurazione"),
        (BenchFailed, "fallito"),
        (BenchDone, "Finito"),
        (BenchAborted, "Annullato"),
        (BenchMeasured, "misurato"),
        (BenchChain, "Catena"),
        (BenchColFps, "fps"),
        (BenchColDropped, "persi"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Raccomandazione"),
        (BenchNoRecommendation, "Nessun passo superato: catena oltre 30 ms o troppo pochi fotogrammi. Prova frequenze fotogrammi o bitrate più bassi."),
        (BenchHint, "Si misura ciò che accade sul Mac in questo momento. I passi sono confrontabili solo se qualcosa si muove: basta un video in riproduzione."),
        (BenchHintPattern, "Con l'immagine di test ogni passo vede lo stesso contenuto in movimento: sul Mac non deve girare nulla."),
        (TipBenchStart, "Misura una dopo l'altra tutte le combinazioni di codec, frequenze fotogrammi e bitrate scelti, ciascuna per la durata impostata. L'immagine continua e il menu può restare aperto."),
        (TipBenchApply, "Impostare codec e impostazioni consigliati e salvarli per questo host."),
        (TipBenchDuration, "Tempo di misura per passo. Più lungo è più stabile; 5 s di solito bastano."),
        (TipBenchHint, "Un passo è superato se arriva almeno il 95 % della frequenza fotogrammi obiettivo, meno dell'1 % dei fotogrammi viene perso e l'intera catena resta entro 30 ms, indipendentemente dalla frequenza fotogrammi. Il tempo dell'encoder dell'host viene mostrato ma non valutato. Consigliata: la migliore qualità colore che supera alla frequenza fotogrammi più alta, con il bitrate più alto."),
        (TipBenchTestPattern, "Per la durata del test l'host mostra un motivo fisso in movimento al posto dello schermo: ogni passo misura lo stesso contenuto."),
    ],
};

pub static PT: Lang = Lang {
    code: "pt",
    name: "Português",
    table: &[
        (AppSubtitle, "Acesso remoto sem perda de cor"),
        (Connect, "Ligar"),
        (Disconnect, "Terminar ligação"),
        (HostAddress, "Endereço do host"),
        (SearchingHosts, "A procurar hosts"),
        (NoHostsFound, "Nenhum host encontrado"),
        (FoundHosts, "Hosts encontrados"),
        (Settings, "Definições"),
        (Language, "Idioma"),
        (Quit, "Sair"),
        (Connecting, "A ligar"),
        (Connected, "Ligado"),
        (ConnectionLost, "Ligação perdida"),
        (Reconnecting, "A ligar novamente"),
        (Fullscreen, "Ecrã inteiro"),
        (PixelExact, "Pixel a pixel"),
        (Stretch, "Ajustar à janela"),
        (ShowOverlay, "Mostrar estatísticas"),
        (Fps, "Imagens por segundo"),
        (DecodeTime, "Descodificação"),
        (Bitrate, "Taxa de bits"),
        (Resolution, "Resolução"),
        (Codec, "Codec"),
        (Latency, "Latência"),
        (EncodeTime, "Codificação"),
        (NetworkTime, "Rede"),
        (AudioBuffer, "Buffer de áudio"),
        (Dropped, "Imagens perdidas"),
        (MaxBitrate, "Taxa de bits máxima"),
        (MaxFps, "Taxa de imagens máxima"),
        (ExpertMode, "Modo avançado"),
        (GamingMode, "Modo de jogo"),
        (FixedRate, "Taxa de imagens fixa"),
        (FixedRateHint, "Mantém a taxa mesmo quando nada se move. Carga permanente no host."),
        (Sound, "Som"),
        (HoldEscHint, "Mantenha ESC para o menu"),
        (NerdMode, "Modo nerd"),
        (More, "Mais"),
        (Back, "Voltar"),
        (SavedForHost, "Guardado para este host"),
        (Queue, "Captura e espera"),
        (OneFrame, "Uma imagem"),
        (Bottleneck, "Estrangulamento"),
        (TabPicture, "Imagem"),
        (TabDisplay, "Ecrã"),
        (CodecConverted, "convertido"),
        (CodecSwitching, "A mudar de codec"),
        (HostCpu, "CPU do host"),
        (HostGpu, "GPU do host"),
        (HostRam, "Memória do host"),
        (NoDisplay, "O host não tem ecrã neste momento"),
        (Encryption, "Encriptação"),
        (EncryptionOn, "ativada"),
        (EncryptionOff, "desativada"),
        (AudioEnabled, "Áudio"),
        (ClipboardEnabled, "Área de transferência"),
        (DecoderLabel, "Descodificador"),
        (RoleAuto, "Automático"),
        (RoleCpu, "Processador"),
        (RoleGpu, "Placa gráfica"),
        (RoleGpuN, "Placa gráfica {n}"),
        (RoleIntegrated, "Integrada"),
        (NextStartHint, "aplica-se a partir do próximo arranque"),
        (AdapterWithOutput, "com saída de ecrã"),
        (AdapterNoOutput, "sem saída de ecrã"),
        (TipOnly420, "Só 4:2:0 e H.264 (D3D11VA); com 4:4:4 o cliente recorre ao processador – mudar o codec no separador Imagem."),
        (DisplayLabel, "Ecrã"),
        (DisplayStage, "Ecrã"),
        (ClientCpu, "CPU do cliente"),
        (Monitor, "Monitor"),
        (Skipped, "saltadas"),
        (PairingTitle, "Emparelhar com o host"),
        (PairingHint, "Introduza o código mostrado no host"),
        (PairingCode, "Código de emparelhamento"),
        (PairingWrong, "Código incorreto"),
        (PairingOk, "Emparelhado"),
        (SecuredWith, "Protegido · código de verificação"),
        (HostFingerprint, "Impressão digital do host"),
        (NotPaired, "Este host ainda não conhece o seu dispositivo. Inicie o host com --pair e ligue novamente."),
        (FirstContact, "Primeiro contacto com este host. Compare o código com o que aparece no host."),
        (ErrorConnectRefused, "O host recusou a ligação"),
        (ErrorTimeout, "O host não responde"),
        (ErrorProtocol, "O outro lado usa outro protocolo"),
        (ErrorNoDecoder, "Sem descodificador para este formato"),
        (SessionTakenOver, "Outro dispositivo assumiu a sessão."),
        (HostKeyChanged, "A impressão digital do host {n} mudou (agora {m}). Ligação recusada. Se o host foi reinstalado, apague a linha dele em {p}."),
        (KeyFileDamaged, "O ficheiro de chave {p} está danificado e foi deixado como está. Verifique-o ou apague-o – é então criada uma chave nova, e o host terá de emparelhar este dispositivo novamente."),
        (FileUnreadable, "Não é possível ler {p} – não é feita a ligação."),
        (FileNotUtf8, "{p} não está guardado em UTF-8 – não é feita a ligação."),
        (FileNotWritable, "Não é possível escrever em {p} – não é feita a ligação."),
        (StorageUnavailable, "A pasta para chaves e definições não está disponível – não é feita a ligação."),
        (ErrorAddress, "Não é possível resolver o endereço {n}"),
        (ErrorNoConnection, "Sem ligação ao host"),
        (ErrorHandshake, "Não foi possível estabelecer a ligação segura"),
        (ErrorFfmpegStart, "Não foi possível iniciar o FFmpeg"),
        (ErrorSound, "Som indisponível"),
        (ErrorGpuDisplay, "Placa gráfica inutilizável, a imagem é mostrada por software"),
        (ErrorGpuLost, "Placa gráfica perdida – reinicie com --anzeige cpu"),
        (ErrorPixelFormat, "O descodificador entrega imagens que este cliente não consegue mostrar"),
        (DecoderFallback, "A placa gráfica escolhida não descodifica – está a ser usado o descodificador por software"),
        (TipBitrate, "Limite superior da taxa de bits. Com movimento o codificador usa-a toda; em redes alheias, melhor entre 25 e 50."),
        (TipFps, "Taxa de imagens pretendida. Não pode exceder a que o ecrã do Mac fornece."),
        (TipGaming, "Imagens-chave mais frequentes e menos atraso tolerado: mais estável com movimento, custa alguma taxa de bits."),
        (TipSound, "Transmitir o som. Desligado poupa cerca de 3 Mbit/s; o host deixa então de enviar som."),
        (TipCodec, "Codec do host, mudado em funcionamento; a imagem para por um instante. \"convertido\" custa uma passagem a mais."),
        (TipFullscreen, "Ecrã inteiro sem margens. Em janela, a imagem é ajustada."),
        (TipPixelExact, "Imagem 1:1 sem redimensionar. Se a janela for mais pequena, vê-se apenas uma parte."),
        (TipShowOverlay, "Mostrar as estatísticas no canto superior esquerdo. Quais as linhas, à direita."),
        (TipNerdMode, "Estatísticas alargadas: cadeia de latência em barra, carga do host e do cliente."),
        (TipStatRows, "Que linhas as estatísticas mostram."),
        (TipDecoderAuto, "NVDEC numa placa NVIDIA; senão D3D11VA na placa que desenha (só 4:2:0 e H.264); senão o processador."),
        (TipDecoderCpu, "Descodificar no processador. Funciona em todo o lado, custa tempo de CPU."),
        (TipDecoderGpu, "Descodificar na placa gráfica. Se não conseguir, o cliente recorre ao processador e diz porquê."),
        (TipDecoderIntegrated, "Descodificar na gráfica integrada (D3D11VA). Se não conseguir, o cliente recorre ao processador e diz porquê."),
        (TipDisplayAuto, "Direct3D 11 na primeira placa com saída de ecrã, senão a primeira NVIDIA, senão a primeira que houver. Sem placa: o processador. Aplica-se a partir do próximo arranque."),
        (TipDisplayGpu, "Desenhar com Direct3D 11 nesta placa. Aplica-se a partir do próximo arranque."),
        (TipDisplayIntegrated, "Desenhar com Direct3D 11 na gráfica integrada – aquela a que o ecrã normalmente está ligado. Aplica-se a partir do próximo arranque."),
        (TipDisplayCpu, "Desenhar no processador, sem Direct3D. Funciona em todo o lado, custa tempo de CPU. Aplica-se a partir do próximo arranque."),
        (TipDisconnect, "Terminar a ligação, voltar ao ecrã inicial."),
        (TabShortcuts, "Atalhos"),
        (ShortcutMenu, "Abrir o menu (este ESC nunca chega ao Mac)"),
        (ShortcutBack, "Voltar ao ecrã inicial"),
        (ShortcutWinKey, "Tecla Windows = tecla Comando do Mac"),
        (ShortcutOthers, "Todas as outras teclas vão para o Mac. Transmite-se a posição da tecla, não o carácter: acentos e AltGr funcionam por si."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Iniciar"),
        (BenchAbort, "Cancelar"),
        (BenchApply, "Aplicar"),
        (BenchDuration, "Duração por passo"),
        (BenchTestPattern, "Padrão de teste"),
        (BenchStep, "Passo {n} de {m}"),
        (BenchPhaseSettings, "a aplicar definições"),
        (BenchPhaseSettle, "a estabilizar"),
        (BenchPhaseMeasure, "a medir"),
        (BenchFailed, "falhou"),
        (BenchDone, "Concluído"),
        (BenchAborted, "Cancelado"),
        (BenchMeasured, "medido"),
        (BenchChain, "Cadeia"),
        (BenchColFps, "fps"),
        (BenchColDropped, "perdidas"),
        (BenchColHostCpu, "CPU host"),
        (BenchRecommendation, "Recomendação"),
        (BenchNoRecommendation, "Nenhum passo passou: cadeia acima de 30 ms ou imagens a menos. Experimente taxas de imagens ou de bits mais baixas."),
        (BenchHint, "Mede-se o que acontece no Mac neste momento. Os passos só são comparáveis se algo se mover: basta um vídeo em reprodução."),
        (BenchHintPattern, "Com o padrão de teste, cada passo vê o mesmo conteúdo em movimento: nada precisa de correr no Mac."),
        (TipBenchStart, "Mede uma a uma todas as combinações dos codecs, taxas de imagens e taxas de bits escolhidos, cada uma durante o tempo definido. A imagem continua e o menu pode ficar aberto."),
        (TipBenchApply, "Definir o codec e as definições recomendados e guardá-los para este host."),
        (TipBenchDuration, "Tempo de medição por passo. Mais longo é mais estável; 5 s costumam chegar."),
        (TipBenchHint, "Um passo passa se chegarem pelo menos 95 % da taxa de imagens alvo, se se perder menos de 1 % das imagens e se toda a cadeia se mantiver dentro de 30 ms, independentemente da taxa de imagens. O tempo do codificador do host é mostrado, mas não avaliado. Recomendado: a melhor qualidade de cor que passa à taxa de imagens mais alta, com a taxa de bits mais alta."),
        (TipBenchTestPattern, "Durante o teste, o host mostra um padrão fixo em movimento em vez do ecrã: cada passo mede o mesmo conteúdo."),
    ],
};

pub static NL: Lang = Lang {
    code: "nl",
    name: "Nederlands",
    table: &[
        (AppSubtitle, "Extern bureaublad zonder kleurverlies"),
        (Connect, "Verbinden"),
        (Disconnect, "Verbinding verbreken"),
        (HostAddress, "Adres van de host"),
        (SearchingHosts, "Zoeken naar hosts"),
        (NoHostsFound, "Geen hosts gevonden"),
        (FoundHosts, "Gevonden hosts"),
        (Settings, "Instellingen"),
        (Language, "Taal"),
        (Quit, "Afsluiten"),
        (Connecting, "Bezig met verbinden"),
        (Connected, "Verbonden"),
        (ConnectionLost, "Verbinding verbroken"),
        (Reconnecting, "Opnieuw verbinden"),
        (Fullscreen, "Volledig scherm"),
        (PixelExact, "Pixel voor pixel"),
        (Stretch, "Aan venster aanpassen"),
        (ShowOverlay, "Statistieken tonen"),
        (Fps, "Beelden per seconde"),
        (DecodeTime, "Decodeertijd"),
        (Bitrate, "Bitrate"),
        (Resolution, "Resolutie"),
        (Codec, "Codec"),
        (Latency, "Vertraging"),
        (EncodeTime, "Encodeertijd"),
        (NetworkTime, "Netwerk"),
        (AudioBuffer, "Audiobuffer"),
        (Dropped, "Verloren beelden"),
        (MaxBitrate, "Maximale bitrate"),
        (MaxFps, "Maximale framerate"),
        (ExpertMode, "Expertmodus"),
        (GamingMode, "Spelmodus"),
        (FixedRate, "Vaste framerate"),
        (FixedRateHint, "Houdt de framerate vast, ook als er niets beweegt. Constante belasting op de host."),
        (Sound, "Geluid"),
        (HoldEscHint, "Houd ESC vast voor het menu"),
        (NerdMode, "Nerdmodus"),
        (More, "Meer"),
        (Back, "Terug"),
        (SavedForHost, "Opgeslagen voor deze host"),
        (Queue, "Opname & wachten"),
        (OneFrame, "Eén beeld"),
        (Bottleneck, "Knelpunt"),
        (TabPicture, "Beeld"),
        (TabDisplay, "Weergave"),
        (CodecConverted, "omgezet"),
        (CodecSwitching, "Codec wordt gewisseld"),
        (HostCpu, "Host-CPU"),
        (HostGpu, "Host-GPU"),
        (HostRam, "Hostgeheugen"),
        (NoDisplay, "De host heeft momenteel geen beeldscherm"),
        (Encryption, "Versleuteling"),
        (EncryptionOn, "aan"),
        (EncryptionOff, "uit"),
        (AudioEnabled, "Geluid"),
        (ClipboardEnabled, "Klembord"),
        (DecoderLabel, "Decoder"),
        (RoleAuto, "Automatisch"),
        (RoleCpu, "Processor"),
        (RoleGpu, "Videokaart"),
        (RoleGpuN, "Videokaart {n}"),
        (RoleIntegrated, "Geïntegreerd"),
        (NextStartHint, "geldt vanaf de volgende start"),
        (AdapterWithOutput, "met beeldschermuitgang"),
        (AdapterNoOutput, "zonder beeldschermuitgang"),
        (TipOnly420, "Alleen 4:2:0 en H.264 (D3D11VA); bij 4:4:4 valt de client terug op de processor – codec omzetten op het tabblad Beeld."),
        (DisplayLabel, "Weergave"),
        (DisplayStage, "Weergave"),
        (ClientCpu, "Client-CPU"),
        (Monitor, "Monitor"),
        (Skipped, "overgeslagen"),
        (PairingTitle, "Koppelen met host"),
        (PairingHint, "Voer de code in die op de host staat"),
        (PairingCode, "Koppelcode"),
        (PairingWrong, "Onjuiste code"),
        (PairingOk, "Gekoppeld"),
        (SecuredWith, "Beveiligd · verificatiecode"),
        (HostFingerprint, "Vingerafdruk van de host"),
        (NotPaired, "Deze host kent je apparaat nog niet. Start de host met --pair en verbind opnieuw."),
        (FirstContact, "Eerste contact met deze host. Vergelijk de code met die op de host."),
        (ErrorConnectRefused, "Host heeft de verbinding geweigerd"),
        (ErrorTimeout, "Host reageert niet"),
        (ErrorProtocol, "De andere kant spreekt een ander protocol"),
        (ErrorNoDecoder, "Geen decoder voor dit formaat"),
        (SessionTakenOver, "Een ander apparaat heeft de sessie overgenomen."),
        (HostKeyChanged, "De vingerafdruk van {n} is gewijzigd (nu {m}). Verbinding geweigerd. Is de host opnieuw geïnstalleerd, verwijder dan zijn regel in {p}."),
        (KeyFileDamaged, "Het sleutelbestand {p} is beschadigd en is ongewijzigd gelaten. Controleer of verwijder het – dan wordt een nieuwe sleutel gemaakt en moet de host dit apparaat opnieuw koppelen."),
        (FileUnreadable, "{p} kan niet worden gelezen – geen verbinding."),
        (FileNotUtf8, "{p} is niet als UTF-8 opgeslagen – geen verbinding."),
        (FileNotWritable, "{p} kan niet worden geschreven – geen verbinding."),
        (StorageUnavailable, "De map voor sleutels en instellingen is niet beschikbaar – geen verbinding."),
        (ErrorAddress, "Het adres {n} kan niet worden omgezet"),
        (ErrorNoConnection, "Geen verbinding met de host"),
        (ErrorHandshake, "De beveiligde verbinding kwam niet tot stand"),
        (ErrorFfmpegStart, "FFmpeg kon niet worden gestart"),
        (ErrorSound, "Geluid niet beschikbaar"),
        (ErrorGpuDisplay, "Videokaart niet bruikbaar, weergave via software"),
        (ErrorGpuLost, "Videokaart verloren – start opnieuw met --anzeige cpu"),
        (ErrorPixelFormat, "De decoder levert beelden die deze client niet kan weergeven"),
        (DecoderFallback, "De gekozen videokaart decodeert niet – softwaredecoder actief"),
        (TipBitrate, "Bovengrens van de bitrate. Bij beweging gebruikt de encoder alles; op andermans netwerk liever 25 tot 50."),
        (TipFps, "Gewenste framerate. Meer dan het scherm van de Mac levert, kan niet."),
        (TipGaming, "Vaker keyframes en minder toegestane achterstand: rustiger bij beweging, kost wat bitrate."),
        (TipSound, "Geluid meesturen. Uit bespaart zo'n 3 Mbit/s; de host stuurt dan geen geluid."),
        (TipCodec, "Codec van de host, wisselt tijdens gebruik; het beeld staat even stil. \"omgezet\" kost één stap extra."),
        (TipFullscreen, "Randloos volledig scherm. In een venster wordt het beeld ingepast."),
        (TipPixelExact, "Beeld 1:1 zonder schalen. Is het venster kleiner, dan zie je een uitsnede."),
        (TipShowOverlay, "Statistieken linksboven tonen. Welke regels, staat rechts."),
        (TipNerdMode, "Uitgebreide statistieken: vertragingsketen als balk, belasting van host en client."),
        (TipStatRows, "Welke regels de statistieken tonen."),
        (TipDecoderAuto, "NVDEC op een NVIDIA-kaart; anders D3D11VA op de kaart die tekent (alleen 4:2:0 en H.264); anders de processor."),
        (TipDecoderCpu, "Decoderen op de processor. Werkt overal, kost rekentijd."),
        (TipDecoderGpu, "Decoderen op de videokaart. Lukt dat niet, dan valt de client terug op de processor en zegt waarom."),
        (TipDecoderIntegrated, "Decoderen op de geïntegreerde grafische kaart (D3D11VA). Lukt dat niet, dan valt de client terug op de processor en zegt waarom."),
        (TipDisplayAuto, "Direct3D 11 op de eerste kaart met beeldschermuitgang, anders de eerste NVIDIA-kaart, anders de eerste die er is. Zonder kaart: de processor. Geldt vanaf de volgende start."),
        (TipDisplayGpu, "Tekenen met Direct3D 11 op deze kaart. Geldt vanaf de volgende start."),
        (TipDisplayIntegrated, "Tekenen met Direct3D 11 op de geïntegreerde grafische kaart – waar het beeldscherm meestal aan hangt. Geldt vanaf de volgende start."),
        (TipDisplayCpu, "Tekenen op de processor, zonder Direct3D. Werkt overal, kost rekentijd. Geldt vanaf de volgende start."),
        (TipDisconnect, "Verbinding beëindigen, terug naar het startscherm."),
        (TabShortcuts, "Sneltoetsen"),
        (ShortcutMenu, "Menu openen (deze ESC komt nooit bij de Mac aan)"),
        (ShortcutBack, "Terug naar het startscherm"),
        (ShortcutWinKey, "Windows-toets = Command-toets van de Mac"),
        (ShortcutOthers, "Alle andere toetsen gaan naar de Mac. Verzonden wordt de positie van de toets, niet het teken – accenten en AltGr kloppen vanzelf."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Starten"),
        (BenchAbort, "Annuleren"),
        (BenchApply, "Toepassen"),
        (BenchDuration, "Duur per stap"),
        (BenchTestPattern, "Testbeeld"),
        (BenchStep, "Stap {n} van {m}"),
        (BenchPhaseSettings, "instellingen worden gezet"),
        (BenchPhaseSettle, "stabiliseren"),
        (BenchPhaseMeasure, "meten"),
        (BenchFailed, "mislukt"),
        (BenchDone, "Klaar"),
        (BenchAborted, "Geannuleerd"),
        (BenchMeasured, "gemeten"),
        (BenchChain, "Keten"),
        (BenchColFps, "fps"),
        (BenchColDropped, "verloren"),
        (BenchColHostCpu, "Host-CPU"),
        (BenchRecommendation, "Aanbeveling"),
        (BenchNoRecommendation, "Geen enkele stap is geslaagd: keten boven 30 ms of te weinig beelden. Probeer lagere framerates of bitrates."),
        (BenchHint, "Gemeten wordt wat er nu op de Mac gebeurt. Stappen zijn alleen vergelijkbaar als er iets beweegt – een lopende video is genoeg."),
        (BenchHintPattern, "Met testbeeld ziet elke stap dezelfde bewegende inhoud – op de Mac hoeft niets te draaien."),
        (TipBenchStart, "Meet alle combinaties van de gekozen codecs, framerates en bitrates na elkaar, elk voor de ingestelde duur. Het beeld loopt door en het menu mag open blijven."),
        (TipBenchApply, "Aanbevolen codec en instellingen zetten en opslaan voor deze host."),
        (TipBenchDuration, "Meettijd per stap. Langer is rustiger; 5 s is meestal genoeg."),
        (TipBenchHint, "Een stap slaagt als minstens 95 % van de doelframerate aankomt, minder dan 1 % van de beelden verloren gaat en de hele keten binnen 30 ms blijft – ongeacht de framerate. De encodertijd van de host wordt getoond maar niet beoordeeld. Aanbevolen: de beste kleurkwaliteit die slaagt bij de hoogste framerate, met de hoogste bitrate."),
        (TipBenchTestPattern, "Voor de duur van de run toont de host een vast bewegend patroon in plaats van het scherm – elke stap meet dezelfde inhoud."),
    ],
};
