// Nordische Sprachen: Schwedisch, Daenisch, Norwegisch (Bokmal), Finnisch,
// Islaendisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static SV: Lang = Lang {
    code: "sv",
    name: "Svenska",
    table: &[
        (AppSubtitle, "Fjärrskrivbord med full färgupplösning"),
        (Connect, "Anslut"),
        (Disconnect, "Koppla från"),
        (HostAddress, "Värdadress"),
        (SearchingHosts, "Söker efter värdar"),
        (NoHostsFound, "Inga värdar hittades"),
        (FoundHosts, "Hittade värdar"),
        (Settings, "Inställningar"),
        (Language, "Språk"),
        (Quit, "Avsluta"),
        (Connecting, "Ansluter"),
        (Connected, "Ansluten"),
        (ConnectionLost, "Anslutningen bröts"),
        (Reconnecting, "Återansluter"),
        (Fullscreen, "Helskärm"),
        (PixelExact, "Pixelexakt"),
        (Stretch, "Anpassa till fönster"),
        (ShowOverlay, "Visa statistik"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Avkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplösning"),
        (Codec, "Codec"),
        (Latency, "Latens"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Överföring"),
        (AudioBuffer, "Ljudbuffert"),
        (Dropped, "Tappade bilder"),
        (MaxBitrate, "Högsta bitrate"),
        (MaxFps, "Högsta bildfrekvens"),
        (ExpertMode, "Expertläge"),
        (GamingMode, "Spelläge"),
        (FixedRate, "Fast bildfrekvens"),
        (FixedRateHint, "Håller bildfrekvensen även när inget rör sig. Konstant belastning på värden."),
        (Sound, "Ljud"),
        (HoldEscHint, "Håll kvar ESC för menyn"),
        (NerdMode, "Nördläge"),
        (More, "Mer"),
        (Back, "Tillbaka"),
        (SavedForHost, "Sparat för den här värden"),
        (Queue, "Infångning & kö"),
        (OneFrame, "En bild"),
        (Bottleneck, "Flaskhals"),
        (TabPicture, "Bild"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverterad"),
        (CodecSwitching, "Byter codec"),
        (HostCpu, "Värdens processor"),
        (HostGpu, "Värdens grafik"),
        (HostRam, "Värdens minne"),
        (NoDisplay, "Värden har ingen skärm just nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Ljud"),
        (ClipboardEnabled, "Urklipp"),
        (DecoderLabel, "Avkodare"),
        (RoleAuto, "Automatisk"),
        (RoleCpu, "Processor"),
        (RoleGpu, "Grafikkort"),
        (RoleGpuN, "Grafikkort {n}"),
        (RoleIntegrated, "Integrerat"),
        (NextStartHint, "gäller från nästa start"),
        (AdapterWithOutput, "med skärmutgång"),
        (AdapterNoOutput, "utan skärmutgång"),
        (TipOnly420, "Bara 4:2:0 och H.264 (D3D11VA); vid 4:4:4 faller klienten tillbaka på processorn – byt codec under fliken Bild."),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens processor"),
        (Monitor, "Bildskärm"),
        (Skipped, "överhoppade"),
        (PairingTitle, "Parkoppla med värd"),
        (PairingHint, "Ange koden som visas på värden"),
        (PairingCode, "Parkopplingskod"),
        (PairingWrong, "Fel kod"),
        (PairingOk, "Parkopplad"),
        (SecuredWith, "Skyddad · verifieringskod"),
        (HostFingerprint, "Värdens fingeravtryck"),
        (NotPaired, "Den här värden känner inte till din enhet ännu. Starta värden med --pair och anslut igen."),
        (FirstContact, "Första kontakten med den här värden. Jämför koden med den på värden."),
        (ErrorConnectRefused, "Värden nekade anslutningen"),
        (ErrorTimeout, "Värden svarar inte"),
        (ErrorProtocol, "Motparten använder ett annat protokoll"),
        (ErrorNoDecoder, "Ingen avkodare för det här formatet"),
        (SessionTakenOver, "En annan enhet har tagit över sessionen."),
        (HostKeyChanged, "Fingeravtrycket för {n} har ändrats (nu {m}). Anslutningen nekades. Om värden har installerats om, ta bort dess rad i {p}."),
        (KeyFileDamaged, "Nyckelfilen {p} är skadad och har lämnats som den är. Kontrollera eller ta bort den – då skapas en ny nyckel, och värden måste parkoppla den här enheten igen."),
        (FileUnreadable, "{p} kan inte läsas – ingen anslutning görs."),
        (FileNotUtf8, "{p} är inte sparad som UTF-8 – ingen anslutning görs."),
        (FileNotWritable, "{p} kan inte skrivas – ingen anslutning görs."),
        (StorageUnavailable, "Mappen för nycklar och inställningar är inte tillgänglig – ingen anslutning görs."),
        (ErrorAddress, "Adressen {n} kan inte slås upp"),
        (ErrorNoConnection, "Ingen anslutning till värden"),
        (ErrorHandshake, "Den säkra anslutningen kunde inte upprättas"),
        (ErrorFfmpegStart, "FFmpeg kunde inte startas"),
        (ErrorSound, "Ljud är inte tillgängligt"),
        (ErrorGpuDisplay, "Grafikkortet går inte att använda, visningen körs i mjukvara"),
        (ErrorGpuLost, "Grafikkortet förlorades – starta om med --anzeige cpu"),
        (ErrorPixelFormat, "Avkodaren levererar bilder som den här klienten inte kan visa"),
        (DecoderFallback, "Det valda grafikkortet avkodar inte – mjukvaruavkodare används"),
        (TipBitrate, "Övre gräns för bitrate. Vid rörelse använder kodaren allt; i andras nätverk hellre 25 till 50."),
        (TipFps, "Önskad bildfrekvens. Mer än Macens skärm levererar går inte."),
        (TipGaming, "Tätare nyckelbilder och mindre tillåten eftersläpning: jämnare vid rörelse, kostar lite bitrate."),
        (TipSound, "Skicka ljud. Av sparar cirka 3 Mbit/s; värden skickar då inget ljud."),
        (TipCodec, "Värdens codec, byts under drift; bilden står stilla ett ögonblick. \"konverterad\" kostar ett steg till."),
        (TipFullscreen, "Kantlös helskärm. I fönster passas bilden in."),
        (TipPixelExact, "Bilden 1:1 utan skalning. Är fönstret mindre visas ett utsnitt."),
        (TipShowOverlay, "Visa statistiken uppe till vänster. Vilka rader, se till höger."),
        (TipNerdMode, "Utökad statistik: latenskedjan som stapel, belastning på värd och klient."),
        (TipStatRows, "Vilka rader statistiken visar."),
        (TipDecoderAuto, "NVDEC på ett NVIDIA-kort; annars D3D11VA på kortet som ritar (bara 4:2:0 och H.264); annars processorn."),
        (TipDecoderCpu, "Avkoda på processorn. Fungerar överallt, kostar processortid."),
        (TipDecoderGpu, "Avkoda på grafikkortet. Klarar det inte det faller klienten tillbaka på processorn och säger varför."),
        (TipDecoderIntegrated, "Avkoda på den integrerade grafiken (D3D11VA). Klarar den inte det faller klienten tillbaka på processorn och säger varför."),
        (TipDisplayAuto, "Direct3D 11 på det första kortet med skärmutgång, annars det första NVIDIA-kortet, annars det första som finns. Utan kort: processorn. Gäller från nästa start."),
        (TipDisplayGpu, "Rita med Direct3D 11 på det här kortet. Gäller från nästa start."),
        (TipDisplayIntegrated, "Rita med Direct3D 11 på den integrerade grafiken – den som skärmen oftast sitter på. Gäller från nästa start."),
        (TipDisplayCpu, "Rita på processorn, utan Direct3D. Fungerar överallt, kostar processortid. Gäller från nästa start."),
        (TipDisconnect, "Avsluta anslutningen, tillbaka till startskärmen."),
        (TabShortcuts, "Kortkommandon"),
        (ShortcutMenu, "Öppna menyn (detta ESC når aldrig Macen)"),
        (ShortcutBack, "Tillbaka till startskärmen"),
        (ShortcutWinKey, "Windows-tangenten = Macens kommandotangent"),
        (ShortcutOthers, "Alla andra tangenter går till Macen. Det som skickas är tangentens position, inte tecknet – å, ä, ö och AltGr fungerar av sig själva."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Starta"),
        (BenchAbort, "Avbryt"),
        (BenchApply, "Använd"),
        (BenchDuration, "Tid per steg"),
        (BenchTestPattern, "Testbild"),
        (BenchStep, "Steg {n} av {m}"),
        (BenchPhaseSettings, "inställningar sätts"),
        (BenchPhaseSettle, "stabiliserar"),
        (BenchPhaseMeasure, "mäter"),
        (BenchFailed, "misslyckades"),
        (BenchDone, "Klart"),
        (BenchAborted, "Avbrutet"),
        (BenchMeasured, "uppmätt"),
        (BenchChain, "Kedja"),
        (BenchColFps, "fps"),
        (BenchColDropped, "tappade"),
        (BenchColHostCpu, "Värd-CPU"),
        (BenchRecommendation, "Rekommendation"),
        (BenchNoRecommendation, "Inget steg klarade sig: kedjan över 30 ms eller för få bilder. Prova lägre bildfrekvens eller bitrate."),
        (BenchHint, "Det som mäts är vad som händer på Macen just nu. Stegen är bara jämförbara när något rör sig – en video som spelas räcker."),
        (BenchHintPattern, "Med testbild ser varje steg samma rörliga innehåll – inget behöver köras på Macen."),
        (TipBenchStart, "Mäter alla kombinationer av valda codecar, bildfrekvenser och bitrate i tur och ordning, var och en under inställd tid. Bilden fortsätter och menyn får vara öppen."),
        (TipBenchApply, "Sätt rekommenderad codec och inställningar och spara dem för den här värden."),
        (TipBenchDuration, "Mättid per steg. Längre är stabilare; 5 s räcker oftast."),
        (TipBenchHint, "Ett steg klarar sig när minst 95 % av målbildfrekvensen kommer fram, under 1 % av bilderna tappas och hela kedjan håller sig inom 30 ms – oavsett bildfrekvens. Värdens kodartid visas men bedöms inte. Rekommenderas: bästa färgkvalitet som klarar sig vid högsta bildfrekvens, med högsta bitrate."),
        (TipBenchTestPattern, "Under körningen visar värden ett fast rörligt mönster i stället för skärmen – varje steg mäter samma innehåll."),
        (DesktopShortcut, "Genväg"),
        (TipDesktopShortcut, "Skapar en genväg till den här värden på skrivbordet. Ett dubbelklick ansluter direkt."),
        (DesktopShortcutCreated, "Genväg skapad på skrivbordet: {n}"),
        (DesktopShortcutFailed, "Genvägen skapades inte: {n}"),
        (DesktopShortcutDescription, "QuadChroma: anslut till {n} ({m})"),
        (FilesSending, "Skickar filer: {n} av {m}"),
        (FilesReceiving, "Tar emot filer: {n} av {m}"),
        (FilesReady, "Filer redo att klistra in: {n}"),
        (FilesSent, "Filer överförda: {n}"),
        (FilesAborted, "Filöverföringen avbröts: {n}"),
        (FilesTooLarge, "Filerna överfördes inte: mer än 4 GB eller 10 000 objekt"),
        (FilesPeerOld, "Den andra sidan kan inte ta emot filer ännu."),
        (TrayOpen, "Öppna"),
        (TrayConnect, "Anslut: {n}"),
        (TrayQuit, "Avsluta"),
        (TrayStillRunning, "QuadChroma körs vidare i meddelandefältet."),
        (TrayStillRunningMac, "QuadChroma körs vidare i menyraden."),
        (FilesAbortLocal, "av den här enheten"),
        (FilesAbortPeer, "av den andra sidan"),
        (FilesAbortConnection, "anslutningen avbröts"),
        (FilesAbortTimeout, "tidsgränsen nåddes utan framsteg"),
        (FilesAbortNoSpace, "för lite diskutrymme"),
        (FilesAbortInvalid, "ogiltiga data"),
        (FilesAbortRead, "läsfel"),
        (FilesAbortWrite, "skrivfel"),
        (FilesAbortClipboard, "urklipp är inte tillgängligt"),
    ],
};

pub static DA: Lang = Lang {
    code: "da",
    name: "Dansk",
    table: &[
        (AppSubtitle, "Fjernskrivebord med fuld farveopløsning"),
        (Connect, "Forbind"),
        (Disconnect, "Afbryd"),
        (HostAddress, "Værtsadresse"),
        (SearchingHosts, "Søger efter værter"),
        (NoHostsFound, "Ingen værter fundet"),
        (FoundHosts, "Fundne værter"),
        (Settings, "Indstillinger"),
        (Language, "Sprog"),
        (Quit, "Afslut"),
        (Connecting, "Forbinder"),
        (Connected, "Forbundet"),
        (ConnectionLost, "Forbindelsen blev afbrudt"),
        (Reconnecting, "Forbinder igen"),
        (Fullscreen, "Fuld skærm"),
        (PixelExact, "Pixelnøjagtig"),
        (Stretch, "Tilpas til vindue"),
        (ShowOverlay, "Vis statistik"),
        (Fps, "Billeder pr. sekund"),
        (DecodeTime, "Afkodningstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Opløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodningstid"),
        (NetworkTime, "Overførsel"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tabte billeder"),
        (MaxBitrate, "Højeste bitrate"),
        (MaxFps, "Højeste billedfrekvens"),
        (ExpertMode, "Eksperttilstand"),
        (GamingMode, "Spiltilstand"),
        (FixedRate, "Fast billedfrekvens"),
        (FixedRateHint, "Holder billedfrekvensen, også når intet bevæger sig. Konstant belastning på værten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menuen"),
        (NerdMode, "Nørdtilstand"),
        (More, "Mere"),
        (Back, "Tilbage"),
        (SavedForHost, "Gemt for denne vært"),
        (Queue, "Optagelse & kø"),
        (OneFrame, "Ét billede"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Billede"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konverteret"),
        (CodecSwitching, "Skifter codec"),
        (HostCpu, "Værtens processor"),
        (HostGpu, "Værtens grafik"),
        (HostRam, "Værtens hukommelse"),
        (NoDisplay, "Værten har ingen skærm lige nu"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "til"),
        (EncryptionOff, "fra"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Udklipsholder"),
        (DecoderLabel, "Afkoder"),
        (RoleAuto, "Automatisk"),
        (RoleCpu, "Processor"),
        (RoleGpu, "Grafikkort"),
        (RoleGpuN, "Grafikkort {n}"),
        (RoleIntegrated, "Integreret"),
        (NextStartHint, "gælder fra næste start"),
        (AdapterWithOutput, "med skærmudgang"),
        (AdapterNoOutput, "uden skærmudgang"),
        (TipOnly420, "Kun 4:2:0 og H.264 (D3D11VA); ved 4:4:4 falder klienten tilbage på processoren – skift codec under fanen Billede."),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens processor"),
        (Monitor, "Skærm"),
        (Skipped, "sprunget over"),
        (PairingTitle, "Par med vært"),
        (PairingHint, "Indtast koden, der vises på værten"),
        (PairingCode, "Parringskode"),
        (PairingWrong, "Forkert kode"),
        (PairingOk, "Parret"),
        (SecuredWith, "Sikret · bekræftelseskode"),
        (HostFingerprint, "Værtens fingeraftryk"),
        (NotPaired, "Denne vært kender ikke din enhed endnu. Start værten med --pair, og forbind igen."),
        (FirstContact, "Første kontakt med denne vært. Sammenlign koden med den på værten."),
        (ErrorConnectRefused, "Værten afviste forbindelsen"),
        (ErrorTimeout, "Værten svarer ikke"),
        (ErrorProtocol, "Modparten bruger en anden protokol"),
        (ErrorNoDecoder, "Ingen afkoder til dette format"),
        (SessionTakenOver, "En anden enhed har overtaget sessionen."),
        (HostKeyChanged, "Fingeraftrykket for {n} er ændret (nu {m}). Forbindelsen blev afvist. Hvis værten er blevet geninstalleret, så slet dens linje i {p}."),
        (KeyFileDamaged, "Nøglefilen {p} er beskadiget og er efterladt uændret. Kontrollér eller slet den – så oprettes en ny nøgle, og værten skal parre denne enhed igen."),
        (FileUnreadable, "{p} kan ikke læses – der oprettes ingen forbindelse."),
        (FileNotUtf8, "{p} er ikke gemt som UTF-8 – der oprettes ingen forbindelse."),
        (FileNotWritable, "{p} kan ikke skrives – der oprettes ingen forbindelse."),
        (StorageUnavailable, "Mappen til nøgler og indstillinger er ikke tilgængelig – der oprettes ingen forbindelse."),
        (ErrorAddress, "Adressen {n} kan ikke slås op"),
        (ErrorNoConnection, "Ingen forbindelse til værten"),
        (ErrorHandshake, "Den sikre forbindelse kunne ikke oprettes"),
        (ErrorFfmpegStart, "FFmpeg kunne ikke startes"),
        (ErrorSound, "Lyd er ikke tilgængelig"),
        (ErrorGpuDisplay, "Grafikkortet kan ikke bruges, visningen kører i software"),
        (ErrorGpuLost, "Grafikkortet gik tabt – genstart med --anzeige cpu"),
        (ErrorPixelFormat, "Afkoderen leverer billeder, som denne klient ikke kan vise"),
        (DecoderFallback, "Det valgte grafikkort afkoder ikke – softwareafkoder i brug"),
        (TipBitrate, "Øvre grænse for bitrate. Ved bevægelse bruger encoderen det hele; på fremmede netværk hellere 25 til 50."),
        (TipFps, "Ønsket billedfrekvens. Mere end Mac'ens skærm leverer, kan ikke lade sig gøre."),
        (TipGaming, "Hyppigere nøglebilleder og mindre tilladt efterslæb: mere jævnt ved bevægelse, koster lidt bitrate."),
        (TipSound, "Send lyd. Fra sparer cirka 3 Mbit/s; værten sender så ingen lyd."),
        (TipCodec, "Værtens codec, skiftes under drift; billedet står stille et øjeblik. \"konverteret\" koster et trin mere."),
        (TipFullscreen, "Kantløs fuld skærm. I vindue tilpasses billedet."),
        (TipPixelExact, "Billedet 1:1 uden skalering. Er vinduet mindre, vises et udsnit."),
        (TipShowOverlay, "Vis statistikken øverst til venstre. Hvilke rækker, se til højre."),
        (TipNerdMode, "Udvidet statistik: forsinkelseskæden som søjle, belastning på vært og klient."),
        (TipStatRows, "Hvilke rækker statistikken viser."),
        (TipDecoderAuto, "NVDEC på et NVIDIA-kort; ellers D3D11VA på det kort, der tegner (kun 4:2:0 og H.264); ellers processoren."),
        (TipDecoderCpu, "Afkod på processoren. Virker overalt, koster regnetid."),
        (TipDecoderGpu, "Afkod på grafikkortet. Kan det ikke, falder klienten tilbage på processoren og siger hvorfor."),
        (TipDecoderIntegrated, "Afkod på den integrerede grafik (D3D11VA). Kan den ikke, falder klienten tilbage på processoren og siger hvorfor."),
        (TipDisplayAuto, "Direct3D 11 på det første kort med skærmudgang, ellers det første NVIDIA-kort, ellers det første, der findes. Uden kort: processoren. Gælder fra næste start."),
        (TipDisplayGpu, "Tegn med Direct3D 11 på dette kort. Gælder fra næste start."),
        (TipDisplayIntegrated, "Tegn med Direct3D 11 på den integrerede grafik – den, skærmen som regel sidder på. Gælder fra næste start."),
        (TipDisplayCpu, "Tegn på processoren, uden Direct3D. Virker overalt, koster regnetid. Gælder fra næste start."),
        (TipDisconnect, "Afslut forbindelsen, tilbage til startskærmen."),
        (TabShortcuts, "Genveje"),
        (ShortcutMenu, "Åbn menuen (denne ESC når aldrig Mac'en)"),
        (ShortcutBack, "Tilbage til startskærmen"),
        (ShortcutWinKey, "Windows-tasten = Mac'ens kommandotast"),
        (ShortcutOthers, "Alle andre taster går til Mac'en. Det er tastens position, der sendes, ikke tegnet – æ, ø, å og AltGr virker af sig selv."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Start"),
        (BenchAbort, "Afbryd"),
        (BenchApply, "Anvend"),
        (BenchDuration, "Tid pr. trin"),
        (BenchTestPattern, "Testbillede"),
        (BenchStep, "Trin {n} af {m}"),
        (BenchPhaseSettings, "indstillinger sættes"),
        (BenchPhaseSettle, "stabiliserer"),
        (BenchPhaseMeasure, "måler"),
        (BenchFailed, "mislykkedes"),
        (BenchDone, "Færdig"),
        (BenchAborted, "Afbrudt"),
        (BenchMeasured, "målt"),
        (BenchChain, "Kæde"),
        (BenchColFps, "fps"),
        (BenchColDropped, "tabte"),
        (BenchColHostCpu, "Værts-CPU"),
        (BenchRecommendation, "Anbefaling"),
        (BenchNoRecommendation, "Intet trin bestod: kæden over 30 ms eller for få billeder. Prøv lavere billedfrekvens eller bitrate."),
        (BenchHint, "Det, der måles, er, hvad der sker på Mac'en lige nu. Trinnene kan kun sammenlignes, når noget bevæger sig – en video, der afspilles, er nok."),
        (BenchHintPattern, "Med testbillede ser hvert trin det samme bevægelige indhold – intet behøver at køre på Mac'en."),
        (TipBenchStart, "Måler alle kombinationer af de valgte codecs, billedfrekvenser og bitrates efter tur, hver i den indstillede tid. Billedet kører videre, og menuen må blive åben."),
        (TipBenchApply, "Sæt den anbefalede codec og indstillinger, og gem dem for denne vært."),
        (TipBenchDuration, "Måletid pr. trin. Længere er mere stabilt; 5 s er som regel nok."),
        (TipBenchHint, "Et trin består, når mindst 95 % af målbilledfrekvensen når frem, under 1 % af billederne tabes, og hele kæden holder sig inden for 30 ms – uanset billedfrekvens. Værtens encodertid vises, men bedømmes ikke. Anbefalet: den bedste farvekvalitet, der består ved den højeste billedfrekvens, med den højeste bitrate."),
        (TipBenchTestPattern, "Under kørslen viser værten et fast bevægeligt mønster i stedet for skærmen – hvert trin måler det samme indhold."),
        (DesktopShortcut, "Opret genvej"),
        (TipDesktopShortcut, "Opretter en genvej til denne vært på skrivebordet. Et dobbeltklik opretter straks forbindelse."),
        (DesktopShortcutCreated, "Genvej oprettet på skrivebordet: {n}"),
        (DesktopShortcutFailed, "Genvejen blev ikke oprettet: {n}"),
        (DesktopShortcutDescription, "QuadChroma: opret forbindelse til {n} ({m})"),
        (FilesSending, "Sender filer: {n} af {m}"),
        (FilesReceiving, "Modtager filer: {n} af {m}"),
        (FilesReady, "Filer klar til indsættelse: {n}"),
        (FilesSent, "Filer overført: {n}"),
        (FilesAborted, "Filoverførslen blev afbrudt: {n}"),
        (FilesTooLarge, "Filerne blev ikke overført: mere end 4 GB eller 10.000 elementer"),
        (FilesPeerOld, "Den anden side kan endnu ikke modtage filer."),
        (TrayOpen, "Åbn"),
        (TrayConnect, "Forbind: {n}"),
        (TrayQuit, "Afslut"),
        (TrayStillRunning, "QuadChroma kører videre i meddelelsesområdet."),
        (TrayStillRunningMac, "QuadChroma kører videre i menulinjen."),
        (FilesAbortLocal, "af denne enhed"),
        (FilesAbortPeer, "af den anden side"),
        (FilesAbortConnection, "forbindelsen blev afbrudt"),
        (FilesAbortTimeout, "tidsgrænse overskredet uden fremskridt"),
        (FilesAbortNoSpace, "for lidt diskplads"),
        (FilesAbortInvalid, "ugyldige data"),
        (FilesAbortRead, "læsefejl"),
        (FilesAbortWrite, "skrivefejl"),
        (FilesAbortClipboard, "udklipsholderen er ikke tilgængelig"),
    ],
};

pub static NB: Lang = Lang {
    code: "nb",
    name: "Norsk bokmål",
    table: &[
        (AppSubtitle, "Fjernskrivebord med full fargeoppløsning"),
        (Connect, "Koble til"),
        (Disconnect, "Koble fra"),
        (HostAddress, "Vertsadresse"),
        (SearchingHosts, "Søker etter verter"),
        (NoHostsFound, "Fant ingen verter"),
        (FoundHosts, "Funne verter"),
        (Settings, "Innstillinger"),
        (Language, "Språk"),
        (Quit, "Avslutt"),
        (Connecting, "Kobler til"),
        (Connected, "Tilkoblet"),
        (ConnectionLost, "Mistet forbindelsen"),
        (Reconnecting, "Kobler til på nytt"),
        (Fullscreen, "Fullskjerm"),
        (PixelExact, "Pikselnøyaktig"),
        (Stretch, "Tilpass til vindu"),
        (ShowOverlay, "Vis statistikk"),
        (Fps, "Bilder per sekund"),
        (DecodeTime, "Dekodingstid"),
        (Bitrate, "Bitrate"),
        (Resolution, "Oppløsning"),
        (Codec, "Codec"),
        (Latency, "Forsinkelse"),
        (EncodeTime, "Kodingstid"),
        (NetworkTime, "Overføring"),
        (AudioBuffer, "Lydbuffer"),
        (Dropped, "Tapte bilder"),
        (MaxBitrate, "Høyeste bitrate"),
        (MaxFps, "Høyeste bildefrekvens"),
        (ExpertMode, "Ekspertmodus"),
        (GamingMode, "Spillmodus"),
        (FixedRate, "Fast bildefrekvens"),
        (FixedRateHint, "Holder bildefrekvensen, også når ingenting beveger seg. Konstant belastning på verten."),
        (Sound, "Lyd"),
        (HoldEscHint, "Hold ESC nede for menyen"),
        (NerdMode, "Nerdemodus"),
        (More, "Mer"),
        (Back, "Tilbake"),
        (SavedForHost, "Lagret for denne verten"),
        (Queue, "Opptak & kø"),
        (OneFrame, "Ett bilde"),
        (Bottleneck, "Flaskehals"),
        (TabPicture, "Bilde"),
        (TabDisplay, "Visning"),
        (CodecConverted, "konvertert"),
        (CodecSwitching, "Bytter codec"),
        (HostCpu, "Vertens prosessor"),
        (HostGpu, "Vertens grafikk"),
        (HostRam, "Vertens minne"),
        (NoDisplay, "Verten har ingen skjerm akkurat nå"),
        (Encryption, "Kryptering"),
        (EncryptionOn, "på"),
        (EncryptionOff, "av"),
        (AudioEnabled, "Lyd"),
        (ClipboardEnabled, "Utklippstavle"),
        (DecoderLabel, "Dekoder"),
        (RoleAuto, "Automatisk"),
        (RoleCpu, "Prosessor"),
        (RoleGpu, "Grafikkort"),
        (RoleGpuN, "Grafikkort {n}"),
        (RoleIntegrated, "Integrert"),
        (NextStartHint, "gjelder fra neste start"),
        (AdapterWithOutput, "med skjermutgang"),
        (AdapterNoOutput, "uten skjermutgang"),
        (TipOnly420, "Bare 4:2:0 og H.264 (D3D11VA); ved 4:4:4 faller klienten tilbake på prosessoren – bytt codec under fanen Bilde."),
        (DisplayLabel, "Visning"),
        (DisplayStage, "Visning"),
        (ClientCpu, "Klientens prosessor"),
        (Monitor, "Skjerm"),
        (Skipped, "hoppet over"),
        (PairingTitle, "Parkoble med vert"),
        (PairingHint, "Skriv inn koden som vises på verten"),
        (PairingCode, "Parkoblingskode"),
        (PairingWrong, "Feil kode"),
        (PairingOk, "Parkoblet"),
        (SecuredWith, "Sikret · bekreftelseskode"),
        (HostFingerprint, "Vertens fingeravtrykk"),
        (NotPaired, "Denne verten kjenner ikke enheten din ennå. Start verten med --pair og koble til på nytt."),
        (FirstContact, "Første kontakt med denne verten. Sammenlign koden med den på verten."),
        (ErrorConnectRefused, "Verten avviste tilkoblingen"),
        (ErrorTimeout, "Verten svarer ikke"),
        (ErrorProtocol, "Motparten bruker en annen protokoll"),
        (ErrorNoDecoder, "Ingen dekoder for dette formatet"),
        (SessionTakenOver, "En annen enhet har tatt over økten."),
        (HostKeyChanged, "Fingeravtrykket til {n} er endret (nå {m}). Tilkoblingen ble avvist. Hvis verten er installert på nytt, slett linjen dens i {p}."),
        (KeyFileDamaged, "Nøkkelfilen {p} er skadet og ble latt være som den er. Kontroller eller slett den – da lages en ny nøkkel, og verten må parkoble denne enheten på nytt."),
        (FileUnreadable, "{p} kan ikke leses – ingen tilkobling opprettes."),
        (FileNotUtf8, "{p} er ikke lagret som UTF-8 – ingen tilkobling opprettes."),
        (FileNotWritable, "{p} kan ikke skrives – ingen tilkobling opprettes."),
        (StorageUnavailable, "Mappen for nøkler og innstillinger er ikke tilgjengelig – ingen tilkobling opprettes."),
        (ErrorAddress, "Adressen {n} kan ikke slås opp"),
        (ErrorNoConnection, "Ingen forbindelse til verten"),
        (ErrorHandshake, "Den sikre forbindelsen kunne ikke opprettes"),
        (ErrorFfmpegStart, "FFmpeg kunne ikke startes"),
        (ErrorSound, "Lyd er ikke tilgjengelig"),
        (ErrorGpuDisplay, "Grafikkortet kan ikke brukes, visningen går i programvare"),
        (ErrorGpuLost, "Mistet grafikkortet – start på nytt med --anzeige cpu"),
        (ErrorPixelFormat, "Dekoderen leverer bilder som denne klienten ikke kan vise"),
        (DecoderFallback, "Det valgte grafikkortet dekoder ikke – programvaredekoder i bruk"),
        (TipBitrate, "Øvre grense for bitrate. Ved bevegelse bruker enkoderen alt; på fremmede nettverk heller 25 til 50."),
        (TipFps, "Ønsket bildefrekvens. Mer enn Mac-ens skjerm leverer, går ikke."),
        (TipGaming, "Hyppigere nøkkelbilder og mindre tillatt etterslep: jevnere ved bevegelse, koster litt bitrate."),
        (TipSound, "Send lyd. Av sparer omtrent 3 Mbit/s; verten sender da ingen lyd."),
        (TipCodec, "Vertens codec, byttes under drift; bildet står stille et øyeblikk. \"konvertert\" koster ett trinn til."),
        (TipFullscreen, "Kantløs fullskjerm. I vindu tilpasses bildet."),
        (TipPixelExact, "Bildet 1:1 uten skalering. Er vinduet mindre, vises et utsnitt."),
        (TipShowOverlay, "Vis statistikken øverst til venstre. Hvilke rader, se til høyre."),
        (TipNerdMode, "Utvidet statistikk: forsinkelseskjeden som stolpe, belastning på vert og klient."),
        (TipStatRows, "Hvilke rader statistikken viser."),
        (TipDecoderAuto, "NVDEC på et NVIDIA-kort; ellers D3D11VA på kortet som tegner (bare 4:2:0 og H.264); ellers prosessoren."),
        (TipDecoderCpu, "Dekod på prosessoren. Virker overalt, koster regnetid."),
        (TipDecoderGpu, "Dekod på grafikkortet. Klarer det ikke, faller klienten tilbake på prosessoren og sier hvorfor."),
        (TipDecoderIntegrated, "Dekod på den integrerte grafikken (D3D11VA). Klarer den ikke, faller klienten tilbake på prosessoren og sier hvorfor."),
        (TipDisplayAuto, "Direct3D 11 på det første kortet med skjermutgang, ellers det første NVIDIA-kortet, ellers det første som finnes. Uten kort: prosessoren. Gjelder fra neste start."),
        (TipDisplayGpu, "Tegn med Direct3D 11 på dette kortet. Gjelder fra neste start."),
        (TipDisplayIntegrated, "Tegn med Direct3D 11 på den integrerte grafikken – den skjermen som regel henger på. Gjelder fra neste start."),
        (TipDisplayCpu, "Tegn på prosessoren, uten Direct3D. Virker overalt, koster regnetid. Gjelder fra neste start."),
        (TipDisconnect, "Avslutt forbindelsen, tilbake til startskjermen."),
        (TabShortcuts, "Snarveier"),
        (ShortcutMenu, "Åpne menyen (denne ESC når aldri Mac-en)"),
        (ShortcutBack, "Tilbake til startskjermen"),
        (ShortcutWinKey, "Windows-tasten = Mac-ens kommandotast"),
        (ShortcutOthers, "Alle andre taster går til Mac-en. Det er tastens posisjon som sendes, ikke tegnet – æ, ø, å og AltGr virker av seg selv."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Start"),
        (BenchAbort, "Avbryt"),
        (BenchApply, "Bruk"),
        (BenchDuration, "Tid per trinn"),
        (BenchTestPattern, "Testbilde"),
        (BenchStep, "Trinn {n} av {m}"),
        (BenchPhaseSettings, "innstillinger settes"),
        (BenchPhaseSettle, "stabiliserer"),
        (BenchPhaseMeasure, "måler"),
        (BenchFailed, "mislyktes"),
        (BenchDone, "Ferdig"),
        (BenchAborted, "Avbrutt"),
        (BenchMeasured, "målt"),
        (BenchChain, "Kjede"),
        (BenchColFps, "fps"),
        (BenchColDropped, "tapte"),
        (BenchColHostCpu, "Verts-CPU"),
        (BenchRecommendation, "Anbefaling"),
        (BenchNoRecommendation, "Ingen trinn besto: kjeden over 30 ms eller for få bilder. Prøv lavere bildefrekvens eller bitrate."),
        (BenchHint, "Det som måles, er det som skjer på Mac-en akkurat nå. Trinnene kan bare sammenlignes når noe beveger seg – en video som spilles av, er nok."),
        (BenchHintPattern, "Med testbilde ser hvert trinn det samme bevegelige innholdet – ingenting trenger å kjøre på Mac-en."),
        (TipBenchStart, "Måler alle kombinasjoner av valgte codecer, bildefrekvenser og bitrater etter tur, hver i den innstilte tiden. Bildet fortsetter, og menyen kan stå åpen."),
        (TipBenchApply, "Sett anbefalt codec og innstillinger, og lagre dem for denne verten."),
        (TipBenchDuration, "Måletid per trinn. Lengre er jevnere; 5 s holder som regel."),
        (TipBenchHint, "Et trinn består når minst 95 % av målbildefrekvensen kommer fram, under 1 % av bildene tapes og hele kjeden holder seg innenfor 30 ms – uansett bildefrekvens. Vertens enkodertid vises, men bedømmes ikke. Anbefalt: beste fargekvalitet som består ved høyeste bildefrekvens, med høyeste bitrate."),
        (TipBenchTestPattern, "Under kjøringen viser verten et fast mønster i bevegelse i stedet for skjermen – hvert trinn måler samme innhold."),
        (DesktopShortcut, "Lag snarvei"),
        (TipDesktopShortcut, "Lager en snarvei til denne verten på skrivebordet. Et dobbeltklikk kobler til med en gang."),
        (DesktopShortcutCreated, "Snarvei opprettet på skrivebordet: {n}"),
        (DesktopShortcutFailed, "Snarveien ble ikke opprettet: {n}"),
        (DesktopShortcutDescription, "QuadChroma: koble til {n} ({m})"),
        (FilesSending, "Sender filer: {n} av {m}"),
        (FilesReceiving, "Mottar filer: {n} av {m}"),
        (FilesReady, "Filer klare til å lime inn: {n}"),
        (FilesSent, "Filer overført: {n}"),
        (FilesAborted, "Filoverføringen ble avbrutt: {n}"),
        (FilesTooLarge, "Filene ble ikke overført: mer enn 4 GB eller 10 000 elementer"),
        (FilesPeerOld, "Den andre siden kan ikke motta filer ennå."),
        (TrayOpen, "Åpne"),
        (TrayConnect, "Koble til: {n}"),
        (TrayQuit, "Avslutt"),
        (TrayStillRunning, "QuadChroma kjører videre i systemstatusfeltet."),
        (TrayStillRunningMac, "QuadChroma kjører videre i menylinjen."),
        (FilesAbortLocal, "av denne enheten"),
        (FilesAbortPeer, "av den andre siden"),
        (FilesAbortConnection, "forbindelsen ble brutt"),
        (FilesAbortTimeout, "tidsavbrudd uten fremdrift"),
        (FilesAbortNoSpace, "for lite diskplass"),
        (FilesAbortInvalid, "ugyldige data"),
        (FilesAbortRead, "lesefeil"),
        (FilesAbortWrite, "skrivefeil"),
        (FilesAbortClipboard, "utklippstavlen er ikke tilgjengelig"),
    ],
};

pub static FI: Lang = Lang {
    code: "fi",
    name: "Suomi",
    table: &[
        (AppSubtitle, "Etätyöpöytä täydellä väritarkkuudella"),
        (Connect, "Yhdistä"),
        (Disconnect, "Katkaise yhteys"),
        (HostAddress, "Isäntäkoneen osoite"),
        (SearchingHosts, "Etsitään isäntäkoneita"),
        (NoHostsFound, "Isäntäkoneita ei löytynyt"),
        (FoundHosts, "Löydetyt isäntäkoneet"),
        (Settings, "Asetukset"),
        (Language, "Kieli"),
        (Quit, "Lopeta"),
        (Connecting, "Yhdistetään"),
        (Connected, "Yhdistetty"),
        (ConnectionLost, "Yhteys katkesi"),
        (Reconnecting, "Yhdistetään uudelleen"),
        (Fullscreen, "Koko näyttö"),
        (PixelExact, "Pikselintarkka"),
        (Stretch, "Sovita ikkunaan"),
        (ShowOverlay, "Näytä tilastot"),
        (Fps, "Kuvaa sekunnissa"),
        (DecodeTime, "Dekoodausaika"),
        (Bitrate, "Bitrate"),
        (Resolution, "Tarkkuus"),
        (Codec, "Codec"),
        (Latency, "Viive"),
        (EncodeTime, "Koodausaika"),
        (NetworkTime, "Siirtoaika"),
        (AudioBuffer, "Äänipuskuri"),
        (Dropped, "Pudonneet kuvat"),
        (MaxBitrate, "Suurin bitrate"),
        (MaxFps, "Suurin kuvataajuus"),
        (ExpertMode, "Asiantuntijatila"),
        (GamingMode, "Pelitila"),
        (FixedRate, "Kiinteä kuvataajuus"),
        (FixedRateHint, "Pitää kuvataajuuden ennallaan, vaikka mikään ei liiku. Jatkuva kuormitus isäntäkoneelle."),
        (Sound, "Ääni"),
        (HoldEscHint, "Pidä ESC pohjassa valikkoa varten"),
        (NerdMode, "Nörttitila"),
        (More, "Lisää"),
        (Back, "Takaisin"),
        (SavedForHost, "Tallennettu tälle isäntäkoneelle"),
        (Queue, "Kaappaus & jono"),
        (OneFrame, "Yksi kuva"),
        (Bottleneck, "Pullonkaula"),
        (TabPicture, "Kuva"),
        (TabDisplay, "Näyttö"),
        (CodecConverted, "muunnettu"),
        (CodecSwitching, "Codec vaihtuu"),
        (HostCpu, "Isäntäkoneen suoritin"),
        (HostGpu, "Isäntäkoneen näytönohjain"),
        (HostRam, "Isäntäkoneen muisti"),
        (NoDisplay, "Isäntäkoneella ei ole näyttöä juuri nyt"),
        (Encryption, "Salaus"),
        (EncryptionOn, "päällä"),
        (EncryptionOff, "pois"),
        (AudioEnabled, "Ääni"),
        (ClipboardEnabled, "Leikepöytä"),
        (DecoderLabel, "Purkaja"),
        (RoleAuto, "Automaattinen"),
        (RoleCpu, "Suoritin"),
        (RoleGpu, "Näytönohjain"),
        (RoleGpuN, "Näytönohjain {n}"),
        (RoleIntegrated, "Integroitu"),
        (NextStartHint, "voimassa seuraavasta käynnistyksestä"),
        (AdapterWithOutput, "näyttöliitännällä"),
        (AdapterNoOutput, "ilman näyttöliitäntää"),
        (TipOnly420, "Vain 4:2:0 ja H.264 (D3D11VA); 4:4:4:llä asiakas palaa suorittimeen – vaihda codec Kuva-välilehdellä."),
        (DisplayLabel, "Näyttö"),
        (DisplayStage, "Näyttö"),
        (ClientCpu, "Asiakaskoneen suoritin"),
        (Monitor, "Monitori"),
        (Skipped, "ohitettu"),
        (PairingTitle, "Muodosta laitepari"),
        (PairingHint, "Syötä isäntäkoneella näkyvä koodi"),
        (PairingCode, "Parikoodi"),
        (PairingWrong, "Väärä koodi"),
        (PairingOk, "Pari muodostettu"),
        (SecuredWith, "Suojattu · vahvistuskoodi"),
        (HostFingerprint, "Isäntäkoneen sormenjälki"),
        (NotPaired, "Tämä isäntäkone ei vielä tunne laitettasi. Käynnistä isäntäkone valitsimella --pair ja yhdistä uudelleen."),
        (FirstContact, "Ensimmäinen yhteys tähän isäntäkoneeseen. Vertaa koodia isäntäkoneella näkyvään koodiin."),
        (ErrorConnectRefused, "Isäntäkone hylkäsi yhteyden"),
        (ErrorTimeout, "Isäntäkone ei vastaa"),
        (ErrorProtocol, "Vastapuoli käyttää eri protokollaa"),
        (ErrorNoDecoder, "Ei purkajaa tälle muodolle"),
        (SessionTakenOver, "Toinen laite on ottanut istunnon haltuunsa."),
        (HostKeyChanged, "Isäntäkoneen {n} sormenjälki on muuttunut (nyt {m}). Yhteys hylättiin. Jos isäntäkone on asennettu uudelleen, poista sen rivi tiedostosta {p}."),
        (KeyFileDamaged, "Avaintiedosto {p} on vioittunut, ja se jätettiin ennalleen. Tarkista tai poista se – silloin luodaan uusi avain, ja isäntäkoneen on muodostettava laitepari tämän laitteen kanssa uudelleen."),
        (FileUnreadable, "Tiedostoa {p} ei voi lukea – ei yhdistetä."),
        (FileNotUtf8, "Tiedostoa {p} ei ole tallennettu UTF-8-muodossa – ei yhdistetä."),
        (FileNotWritable, "Tiedostoon {p} ei voi kirjoittaa – ei yhdistetä."),
        (StorageUnavailable, "Avainten ja asetusten kansio ei ole käytettävissä – ei yhdistetä."),
        (ErrorAddress, "Osoitetta {n} ei voi selvittää"),
        (ErrorNoConnection, "Ei yhteyttä isäntäkoneeseen"),
        (ErrorHandshake, "Suojattua yhteyttä ei saatu muodostettua"),
        (ErrorFfmpegStart, "FFmpegiä ei voitu käynnistää"),
        (ErrorSound, "Ääni ei ole käytettävissä"),
        (ErrorGpuDisplay, "Näytönohjainta ei voi käyttää, näyttö toimii ohjelmistolla"),
        (ErrorGpuLost, "Näytönohjain menetettiin – käynnistä uudelleen valitsimella --anzeige cpu"),
        (ErrorPixelFormat, "Purkaja tuottaa kuvia, joita tämä asiakas ei pysty näyttämään"),
        (DecoderFallback, "Valittu näytönohjain ei pura – ohjelmistopurkaja käytössä"),
        (TipBitrate, "Bitraten yläraja. Liikkeessä enkooderi käyttää sen kokonaan; vieraissa verkoissa mieluummin 25–50."),
        (TipFps, "Tavoitekuvataajuus. Enempää kuin Macin näyttö tuottaa ei voi saada."),
        (TipGaming, "Tiheämmin avainkuvia ja vähemmän sallittua jonoa: tasaisempi liikkeessä, maksaa hieman bitratea."),
        (TipSound, "Lähetä ääni. Pois päältä säästää noin 3 Mbit/s; isäntäkone ei silloin lähetä ääntä lainkaan."),
        (TipCodec, "Isäntäkoneen codec, vaihtuu lennossa; kuva pysähtyy hetkeksi. \"muunnettu\" maksaa yhden ylimääräisen vaiheen."),
        (TipFullscreen, "Reunaton koko näyttö. Ikkunassa kuva sovitetaan."),
        (TipPixelExact, "Kuva 1:1 ilman skaalausta. Jos ikkuna on pienempi, näkyy vain osa."),
        (TipShowOverlay, "Näytä tilastot vasemmassa yläkulmassa. Mitkä rivit, valitaan oikealta."),
        (TipNerdMode, "Laajennetut tilastot: viiveketju palkkina, isäntäkoneen ja asiakaskoneen kuormitus."),
        (TipStatRows, "Mitkä rivit tilastoissa näytetään."),
        (TipDecoderAuto, "NVDEC NVIDIA-kortilla; muuten D3D11VA piirtävällä näytönohjaimella (vain 4:2:0 ja H.264); muuten suoritin."),
        (TipDecoderCpu, "Purku suorittimella. Toimii kaikkialla, vie laskenta-aikaa."),
        (TipDecoderGpu, "Purku näytönohjaimella. Jos se ei onnistu, asiakas palaa suorittimeen ja kertoo syyn."),
        (TipDecoderIntegrated, "Purku integroidulla näytönohjaimella (D3D11VA). Jos se ei onnistu, asiakas palaa suorittimeen ja kertoo syyn."),
        (TipDisplayAuto, "Direct3D 11 ensimmäisellä näytönohjaimella, jossa on näyttöliitäntä; muuten ensimmäisellä NVIDIA-kortilla; muuten ensimmäisellä, joka löytyy. Ilman näytönohjainta: suoritin. Voimassa seuraavasta käynnistyksestä."),
        (TipDisplayGpu, "Piirto Direct3D 11:llä tällä näytönohjaimella. Voimassa seuraavasta käynnistyksestä."),
        (TipDisplayIntegrated, "Piirto Direct3D 11:llä integroidulla näytönohjaimella – siihen näyttö on yleensä kytketty. Voimassa seuraavasta käynnistyksestä."),
        (TipDisplayCpu, "Piirto suorittimella, ilman Direct3D:tä. Toimii kaikkialla, vie laskenta-aikaa. Voimassa seuraavasta käynnistyksestä."),
        (TipDisconnect, "Katkaise yhteys, takaisin aloitusnäyttöön."),
        (TabShortcuts, "Pikanäppäimet"),
        (ShortcutMenu, "Avaa valikko (tämä ESC ei koskaan mene Macille)"),
        (ShortcutBack, "Takaisin aloitusnäyttöön"),
        (ShortcutWinKey, "Windows-näppäin = Macin komentonäppäin"),
        (ShortcutOthers, "Kaikki muut näppäimet menevät Macille. Välitetään näppäimen sijainti, ei merkkiä – ä, ö ja AltGr toimivat itsestään."),
        // Benchmark
        (TabBenchmark, "Benchmark"),
        (BenchStart, "Aloita"),
        (BenchAbort, "Keskeytä"),
        (BenchApply, "Käytä"),
        (BenchDuration, "Kesto vaihetta kohti"),
        (BenchTestPattern, "Testikuva"),
        (BenchStep, "Vaihe {n} / {m}"),
        (BenchPhaseSettings, "asetuksia asetetaan"),
        (BenchPhaseSettle, "tasaantuu"),
        (BenchPhaseMeasure, "mitataan"),
        (BenchFailed, "epäonnistui"),
        (BenchDone, "Valmis"),
        (BenchAborted, "Keskeytetty"),
        (BenchMeasured, "mitattu"),
        (BenchChain, "Ketju"),
        (BenchColFps, "fps"),
        (BenchColDropped, "pudonnut"),
        (BenchColHostCpu, "Isäntä-CPU"),
        (BenchRecommendation, "Suositus"),
        (BenchNoRecommendation, "Yksikään vaihe ei läpäissyt: ketju yli 30 ms tai liian vähän kuvia. Kokeile pienempää kuvataajuutta tai bitratea."),
        (BenchHint, "Mitataan sitä, mitä Macilla juuri nyt tapahtuu. Vaiheet ovat vertailukelpoisia vain, kun jokin liikkuu – pyörivä video riittää."),
        (BenchHintPattern, "Testikuvan kanssa jokainen vaihe näkee saman liikkuvan sisällön – Macilla ei tarvitse pyöriä mitään."),
        (TipBenchStart, "Mittaa vuorotellen kaikki valittujen codecien, kuvataajuuksien ja bitratejen yhdistelmät, kunkin asetetun keston ajan. Kuva jatkuu ja valikko saa jäädä auki."),
        (TipBenchApply, "Aseta suositeltu codec ja asetukset ja tallenna ne tälle isäntäkoneelle."),
        (TipBenchDuration, "Mittausaika vaihetta kohti. Pidempi on vakaampi; 5 s riittää yleensä."),
        (TipBenchHint, "Vaihe läpäisee, kun vähintään 95 % tavoitekuvataajuudesta saapuu, alle 1 % kuvista putoaa ja koko ketju pysyy 30 ms:n sisällä – kuvataajuudesta riippumatta. Isäntäkoneen enkooderiaika näytetään, mutta sitä ei arvioida. Suositus: paras värilaatu, joka läpäisee suurimmalla kuvataajuudella, suurimmalla bitratella."),
        (TipBenchTestPattern, "Ajon ajan isäntäkone näyttää näytön sijaan kiinteän liikkuvan kuvion – jokainen vaihe mittaa saman sisällön."),
        (DesktopShortcut, "Pikakuvake"),
        (TipDesktopShortcut, "Luo työpöydälle pikakuvakkeen tähän isäntäkoneeseen. Kaksoisnapsautus muodostaa yhteyden heti."),
        (DesktopShortcutCreated, "Pikakuvake luotu työpöydälle: {n}"),
        (DesktopShortcutFailed, "Pikakuvaketta ei luotu: {n}"),
        (DesktopShortcutDescription, "QuadChroma: yhdistä kohteeseen {n} ({m})"),
        (FilesSending, "Lähetetään tiedostoja: {n} / {m}"),
        (FilesReceiving, "Vastaanotetaan tiedostoja: {n} / {m}"),
        (FilesReady, "Tiedostot valmiina liitettäviksi: {n}"),
        (FilesSent, "Tiedostot siirretty: {n}"),
        (FilesAborted, "Tiedostonsiirto keskeytyi: {n}"),
        (FilesTooLarge, "Tiedostoja ei siirretty: yli 4 GB tai 10 000 kohdetta"),
        (FilesPeerOld, "Vastapuoli ei vielä voi vastaanottaa tiedostoja."),
        (TrayOpen, "Avaa"),
        (TrayConnect, "Yhdistä: {n}"),
        (TrayQuit, "Lopeta"),
        (TrayStillRunning, "QuadChroma toimii edelleen ilmaisinalueella."),
        (TrayStillRunningMac, "QuadChroma toimii edelleen valikkorivillä."),
        (FilesAbortLocal, "tämän laitteen keskeyttämä"),
        (FilesAbortPeer, "vastapuolen keskeyttämä"),
        (FilesAbortConnection, "yhteys katkesi"),
        (FilesAbortTimeout, "aikakatkaisu, ei edistystä"),
        (FilesAbortNoSpace, "levytila ei riitä"),
        (FilesAbortInvalid, "virheelliset tiedot"),
        (FilesAbortRead, "lukuvirhe"),
        (FilesAbortWrite, "kirjoitusvirhe"),
        (FilesAbortClipboard, "leikepöytä ei ole käytettävissä"),
    ],
};

pub static IS: Lang = Lang {
    code: "is",
    name: "Íslenska",
    table: &[
        (AppSubtitle, "Fjartengt skjáborð með fullri litupplausn"),
        (Connect, "Tengjast"),
        (Disconnect, "Aftengja"),
        (HostAddress, "Vistfang hýsils"),
        (SearchingHosts, "Leita að hýslum"),
        (NoHostsFound, "Enginn hýsill fannst"),
        (FoundHosts, "Hýslar sem fundust"),
        (Settings, "Stillingar"),
        (Language, "Tungumál"),
        (Quit, "Hætta"),
        (Connecting, "Tengist"),
        (Connected, "Tengt"),
        (ConnectionLost, "Tenging rofnaði"),
        (Reconnecting, "Tengist aftur"),
        (Fullscreen, "Allur skjárinn"),
        (PixelExact, "Dílanákvæmt"),
        (Stretch, "Laga að glugga"),
        (ShowOverlay, "Sýna tölfræði"),
        (Fps, "Rammar á sekúndu"),
        (DecodeTime, "Afkóðunartími"),
        (Bitrate, "Bitrate"),
        (Resolution, "Upplausn"),
        (Codec, "Codec"),
        (Latency, "Biðtími"),
        (EncodeTime, "Kóðunartími"),
        (NetworkTime, "Flutningstími"),
        (AudioBuffer, "Hljóðbiðminni"),
        (Dropped, "Týndir rammar"),
        (MaxBitrate, "Hámarks bitrate"),
        (MaxFps, "Hámarks rammatíðni"),
        (ExpertMode, "Sérfræðihamur"),
        (GamingMode, "Leikjahamur"),
        (FixedRate, "Föst rammatíðni"),
        (FixedRateHint, "Heldur rammatíðninni þótt ekkert hreyfist. Stöðugt álag á hýsilinn."),
        (Sound, "Hljóð"),
        (HoldEscHint, "Haltu ESC inni fyrir valmyndina"),
        (NerdMode, "Nördahamur"),
        (More, "Meira"),
        (Back, "Til baka"),
        (SavedForHost, "Vistað fyrir þennan hýsil"),
        (Queue, "Upptaka & bið"),
        (OneFrame, "Einn rammi"),
        (Bottleneck, "Flöskuháls"),
        (TabPicture, "Mynd"),
        (TabDisplay, "Birting"),
        (CodecConverted, "umbreytt"),
        (CodecSwitching, "Skiptir um codec"),
        (HostCpu, "Örgjörvi hýsils"),
        (HostGpu, "Skjákort hýsils"),
        (HostRam, "Minni hýsils"),
        (NoDisplay, "Hýsillinn hefur engan skjá í augnablikinu"),
        (Encryption, "Dulkóðun"),
        (EncryptionOn, "kveikt"),
        (EncryptionOff, "slökkt"),
        (AudioEnabled, "Hljóð"),
        (ClipboardEnabled, "Klippiborð"),
        (DecoderLabel, "Afkóðari"),
        (RoleAuto, "Sjálfvirkt"),
        (RoleCpu, "Örgjörvi"),
        (RoleGpu, "Skjákort"),
        (RoleGpuN, "Skjákort {n}"),
        (RoleIntegrated, "Innbyggt"),
        (NextStartHint, "gildir frá næstu ræsingu"),
        (AdapterWithOutput, "með skjátengi"),
        (AdapterNoOutput, "án skjátengis"),
        (TipOnly420, "Aðeins 4:2:0 og H.264 (D3D11VA); með 4:4:4 fellur biðlarinn aftur á örgjörvann – skiptu um codec í flipanum Mynd."),
        (DisplayLabel, "Birting"),
        (DisplayStage, "Birting"),
        (ClientCpu, "Örgjörvi biðlara"),
        (Monitor, "Skjár"),
        (Skipped, "sleppt"),
        (PairingTitle, "Para við hýsil"),
        (PairingHint, "Sláðu inn kóðann sem birtist á hýslinum"),
        (PairingCode, "Pörunarkóði"),
        (PairingWrong, "Rangur kóði"),
        (PairingOk, "Parað"),
        (SecuredWith, "Öruggt · staðfestingarkóði"),
        (HostFingerprint, "Fingrafar hýsilsins"),
        (NotPaired, "Þessi hýsill þekkir ekki tækið þitt enn. Ræstu hýsilinn með --pair og tengdu aftur."),
        (FirstContact, "Fyrsta tenging við þennan hýsil. Berðu kóðann saman við þann sem birtist á hýslinum."),
        (ErrorConnectRefused, "Hýsillinn hafnaði tengingunni"),
        (ErrorTimeout, "Hýsillinn svarar ekki"),
        (ErrorProtocol, "Hinn endinn notar annan samskiptastaðal"),
        (ErrorNoDecoder, "Enginn afkóðari fyrir þetta snið"),
        (SessionTakenOver, "Annað tæki hefur tekið yfir lotuna."),
        (HostKeyChanged, "Fingrafarið fyrir {n} hefur breyst (nú {m}). Tengingu hafnað. Ef hýsillinn var settur upp aftur skaltu eyða línu hans í {p}."),
        (KeyFileDamaged, "Lyklaskráin {p} er skemmd og var látin óbreytt. Athugaðu hana eða eyddu henni – þá verður til nýr lykill og hýsillinn þarf að para þetta tæki aftur."),
        (FileUnreadable, "Ekki er hægt að lesa {p} – engin tenging."),
        (FileNotUtf8, "{p} er ekki vistuð sem UTF-8 – engin tenging."),
        (FileNotWritable, "Ekki er hægt að skrifa í {p} – engin tenging."),
        (StorageUnavailable, "Mappan fyrir lykla og stillingar er ekki tiltæk – engin tenging."),
        (ErrorAddress, "Ekki tókst að fletta upp vistfanginu {n}"),
        (ErrorNoConnection, "Engin tenging við hýsilinn"),
        (ErrorHandshake, "Ekki tókst að koma á öruggri tengingu"),
        (ErrorFfmpegStart, "Ekki tókst að ræsa FFmpeg"),
        (ErrorSound, "Hljóð er ekki tiltækt"),
        (ErrorGpuDisplay, "Skjákortið er ónothæft, birting fer fram í hugbúnaði"),
        (ErrorGpuLost, "Skjákortið tapaðist – ræstu aftur með --anzeige cpu"),
        (ErrorPixelFormat, "Afkóðarinn skilar myndum sem þessi biðlari getur ekki birt"),
        (DecoderFallback, "Valda skjákortið afkóðar ekki – hugbúnaðarafkóðari í notkun"),
        (TipBitrate, "Efri mörk bitrate. Við hreyfingu nýtir kóðarinn þau öll; á ókunnum netum frekar 25 til 50."),
        (TipFps, "Æskileg rammatíðni. Meira en skjár Macsins skilar er ekki hægt."),
        (TipGaming, "Tíðari lykilrammar og minni leyfð uppsöfnun: jafnara við hreyfingu, kostar dálítið bitrate."),
        (TipSound, "Senda hljóð. Slökkt sparar um 3 Mbit/s; hýsillinn sendir þá ekkert hljóð."),
        (TipCodec, "Codec hýsilsins, skipt í gangi; myndin stöðvast augnablik. \"umbreytt\" kostar eina umferð til viðbótar."),
        (TipFullscreen, "Allur skjárinn án ramma. Í glugga er myndin löguð að."),
        (TipPixelExact, "Mynd 1:1 án skölunar. Sé glugginn minni sést aðeins hluti."),
        (TipShowOverlay, "Sýna tölfræðina efst til vinstri. Hvaða línur, sjá til hægri."),
        (TipNerdMode, "Ítarleg tölfræði: biðtímakeðjan sem súla, álag á hýsil og biðlara."),
        (TipStatRows, "Hvaða línur tölfræðin sýnir."),
        (TipDecoderAuto, "NVDEC á NVIDIA-korti; annars D3D11VA á kortinu sem teiknar (aðeins 4:2:0 og H.264); annars örgjörvinn."),
        (TipDecoderCpu, "Afkóða á örgjörvanum. Virkar alls staðar, kostar reiknitíma."),
        (TipDecoderGpu, "Afkóða á skjákortinu. Ráði það ekki við það fellur biðlarinn aftur á örgjörvann og segir hvers vegna."),
        (TipDecoderIntegrated, "Afkóða á innbyggða skjákortinu (D3D11VA). Ráði það ekki við það fellur biðlarinn aftur á örgjörvann og segir hvers vegna."),
        (TipDisplayAuto, "Direct3D 11 á fyrsta kortinu með skjátengi, annars fyrsta NVIDIA-kortinu, annars því fyrsta sem finnst. Án korts: örgjörvinn. Gildir frá næstu ræsingu."),
        (TipDisplayGpu, "Teikna með Direct3D 11 á þessu korti. Gildir frá næstu ræsingu."),
        (TipDisplayIntegrated, "Teikna með Direct3D 11 á innbyggða skjákortinu – því sem skjárinn er oftast tengdur við. Gildir frá næstu ræsingu."),
        (TipDisplayCpu, "Teikna á örgjörvanum, án Direct3D. Virkar alls staðar, kostar reiknitíma. Gildir frá næstu ræsingu."),
        (TipDisconnect, "Slíta tengingu, aftur á upphafsskjá."),
        (TabShortcuts, "Flýtilyklar"),
        (ShortcutMenu, "Opna valmyndina (þetta ESC berst aldrei til Macsins)"),
        (ShortcutBack, "Aftur á upphafsskjá"),
        (ShortcutWinKey, "Windows-lykill = skipanalykill Macsins"),
        (ShortcutOthers, "Allir aðrir lyklar fara til Macsins. Staða lykilsins er send, ekki táknið – broddstafir og AltGr virka af sjálfu sér."),
        // Benchmark
        (TabBenchmark, "Afkastapróf"),
        (BenchStart, "Byrja"),
        (BenchAbort, "Hætta við"),
        (BenchApply, "Nota"),
        (BenchDuration, "Tími á skref"),
        (BenchTestPattern, "Prófmynd"),
        (BenchStep, "Skref {n} af {m}"),
        (BenchPhaseSettings, "stillingar settar"),
        (BenchPhaseSettle, "jafnar sig"),
        (BenchPhaseMeasure, "mælir"),
        (BenchFailed, "mistókst"),
        (BenchDone, "Lokið"),
        (BenchAborted, "Hætt við"),
        (BenchMeasured, "mælt"),
        (BenchChain, "Keðja"),
        (BenchColFps, "fps"),
        (BenchColDropped, "týndir"),
        (BenchColHostCpu, "CPU hýsils"),
        (BenchRecommendation, "Ráðlegging"),
        (BenchNoRecommendation, "Ekkert skref stóðst: keðjan yfir 30 ms eða of fáir rammar. Prófaðu lægri rammatíðni eða bitrate."),
        (BenchHint, "Mælt er það sem gerist á Macnum núna. Skrefin eru aðeins samanburðarhæf ef eitthvað hreyfist – myndband í spilun nægir."),
        (BenchHintPattern, "Með prófmynd sér hvert skref sama hreyfða efnið – ekkert þarf að keyra á Macnum."),
        (TipBenchStart, "Mælir allar samsetningar valinna codeca, rammatíðna og bitrate hverja á fætur annarri, hverja í stilltan tíma. Myndin heldur áfram og valmyndin má vera opin."),
        (TipBenchApply, "Setja ráðlagðan codec og stillingar og vista fyrir þennan hýsil."),
        (TipBenchDuration, "Mælitími á skref. Lengri er stöðugri; 5 s duga yfirleitt."),
        (TipBenchHint, "Skref stenst ef að minnsta kosti 95 % af markrammatíðninni berast, undir 1 % rammanna týnast og öll keðjan helst innan 30 ms – óháð rammatíðni. Kóðaratími hýsilsins er sýndur en ekki metinn. Ráðlagt: bestu litgæðin sem standast við hæstu rammatíðni, með hæsta bitrate."),
        (TipBenchTestPattern, "Meðan á keyrslunni stendur sýnir hýsillinn fast hreyfimynstur í stað skjásins – hvert skref mælir sama efni."),
        (DesktopShortcut, "Flýtileið"),
        (TipDesktopShortcut, "Býr til flýtileið að þessum hýsli á skjáborðinu. Tvísmellur tengist strax."),
        (DesktopShortcutCreated, "Flýtileið búin til á skjáborðinu: {n}"),
        (DesktopShortcutFailed, "Flýtileið var ekki búin til: {n}"),
        (DesktopShortcutDescription, "QuadChroma: tengjast {n} ({m})"),
        (FilesSending, "Sendir skrár: {n} af {m}"),
        (FilesReceiving, "Tekur við skrám: {n} af {m}"),
        (FilesReady, "Skrár tilbúnar til að líma: {n}"),
        (FilesSent, "Skrár fluttar: {n}"),
        (FilesAborted, "Hætt var við skráaflutning: {n}"),
        (FilesTooLarge, "Skrár ekki fluttar: meira en 4 GB eða 10.000 atriði"),
        (FilesPeerOld, "Hin hliðin getur ekki enn tekið við skrám."),
        (TrayOpen, "Opna"),
        (TrayConnect, "Tengjast: {n}"),
        (TrayQuit, "Hætta"),
        (TrayStillRunning, "QuadChroma keyrir áfram á tilkynningasvæðinu."),
        (TrayStillRunningMac, "QuadChroma keyrir áfram á valmyndastikunni."),
        (FilesAbortLocal, "af þessu tæki"),
        (FilesAbortPeer, "af hinni hliðinni"),
        (FilesAbortConnection, "tenging rofnaði"),
        (FilesAbortTimeout, "tímamörk, engin framvinda"),
        (FilesAbortNoSpace, "ekki nóg diskpláss"),
        (FilesAbortInvalid, "ógild gögn"),
        (FilesAbortRead, "lesvilla"),
        (FilesAbortWrite, "skrifvilla"),
        (FilesAbortClipboard, "klippiborð ekki tiltækt"),
    ],
};
