// Sprachtabellen Ost- und Suedosteuropa:
// Polnisch, Tschechisch, Slowakisch, Ungarisch, Rumaenisch, Bulgarisch, Griechisch.

use crate::strings::{Key::*, Lang};

pub static PL: Lang = Lang {
    code: "pl",
    name: "Polski",
    table: &[
        (AppSubtitle, "Zdalny pulpit z pełnym odwzorowaniem kolorów"),
        (Connect, "Połącz"),
        (Disconnect, "Rozłącz"),
        (HostAddress, "Adres hosta"),
        (SearchingHosts, "Wyszukiwanie hostów"),
        (NoHostsFound, "Nie znaleziono hostów"),
        (FoundHosts, "Znalezione hosty"),
        (Settings, "Ustawienia"),
        (Language, "Język"),
        (Quit, "Zakończ"),
        (Connecting, "Łączenie"),
        (Connected, "Połączono"),
        (ConnectionLost, "Utracono połączenie"),
        (Reconnecting, "Ponowne łączenie"),
        (Fullscreen, "Pełny ekran"),
        (PixelExact, "Piksel w piksel"),
        (Stretch, "Dopasuj do okna"),
        (ShowOverlay, "Pokaż statystyki"),
        (Fps, "Klatki na sekundę"),
        (DecodeTime, "Czas dekodowania"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozdzielczość"),
        (Codec, "Kodek"),
        (Latency, "Opóźnienie"),
        (EncodeTime, "Czas kodowania"),
        (NetworkTime, "Czas transmisji"),
        (AudioBuffer, "Bufor dźwięku"),
        (Dropped, "Pominięte klatki"),
        (MaxBitrate, "Maksymalny bitrate"),
        (MaxFps, "Maksymalna liczba klatek"),
        (ExpertMode, "Tryb eksperta"),
        (GamingMode, "Tryb gry"),
        (FixedRate, "Stała liczba klatek"),
        (FixedRateHint, "Utrzymuje liczbę klatek, nawet gdy nic się nie porusza. Stałe obciążenie hosta."),
        (HoldEscHint, "Trzymaj ESC, aby otworzyć menu"),
        (NerdMode, "Tryb nerda"),
        (More, "Więcej"),
        (Back, "Wstecz"),
        (SavedForHost, "Zapisano dla tego hosta"),
        (Queue, "Przechwyt i kolejka"),
        (OneFrame, "Jedna klatka"),
        (Bottleneck, "Wąskie gardło"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Ekran"),
        (CodecConverted, "z konwersją"),
        (CodecSwitching, "Zmiana kodeka"),
        (HostCpu, "Procesor hosta"),
        (HostGpu, "Grafika hosta"),
        (HostRam, "Pamięć hosta"),
        (Encryption, "Szyfrowanie"),
        (EncryptionOn, "wł."),
        (EncryptionOff, "wył."),
        (AudioEnabled, "Dźwięk"),
        (ClipboardEnabled, "Schowek"),
        (PairingTitle, "Parowanie z hostem"),
        (PairingHint, "Wpisz kod wyświetlony na hoście"),
        (PairingCode, "Kod parowania"),
        (PairingWrong, "Błędny kod"),
        (PairingOk, "Sparowano"),
        (SecuredWith, "Zabezpieczone · kod weryfikacyjny"),
        (HostFingerprint, "Odcisk klucza hosta"),
        (NotPaired, "Ten host jeszcze nie zna twojego urządzenia. Uruchom hosta z opcją --pair i połącz się ponownie."),
        (FirstContact, "Pierwszy kontakt z tym hostem. Porównaj kod z tym na hoście."),
        (ErrorConnectRefused, "Host odrzucił połączenie"),
        (ErrorTimeout, "Host nie odpowiada"),
        (ErrorProtocol, "Druga strona używa innego protokołu"),
        (ErrorNoDecoder, "Brak dekodera dla tego formatu"),
    ],
};

pub static CS: Lang = Lang {
    code: "cs",
    name: "Čeština",
    table: &[
        (AppSubtitle, "Vzdálená plocha s plným barevným podáním"),
        (Connect, "Připojit"),
        (Disconnect, "Odpojit"),
        (HostAddress, "Adresa hostitele"),
        (SearchingHosts, "Hledání hostitelů"),
        (NoHostsFound, "Žádný hostitel nenalezen"),
        (FoundHosts, "Nalezení hostitelé"),
        (Settings, "Nastavení"),
        (Language, "Jazyk"),
        (Quit, "Ukončit"),
        (Connecting, "Připojování"),
        (Connected, "Připojeno"),
        (ConnectionLost, "Spojení přerušeno"),
        (Reconnecting, "Obnovování spojení"),
        (Fullscreen, "Celá obrazovka"),
        (PixelExact, "Přesně na pixel"),
        (Stretch, "Přizpůsobit oknu"),
        (ShowOverlay, "Zobrazit statistiky"),
        (Fps, "Snímky za sekundu"),
        (DecodeTime, "Doba dekódování"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozlišení"),
        (Codec, "Kodek"),
        (Latency, "Latence"),
        (EncodeTime, "Doba kódování"),
        (NetworkTime, "Doba přenosu"),
        (AudioBuffer, "Zvukový buffer"),
        (Dropped, "Zahozené snímky"),
        (MaxBitrate, "Maximální bitrate"),
        (MaxFps, "Maximální snímková frekvence"),
        (ExpertMode, "Expertní režim"),
        (GamingMode, "Herní režim"),
        (FixedRate, "Pevná snímková frekvence"),
        (FixedRateHint, "Udržuje snímkovou frekvenci, i když se nic nehýbe. Trvalá zátěž hostitele."),
        (HoldEscHint, "Držte ESC pro nabídku"),
        (NerdMode, "Nerdovský režim"),
        (More, "Více"),
        (Back, "Zpět"),
        (SavedForHost, "Uloženo pro tohoto hostitele"),
        (Queue, "Snímání a fronta"),
        (OneFrame, "Jeden snímek"),
        (Bottleneck, "Úzké hrdlo"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Zobrazení"),
        (CodecConverted, "s převodem"),
        (CodecSwitching, "Přepínání kodeku"),
        (HostCpu, "Procesor hostitele"),
        (HostGpu, "Grafika hostitele"),
        (HostRam, "Paměť hostitele"),
        (Encryption, "Šifrování"),
        (EncryptionOn, "zap."),
        (EncryptionOff, "vyp."),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Schránka"),
        (PairingTitle, "Spárovat s hostitelem"),
        (PairingHint, "Zadejte kód zobrazený na hostiteli"),
        (PairingCode, "Párovací kód"),
        (PairingWrong, "Špatný kód"),
        (PairingOk, "Spárováno"),
        (SecuredWith, "Zabezpečeno · ověřovací kód"),
        (HostFingerprint, "Otisk klíče hostitele"),
        (NotPaired, "Tento hostitel zatím nezná vaše zařízení. Spusťte hostitele s volbou --pair a připojte se znovu."),
        (FirstContact, "První kontakt s tímto hostitelem. Porovnejte kód s tím na hostiteli."),
        (ErrorConnectRefused, "Hostitel odmítl spojení"),
        (ErrorTimeout, "Hostitel neodpovídá"),
        (ErrorProtocol, "Protistrana používá jiný protokol"),
        (ErrorNoDecoder, "Pro tento formát chybí dekodér"),
    ],
};

pub static SK: Lang = Lang {
    code: "sk",
    name: "Slovenčina",
    table: &[
        (AppSubtitle, "Vzdialená plocha s plným podaním farieb"),
        (Connect, "Pripojiť"),
        (Disconnect, "Odpojiť"),
        (HostAddress, "Adresa hostiteľa"),
        (SearchingHosts, "Hľadanie hostiteľov"),
        (NoHostsFound, "Nenašiel sa žiadny hostiteľ"),
        (FoundHosts, "Nájdení hostitelia"),
        (Settings, "Nastavenia"),
        (Language, "Jazyk"),
        (Quit, "Ukončiť"),
        (Connecting, "Pripájanie"),
        (Connected, "Pripojené"),
        (ConnectionLost, "Spojenie prerušené"),
        (Reconnecting, "Obnovovanie spojenia"),
        (Fullscreen, "Celá obrazovka"),
        (PixelExact, "Presne na pixel"),
        (Stretch, "Prispôsobiť oknu"),
        (ShowOverlay, "Zobraziť štatistiky"),
        (Fps, "Snímky za sekundu"),
        (DecodeTime, "Čas dekódovania"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rozlíšenie"),
        (Codec, "Kodek"),
        (Latency, "Latencia"),
        (EncodeTime, "Čas kódovania"),
        (NetworkTime, "Čas prenosu"),
        (AudioBuffer, "Zvukový buffer"),
        (Dropped, "Zahodené snímky"),
        (MaxBitrate, "Maximálny bitrate"),
        (MaxFps, "Maximálna snímková frekvencia"),
        (ExpertMode, "Expertný režim"),
        (GamingMode, "Herný režim"),
        (FixedRate, "Pevná snímková frekvencia"),
        (FixedRateHint, "Udržiava snímkovú frekvenciu, aj keď sa nič nehýbe. Trvalá záťaž hostiteľa."),
        (HoldEscHint, "Držte ESC pre ponuku"),
        (NerdMode, "Nerdovský režim"),
        (More, "Viac"),
        (Back, "Späť"),
        (SavedForHost, "Uložené pre tohto hostiteľa"),
        (Queue, "Snímanie a fronta"),
        (OneFrame, "Jeden snímok"),
        (Bottleneck, "Úzke hrdlo"),
        (TabPicture, "Obraz"),
        (TabDisplay, "Zobrazenie"),
        (CodecConverted, "s prevodom"),
        (CodecSwitching, "Prepínanie kodeku"),
        (HostCpu, "Procesor hostiteľa"),
        (HostGpu, "Grafika hostiteľa"),
        (HostRam, "Pamäť hostiteľa"),
        (Encryption, "Šifrovanie"),
        (EncryptionOn, "zap."),
        (EncryptionOff, "vyp."),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Schránka"),
        (PairingTitle, "Spárovať s hostiteľom"),
        (PairingHint, "Zadajte kód zobrazený na hostiteľovi"),
        (PairingCode, "Párovací kód"),
        (PairingWrong, "Nesprávny kód"),
        (PairingOk, "Spárované"),
        (SecuredWith, "Zabezpečené · overovací kód"),
        (HostFingerprint, "Odtlačok kľúča hostiteľa"),
        (NotPaired, "Tento hostiteľ zatiaľ nepozná vaše zariadenie. Spustite hostiteľa s voľbou --pair a pripojte sa znova."),
        (FirstContact, "Prvý kontakt s týmto hostiteľom. Porovnajte kód s tým na hostiteľovi."),
        (ErrorConnectRefused, "Hostiteľ odmietol spojenie"),
        (ErrorTimeout, "Hostiteľ neodpovedá"),
        (ErrorProtocol, "Druhá strana používa iný protokol"),
        (ErrorNoDecoder, "Pre tento formát chýba dekodér"),
    ],
};

pub static HU: Lang = Lang {
    code: "hu",
    name: "Magyar",
    table: &[
        (AppSubtitle, "Távoli asztal teljes színhűséggel"),
        (Connect, "Csatlakozás"),
        (Disconnect, "Kapcsolat bontása"),
        (HostAddress, "Gazdagép címe"),
        (SearchingHosts, "Gazdagépek keresése"),
        (NoHostsFound, "Nem található gazdagép"),
        (FoundHosts, "Megtalált gazdagépek"),
        (Settings, "Beállítások"),
        (Language, "Nyelv"),
        (Quit, "Kilépés"),
        (Connecting, "Kapcsolódás"),
        (Connected, "Csatlakozva"),
        (ConnectionLost, "A kapcsolat megszakadt"),
        (Reconnecting, "Újracsatlakozás"),
        (Fullscreen, "Teljes képernyő"),
        (PixelExact, "Pixelpontos"),
        (Stretch, "Ablakhoz igazítás"),
        (ShowOverlay, "Statisztika mutatása"),
        (Fps, "Képkocka/másodperc"),
        (DecodeTime, "Dekódolási idő"),
        (Bitrate, "Bitráta"),
        (Resolution, "Felbontás"),
        (Codec, "Kodek"),
        (Latency, "Késleltetés"),
        (EncodeTime, "Kódolási idő"),
        (NetworkTime, "Átviteli idő"),
        (AudioBuffer, "Hangpuffer"),
        (Dropped, "Eldobott képkockák"),
        (MaxBitrate, "Maximális bitráta"),
        (MaxFps, "Maximális képkockaszám"),
        (ExpertMode, "Szakértői mód"),
        (GamingMode, "Játékmód"),
        (FixedRate, "Állandó képkockaszám"),
        (FixedRateHint, "Tartja a képkockaszámot akkor is, ha semmi nem mozog. Folyamatos terhelés a gazdagépen."),
        (HoldEscHint, "Tartsa nyomva az ESC-et a menühöz"),
        (NerdMode, "Nerd mód"),
        (More, "Több"),
        (Back, "Vissza"),
        (SavedForHost, "Mentve ehhez a gazdagéphez"),
        (Queue, "Rögzítés és sor"),
        (OneFrame, "Egy képkocka"),
        (Bottleneck, "Szűk keresztmetszet"),
        (TabPicture, "Kép"),
        (TabDisplay, "Megjelenítés"),
        (CodecConverted, "átalakítva"),
        (CodecSwitching, "Kodekváltás"),
        (HostCpu, "Gazdagép CPU-ja"),
        (HostGpu, "Gazdagép GPU-ja"),
        (HostRam, "Gazdagép memóriája"),
        (Encryption, "Titkosítás"),
        (EncryptionOn, "be"),
        (EncryptionOff, "ki"),
        (AudioEnabled, "Hang"),
        (ClipboardEnabled, "Vágólap"),
        (PairingTitle, "Párosítás a gazdagéppel"),
        (PairingHint, "Írja be a gazdagépen látható kódot"),
        (PairingCode, "Párosítási kód"),
        (PairingWrong, "Hibás kód"),
        (PairingOk, "Párosítva"),
        (SecuredWith, "Védett · ellenőrző kód"),
        (HostFingerprint, "Gazdagép ujjlenyomata"),
        (NotPaired, "Ez a gazdagép még nem ismeri az eszközét. Indítsa el a gazdagépet a --pair kapcsolóval, és csatlakozzon újra."),
        (FirstContact, "Első kapcsolat ezzel a gazdagéppel. Hasonlítsa össze a kódot a gazdagépen láthatóval."),
        (ErrorConnectRefused, "A gazdagép elutasította a kapcsolatot"),
        (ErrorTimeout, "A gazdagép nem válaszol"),
        (ErrorProtocol, "A túloldal más protokollt használ"),
        (ErrorNoDecoder, "Nincs dekóder ehhez a formátumhoz"),
    ],
};

pub static RO: Lang = Lang {
    code: "ro",
    name: "Română",
    table: &[
        (AppSubtitle, "Desktop la distanță cu culori complete"),
        (Connect, "Conectare"),
        (Disconnect, "Deconectare"),
        (HostAddress, "Adresa gazdei"),
        (SearchingHosts, "Se caută gazde"),
        (NoHostsFound, "Nicio gazdă găsită"),
        (FoundHosts, "Gazde găsite"),
        (Settings, "Setări"),
        (Language, "Limbă"),
        (Quit, "Ieșire"),
        (Connecting, "Se conectează"),
        (Connected, "Conectat"),
        (ConnectionLost, "Conexiune pierdută"),
        (Reconnecting, "Se reconectează"),
        (Fullscreen, "Ecran complet"),
        (PixelExact, "Exact pe pixel"),
        (Stretch, "Potrivire la fereastră"),
        (ShowOverlay, "Afișează statisticile"),
        (Fps, "Cadre pe secundă"),
        (DecodeTime, "Timp de decodare"),
        (Bitrate, "Bitrate"),
        (Resolution, "Rezoluție"),
        (Codec, "Codec"),
        (Latency, "Latență"),
        (EncodeTime, "Codare"),
        (NetworkTime, "Transfer"),
        (AudioBuffer, "Buffer audio"),
        (Dropped, "Pierdute"),
        (MaxBitrate, "Bitrate maxim"),
        (MaxFps, "Rată maximă de cadre"),
        (ExpertMode, "Mod expert"),
        (GamingMode, "Mod joc"),
        (FixedRate, "Rată fixă de cadre"),
        (FixedRateHint, "Menține rata chiar și când nimic nu se mișcă. Încărcare continuă pe gazdă."),
        (HoldEscHint, "Țineți ESC apăsat pentru meniu"),
        (NerdMode, "Mod nerd"),
        (More, "Mai multe"),
        (Back, "Înapoi"),
        (SavedForHost, "Salvat pentru această gazdă"),
        (Queue, "Captură și coadă"),
        (OneFrame, "Un cadru"),
        (Bottleneck, "Gâtuire"),
        (TabPicture, "Imagine"),
        (TabDisplay, "Afișare"),
        (CodecConverted, "cu conversie"),
        (CodecSwitching, "Se schimbă codecul"),
        (HostCpu, "Procesorul gazdei"),
        (HostGpu, "Grafica gazdei"),
        (HostRam, "Memoria gazdei"),
        (Encryption, "Criptare"),
        (EncryptionOn, "pornită"),
        (EncryptionOff, "oprită"),
        (AudioEnabled, "Sunet"),
        (ClipboardEnabled, "Clipboard"),
        (PairingTitle, "Asociere cu gazda"),
        (PairingHint, "Introduceți codul afișat pe gazdă"),
        (PairingCode, "Cod de asociere"),
        (PairingWrong, "Cod greșit"),
        (PairingOk, "Asociat"),
        (SecuredWith, "Securizat · cod de verificare"),
        (HostFingerprint, "Amprenta gazdei"),
        (NotPaired, "Această gazdă nu cunoaște încă dispozitivul dvs. Porniți gazda cu --pair și conectați-vă din nou."),
        (FirstContact, "Primul contact cu această gazdă. Comparați codul cu cel afișat pe gazdă."),
        (ErrorConnectRefused, "Gazda a refuzat conexiunea"),
        (ErrorTimeout, "Gazda nu răspunde"),
        (ErrorProtocol, "Cealaltă parte folosește alt protocol"),
        (ErrorNoDecoder, "Nu există decodor pentru acest format"),
    ],
};

pub static BG: Lang = Lang {
    code: "bg",
    name: "Български",
    table: &[
        (AppSubtitle, "Отдалечен работен плот с пълни цветове"),
        (Connect, "Свързване"),
        (Disconnect, "Прекъсване"),
        (HostAddress, "Адрес на хоста"),
        (SearchingHosts, "Търсене на хостове"),
        (NoHostsFound, "Няма намерени хостове"),
        (FoundHosts, "Намерени хостове"),
        (Settings, "Настройки"),
        (Language, "Език"),
        (Quit, "Изход"),
        (Connecting, "Свързва се"),
        (Connected, "Свързано"),
        (ConnectionLost, "Връзката прекъсна"),
        (Reconnecting, "Повторно свързване"),
        (Fullscreen, "Цял екран"),
        (PixelExact, "Точно по пиксели"),
        (Stretch, "Побиране в прозореца"),
        (ShowOverlay, "Показване на статистика"),
        (Fps, "Кадри в секунда"),
        (DecodeTime, "Време за декодиране"),
        (Bitrate, "Битрейт"),
        (Resolution, "Резолюция"),
        (Codec, "Кодек"),
        (Latency, "Закъснение"),
        (EncodeTime, "Кодиране"),
        (NetworkTime, "Пренос"),
        (AudioBuffer, "Аудио буфер"),
        (Dropped, "Пропуснати"),
        (MaxBitrate, "Максимален битрейт"),
        (MaxFps, "Максимални кадри в секунда"),
        (ExpertMode, "Експертен режим"),
        (GamingMode, "Игрови режим"),
        (FixedRate, "Постоянни кадри в секунда"),
        (FixedRateHint, "Запазва честотата, дори когато нищо не се движи. Постоянно натоварване на хоста."),
        (HoldEscHint, "Задръжте ESC за менюто"),
        (NerdMode, "Режим за маниаци"),
        (More, "Още"),
        (Back, "Назад"),
        (SavedForHost, "Запазено за този хост"),
        (Queue, "Заснемане и чакане"),
        (OneFrame, "Един кадър"),
        (Bottleneck, "Тясно място"),
        (TabPicture, "Картина"),
        (TabDisplay, "Екран"),
        (CodecConverted, "с преобразуване"),
        (CodecSwitching, "Сменя се кодекът"),
        (HostCpu, "Процесор на хоста"),
        (HostGpu, "Графика на хоста"),
        (HostRam, "Памет на хоста"),
        (Encryption, "Шифроване"),
        (EncryptionOn, "вкл."),
        (EncryptionOff, "изкл."),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Клипборд"),
        (PairingTitle, "Сдвояване с хоста"),
        (PairingHint, "Въведете кода, показан на хоста"),
        (PairingCode, "Код за сдвояване"),
        (PairingWrong, "Грешен код"),
        (PairingOk, "Сдвоено"),
        (SecuredWith, "Защитено · код за проверка"),
        (HostFingerprint, "Отпечатък на хоста"),
        (NotPaired, "Този хост още не познава устройството ви. Стартирайте хоста с --pair и се свържете отново."),
        (FirstContact, "Първи контакт с този хост. Сравнете кода с този на хоста."),
        (ErrorConnectRefused, "Хостът отказа връзката"),
        (ErrorTimeout, "Хостът не отговаря"),
        (ErrorProtocol, "Отсрещната страна използва друг протокол"),
        (ErrorNoDecoder, "Няма декодер за този формат"),
    ],
};

pub static EL: Lang = Lang {
    code: "el",
    name: "Ελληνικά",
    table: &[
        (AppSubtitle, "Απομακρυσμένη επιφάνεια με πλήρη χρώματα"),
        (Connect, "Σύνδεση"),
        (Disconnect, "Αποσύνδεση"),
        (HostAddress, "Διεύθυνση host"),
        (SearchingHosts, "Αναζήτηση host"),
        (NoHostsFound, "Δεν βρέθηκαν host"),
        (FoundHosts, "Host που βρέθηκαν"),
        (Settings, "Ρυθμίσεις"),
        (Language, "Γλώσσα"),
        (Quit, "Έξοδος"),
        (Connecting, "Γίνεται σύνδεση"),
        (Connected, "Συνδεδεμένο"),
        (ConnectionLost, "Η σύνδεση χάθηκε"),
        (Reconnecting, "Επανασύνδεση"),
        (Fullscreen, "Πλήρης οθόνη"),
        (PixelExact, "Ακριβώς σε pixel"),
        (Stretch, "Προσαρμογή στο παράθυρο"),
        (ShowOverlay, "Εμφάνιση στατιστικών"),
        (Fps, "Καρέ ανά δευτερόλεπτο"),
        (DecodeTime, "Χρόνος αποκωδικοποίησης"),
        (Bitrate, "Bitrate"),
        (Resolution, "Ανάλυση"),
        (Codec, "Codec"),
        (Latency, "Καθυστέρηση"),
        (EncodeTime, "Κωδικοποίηση"),
        (NetworkTime, "Μετάδοση"),
        (AudioBuffer, "Buffer ήχου"),
        (Dropped, "Χαμένα"),
        (MaxBitrate, "Μέγιστο bitrate"),
        (MaxFps, "Μέγιστος ρυθμός καρέ"),
        (ExpertMode, "Λειτουργία για προχωρημένους"),
        (GamingMode, "Λειτουργία παιχνιδιού"),
        (FixedRate, "Σταθερός ρυθμός καρέ"),
        (FixedRateHint, "Διατηρεί τον ρυθμό ακόμη και όταν δεν κινείται τίποτα. Συνεχής φόρτος στον host."),
        (HoldEscHint, "Κρατήστε το ESC για το μενού"),
        (NerdMode, "Λειτουργία nerd"),
        (More, "Περισσότερα"),
        (Back, "Πίσω"),
        (SavedForHost, "Αποθηκεύτηκε για αυτόν τον host"),
        (Queue, "Λήψη και αναμονή"),
        (OneFrame, "Ένα καρέ"),
        (Bottleneck, "Σημείο συμφόρησης"),
        (TabPicture, "Εικόνα"),
        (TabDisplay, "Προβολή"),
        (CodecConverted, "με μετατροπή"),
        (CodecSwitching, "Γίνεται αλλαγή codec"),
        (HostCpu, "CPU host"),
        (HostGpu, "GPU host"),
        (HostRam, "Μνήμη host"),
        (Encryption, "Κρυπτογράφηση"),
        (EncryptionOn, "ενεργή"),
        (EncryptionOff, "ανενεργή"),
        (AudioEnabled, "Ήχος"),
        (ClipboardEnabled, "Πρόχειρο"),
        (PairingTitle, "Σύζευξη με τον host"),
        (PairingHint, "Εισαγάγετε τον κωδικό που δείχνει ο host"),
        (PairingCode, "Κωδικός σύζευξης"),
        (PairingWrong, "Λάθος κωδικός"),
        (PairingOk, "Έγινε σύζευξη"),
        (SecuredWith, "Ασφαλές · κωδικός επαλήθευσης"),
        (HostFingerprint, "Αποτύπωμα του host"),
        (NotPaired, "Αυτός ο host δεν γνωρίζει ακόμη τη συσκευή σας. Εκκινήστε τον host με --pair και συνδεθείτε ξανά."),
        (FirstContact, "Πρώτη επαφή με αυτόν τον host. Συγκρίνετε τον κωδικό με αυτόν στον host."),
        (ErrorConnectRefused, "Ο host απέρριψε τη σύνδεση"),
        (ErrorTimeout, "Ο host δεν απαντά"),
        (ErrorProtocol, "Η άλλη πλευρά χρησιμοποιεί άλλο πρωτόκολλο"),
        (ErrorNoDecoder, "Δεν υπάρχει decoder για αυτή τη μορφή"),
    ],
};
