// Sprachtabellen: Estnisch, Lettisch, Litauisch, Slowenisch, Kroatisch,
// Ukrainisch. Aufbau und Schluessel wie in strings.rs.

use crate::strings::{Key::*, Lang};

pub static ET: Lang = Lang {
    code: "et",
    name: "Eesti",
    table: &[
        (AppSubtitle, "Kaugtöölaud täieliku värvitäpsusega"),
        (Connect, "Ühenda"),
        (Disconnect, "Katkesta ühendus"),
        (HostAddress, "Hosti aadress"),
        (SearchingHosts, "Otsin hoste"),
        (NoHostsFound, "Hoste ei leitud"),
        (FoundHosts, "Leitud hostid"),
        (Settings, "Sätted"),
        (Language, "Keel"),
        (Quit, "Välju"),
        (Connecting, "Ühendan"),
        (Connected, "Ühendatud"),
        (ConnectionLost, "Ühendus katkes"),
        (Reconnecting, "Ühendan uuesti"),
        (Fullscreen, "Täisekraan"),
        (PixelExact, "Pikslitäpne"),
        (Stretch, "Sobita aknasse"),
        (ShowOverlay, "Näita statistikat"),
        (Fps, "Kaadrit sekundis"),
        (DecodeTime, "Dekodeerimisaeg"),
        (Bitrate, "Bitikiirus"),
        (Resolution, "Eraldusvõime"),
        (Codec, "Koodek"),
        (Latency, "Viivitus"),
        (EncodeTime, "Kodeerimisaeg"),
        (NetworkTime, "Ülekandeaeg"),
        (AudioBuffer, "Helipuhver"),
        (Dropped, "Vahelejäänud"),
        (MaxBitrate, "Suurim bitikiirus"),
        (MaxFps, "Suurim kaadrisagedus"),
        (ExpertMode, "Eksperdirežiim"),
        (GamingMode, "Mängurežiim"),
        (FixedRate, "Püsiv kaadrisagedus"),
        (FixedRateHint, "Hoiab kaadrisagedust ka siis, kui miski ei liigu. Pidev koormus hostile."),
        (Sound, "Heli"),
        (HoldEscHint, "Hoia ESC all menüü avamiseks"),
        (NerdMode, "Tehniline vaade"),
        (More, "Veel"),
        (Back, "Tagasi"),
        (SavedForHost, "Salvestatud selle hosti jaoks"),
        (Queue, "Hõive ja ootamine"),
        (OneFrame, "Üks kaader"),
        (Bottleneck, "Kitsaskoht"),
        (TabPicture, "Pilt"),
        (TabDisplay, "Kuva"),
        (CodecConverted, "teisendatud"),
        (CodecSwitching, "Vahetan koodekit"),
        (HostCpu, "Hosti protsessor"),
        (HostGpu, "Hosti graafika"),
        (HostRam, "Hosti mälu"),
        (NoDisplay, "Hostil pole praegu ekraani"),
        (Encryption, "Krüptimine"),
        (EncryptionOn, "sees"),
        (EncryptionOff, "väljas"),
        (AudioEnabled, "Heli"),
        (ClipboardEnabled, "Lõikelaud"),
        (DecoderLabel, "Dekooder"),
        (DecoderAuto, "Automaatne"),
        (DecoderSoftware, "Tarkvara"),
        (DecoderNvidia, "Graafikakaart"),
        (PairingTitle, "Seo hostiga"),
        (PairingHint, "Sisesta hostis kuvatud kood"),
        (PairingCode, "Sidumiskood"),
        (PairingWrong, "Vale kood"),
        (PairingOk, "Seotud"),
        (SecuredWith, "Turvatud · kontrollkood"),
        (HostFingerprint, "Hosti sõrmejälg"),
        (NotPaired, "See host ei tunne veel sinu seadet. Käivita host võtmega --pair ja ühenda uuesti."),
        (FirstContact, "Esimene kontakt selle hostiga. Võrdle koodi hostis kuvatuga."),
        (ErrorConnectRefused, "Host keeldus ühendusest"),
        (ErrorTimeout, "Host ei vastanud"),
        (ErrorProtocol, "Teine pool kasutab teist protokolli"),
        (ErrorNoDecoder, "Selle vormingu jaoks pole dekoodrit"),
    ],
};

pub static LV: Lang = Lang {
    code: "lv",
    name: "Latviešu",
    table: &[
        (AppSubtitle, "Attālā darbvirsma ar pilnu krāsu detalizāciju"),
        (Connect, "Savienot"),
        (Disconnect, "Atvienot"),
        (HostAddress, "Hosta adrese"),
        (SearchingHosts, "Meklē hostus"),
        (NoHostsFound, "Hosti nav atrasti"),
        (FoundHosts, "Atrastie hosti"),
        (Settings, "Iestatījumi"),
        (Language, "Valoda"),
        (Quit, "Iziet"),
        (Connecting, "Savienojas"),
        (Connected, "Savienots"),
        (ConnectionLost, "Savienojums pārtrūka"),
        (Reconnecting, "Savienojas atkārtoti"),
        (Fullscreen, "Pilnekrāns"),
        (PixelExact, "Pikseļu precizitāte"),
        (Stretch, "Ietilpināt logā"),
        (ShowOverlay, "Rādīt statistiku"),
        (Fps, "Kadri sekundē"),
        (DecodeTime, "Dekodēšanas laiks"),
        (Bitrate, "Bitu ātrums"),
        (Resolution, "Izšķirtspēja"),
        (Codec, "Kodeks"),
        (Latency, "Aizkave"),
        (EncodeTime, "Kodēšanas laiks"),
        (NetworkTime, "Pārraides laiks"),
        (AudioBuffer, "Audio buferis"),
        (Dropped, "Izlaisti"),
        (MaxBitrate, "Maksimālais bitu ātrums"),
        (MaxFps, "Maksimālais kadru ātrums"),
        (ExpertMode, "Eksperta režīms"),
        (GamingMode, "Spēļu režīms"),
        (FixedRate, "Fiksēts kadru ātrums"),
        (FixedRateHint, "Uztur kadru ātrumu arī tad, kad nekas nekustas. Pastāvīga slodze hostam."),
        (Sound, "Skaņa"),
        (HoldEscHint, "Turiet ESC, lai atvērtu izvēlni"),
        (NerdMode, "Nerda režīms"),
        (More, "Vairāk"),
        (Back, "Atpakaļ"),
        (SavedForHost, "Saglabāts šim hostam"),
        (Queue, "Uzņemšana un rinda"),
        (OneFrame, "Viens kadrs"),
        (Bottleneck, "Šaurā vieta"),
        (TabPicture, "Attēls"),
        (TabDisplay, "Ekrāns"),
        (CodecConverted, "konvertēts"),
        (CodecSwitching, "Pārslēdz kodeku"),
        (HostCpu, "Hosta procesors"),
        (HostGpu, "Hosta grafika"),
        (HostRam, "Hosta atmiņa"),
        (NoDisplay, "Hostam pašlaik nav ekrāna"),
        (Encryption, "Šifrēšana"),
        (EncryptionOn, "ieslēgta"),
        (EncryptionOff, "izslēgta"),
        (AudioEnabled, "Skaņa"),
        (ClipboardEnabled, "Starpliktuve"),
        (DecoderLabel, "Dekoders"),
        (DecoderAuto, "Automātiski"),
        (DecoderSoftware, "Programmatūra"),
        (DecoderNvidia, "Videokarte"),
        (PairingTitle, "Savienot pārī ar hostu"),
        (PairingHint, "Ievadiet hostā redzamo kodu"),
        (PairingCode, "Savienošanas kods"),
        (PairingWrong, "Nepareizs kods"),
        (PairingOk, "Savienots pārī"),
        (SecuredWith, "Aizsargāts · pārbaudes kods"),
        (HostFingerprint, "Hosta atslēgas nospiedums"),
        (NotPaired, "Šis hosts vēl nepazīst jūsu ierīci. Palaidiet hostu ar --pair un savienojiet vēlreiz."),
        (FirstContact, "Pirmais kontakts ar šo hostu. Salīdziniet kodu ar to, kas redzams hostā."),
        (ErrorConnectRefused, "Hosts noraidīja savienojumu"),
        (ErrorTimeout, "Hosts neatbildēja"),
        (ErrorProtocol, "Otra puse lieto citu protokolu"),
        (ErrorNoDecoder, "Šim formātam nav dekodera"),
    ],
};

pub static LT: Lang = Lang {
    code: "lt",
    name: "Lietuvių",
    table: &[
        (AppSubtitle, "Nuotolinis darbalaukis su visa spalvų raiška"),
        (Connect, "Prisijungti"),
        (Disconnect, "Atsijungti"),
        (HostAddress, "Hosto adresas"),
        (SearchingHosts, "Ieškoma hostų"),
        (NoHostsFound, "Hostų nerasta"),
        (FoundHosts, "Rasti hostai"),
        (Settings, "Nustatymai"),
        (Language, "Kalba"),
        (Quit, "Išeiti"),
        (Connecting, "Jungiamasi"),
        (Connected, "Prisijungta"),
        (ConnectionLost, "Ryšys nutrūko"),
        (Reconnecting, "Jungiamasi iš naujo"),
        (Fullscreen, "Visas ekranas"),
        (PixelExact, "Pikselių tikslumas"),
        (Stretch, "Pritaikyti prie lango"),
        (ShowOverlay, "Rodyti statistiką"),
        (Fps, "Kadrai per sekundę"),
        (DecodeTime, "Dekodavimo laikas"),
        (Bitrate, "Bitų sparta"),
        (Resolution, "Skiriamoji geba"),
        (Codec, "Kodekas"),
        (Latency, "Delsa"),
        (EncodeTime, "Kodavimo laikas"),
        (NetworkTime, "Perdavimo laikas"),
        (AudioBuffer, "Garso buferis"),
        (Dropped, "Praleista"),
        (MaxBitrate, "Didžiausia bitų sparta"),
        (MaxFps, "Didžiausias kadrų dažnis"),
        (ExpertMode, "Eksperto režimas"),
        (GamingMode, "Žaidimų režimas"),
        (FixedRate, "Pastovus kadrų dažnis"),
        (FixedRateHint, "Išlaiko kadrų dažnį, net kai niekas nejuda. Nuolatinė hosto apkrova."),
        (Sound, "Garsas"),
        (HoldEscHint, "Laikykite ESC, kad atsidarytų meniu"),
        (NerdMode, "Nerdo režimas"),
        (More, "Daugiau"),
        (Back, "Atgal"),
        (SavedForHost, "Įrašyta šiam hostui"),
        (Queue, "Fiksavimas ir eilė"),
        (OneFrame, "Vienas kadras"),
        (Bottleneck, "Siauroji vieta"),
        (TabPicture, "Vaizdas"),
        (TabDisplay, "Ekranas"),
        (CodecConverted, "konvertuota"),
        (CodecSwitching, "Keičiamas kodekas"),
        (HostCpu, "Hosto procesorius"),
        (HostGpu, "Hosto grafika"),
        (HostRam, "Hosto atmintis"),
        (NoDisplay, "Hostas šiuo metu neturi ekrano"),
        (Encryption, "Šifravimas"),
        (EncryptionOn, "įjungtas"),
        (EncryptionOff, "išjungtas"),
        (AudioEnabled, "Garsas"),
        (ClipboardEnabled, "Iškarpinė"),
        (DecoderLabel, "Dekoderis"),
        (DecoderAuto, "Automatinis"),
        (DecoderSoftware, "Programinis"),
        (DecoderNvidia, "Vaizdo plokštė"),
        (PairingTitle, "Susieti su hostu"),
        (PairingHint, "Įveskite hoste rodomą kodą"),
        (PairingCode, "Susiejimo kodas"),
        (PairingWrong, "Neteisingas kodas"),
        (PairingOk, "Susieta"),
        (SecuredWith, "Apsaugota · patvirtinimo kodas"),
        (HostFingerprint, "Hosto rakto atspaudas"),
        (NotPaired, "Šis hostas dar nepažįsta jūsų įrenginio. Paleiskite hostą su --pair ir prisijunkite iš naujo."),
        (FirstContact, "Pirmas kontaktas su šiuo hostu. Palyginkite kodą su rodomu hoste."),
        (ErrorConnectRefused, "Hostas atmetė ryšį"),
        (ErrorTimeout, "Hostas neatsakė"),
        (ErrorProtocol, "Kita pusė naudoja kitą protokolą"),
        (ErrorNoDecoder, "Šiam formatui nėra dekoderio"),
    ],
};

pub static SL: Lang = Lang {
    code: "sl",
    name: "Slovenščina",
    table: &[
        (AppSubtitle, "Oddaljeno namizje s polno barvno ločljivostjo"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini povezavo"),
        (HostAddress, "Naslov gostitelja"),
        (SearchingHosts, "Iskanje gostiteljev"),
        (NoHostsFound, "Ni najdenih gostiteljev"),
        (FoundHosts, "Najdeni gostitelji"),
        (Settings, "Nastavitve"),
        (Language, "Jezik"),
        (Quit, "Končaj"),
        (Connecting, "Povezovanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Povezava prekinjena"),
        (Reconnecting, "Ponovno povezovanje"),
        (Fullscreen, "Celozaslonsko"),
        (PixelExact, "Pikselna natančnost"),
        (Stretch, "Prilagodi oknu"),
        (ShowOverlay, "Prikaži statistiko"),
        (Fps, "Sličic na sekundo"),
        (DecodeTime, "Čas dekodiranja"),
        (Bitrate, "Bitna hitrost"),
        (Resolution, "Ločljivost"),
        (Codec, "Kodek"),
        (Latency, "Zakasnitev"),
        (EncodeTime, "Čas kodiranja"),
        (NetworkTime, "Čas prenosa"),
        (AudioBuffer, "Zvočni medpomnilnik"),
        (Dropped, "Izpuščene"),
        (MaxBitrate, "Največja bitna hitrost"),
        (MaxFps, "Največja hitrost sličic"),
        (ExpertMode, "Strokovni način"),
        (GamingMode, "Igralni način"),
        (FixedRate, "Stalna hitrost sličic"),
        (FixedRateHint, "Ohranja hitrost sličic tudi, ko se nič ne premika. Stalna obremenitev gostitelja."),
        (Sound, "Zvok"),
        (HoldEscHint, "Držite ESC za meni"),
        (NerdMode, "Nerdovski način"),
        (More, "Več"),
        (Back, "Nazaj"),
        (SavedForHost, "Shranjeno za tega gostitelja"),
        (Queue, "Zajem in čakanje"),
        (OneFrame, "Ena sličica"),
        (Bottleneck, "Ozko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbo"),
        (CodecSwitching, "Menjava kodeka"),
        (HostCpu, "Procesor gostitelja"),
        (HostGpu, "Grafika gostitelja"),
        (HostRam, "Pomnilnik gostitelja"),
        (NoDisplay, "Gostitelj trenutno nima zaslona"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "vklopljeno"),
        (EncryptionOff, "izklopljeno"),
        (AudioEnabled, "Zvok"),
        (ClipboardEnabled, "Odložišče"),
        (DecoderLabel, "Dekodirnik"),
        (DecoderAuto, "Samodejno"),
        (DecoderSoftware, "Programsko"),
        (DecoderNvidia, "Grafična kartica"),
        (PairingTitle, "Seznanitev z gostiteljem"),
        (PairingHint, "Vnesite kodo, prikazano na gostitelju"),
        (PairingCode, "Koda za seznanitev"),
        (PairingWrong, "Napačna koda"),
        (PairingOk, "Seznanjeno"),
        (SecuredWith, "Zavarovano · overitvena koda"),
        (HostFingerprint, "Prstni odtis gostitelja"),
        (NotPaired, "Ta gostitelj še ne pozna vaše naprave. Zaženite gostitelja z --pair in se znova povežite."),
        (FirstContact, "Prvi stik s tem gostiteljem. Primerjajte kodo s tisto na gostitelju."),
        (ErrorConnectRefused, "Gostitelj je zavrnil povezavo"),
        (ErrorTimeout, "Gostitelj se ni odzval"),
        (ErrorProtocol, "Nasprotna stran uporablja drug protokol"),
        (ErrorNoDecoder, "Za to obliko ni dekodirnika"),
    ],
};

pub static HR: Lang = Lang {
    code: "hr",
    name: "Hrvatski",
    table: &[
        (AppSubtitle, "Udaljena radna površina s punim detaljima boje"),
        (Connect, "Poveži"),
        (Disconnect, "Prekini vezu"),
        (HostAddress, "Adresa hosta"),
        (SearchingHosts, "Traženje hostova"),
        (NoHostsFound, "Nema pronađenih hostova"),
        (FoundHosts, "Pronađeni hostovi"),
        (Settings, "Postavke"),
        (Language, "Jezik"),
        (Quit, "Izlaz"),
        (Connecting, "Povezivanje"),
        (Connected, "Povezano"),
        (ConnectionLost, "Veza prekinuta"),
        (Reconnecting, "Ponovno povezivanje"),
        (Fullscreen, "Cijeli zaslon"),
        (PixelExact, "Pikselna točnost"),
        (Stretch, "Prilagodi prozoru"),
        (ShowOverlay, "Prikaži statistiku"),
        (Fps, "Sličica u sekundi"),
        (DecodeTime, "Vrijeme dekodiranja"),
        (Bitrate, "Brzina prijenosa"),
        (Resolution, "Razlučivost"),
        (Codec, "Kodek"),
        (Latency, "Kašnjenje"),
        (EncodeTime, "Vrijeme kodiranja"),
        (NetworkTime, "Vrijeme prijenosa"),
        (AudioBuffer, "Međuspremnik zvuka"),
        (Dropped, "Ispušteno"),
        (MaxBitrate, "Najveća brzina prijenosa"),
        (MaxFps, "Najveći broj sličica"),
        (ExpertMode, "Stručni način"),
        (GamingMode, "Način za igre"),
        (FixedRate, "Stalan broj sličica"),
        (FixedRateHint, "Održava broj sličica i kad se ništa ne miče. Stalno opterećenje hosta."),
        (Sound, "Zvuk"),
        (HoldEscHint, "Držite ESC za izbornik"),
        (NerdMode, "Način za nerdove"),
        (More, "Više"),
        (Back, "Natrag"),
        (SavedForHost, "Spremljeno za ovaj host"),
        (Queue, "Snimanje i čekanje"),
        (OneFrame, "Jedna sličica"),
        (Bottleneck, "Usko grlo"),
        (TabPicture, "Slika"),
        (TabDisplay, "Prikaz"),
        (CodecConverted, "s pretvorbom"),
        (CodecSwitching, "Promjena kodeka"),
        (HostCpu, "Procesor hosta"),
        (HostGpu, "Grafika hosta"),
        (HostRam, "Memorija hosta"),
        (NoDisplay, "Host trenutno nema zaslon"),
        (Encryption, "Šifriranje"),
        (EncryptionOn, "uključeno"),
        (EncryptionOff, "isključeno"),
        (AudioEnabled, "Zvuk"),
        (ClipboardEnabled, "Međuspremnik"),
        (DecoderLabel, "Dekoder"),
        (DecoderAuto, "Automatski"),
        (DecoderSoftware, "Softverski"),
        (DecoderNvidia, "Grafička kartica"),
        (PairingTitle, "Uparivanje s hostom"),
        (PairingHint, "Unesite kod prikazan na hostu"),
        (PairingCode, "Kod za uparivanje"),
        (PairingWrong, "Netočan kod"),
        (PairingOk, "Upareno"),
        (SecuredWith, "Zaštićeno · kod za provjeru"),
        (HostFingerprint, "Otisak ključa hosta"),
        (NotPaired, "Ovaj host još ne poznaje vaš uređaj. Pokrenite host s --pair i povežite se ponovno."),
        (FirstContact, "Prvi kontakt s ovim hostom. Usporedite kod s onim na hostu."),
        (ErrorConnectRefused, "Host je odbio vezu"),
        (ErrorTimeout, "Host nije odgovorio"),
        (ErrorProtocol, "Druga strana koristi drugi protokol"),
        (ErrorNoDecoder, "Nema dekodera za ovaj format"),
    ],
};

pub static UK: Lang = Lang {
    code: "uk",
    name: "Українська",
    table: &[
        (AppSubtitle, "Віддалений робочий стіл з повною деталізацією кольору"),
        (Connect, "Підключитися"),
        (Disconnect, "Відключитися"),
        (HostAddress, "Адреса хоста"),
        (SearchingHosts, "Пошук хостів"),
        (NoHostsFound, "Хостів не знайдено"),
        (FoundHosts, "Знайдені хости"),
        (Settings, "Налаштування"),
        (Language, "Мова"),
        (Quit, "Вийти"),
        (Connecting, "Підключення"),
        (Connected, "Підключено"),
        (ConnectionLost, "З'єднання втрачено"),
        (Reconnecting, "Повторне підключення"),
        (Fullscreen, "Повний екран"),
        (PixelExact, "Піксельна точність"),
        (Stretch, "Вписати у вікно"),
        (ShowOverlay, "Показати статистику"),
        (Fps, "Кадрів за секунду"),
        (DecodeTime, "Час декодування"),
        (Bitrate, "Бітрейт"),
        (Resolution, "Роздільність"),
        (Codec, "Кодек"),
        (Latency, "Затримка"),
        (EncodeTime, "Час кодування"),
        (NetworkTime, "Час передачі"),
        (AudioBuffer, "Буфер звуку"),
        (Dropped, "Пропущено"),
        (MaxBitrate, "Максимальний бітрейт"),
        (MaxFps, "Максимальна частота кадрів"),
        (ExpertMode, "Режим експерта"),
        (GamingMode, "Ігровий режим"),
        (FixedRate, "Стала частота кадрів"),
        (FixedRateHint, "Утримує частоту кадрів, навіть коли нічого не рухається. Постійне навантаження на хост."),
        (Sound, "Звук"),
        (HoldEscHint, "Утримуйте ESC для меню"),
        (NerdMode, "Режим нерда"),
        (More, "Більше"),
        (Back, "Назад"),
        (SavedForHost, "Збережено для цього хоста"),
        (Queue, "Захоплення і черга"),
        (OneFrame, "Один кадр"),
        (Bottleneck, "Вузьке місце"),
        (TabPicture, "Зображення"),
        (TabDisplay, "Екран"),
        (CodecConverted, "з перетворенням"),
        (CodecSwitching, "Зміна кодека"),
        (HostCpu, "Процесор хоста"),
        (HostGpu, "Графіка хоста"),
        (HostRam, "Пам'ять хоста"),
        (NoDisplay, "У хоста зараз немає екрана"),
        (Encryption, "Шифрування"),
        (EncryptionOn, "увімкнено"),
        (EncryptionOff, "вимкнено"),
        (AudioEnabled, "Звук"),
        (ClipboardEnabled, "Буфер обміну"),
        (DecoderLabel, "Декодер"),
        (DecoderAuto, "Автоматично"),
        (DecoderSoftware, "Програмний"),
        (DecoderNvidia, "Відеокарта"),
        (PairingTitle, "Створення пари з хостом"),
        (PairingHint, "Введіть код, показаний на хості"),
        (PairingCode, "Код підключення"),
        (PairingWrong, "Неправильний код"),
        (PairingOk, "Пару створено"),
        (SecuredWith, "Захищено · код підтвердження"),
        (HostFingerprint, "Відбиток ключа хоста"),
        (NotPaired, "Цей хост ще не знає вашого пристрою. Запустіть хост із --pair і підключіться знову."),
        (FirstContact, "Перший контакт із цим хостом. Порівняйте код із тим, що на хості."),
        (ErrorConnectRefused, "Хост відхилив з'єднання"),
        (ErrorTimeout, "Хост не відповів"),
        (ErrorProtocol, "Інша сторона використовує інший протокол"),
        (ErrorNoDecoder, "Немає декодера для цього формату"),
    ],
};
