// Pruefprogramm fuer host/clipboard.m: Kennzeichnung des empfangenen Textes,
// Widerhall, Uebertragung dessen, was der Nutzer am Mac kopiert, und Lesen
// nur mit Zuschauer (qc_clip_bedingung).
//
//   clang -fobjc-arc -O2 -Wall -Ihost -mmacosx-version-min=14.0 \
//         -framework Foundation -framework AppKit host/ablagetest.m -o /tmp/ablagetest
//   /tmp/ablagetest
//
// clipboard.m wird hier eingebunden und arbeitet auf einer eigenen, benannten
// Ablage statt der allgemeinen: die Zwischenablage des Nutzers und ein
// laufender Host bleiben unberuehrt, und in /tmp/quadchroma-m1.log landet
// nichts (die Zeilen gehen nur nach stdout). Rueckgabe: Zahl der Fehler.

#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#include <stdio.h>
#include <string.h>
#include <stdatomic.h>

static FILE *pruef_fopen(const char *pfad, const char *modus) {
    if (strcmp(pfad, "/tmp/quadchroma-m1.log") == 0) pfad = "/dev/null";
    return fopen(pfad, modus);
}

#define ABLAGE @"tech.quadchroma.ablagetest"
#define fopen pruef_fopen
#define generalPasteboard pasteboardWithName:ABLAGE
#include "clipboard.m"
#undef generalPasteboard
#undef fopen

static int g_fehler = 0;
static NSMutableArray<NSString *> *g_empfangen;

static void pruefe(int ok, const char *was) {
    printf("%s  %s\n", ok ? "ok     " : "FEHLER ", was);
    if (!ok) g_fehler++;
}

// Was der Host zum Client schicken wuerde.
static void empfangen(const char *utf8, size_t len) {
    NSString *s = [[NSString alloc] initWithBytes:utf8 length:len encoding:NSUTF8StringEncoding];
    @synchronized (g_empfangen) { [g_empfangen addObject:s ?: @"?"]; }
}

static NSUInteger anzahl(void) {
    @synchronized (g_empfangen) { return g_empfangen.count; }
}

static NSString *zuletzt(void) {
    @synchronized (g_empfangen) { return g_empfangen.lastObject; }
}

// Schaut gerade jemand zu? Im Host ist das g_client_fd >= 0.
static _Atomic int g_zuschauer = 1;
static int zuschauer_da(void) { return atomic_load(&g_zuschauer); }

static void laufen(double s) {
    [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:s]];
}

// Der Nutzer kopiert am Mac: ein Eintrag, wie ihn ein Programm ablegt.
static void kopieren(NSPasteboard *pb, NSString *text, NSString *kennung) {
    NSPasteboardItem *it = [[NSPasteboardItem alloc] init];
    [it setString:text forType:NSPasteboardTypeString];
    if (kennung) [it setData:[NSData data] forType:kennung];
    [pb clearContents];
    [pb writeObjects:@[it]];
}

int main(void) {
    @autoreleasepool {
        setvbuf(stdout, NULL, _IONBF, 0);
        g_empfangen = [NSMutableArray array];
        NSPasteboard *pb = [NSPasteboard pasteboardWithName:ABLAGE];
        [pb clearContents];
        qc_clip_start(empfangen);
        laufen(0.4);

        printf("\n-- Nutzer kopiert am Mac\n");
        kopieren(pb, @"vom Nutzer", nil);
        laufen(0.5);
        pruefe(anzahl() == 1 && [zuletzt() isEqualToString:@"vom Nutzer"], "wird uebertragen");

        printf("\n-- Text vom Client\n");
        qc_clip_set("vom Client", 10);
        laufen(0.5);
        NSPasteboardItem *it = pb.pasteboardItems.firstObject;
        NSArray *typen = it.types;
        printf("         (Eintraege %lu, Typen: %s)\n", (unsigned long)pb.pasteboardItems.count,
               [typen componentsJoinedByString:@", "].UTF8String);
        pruefe(pb.pasteboardItems.count == 1 && [[it stringForType:NSPasteboardTypeString] isEqualToString:@"vom Client"],
               "steht als einziger Eintrag in der Ablage");
        pruefe([typen containsObject:@"org.nspasteboard.TransientType"] &&
               [typen containsObject:@"org.nspasteboard.AutoGeneratedType"],
               "traegt TransientType und AutoGeneratedType (nicht in den Verlauf)");
        NSData *tr = [it dataForType:@"org.nspasteboard.TransientType"];
        NSData *ag = [it dataForType:@"org.nspasteboard.AutoGeneratedType"];
        pruefe(tr && ag && tr.length == 0 && ag.length == 0,
               "beide Kennungen mit leerem Inhalt, wie die Verabredung es vorsieht");
        pruefe(anzahl() == 1, "kein Widerhall zum Client");
        // Faellt der Zaehlerabgleich einmal aus (eine fremde Aenderung kam
        // dazwischen), liest die Abfrage den eigenen, gekennzeichneten Eintrag
        // wieder - der Lesefilter verwirft die Kennungen nicht, g_last faengt
        // den Widerhall ab. Die Abfrage laeuft auf der Hauptschleife, wie hier.
        g_self_change = -1;
        g_seen -= 1;
        laufen(0.5);
        pruefe(anzahl() == 1, "auch ohne Zaehlerabgleich kein Widerhall (g_last)");

        printf("\n-- Nutzer kopiert danach wieder am Mac\n");
        kopieren(pb, @"zweiter Text", nil);
        laufen(0.5);
        pruefe(anzahl() == 2 && [zuletzt() isEqualToString:@"zweiter Text"], "wird weiter uebertragen");
        kopieren(pb, @"vom Client", nil);
        laufen(0.5);
        pruefe(anzahl() == 3 && [zuletzt() isEqualToString:@"vom Client"],
               "auch derselbe Text wie vorher vom Client, wenn der Nutzer ihn neu kopiert");

        printf("\n-- Kennungen fremder Programme\n");
        kopieren(pb, @"geheim", @"org.nspasteboard.ConcealedType");
        laufen(0.5);
        pruefe(anzahl() == 3, "verdeckter Eintrag (Passwortverwalter) bleibt auf dem Mac");
        kopieren(pb, @"voruebergehend", @"org.nspasteboard.TransientType");
        laufen(0.5);
        printf("         (voruebergehender Eintrag eines anderen Programms: %s)\n",
               anzahl() == 4 ? "uebertragen" : "nicht uebertragen");

        // Wie im Dienstbetrieb (main.m): gelesen wird nur mit Zuschauer.
        printf("\n-- Nur mit Zuschauer (qc_clip_bedingung)\n");
        qc_clip_bedingung(zuschauer_da);
        atomic_store(&g_zuschauer, 1);
        NSUInteger n0 = anzahl();
        kopieren(pb, @"Text A", nil);
        laufen(0.5);
        pruefe(anzahl() == n0 + 1 && [zuletzt() isEqualToString:@"Text A"], "mit Zuschauer: uebertragen");
        atomic_store(&g_zuschauer, 0);
        kopieren(pb, @"Text B", nil);
        laufen(0.5);
        pruefe(anzahl() == n0 + 1 && ![g_last isEqualToString:@"Text B"],
               "ohne Zuschauer: weder gelesen noch gesendet");
        atomic_store(&g_zuschauer, 1);
        laufen(0.5);
        pruefe(anzahl() == n0 + 1, "die Aenderung ohne Zuschauer wird spaeter nicht nachgereicht");
        // Der Nutzer kopiert wieder den Text von vorhin. In der Ablage stand
        // inzwischen "Text B" - das ist eine echte Aenderung und muss hinaus,
        // auch zu einem Zuschauer, der "Text A" nie bekommen hat.
        kopieren(pb, @"Text A", nil);
        laufen(0.5);
        pruefe(anzahl() == n0 + 2 && [zuletzt() isEqualToString:@"Text A"],
               "danach mit Zuschauer: derselbe Text wie vor der Pause wird wieder uebertragen");
        NSUInteger n1 = anzahl();
        qc_clip_set("vom Client 2", 12);
        laufen(0.5);
        pruefe(anzahl() == n1, "auch danach kein Widerhall zum Client");
        qc_clip_bedingung(NULL);

        [pb releaseGlobally];
        printf("\n%s: %d Fehler\n", g_fehler ? "NICHT BESTANDEN" : "bestanden", g_fehler);
        return g_fehler;
    }
}
