// Oberflaechentexte des Mac-Hosts, siehe texte.h.
//
// Je Sprache eine Tabelle mit einem Eintrag je Schluessel (benannte
// Initialisierer, damit Reihenfolge und Schluessel sichtbar zusammenstehen).
// Ein fehlender Eintrag ist NULL: die Oberflaeche faellt dann auf Englisch
// zurueck, der Pruefstand menuetest meldet ihn als Fehler.
#import "texte.h"
#include <stdatomic.h>

typedef struct {
    const char *code;
    const char *name;
    const char *t[QCTextAnzahl];
} qc_sprache;

// Englisch: Grundlage und Rueckfall fuer jeden fehlenden Eintrag.
static const qc_sprache QC_EN = { "en", "English", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

// Deutsch: echte Umlaute, typografische Anfuehrungszeichen und Gedankenstrich
// wie die deutschen Texte in client/src/strings.rs.
static const qc_sprache QC_DE = { "de", "Deutsch", {
    [QCTextHostReady]              = "Bereit für Verbindungen",
    [QCTextHostConnected]          = "Verbunden: {n}",
    [QCTextHostDeviceId]           = "Geräte-ID: {i}",
    [QCTextHostPassword]           = "Passwort: {p}",
    [QCTextHostCopied]             = "Kopiert",
    [QCTextHostChangePassword]     = "Passwort ändern …",
    [QCTextHostRandomPassword]     = "Neues Zufallspasswort",
    [QCTextHostNewPassword]        = "Neues Passwort (mindestens 8 Zeichen)",
    [QCTextHostRepeatPassword]     = "Passwort wiederholen",
    [QCTextHostPasswordsDiffer]    = "Die Passwörter stimmen nicht überein.",
    [QCTextHostPasswordShort]      = "Bitte mindestens 8 Zeichen.",
    [QCTextHostPasswordSaved]      = "Passwort gespeichert.",
    [QCTextHostPasswordUnreadable] = "Passwortdatei unlesbar – neue Geräte nur über „Zulassen“.",
    [QCTextHostDevices]            = "Erlaubte Geräte",
    [QCTextHostNoDevices]          = "Noch keine Geräte",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – seit {d}",
    [QCTextHostRemove]             = "Entfernen",
    [QCTextHostRemoveAll]          = "Alle Geräte entfernen …",
    [QCTextHostRemoveAllAsk]       = "Alle erlaubten Geräte entfernen? Sie brauchen dann wieder das Passwort.",
    [QCTextHostListDamaged]        = "Geräteliste beschädigt",
    [QCTextHostListReset]          = "Geräteliste zurücksetzen",
    [QCTextHostRequest]            = "{n} (ID {i}) möchte diesen Computer steuern.",
    [QCTextHostAllow]              = "Zulassen",
    [QCTextHostDeny]               = "Ablehnen",
    [QCTextHostStartLogin]         = "Beim Anmelden starten",
    [QCTextHostStartWindows]       = "Mit Windows starten",
    [QCTextHostMoveToApps]         = "QuadChroma zuerst in den Ordner Programme bewegen",
    [QCTextHostScreenMissing]      = "Bildschirmaufnahme nicht erlaubt – Systemeinstellungen öffnen …",
    [QCTextHostAccessMissing]      = "Bedienungshilfen nicht erlaubt – Systemeinstellungen öffnen …",
    [QCTextHostPortBusy]           = "Port {p} ist von einem anderen Programm belegt",
    [QCTextHostQuit]               = "QuadChroma beenden",
    [QCTextHostStopSharing]        = "Freigabe beenden",
    [QCTextHostTooltip]            = "QuadChroma – Freigabe läuft (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Abbrechen",
    [QCTextHostPasswordNotSaved]   = "Das Passwort ließ sich nicht speichern.",
}};

// Die uebrigen 27 Sprachen: vorerst der englische Text als Platzhalter;
// Paket P6 uebersetzt sie - identisch mit client/src/strings*.rs.
static const qc_sprache QC_FR = { "fr", "Français", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_ES = { "es", "Español", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_IT = { "it", "Italiano", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_PT = { "pt", "Português", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_NL = { "nl", "Nederlands", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_SV = { "sv", "Svenska", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_DA = { "da", "Dansk", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_NB = { "nb", "Norsk bokmål", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_FI = { "fi", "Suomi", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_IS = { "is", "Íslenska", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_PL = { "pl", "Polski", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_CS = { "cs", "Čeština", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_SK = { "sk", "Slovenčina", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_HU = { "hu", "Magyar", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_RO = { "ro", "Română", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_BG = { "bg", "Български", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_EL = { "el", "Ελληνικά", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_ET = { "et", "Eesti", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_LV = { "lv", "Latviešu", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_LT = { "lt", "Lietuvių", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_SL = { "sl", "Slovenščina", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_HR = { "hr", "Hrvatski", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_UK = { "uk", "Українська", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_RU = { "ru", "Русский", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_ZH = { "zh", "简体中文", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_JA = { "ja", "日本語", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache QC_TR = { "tr", "Türkçe", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
}};

static const qc_sprache *const g_sprachen[] = {
    &QC_EN, &QC_DE, &QC_FR, &QC_ES, &QC_IT, &QC_PT, &QC_NL, &QC_SV, &QC_DA, &QC_NB,
    &QC_FI, &QC_IS, &QC_PL, &QC_CS, &QC_SK, &QC_HU, &QC_RO, &QC_BG, &QC_EL, &QC_ET,
    &QC_LV, &QC_LT, &QC_SL, &QC_HR, &QC_UK, &QC_RU, &QC_ZH, &QC_JA, &QC_TR,
};

#define QC_SPRACHEN ((int)(sizeof g_sprachen / sizeof g_sprachen[0]))

// Gewaehlte Sprache (Tabellenplatz). Gesetzt beim Start der Oberflaeche,
// gelesen aus jedem Faden - daher atomar.
static _Atomic int g_aktuell = 0;

int qc_texte_sprachen(void) { return QC_SPRACHEN; }

const char *qc_texte_code(int sprache) {
    return sprache >= 0 && sprache < QC_SPRACHEN ? g_sprachen[sprache]->code : NULL;
}

const char *qc_texte_name(int sprache) {
    return sprache >= 0 && sprache < QC_SPRACHEN ? g_sprachen[sprache]->name : NULL;
}

const char *qc_texte_eintrag(int sprache, QCText t) {
    if (sprache < 0 || sprache >= QC_SPRACHEN || (int)t < 0 || t >= QCTextAnzahl) return NULL;
    return g_sprachen[sprache]->t[t];
}

static int platz_fuer(NSString *code) {
    for (int i = 0; i < QC_SPRACHEN; i++)
        if ([code isEqualToString:@(g_sprachen[i]->code)]) return i;
    return -1;
}

int qc_texte_waehlen(NSArray<NSString *> *bevorzugt) {
    for (NSString *roh in bevorzugt) {
        if (![roh isKindOfClass:[NSString class]]) continue;
        // "de-DE", "pt_BR", "zh-Hans-CN": erst ganz, dann der Sprachteil.
        NSString *s = [[roh lowercaseString] stringByReplacingOccurrencesOfString:@"_" withString:@"-"];
        int p = platz_fuer(s);
        if (p >= 0) return p;
        NSRange r = [s rangeOfString:@"-"];
        if (r.location != NSNotFound) {
            p = platz_fuer([s substringToIndex:r.location]);
            if (p >= 0) return p;
        }
    }
    return 0;
}

void qc_texte_setzen(int sprache) {
    atomic_store(&g_aktuell, sprache >= 0 && sprache < QC_SPRACHEN ? sprache : 0);
}

int qc_texte_aktuell(void) { return atomic_load(&g_aktuell); }

void qc_texte_systemsprache(void) {
    qc_texte_setzen(qc_texte_waehlen([NSLocale preferredLanguages]));
}

NSString *qc_text(QCText t) {
    if ((int)t < 0 || t >= QCTextAnzahl) return @"";
    const char *s = g_sprachen[atomic_load(&g_aktuell)]->t[t];
    if (!s) s = g_sprachen[0]->t[t];
    return s ? @(s) : @"";
}

NSString *qc_text_mit(QCText t, NSDictionary<NSString *, NSString *> *werte) {
    NSString *vorlage = qc_text(t);
    NSMutableString *aus = [NSMutableString stringWithCapacity:vorlage.length + 32];
    NSUInteger n = vorlage.length, i = 0, stueck = 0;
    while (i < n) {
        // Platzhalter: genau "{x}" mit einem Zeichen, fuer das ein Wert da ist.
        // Alles andere wird stueckweise uebernommen, wie es steht.
        if ([vorlage characterAtIndex:i] == '{' && i + 2 < n && [vorlage characterAtIndex:i + 2] == '}') {
            NSString *wert = werte[[vorlage substringWithRange:NSMakeRange(i + 1, 1)]];
            if (wert) {
                [aus appendString:[vorlage substringWithRange:NSMakeRange(stueck, i - stueck)]];
                [aus appendString:wert];
                i += 3;
                stueck = i;
                continue;
            }
        }
        i++;
    }
    [aus appendString:[vorlage substringFromIndex:stueck]];
    return aus;
}
