// Oberflaechentexte des Mac-Hosts, siehe texte.h.
//
// Je Sprache eine Tabelle mit einem Eintrag je Schluessel (benannte
// Initialisierer, damit Reihenfolge und Schluessel sichtbar zusammenstehen).
// Ein fehlender Eintrag ist NULL: die Oberflaeche faellt dann auf Englisch
// zurueck, der Pruefstand menuetest meldet ihn als Fehler.
#import "texte.h"
#include <stdatomic.h>

typedef struct {
    const char *code;
    const char *name;
    const char *t[QCTextAnzahl];
} qc_sprache;

// Englisch: Grundlage und Rueckfall fuer jeden fehlenden Eintrag.
static const qc_sprache QC_EN = { "en", "English", {
    [QCTextHostReady]              = "Ready for connections",
    [QCTextHostConnected]          = "Connected: {n}",
    [QCTextHostDeviceId]           = "Device ID: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copied",
    [QCTextHostChangePassword]     = "Change password ...",
    [QCTextHostRandomPassword]     = "New random password",
    [QCTextHostNewPassword]        = "New password (at least 8 characters)",
    [QCTextHostRepeatPassword]     = "Repeat password",
    [QCTextHostPasswordsDiffer]    = "The passwords do not match.",
    [QCTextHostPasswordShort]      = "At least 8 characters, please.",
    [QCTextHostPasswordSaved]      = "Password saved.",
    [QCTextHostPasswordUnreadable] = "Password file unreadable - new devices only via \"Allow\".",
    [QCTextHostDevices]            = "Allowed devices",
    [QCTextHostNoDevices]          = "No devices yet",
    [QCTextHostDeviceLine]         = "{n} - ID {i} - since {d}",
    [QCTextHostRemove]             = "Remove",
    [QCTextHostRemoveAll]          = "Remove all devices ...",
    [QCTextHostRemoveAllAsk]       = "Remove all allowed devices? They will need the password again.",
    [QCTextHostListDamaged]        = "Device list damaged",
    [QCTextHostListReset]          = "Reset device list",
    [QCTextHostRequest]            = "{n} (ID {i}) wants to control this computer.",
    [QCTextHostAllow]              = "Allow",
    [QCTextHostDeny]               = "Deny",
    [QCTextHostStartLogin]         = "Start at login",
    [QCTextHostStartWindows]       = "Start with Windows",
    [QCTextHostMoveToApps]         = "Move QuadChroma to Applications first",
    [QCTextHostScreenMissing]      = "Screen Recording not allowed - open System Settings ...",
    [QCTextHostAccessMissing]      = "Accessibility not allowed - open System Settings ...",
    [QCTextHostPortBusy]           = "Port {p} is used by another program",
    [QCTextHostQuit]               = "Quit QuadChroma",
    [QCTextHostStopSharing]        = "Stop sharing",
    [QCTextHostTooltip]            = "QuadChroma - sharing this PC (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Cancel",
    [QCTextHostPasswordNotSaved]   = "The password could not be saved.",
    [QCTextHostPasswordInvalid]    = "The password contains characters that are not allowed.",
    [QCTextHostPasswordTitle]      = "Change password",
}};

// Deutsch: echte Umlaute, typografische Anfuehrungszeichen, Gedankenstrich und
// Auslassungszeichen (U+2026) - zeichengleich mit den Host-Schluesseln in
// client/src/strings.rs (Englisch dort wie hier mit "...").
static const qc_sprache QC_DE = { "de", "Deutsch", {
    [QCTextHostReady]              = "Bereit für Verbindungen",
    [QCTextHostConnected]          = "Verbunden: {n}",
    [QCTextHostDeviceId]           = "Geräte-ID: {i}",
    [QCTextHostPassword]           = "Passwort: {p}",
    [QCTextHostCopied]             = "Kopiert",
    [QCTextHostChangePassword]     = "Passwort ändern …",
    [QCTextHostRandomPassword]     = "Neues Zufallspasswort",
    [QCTextHostNewPassword]        = "Neues Passwort (mindestens 8 Zeichen)",
    [QCTextHostRepeatPassword]     = "Passwort wiederholen",
    [QCTextHostPasswordsDiffer]    = "Die Passwörter stimmen nicht überein.",
    [QCTextHostPasswordShort]      = "Bitte mindestens 8 Zeichen.",
    [QCTextHostPasswordSaved]      = "Passwort gespeichert.",
    [QCTextHostPasswordUnreadable] = "Passwortdatei unlesbar – neue Geräte nur über „Zulassen“.",
    [QCTextHostDevices]            = "Erlaubte Geräte",
    [QCTextHostNoDevices]          = "Noch keine Geräte",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – seit {d}",
    [QCTextHostRemove]             = "Entfernen",
    [QCTextHostRemoveAll]          = "Alle Geräte entfernen …",
    [QCTextHostRemoveAllAsk]       = "Alle erlaubten Geräte entfernen? Sie brauchen dann wieder das Passwort.",
    [QCTextHostListDamaged]        = "Geräteliste beschädigt",
    [QCTextHostListReset]          = "Geräteliste zurücksetzen",
    [QCTextHostRequest]            = "{n} (ID {i}) möchte diesen Computer steuern.",
    [QCTextHostAllow]              = "Zulassen",
    [QCTextHostDeny]               = "Ablehnen",
    [QCTextHostStartLogin]         = "Beim Anmelden starten",
    [QCTextHostStartWindows]       = "Mit Windows starten",
    [QCTextHostMoveToApps]         = "QuadChroma zuerst in den Ordner Programme bewegen",
    [QCTextHostScreenMissing]      = "Bildschirmaufnahme nicht erlaubt – Systemeinstellungen öffnen …",
    [QCTextHostAccessMissing]      = "Bedienungshilfen nicht erlaubt – Systemeinstellungen öffnen …",
    [QCTextHostPortBusy]           = "Port {p} ist von einem anderen Programm belegt",
    [QCTextHostQuit]               = "QuadChroma beenden",
    [QCTextHostStopSharing]        = "Freigabe beenden",
    [QCTextHostTooltip]            = "QuadChroma – Freigabe läuft (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Abbrechen",
    [QCTextHostPasswordNotSaved]   = "Das Passwort konnte nicht gespeichert werden.",
    [QCTextHostPasswordInvalid]    = "Das Passwort enthält unzulässige Zeichen.",
    [QCTextHostPasswordTitle]      = "Passwort ändern",
}};

// Die uebrigen 27 Sprachen (Paket P6): dieselben Uebersetzungen wie in
// client/src/strings*.rs - gleicher Text, gleiche Anfuehrungszeichen und
// Auslassungspunkte wie die bestehenden Texte jeder Tabelle.
static const qc_sprache QC_FR = { "fr", "Français", {
    [QCTextHostReady]              = "Prêt pour les connexions",
    [QCTextHostConnected]          = "Connecté : {n}",
    [QCTextHostDeviceId]           = "ID de l'appareil : {i}",
    [QCTextHostPassword]           = "Mot de passe : {p}",
    [QCTextHostCopied]             = "Copié",
    [QCTextHostChangePassword]     = "Changer le mot de passe …",
    [QCTextHostRandomPassword]     = "Nouveau mot de passe aléatoire",
    [QCTextHostNewPassword]        = "Nouveau mot de passe (au moins 8 caractères)",
    [QCTextHostRepeatPassword]     = "Répéter le mot de passe",
    [QCTextHostPasswordsDiffer]    = "Les mots de passe ne correspondent pas.",
    [QCTextHostPasswordShort]      = "Veuillez saisir au moins 8 caractères.",
    [QCTextHostPasswordSaved]      = "Mot de passe enregistré.",
    [QCTextHostPasswordUnreadable] = "Fichier du mot de passe illisible – nouveaux appareils uniquement via « Autoriser ».",
    [QCTextHostDevices]            = "Appareils autorisés",
    [QCTextHostNoDevices]          = "Aucun appareil pour l'instant",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – depuis le {d}",
    [QCTextHostRemove]             = "Retirer",
    [QCTextHostRemoveAll]          = "Retirer tous les appareils …",
    [QCTextHostRemoveAllAsk]       = "Retirer tous les appareils autorisés ? Ils auront de nouveau besoin du mot de passe.",
    [QCTextHostListDamaged]        = "Liste des appareils endommagée",
    [QCTextHostListReset]          = "Réinitialiser la liste des appareils",
    [QCTextHostRequest]            = "{n} (ID {i}) souhaite contrôler cet ordinateur.",
    [QCTextHostAllow]              = "Autoriser",
    [QCTextHostDeny]               = "Refuser",
    [QCTextHostStartLogin]         = "Lancer à l'ouverture de session",
    [QCTextHostStartWindows]       = "Démarrer avec Windows",
    [QCTextHostMoveToApps]         = "Déplacez d'abord QuadChroma dans Applications",
    [QCTextHostScreenMissing]      = "Enregistrement de l'écran non autorisé – ouvrir Réglages Système …",
    [QCTextHostAccessMissing]      = "Accessibilité non autorisée – ouvrir Réglages Système …",
    [QCTextHostPortBusy]           = "Le port {p} est utilisé par un autre programme",
    [QCTextHostQuit]               = "Quitter QuadChroma",
    [QCTextHostStopSharing]        = "Arrêter le partage",
    [QCTextHostTooltip]            = "QuadChroma – ce PC est partagé (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code : {c}",
    [QCTextAccessCancel]           = "Annuler",
    [QCTextHostPasswordNotSaved]   = "Le mot de passe n'a pas pu être enregistré.",
    [QCTextHostPasswordInvalid]    = "Le mot de passe contient des caractères non autorisés.",
    [QCTextHostPasswordTitle]      = "Changer le mot de passe",
}};

static const qc_sprache QC_ES = { "es", "Español", {
    [QCTextHostReady]              = "Listo para conexiones",
    [QCTextHostConnected]          = "Conectado: {n}",
    [QCTextHostDeviceId]           = "ID del dispositivo: {i}",
    [QCTextHostPassword]           = "Contraseña: {p}",
    [QCTextHostCopied]             = "Copiado",
    [QCTextHostChangePassword]     = "Cambiar contraseña …",
    [QCTextHostRandomPassword]     = "Nueva contraseña aleatoria",
    [QCTextHostNewPassword]        = "Nueva contraseña (mínimo 8 caracteres)",
    [QCTextHostRepeatPassword]     = "Repetir contraseña",
    [QCTextHostPasswordsDiffer]    = "Las contraseñas no coinciden.",
    [QCTextHostPasswordShort]      = "Usa al menos 8 caracteres.",
    [QCTextHostPasswordSaved]      = "Contraseña guardada.",
    [QCTextHostPasswordUnreadable] = "Archivo de contraseña ilegible – dispositivos nuevos solo mediante \"Permitir\".",
    [QCTextHostDevices]            = "Dispositivos permitidos",
    [QCTextHostNoDevices]          = "Aún no hay dispositivos",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – desde el {d}",
    [QCTextHostRemove]             = "Quitar",
    [QCTextHostRemoveAll]          = "Quitar todos los dispositivos …",
    [QCTextHostRemoveAllAsk]       = "¿Quitar todos los dispositivos permitidos? Volverán a necesitar la contraseña.",
    [QCTextHostListDamaged]        = "Lista de dispositivos dañada",
    [QCTextHostListReset]          = "Restablecer lista de dispositivos",
    [QCTextHostRequest]            = "{n} (ID {i}) quiere controlar este ordenador.",
    [QCTextHostAllow]              = "Permitir",
    [QCTextHostDeny]               = "Rechazar",
    [QCTextHostStartLogin]         = "Abrir al iniciar sesión",
    [QCTextHostStartWindows]       = "Iniciar con Windows",
    [QCTextHostMoveToApps]         = "Mueve primero QuadChroma a Aplicaciones",
    [QCTextHostScreenMissing]      = "Grabación de pantalla no permitida – abrir Configuración del Sistema …",
    [QCTextHostAccessMissing]      = "Accesibilidad no permitida – abrir Configuración del Sistema …",
    [QCTextHostPortBusy]           = "El puerto {p} lo está usando otro programa",
    [QCTextHostQuit]               = "Salir de QuadChroma",
    [QCTextHostStopSharing]        = "Dejar de compartir",
    [QCTextHostTooltip]            = "QuadChroma – este PC está compartido (ID {i})",
    [QCTextHostOk]                 = "Aceptar",
    [QCTextAccessCode]             = "Código: {c}",
    [QCTextAccessCancel]           = "Cancelar",
    [QCTextHostPasswordNotSaved]   = "No se ha podido guardar la contraseña.",
    [QCTextHostPasswordInvalid]    = "La contraseña contiene caracteres no permitidos.",
    [QCTextHostPasswordTitle]      = "Cambiar contraseña",
}};

static const qc_sprache QC_IT = { "it", "Italiano", {
    [QCTextHostReady]              = "Pronto per le connessioni",
    [QCTextHostConnected]          = "Connesso: {n}",
    [QCTextHostDeviceId]           = "ID dispositivo: {i}",
    [QCTextHostPassword]           = "Password: {p}",
    [QCTextHostCopied]             = "Copiato",
    [QCTextHostChangePassword]     = "Cambia password …",
    [QCTextHostRandomPassword]     = "Nuova password casuale",
    [QCTextHostNewPassword]        = "Nuova password (almeno 8 caratteri)",
    [QCTextHostRepeatPassword]     = "Ripeti password",
    [QCTextHostPasswordsDiffer]    = "Le password non coincidono.",
    [QCTextHostPasswordShort]      = "Servono almeno 8 caratteri.",
    [QCTextHostPasswordSaved]      = "Password salvata.",
    [QCTextHostPasswordUnreadable] = "File della password illeggibile – nuovi dispositivi solo tramite \"Consenti\".",
    [QCTextHostDevices]            = "Dispositivi consentiti",
    [QCTextHostNoDevices]          = "Ancora nessun dispositivo",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – dal {d}",
    [QCTextHostRemove]             = "Rimuovi",
    [QCTextHostRemoveAll]          = "Rimuovi tutti i dispositivi …",
    [QCTextHostRemoveAllAsk]       = "Rimuovere tutti i dispositivi consentiti? Avranno di nuovo bisogno della password.",
    [QCTextHostListDamaged]        = "Elenco dispositivi danneggiato",
    [QCTextHostListReset]          = "Reimposta elenco dispositivi",
    [QCTextHostRequest]            = "{n} (ID {i}) vuole controllare questo computer.",
    [QCTextHostAllow]              = "Consenti",
    [QCTextHostDeny]               = "Rifiuta",
    [QCTextHostStartLogin]         = "Avvia al login",
    [QCTextHostStartWindows]       = "Avvia con Windows",
    [QCTextHostMoveToApps]         = "Sposta prima QuadChroma in Applicazioni",
    [QCTextHostScreenMissing]      = "Registrazione schermo non consentita – apri Impostazioni di Sistema …",
    [QCTextHostAccessMissing]      = "Accessibilità non consentita – apri Impostazioni di Sistema …",
    [QCTextHostPortBusy]           = "La porta {p} è usata da un altro programma",
    [QCTextHostQuit]               = "Esci da QuadChroma",
    [QCTextHostStopSharing]        = "Interrompi condivisione",
    [QCTextHostTooltip]            = "QuadChroma – questo PC è condiviso (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Codice: {c}",
    [QCTextAccessCancel]           = "Annulla",
    [QCTextHostPasswordNotSaved]   = "Impossibile salvare la password.",
    [QCTextHostPasswordInvalid]    = "La password contiene caratteri non consentiti.",
    [QCTextHostPasswordTitle]      = "Cambia password",
}};

static const qc_sprache QC_PT = { "pt", "Português", {
    [QCTextHostReady]              = "Pronto para ligações",
    [QCTextHostConnected]          = "Ligado: {n}",
    [QCTextHostDeviceId]           = "ID do dispositivo: {i}",
    [QCTextHostPassword]           = "Palavra-passe: {p}",
    [QCTextHostCopied]             = "Copiado",
    [QCTextHostChangePassword]     = "Alterar palavra-passe …",
    [QCTextHostRandomPassword]     = "Nova palavra-passe aleatória",
    [QCTextHostNewPassword]        = "Nova palavra-passe (pelo menos 8 caracteres)",
    [QCTextHostRepeatPassword]     = "Repetir palavra-passe",
    [QCTextHostPasswordsDiffer]    = "As palavras-passe não coincidem.",
    [QCTextHostPasswordShort]      = "Utilize pelo menos 8 caracteres.",
    [QCTextHostPasswordSaved]      = "Palavra-passe guardada.",
    [QCTextHostPasswordUnreadable] = "Ficheiro da palavra-passe ilegível – novos dispositivos só através de \"Permitir\".",
    [QCTextHostDevices]            = "Dispositivos permitidos",
    [QCTextHostNoDevices]          = "Ainda sem dispositivos",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – desde {d}",
    [QCTextHostRemove]             = "Remover",
    [QCTextHostRemoveAll]          = "Remover todos os dispositivos …",
    [QCTextHostRemoveAllAsk]       = "Remover todos os dispositivos permitidos? Voltarão a precisar da palavra-passe.",
    [QCTextHostListDamaged]        = "Lista de dispositivos danificada",
    [QCTextHostListReset]          = "Repor lista de dispositivos",
    [QCTextHostRequest]            = "{n} (ID {i}) pretende controlar este computador.",
    [QCTextHostAllow]              = "Permitir",
    [QCTextHostDeny]               = "Recusar",
    [QCTextHostStartLogin]         = "Abrir ao iniciar sessão",
    [QCTextHostStartWindows]       = "Iniciar com o Windows",
    [QCTextHostMoveToApps]         = "Mova primeiro o QuadChroma para Aplicações",
    [QCTextHostScreenMissing]      = "Gravação do ecrã não permitida – abrir Definições do Sistema …",
    [QCTextHostAccessMissing]      = "Acessibilidade não permitida – abrir Definições do Sistema …",
    [QCTextHostPortBusy]           = "A porta {p} está a ser usada por outro programa",
    [QCTextHostQuit]               = "Sair do QuadChroma",
    [QCTextHostStopSharing]        = "Parar a partilha",
    [QCTextHostTooltip]            = "QuadChroma – este PC está partilhado (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Código: {c}",
    [QCTextAccessCancel]           = "Cancelar",
    [QCTextHostPasswordNotSaved]   = "Não foi possível guardar a palavra-passe.",
    [QCTextHostPasswordInvalid]    = "A palavra-passe contém caracteres não permitidos.",
    [QCTextHostPasswordTitle]      = "Alterar palavra-passe",
}};

static const qc_sprache QC_NL = { "nl", "Nederlands", {
    [QCTextHostReady]              = "Klaar voor verbindingen",
    [QCTextHostConnected]          = "Verbonden: {n}",
    [QCTextHostDeviceId]           = "Apparaat-ID: {i}",
    [QCTextHostPassword]           = "Wachtwoord: {p}",
    [QCTextHostCopied]             = "Gekopieerd",
    [QCTextHostChangePassword]     = "Wachtwoord wijzigen …",
    [QCTextHostRandomPassword]     = "Nieuw willekeurig wachtwoord",
    [QCTextHostNewPassword]        = "Nieuw wachtwoord (minstens 8 tekens)",
    [QCTextHostRepeatPassword]     = "Wachtwoord herhalen",
    [QCTextHostPasswordsDiffer]    = "De wachtwoorden komen niet overeen.",
    [QCTextHostPasswordShort]      = "Gebruik minstens 8 tekens.",
    [QCTextHostPasswordSaved]      = "Wachtwoord opgeslagen.",
    [QCTextHostPasswordUnreadable] = "Wachtwoordbestand onleesbaar – nieuwe apparaten alleen via \"Toestaan\".",
    [QCTextHostDevices]            = "Toegestane apparaten",
    [QCTextHostNoDevices]          = "Nog geen apparaten",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – sinds {d}",
    [QCTextHostRemove]             = "Verwijderen",
    [QCTextHostRemoveAll]          = "Alle apparaten verwijderen …",
    [QCTextHostRemoveAllAsk]       = "Alle toegestane apparaten verwijderen? Ze hebben dan opnieuw het wachtwoord nodig.",
    [QCTextHostListDamaged]        = "Apparatenlijst beschadigd",
    [QCTextHostListReset]          = "Apparatenlijst opnieuw instellen",
    [QCTextHostRequest]            = "{n} (ID {i}) wil deze computer bedienen.",
    [QCTextHostAllow]              = "Toestaan",
    [QCTextHostDeny]               = "Weigeren",
    [QCTextHostStartLogin]         = "Starten bij inloggen",
    [QCTextHostStartWindows]       = "Starten met Windows",
    [QCTextHostMoveToApps]         = "Verplaats QuadChroma eerst naar Programma's",
    [QCTextHostScreenMissing]      = "Schermopname niet toegestaan – Systeeminstellingen openen …",
    [QCTextHostAccessMissing]      = "Toegankelijkheid niet toegestaan – Systeeminstellingen openen …",
    [QCTextHostPortBusy]           = "Poort {p} wordt door een ander programma gebruikt",
    [QCTextHostQuit]               = "QuadChroma afsluiten",
    [QCTextHostStopSharing]        = "Delen stoppen",
    [QCTextHostTooltip]            = "QuadChroma – deze pc wordt gedeeld (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Code: {c}",
    [QCTextAccessCancel]           = "Annuleren",
    [QCTextHostPasswordNotSaved]   = "Het wachtwoord kon niet worden opgeslagen.",
    [QCTextHostPasswordInvalid]    = "Het wachtwoord bevat tekens die niet zijn toegestaan.",
    [QCTextHostPasswordTitle]      = "Wachtwoord wijzigen",
}};

static const qc_sprache QC_SV = { "sv", "Svenska", {
    [QCTextHostReady]              = "Redo för anslutningar",
    [QCTextHostConnected]          = "Ansluten: {n}",
    [QCTextHostDeviceId]           = "Enhets-ID: {i}",
    [QCTextHostPassword]           = "Lösenord: {p}",
    [QCTextHostCopied]             = "Kopierat",
    [QCTextHostChangePassword]     = "Ändra lösenord …",
    [QCTextHostRandomPassword]     = "Nytt slumpmässigt lösenord",
    [QCTextHostNewPassword]        = "Nytt lösenord (minst 8 tecken)",
    [QCTextHostRepeatPassword]     = "Upprepa lösenordet",
    [QCTextHostPasswordsDiffer]    = "Lösenorden stämmer inte överens.",
    [QCTextHostPasswordShort]      = "Använd minst 8 tecken.",
    [QCTextHostPasswordSaved]      = "Lösenordet har sparats.",
    [QCTextHostPasswordUnreadable] = "Lösenordsfilen går inte att läsa – nya enheter bara via \"Tillåt\".",
    [QCTextHostDevices]            = "Tillåtna enheter",
    [QCTextHostNoDevices]          = "Inga enheter än",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – sedan {d}",
    [QCTextHostRemove]             = "Ta bort",
    [QCTextHostRemoveAll]          = "Ta bort alla enheter …",
    [QCTextHostRemoveAllAsk]       = "Ta bort alla tillåtna enheter? De behöver då lösenordet igen.",
    [QCTextHostListDamaged]        = "Enhetslistan är skadad",
    [QCTextHostListReset]          = "Återställ enhetslistan",
    [QCTextHostRequest]            = "{n} (ID {i}) vill styra den här datorn.",
    [QCTextHostAllow]              = "Tillåt",
    [QCTextHostDeny]               = "Neka",
    [QCTextHostStartLogin]         = "Starta vid inloggning",
    [QCTextHostStartWindows]       = "Starta med Windows",
    [QCTextHostMoveToApps]         = "Flytta först QuadChroma till Program",
    [QCTextHostScreenMissing]      = "Skärminspelning inte tillåten – öppna Systeminställningar …",
    [QCTextHostAccessMissing]      = "Hjälpmedel inte tillåtet – öppna Systeminställningar …",
    [QCTextHostPortBusy]           = "Port {p} används av ett annat program",
    [QCTextHostQuit]               = "Avsluta QuadChroma",
    [QCTextHostStopSharing]        = "Sluta dela",
    [QCTextHostTooltip]            = "QuadChroma – den här datorn delas (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kod: {c}",
    [QCTextAccessCancel]           = "Avbryt",
    [QCTextHostPasswordNotSaved]   = "Lösenordet kunde inte sparas.",
    [QCTextHostPasswordInvalid]    = "Lösenordet innehåller otillåtna tecken.",
    [QCTextHostPasswordTitle]      = "Ändra lösenord",
}};

static const qc_sprache QC_DA = { "da", "Dansk", {
    [QCTextHostReady]              = "Klar til forbindelser",
    [QCTextHostConnected]          = "Forbundet: {n}",
    [QCTextHostDeviceId]           = "Enheds-ID: {i}",
    [QCTextHostPassword]           = "Adgangskode: {p}",
    [QCTextHostCopied]             = "Kopieret",
    [QCTextHostChangePassword]     = "Skift adgangskode …",
    [QCTextHostRandomPassword]     = "Ny tilfældig adgangskode",
    [QCTextHostNewPassword]        = "Ny adgangskode (mindst 8 tegn)",
    [QCTextHostRepeatPassword]     = "Gentag adgangskoden",
    [QCTextHostPasswordsDiffer]    = "Adgangskoderne er ikke ens.",
    [QCTextHostPasswordShort]      = "Brug mindst 8 tegn.",
    [QCTextHostPasswordSaved]      = "Adgangskoden er gemt.",
    [QCTextHostPasswordUnreadable] = "Filen med adgangskoden kan ikke læses – nye enheder kun via \"Tillad\".",
    [QCTextHostDevices]            = "Tilladte enheder",
    [QCTextHostNoDevices]          = "Ingen enheder endnu",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – siden {d}",
    [QCTextHostRemove]             = "Fjern",
    [QCTextHostRemoveAll]          = "Fjern alle enheder …",
    [QCTextHostRemoveAllAsk]       = "Fjern alle tilladte enheder? De skal så bruge adgangskoden igen.",
    [QCTextHostListDamaged]        = "Enhedslisten er beskadiget",
    [QCTextHostListReset]          = "Nulstil enhedslisten",
    [QCTextHostRequest]            = "{n} (ID {i}) vil styre denne computer.",
    [QCTextHostAllow]              = "Tillad",
    [QCTextHostDeny]               = "Afvis",
    [QCTextHostStartLogin]         = "Start ved login",
    [QCTextHostStartWindows]       = "Start med Windows",
    [QCTextHostMoveToApps]         = "Flyt først QuadChroma til Programmer",
    [QCTextHostScreenMissing]      = "Skærmoptagelse ikke tilladt – åbn Systemindstillinger …",
    [QCTextHostAccessMissing]      = "Tilgængelighed ikke tilladt – åbn Systemindstillinger …",
    [QCTextHostPortBusy]           = "Port {p} bruges af et andet program",
    [QCTextHostQuit]               = "Afslut QuadChroma",
    [QCTextHostStopSharing]        = "Stop deling",
    [QCTextHostTooltip]            = "QuadChroma – denne pc deles (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kode: {c}",
    [QCTextAccessCancel]           = "Afbryd",
    [QCTextHostPasswordNotSaved]   = "Adgangskoden kunne ikke gemmes.",
    [QCTextHostPasswordInvalid]    = "Adgangskoden indeholder tegn, der ikke er tilladt.",
    [QCTextHostPasswordTitle]      = "Skift adgangskode",
}};

static const qc_sprache QC_NB = { "nb", "Norsk bokmål", {
    [QCTextHostReady]              = "Klar for tilkoblinger",
    [QCTextHostConnected]          = "Tilkoblet: {n}",
    [QCTextHostDeviceId]           = "Enhets-ID: {i}",
    [QCTextHostPassword]           = "Passord: {p}",
    [QCTextHostCopied]             = "Kopiert",
    [QCTextHostChangePassword]     = "Endre passord …",
    [QCTextHostRandomPassword]     = "Nytt tilfeldig passord",
    [QCTextHostNewPassword]        = "Nytt passord (minst 8 tegn)",
    [QCTextHostRepeatPassword]     = "Gjenta passordet",
    [QCTextHostPasswordsDiffer]    = "Passordene er ikke like.",
    [QCTextHostPasswordShort]      = "Bruk minst 8 tegn.",
    [QCTextHostPasswordSaved]      = "Passordet er lagret.",
    [QCTextHostPasswordUnreadable] = "Passordfilen kan ikke leses – nye enheter bare via \"Tillat\".",
    [QCTextHostDevices]            = "Tillatte enheter",
    [QCTextHostNoDevices]          = "Ingen enheter ennå",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – siden {d}",
    [QCTextHostRemove]             = "Fjern",
    [QCTextHostRemoveAll]          = "Fjern alle enheter …",
    [QCTextHostRemoveAllAsk]       = "Fjerne alle tillatte enheter? De trenger da passordet igjen.",
    [QCTextHostListDamaged]        = "Enhetslisten er skadet",
    [QCTextHostListReset]          = "Tilbakestill enhetslisten",
    [QCTextHostRequest]            = "{n} (ID {i}) vil styre denne datamaskinen.",
    [QCTextHostAllow]              = "Tillat",
    [QCTextHostDeny]               = "Avvis",
    [QCTextHostStartLogin]         = "Start ved pålogging",
    [QCTextHostStartWindows]       = "Start med Windows",
    [QCTextHostMoveToApps]         = "Flytt QuadChroma til Programmer først",
    [QCTextHostScreenMissing]      = "Skjermopptak ikke tillatt – åpne Systeminnstillinger …",
    [QCTextHostAccessMissing]      = "Tilgjengelighet ikke tillatt – åpne Systeminnstillinger …",
    [QCTextHostPortBusy]           = "Port {p} brukes av et annet program",
    [QCTextHostQuit]               = "Avslutt QuadChroma",
    [QCTextHostStopSharing]        = "Stopp deling",
    [QCTextHostTooltip]            = "QuadChroma – denne PC-en deles (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kode: {c}",
    [QCTextAccessCancel]           = "Avbryt",
    [QCTextHostPasswordNotSaved]   = "Passordet kunne ikke lagres.",
    [QCTextHostPasswordInvalid]    = "Passordet inneholder tegn som ikke er tillatt.",
    [QCTextHostPasswordTitle]      = "Endre passord",
}};

static const qc_sprache QC_FI = { "fi", "Suomi", {
    [QCTextHostReady]              = "Valmis yhteyksille",
    [QCTextHostConnected]          = "Yhdistetty: {n}",
    [QCTextHostDeviceId]           = "Laitteen ID: {i}",
    [QCTextHostPassword]           = "Salasana: {p}",
    [QCTextHostCopied]             = "Kopioitu",
    [QCTextHostChangePassword]     = "Vaihda salasana …",
    [QCTextHostRandomPassword]     = "Uusi satunnainen salasana",
    [QCTextHostNewPassword]        = "Uusi salasana (vähintään 8 merkkiä)",
    [QCTextHostRepeatPassword]     = "Toista salasana",
    [QCTextHostPasswordsDiffer]    = "Salasanat eivät täsmää.",
    [QCTextHostPasswordShort]      = "Käytä vähintään 8 merkkiä.",
    [QCTextHostPasswordSaved]      = "Salasana tallennettu.",
    [QCTextHostPasswordUnreadable] = "Salasanatiedostoa ei voi lukea – uudet laitteet vain \"Salli\"-painikkeella.",
    [QCTextHostDevices]            = "Sallitut laitteet",
    [QCTextHostNoDevices]          = "Ei vielä laitteita",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – {d} alkaen",
    [QCTextHostRemove]             = "Poista",
    [QCTextHostRemoveAll]          = "Poista kaikki laitteet …",
    [QCTextHostRemoveAllAsk]       = "Poistetaanko kaikki sallitut laitteet? Ne tarvitsevat sen jälkeen salasanan uudelleen.",
    [QCTextHostListDamaged]        = "Laiteluettelo on vioittunut",
    [QCTextHostListReset]          = "Nollaa laiteluettelo",
    [QCTextHostRequest]            = "{n} (ID {i}) haluaa ohjata tätä tietokonetta.",
    [QCTextHostAllow]              = "Salli",
    [QCTextHostDeny]               = "Hylkää",
    [QCTextHostStartLogin]         = "Käynnistä kirjauduttaessa",
    [QCTextHostStartWindows]       = "Käynnistä Windowsin mukana",
    [QCTextHostMoveToApps]         = "Siirrä QuadChroma ensin Ohjelmat-kansioon",
    [QCTextHostScreenMissing]      = "Näytön tallennus ei ole sallittu – avaa Järjestelmäasetukset …",
    [QCTextHostAccessMissing]      = "Käyttöapu ei ole sallittu – avaa Järjestelmäasetukset …",
    [QCTextHostPortBusy]           = "Portti {p} on toisen ohjelman käytössä",
    [QCTextHostQuit]               = "Lopeta QuadChroma",
    [QCTextHostStopSharing]        = "Lopeta jakaminen",
    [QCTextHostTooltip]            = "QuadChroma – tämä tietokone on jaettu (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Koodi: {c}",
    [QCTextAccessCancel]           = "Keskeytä",
    [QCTextHostPasswordNotSaved]   = "Salasanaa ei voitu tallentaa.",
    [QCTextHostPasswordInvalid]    = "Salasana sisältää merkkejä, jotka eivät ole sallittuja.",
    [QCTextHostPasswordTitle]      = "Vaihda salasana",
}};

static const qc_sprache QC_IS = { "is", "Íslenska", {
    [QCTextHostReady]              = "Tilbúið fyrir tengingar",
    [QCTextHostConnected]          = "Tengt: {n}",
    [QCTextHostDeviceId]           = "ID tækis: {i}",
    [QCTextHostPassword]           = "Lykilorð: {p}",
    [QCTextHostCopied]             = "Afritað",
    [QCTextHostChangePassword]     = "Breyta lykilorði …",
    [QCTextHostRandomPassword]     = "Nýtt handahófskennt lykilorð",
    [QCTextHostNewPassword]        = "Nýtt lykilorð (minnst 8 stafir)",
    [QCTextHostRepeatPassword]     = "Endurtaka lykilorð",
    [QCTextHostPasswordsDiffer]    = "Lykilorðin eru ekki eins.",
    [QCTextHostPasswordShort]      = "Notaðu minnst 8 stafi.",
    [QCTextHostPasswordSaved]      = "Lykilorð vistað.",
    [QCTextHostPasswordUnreadable] = "Ekki er hægt að lesa lykilorðaskrána – ný tæki aðeins með \"Leyfa\".",
    [QCTextHostDevices]            = "Leyfð tæki",
    [QCTextHostNoDevices]          = "Engin tæki enn",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – frá {d}",
    [QCTextHostRemove]             = "Fjarlægja",
    [QCTextHostRemoveAll]          = "Fjarlægja öll tæki …",
    [QCTextHostRemoveAllAsk]       = "Fjarlægja öll leyfð tæki? Þau þurfa þá lykilorðið aftur.",
    [QCTextHostListDamaged]        = "Tækjalistinn er skemmdur",
    [QCTextHostListReset]          = "Endurstilla tækjalista",
    [QCTextHostRequest]            = "{n} (ID {i}) vill stjórna þessari tölvu.",
    [QCTextHostAllow]              = "Leyfa",
    [QCTextHostDeny]               = "Hafna",
    [QCTextHostStartLogin]         = "Ræsa við innskráningu",
    [QCTextHostStartWindows]       = "Ræsa með Windows",
    [QCTextHostMoveToApps]         = "Færðu QuadChroma fyrst í Forrit-möppuna",
    [QCTextHostScreenMissing]      = "Skjáupptaka ekki leyfð – opna kerfisstillingar …",
    [QCTextHostAccessMissing]      = "Aðgengi ekki leyft – opna kerfisstillingar …",
    [QCTextHostPortBusy]           = "Gátt {p} er í notkun hjá öðru forriti",
    [QCTextHostQuit]               = "Hætta í QuadChroma",
    [QCTextHostStopSharing]        = "Hætta að deila",
    [QCTextHostTooltip]            = "QuadChroma – þessari tölvu er deilt (ID {i})",
    [QCTextHostOk]                 = "Í lagi",
    [QCTextAccessCode]             = "Kóði: {c}",
    [QCTextAccessCancel]           = "Hætta við",
    [QCTextHostPasswordNotSaved]   = "Ekki tókst að vista lykilorðið.",
    [QCTextHostPasswordInvalid]    = "Lykilorðið inniheldur stafi sem eru ekki leyfðir.",
    [QCTextHostPasswordTitle]      = "Breyta lykilorði",
}};

static const qc_sprache QC_PL = { "pl", "Polski", {
    [QCTextHostReady]              = "Gotowy na połączenia",
    [QCTextHostConnected]          = "Połączono: {n}",
    [QCTextHostDeviceId]           = "ID urządzenia: {i}",
    [QCTextHostPassword]           = "Hasło: {p}",
    [QCTextHostCopied]             = "Skopiowano",
    [QCTextHostChangePassword]     = "Zmień hasło …",
    [QCTextHostRandomPassword]     = "Nowe losowe hasło",
    [QCTextHostNewPassword]        = "Nowe hasło (co najmniej 8 znaków)",
    [QCTextHostRepeatPassword]     = "Powtórz hasło",
    [QCTextHostPasswordsDiffer]    = "Hasła nie są zgodne.",
    [QCTextHostPasswordShort]      = "Użyj co najmniej 8 znaków.",
    [QCTextHostPasswordSaved]      = "Hasło zapisane.",
    [QCTextHostPasswordUnreadable] = "Nie można odczytać pliku hasła – nowe urządzenia tylko przez \"Zezwól\".",
    [QCTextHostDevices]            = "Dozwolone urządzenia",
    [QCTextHostNoDevices]          = "Brak urządzeń",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – od {d}",
    [QCTextHostRemove]             = "Usuń",
    [QCTextHostRemoveAll]          = "Usuń wszystkie urządzenia …",
    [QCTextHostRemoveAllAsk]       = "Usunąć wszystkie dozwolone urządzenia? Będą znowu potrzebować hasła.",
    [QCTextHostListDamaged]        = "Lista urządzeń uszkodzona",
    [QCTextHostListReset]          = "Zresetuj listę urządzeń",
    [QCTextHostRequest]            = "{n} (ID {i}) chce sterować tym komputerem.",
    [QCTextHostAllow]              = "Zezwól",
    [QCTextHostDeny]               = "Odmów",
    [QCTextHostStartLogin]         = "Uruchamiaj po zalogowaniu",
    [QCTextHostStartWindows]       = "Uruchamiaj z systemem Windows",
    [QCTextHostMoveToApps]         = "Najpierw przenieś QuadChroma do folderu Aplikacje",
    [QCTextHostScreenMissing]      = "Nagrywanie ekranu niedozwolone – otwórz Ustawienia systemowe …",
    [QCTextHostAccessMissing]      = "Dostępność niedozwolona – otwórz Ustawienia systemowe …",
    [QCTextHostPortBusy]           = "Port {p} jest używany przez inny program",
    [QCTextHostQuit]               = "Zakończ QuadChroma",
    [QCTextHostStopSharing]        = "Zatrzymaj udostępnianie",
    [QCTextHostTooltip]            = "QuadChroma – ten komputer jest udostępniony (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kod: {c}",
    [QCTextAccessCancel]           = "Anuluj",
    [QCTextHostPasswordNotSaved]   = "Nie udało się zapisać hasła.",
    [QCTextHostPasswordInvalid]    = "Hasło zawiera niedozwolone znaki.",
    [QCTextHostPasswordTitle]      = "Zmień hasło",
}};

static const qc_sprache QC_CS = { "cs", "Čeština", {
    [QCTextHostReady]              = "Připraveno k připojení",
    [QCTextHostConnected]          = "Připojeno: {n}",
    [QCTextHostDeviceId]           = "ID zařízení: {i}",
    [QCTextHostPassword]           = "Heslo: {p}",
    [QCTextHostCopied]             = "Zkopírováno",
    [QCTextHostChangePassword]     = "Změnit heslo …",
    [QCTextHostRandomPassword]     = "Nové náhodné heslo",
    [QCTextHostNewPassword]        = "Nové heslo (alespoň 8 znaků)",
    [QCTextHostRepeatPassword]     = "Zopakujte heslo",
    [QCTextHostPasswordsDiffer]    = "Hesla se neshodují.",
    [QCTextHostPasswordShort]      = "Použijte alespoň 8 znaků.",
    [QCTextHostPasswordSaved]      = "Heslo uloženo.",
    [QCTextHostPasswordUnreadable] = "Soubor s heslem nelze přečíst – nová zařízení jen přes \"Povolit\".",
    [QCTextHostDevices]            = "Povolená zařízení",
    [QCTextHostNoDevices]          = "Zatím žádná zařízení",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – od {d}",
    [QCTextHostRemove]             = "Odebrat",
    [QCTextHostRemoveAll]          = "Odebrat všechna zařízení …",
    [QCTextHostRemoveAllAsk]       = "Odebrat všechna povolená zařízení? Pak budou znovu potřebovat heslo.",
    [QCTextHostListDamaged]        = "Seznam zařízení je poškozený",
    [QCTextHostListReset]          = "Obnovit seznam zařízení",
    [QCTextHostRequest]            = "{n} (ID {i}) chce ovládat tento počítač.",
    [QCTextHostAllow]              = "Povolit",
    [QCTextHostDeny]               = "Odmítnout",
    [QCTextHostStartLogin]         = "Spouštět po přihlášení",
    [QCTextHostStartWindows]       = "Spouštět se systémem Windows",
    [QCTextHostMoveToApps]         = "Nejdřív přesuňte QuadChroma do složky Aplikace",
    [QCTextHostScreenMissing]      = "Nahrávání obrazovky není povoleno – otevřít Nastavení systému …",
    [QCTextHostAccessMissing]      = "Zpřístupnění není povoleno – otevřít Nastavení systému …",
    [QCTextHostPortBusy]           = "Port {p} používá jiný program",
    [QCTextHostQuit]               = "Ukončit QuadChroma",
    [QCTextHostStopSharing]        = "Ukončit sdílení",
    [QCTextHostTooltip]            = "QuadChroma – tento počítač je sdílen (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kód: {c}",
    [QCTextAccessCancel]           = "Zrušit",
    [QCTextHostPasswordNotSaved]   = "Heslo se nepodařilo uložit.",
    [QCTextHostPasswordInvalid]    = "Heslo obsahuje nepovolené znaky.",
    [QCTextHostPasswordTitle]      = "Změnit heslo",
}};

static const qc_sprache QC_SK = { "sk", "Slovenčina", {
    [QCTextHostReady]              = "Pripravené na pripojenie",
    [QCTextHostConnected]          = "Pripojené: {n}",
    [QCTextHostDeviceId]           = "ID zariadenia: {i}",
    [QCTextHostPassword]           = "Heslo: {p}",
    [QCTextHostCopied]             = "Skopírované",
    [QCTextHostChangePassword]     = "Zmeniť heslo …",
    [QCTextHostRandomPassword]     = "Nové náhodné heslo",
    [QCTextHostNewPassword]        = "Nové heslo (aspoň 8 znakov)",
    [QCTextHostRepeatPassword]     = "Zopakujte heslo",
    [QCTextHostPasswordsDiffer]    = "Heslá sa nezhodujú.",
    [QCTextHostPasswordShort]      = "Použite aspoň 8 znakov.",
    [QCTextHostPasswordSaved]      = "Heslo uložené.",
    [QCTextHostPasswordUnreadable] = "Súbor s heslom sa nedá prečítať – nové zariadenia len cez \"Povoliť\".",
    [QCTextHostDevices]            = "Povolené zariadenia",
    [QCTextHostNoDevices]          = "Zatiaľ žiadne zariadenia",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – od {d}",
    [QCTextHostRemove]             = "Odstrániť",
    [QCTextHostRemoveAll]          = "Odstrániť všetky zariadenia …",
    [QCTextHostRemoveAllAsk]       = "Odstrániť všetky povolené zariadenia? Potom budú znova potrebovať heslo.",
    [QCTextHostListDamaged]        = "Zoznam zariadení je poškodený",
    [QCTextHostListReset]          = "Obnoviť zoznam zariadení",
    [QCTextHostRequest]            = "{n} (ID {i}) chce ovládať tento počítač.",
    [QCTextHostAllow]              = "Povoliť",
    [QCTextHostDeny]               = "Odmietnuť",
    [QCTextHostStartLogin]         = "Spúšťať po prihlásení",
    [QCTextHostStartWindows]       = "Spúšťať so systémom Windows",
    [QCTextHostMoveToApps]         = "Najprv presuňte QuadChroma do priečinka Aplikácie",
    [QCTextHostScreenMissing]      = "Nahrávanie obrazovky nie je povolené – otvoriť Systémové nastavenia …",
    [QCTextHostAccessMissing]      = "Prístupnosť nie je povolená – otvoriť Systémové nastavenia …",
    [QCTextHostPortBusy]           = "Port {p} používa iný program",
    [QCTextHostQuit]               = "Ukončiť QuadChroma",
    [QCTextHostStopSharing]        = "Ukončiť zdieľanie",
    [QCTextHostTooltip]            = "QuadChroma – tento počítač je zdieľaný (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kód: {c}",
    [QCTextAccessCancel]           = "Zrušiť",
    [QCTextHostPasswordNotSaved]   = "Heslo sa nepodarilo uložiť.",
    [QCTextHostPasswordInvalid]    = "Heslo obsahuje nepovolené znaky.",
    [QCTextHostPasswordTitle]      = "Zmeniť heslo",
}};

static const qc_sprache QC_HU = { "hu", "Magyar", {
    [QCTextHostReady]              = "Kapcsolódásra kész",
    [QCTextHostConnected]          = "Csatlakozva: {n}",
    [QCTextHostDeviceId]           = "Eszközazonosító: {i}",
    [QCTextHostPassword]           = "Jelszó: {p}",
    [QCTextHostCopied]             = "Másolva",
    [QCTextHostChangePassword]     = "Jelszó módosítása …",
    [QCTextHostRandomPassword]     = "Új véletlen jelszó",
    [QCTextHostNewPassword]        = "Új jelszó (legalább 8 karakter)",
    [QCTextHostRepeatPassword]     = "Jelszó megismétlése",
    [QCTextHostPasswordsDiffer]    = "A jelszavak nem egyeznek.",
    [QCTextHostPasswordShort]      = "Legalább 8 karaktert adjon meg.",
    [QCTextHostPasswordSaved]      = "Jelszó mentve.",
    [QCTextHostPasswordUnreadable] = "A jelszófájl nem olvasható – új eszközök csak az \"Engedélyezés\" gombbal.",
    [QCTextHostDevices]            = "Engedélyezett eszközök",
    [QCTextHostNoDevices]          = "Még nincsenek eszközök",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – {d} óta",
    [QCTextHostRemove]             = "Eltávolítás",
    [QCTextHostRemoveAll]          = "Minden eszköz eltávolítása …",
    [QCTextHostRemoveAllAsk]       = "Eltávolítja az összes engedélyezett eszközt? Ezután újra szükségük lesz a jelszóra.",
    [QCTextHostListDamaged]        = "Az eszközlista sérült",
    [QCTextHostListReset]          = "Eszközlista visszaállítása",
    [QCTextHostRequest]            = "{n} (ID {i}) szeretné vezérelni ezt a számítógépet.",
    [QCTextHostAllow]              = "Engedélyezés",
    [QCTextHostDeny]               = "Elutasítás",
    [QCTextHostStartLogin]         = "Indítás bejelentkezéskor",
    [QCTextHostStartWindows]       = "Indítás a Windows-zal",
    [QCTextHostMoveToApps]         = "Előbb helyezze át a QuadChromát az Alkalmazások mappába",
    [QCTextHostScreenMissing]      = "Képernyőfelvétel nincs engedélyezve – Rendszerbeállítások megnyitása …",
    [QCTextHostAccessMissing]      = "Kisegítő lehetőségek nincsenek engedélyezve – Rendszerbeállítások megnyitása …",
    [QCTextHostPortBusy]           = "A(z) {p} portot egy másik program használja",
    [QCTextHostQuit]               = "Kilépés a QuadChromából",
    [QCTextHostStopSharing]        = "Megosztás leállítása",
    [QCTextHostTooltip]            = "QuadChroma – a számítógép megosztva (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kód: {c}",
    [QCTextAccessCancel]           = "Mégse",
    [QCTextHostPasswordNotSaved]   = "A jelszót nem sikerült menteni.",
    [QCTextHostPasswordInvalid]    = "A jelszó nem engedélyezett karaktereket tartalmaz.",
    [QCTextHostPasswordTitle]      = "Jelszó módosítása",
}};

static const qc_sprache QC_RO = { "ro", "Română", {
    [QCTextHostReady]              = "Pregătit pentru conexiuni",
    [QCTextHostConnected]          = "Conectat: {n}",
    [QCTextHostDeviceId]           = "ID dispozitiv: {i}",
    [QCTextHostPassword]           = "Parolă: {p}",
    [QCTextHostCopied]             = "Copiat",
    [QCTextHostChangePassword]     = "Schimbă parola …",
    [QCTextHostRandomPassword]     = "Parolă aleatorie nouă",
    [QCTextHostNewPassword]        = "Parolă nouă (cel puțin 8 caractere)",
    [QCTextHostRepeatPassword]     = "Repetați parola",
    [QCTextHostPasswordsDiffer]    = "Parolele nu coincid.",
    [QCTextHostPasswordShort]      = "Folosiți cel puțin 8 caractere.",
    [QCTextHostPasswordSaved]      = "Parola a fost salvată.",
    [QCTextHostPasswordUnreadable] = "Fișierul parolei nu poate fi citit – dispozitive noi doar prin \"Permite\".",
    [QCTextHostDevices]            = "Dispozitive permise",
    [QCTextHostNoDevices]          = "Încă niciun dispozitiv",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – din {d}",
    [QCTextHostRemove]             = "Elimină",
    [QCTextHostRemoveAll]          = "Elimină toate dispozitivele …",
    [QCTextHostRemoveAllAsk]       = "Eliminați toate dispozitivele permise? Vor avea din nou nevoie de parolă.",
    [QCTextHostListDamaged]        = "Lista de dispozitive este deteriorată",
    [QCTextHostListReset]          = "Resetează lista de dispozitive",
    [QCTextHostRequest]            = "{n} (ID {i}) dorește să controleze acest computer.",
    [QCTextHostAllow]              = "Permite",
    [QCTextHostDeny]               = "Refuză",
    [QCTextHostStartLogin]         = "Pornește la autentificare",
    [QCTextHostStartWindows]       = "Pornește odată cu Windows",
    [QCTextHostMoveToApps]         = "Mutați mai întâi QuadChroma în Aplicații",
    [QCTextHostScreenMissing]      = "Înregistrarea ecranului nu este permisă – deschideți Configurări sistem …",
    [QCTextHostAccessMissing]      = "Accesibilitatea nu este permisă – deschideți Configurări sistem …",
    [QCTextHostPortBusy]           = "Portul {p} este folosit de alt program",
    [QCTextHostQuit]               = "Ieșire din QuadChroma",
    [QCTextHostStopSharing]        = "Oprește partajarea",
    [QCTextHostTooltip]            = "QuadChroma – acest PC este partajat (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Cod: {c}",
    [QCTextAccessCancel]           = "Anulare",
    [QCTextHostPasswordNotSaved]   = "Parola nu a putut fi salvată.",
    [QCTextHostPasswordInvalid]    = "Parola conține caractere nepermise.",
    [QCTextHostPasswordTitle]      = "Schimbă parola",
}};

static const qc_sprache QC_BG = { "bg", "Български", {
    [QCTextHostReady]              = "Готов за връзки",
    [QCTextHostConnected]          = "Свързано: {n}",
    [QCTextHostDeviceId]           = "ID на устройството: {i}",
    [QCTextHostPassword]           = "Парола: {p}",
    [QCTextHostCopied]             = "Копирано",
    [QCTextHostChangePassword]     = "Смяна на паролата …",
    [QCTextHostRandomPassword]     = "Нова случайна парола",
    [QCTextHostNewPassword]        = "Нова парола (поне 8 знака)",
    [QCTextHostRepeatPassword]     = "Повторете паролата",
    [QCTextHostPasswordsDiffer]    = "Паролите не съвпадат.",
    [QCTextHostPasswordShort]      = "Използвайте поне 8 знака.",
    [QCTextHostPasswordSaved]      = "Паролата е запазена.",
    [QCTextHostPasswordUnreadable] = "Файлът с паролата не може да се прочете – нови устройства само чрез \"Разреши\".",
    [QCTextHostDevices]            = "Разрешени устройства",
    [QCTextHostNoDevices]          = "Все още няма устройства",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – от {d}",
    [QCTextHostRemove]             = "Премахни",
    [QCTextHostRemoveAll]          = "Премахни всички устройства …",
    [QCTextHostRemoveAllAsk]       = "Да се премахнат ли всички разрешени устройства? Те отново ще се нуждаят от паролата.",
    [QCTextHostListDamaged]        = "Списъкът с устройства е повреден",
    [QCTextHostListReset]          = "Нулиране на списъка с устройства",
    [QCTextHostRequest]            = "{n} (ID {i}) иска да управлява този компютър.",
    [QCTextHostAllow]              = "Разреши",
    [QCTextHostDeny]               = "Отхвърли",
    [QCTextHostStartLogin]         = "Стартиране при влизане",
    [QCTextHostStartWindows]       = "Стартиране с Windows",
    [QCTextHostMoveToApps]         = "Първо преместете QuadChroma в папката Програми",
    [QCTextHostScreenMissing]      = "Записът на екрана не е разрешен – отворете Системни настройки …",
    [QCTextHostAccessMissing]      = "Достъпността не е разрешена – отворете Системни настройки …",
    [QCTextHostPortBusy]           = "Порт {p} се използва от друга програма",
    [QCTextHostQuit]               = "Изход от QuadChroma",
    [QCTextHostStopSharing]        = "Спиране на споделянето",
    [QCTextHostTooltip]            = "QuadChroma – този компютър е споделен (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Код: {c}",
    [QCTextAccessCancel]           = "Отказ",
    [QCTextHostPasswordNotSaved]   = "Паролата не можа да бъде запазена.",
    [QCTextHostPasswordInvalid]    = "Паролата съдържа непозволени знаци.",
    [QCTextHostPasswordTitle]      = "Смяна на паролата",
}};

static const qc_sprache QC_EL = { "el", "Ελληνικά", {
    [QCTextHostReady]              = "Έτοιμο για συνδέσεις",
    [QCTextHostConnected]          = "Συνδεδεμένο: {n}",
    [QCTextHostDeviceId]           = "ID συσκευής: {i}",
    [QCTextHostPassword]           = "Κωδικός πρόσβασης: {p}",
    [QCTextHostCopied]             = "Αντιγράφηκε",
    [QCTextHostChangePassword]     = "Αλλαγή κωδικού πρόσβασης …",
    [QCTextHostRandomPassword]     = "Νέος τυχαίος κωδικός πρόσβασης",
    [QCTextHostNewPassword]        = "Νέος κωδικός πρόσβασης (τουλάχιστον 8 χαρακτήρες)",
    [QCTextHostRepeatPassword]     = "Επανάληψη κωδικού πρόσβασης",
    [QCTextHostPasswordsDiffer]    = "Οι κωδικοί πρόσβασης δεν ταιριάζουν.",
    [QCTextHostPasswordShort]      = "Χρησιμοποιήστε τουλάχιστον 8 χαρακτήρες.",
    [QCTextHostPasswordSaved]      = "Ο κωδικός πρόσβασης αποθηκεύτηκε.",
    [QCTextHostPasswordUnreadable] = "Το αρχείο του κωδικού πρόσβασης δεν διαβάζεται – νέες συσκευές μόνο μέσω \"Αποδοχή\".",
    [QCTextHostDevices]            = "Επιτρεπόμενες συσκευές",
    [QCTextHostNoDevices]          = "Δεν υπάρχουν ακόμη συσκευές",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – από {d}",
    [QCTextHostRemove]             = "Αφαίρεση",
    [QCTextHostRemoveAll]          = "Αφαίρεση όλων των συσκευών …",
    [QCTextHostRemoveAllAsk]       = "Αφαίρεση όλων των επιτρεπόμενων συσκευών; Θα χρειαστούν ξανά τον κωδικό πρόσβασης.",
    [QCTextHostListDamaged]        = "Η λίστα συσκευών είναι κατεστραμμένη",
    [QCTextHostListReset]          = "Επαναφορά λίστας συσκευών",
    [QCTextHostRequest]            = "Η συσκευή {n} (ID {i}) θέλει να ελέγξει αυτόν τον υπολογιστή.",
    [QCTextHostAllow]              = "Αποδοχή",
    [QCTextHostDeny]               = "Απόρριψη",
    [QCTextHostStartLogin]         = "Εκκίνηση κατά τη σύνδεση",
    [QCTextHostStartWindows]       = "Εκκίνηση με τα Windows",
    [QCTextHostMoveToApps]         = "Μετακινήστε πρώτα το QuadChroma στις Εφαρμογές",
    [QCTextHostScreenMissing]      = "Η εγγραφή οθόνης δεν επιτρέπεται – άνοιγμα Ρυθμίσεων συστήματος …",
    [QCTextHostAccessMissing]      = "Η προσβασιμότητα δεν επιτρέπεται – άνοιγμα Ρυθμίσεων συστήματος …",
    [QCTextHostPortBusy]           = "Η θύρα {p} χρησιμοποιείται από άλλο πρόγραμμα",
    [QCTextHostQuit]               = "Έξοδος από το QuadChroma",
    [QCTextHostStopSharing]        = "Διακοπή κοινής χρήσης",
    [QCTextHostTooltip]            = "QuadChroma – ο υπολογιστής είναι σε κοινή χρήση (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Κωδικός επαλήθευσης: {c}",
    [QCTextAccessCancel]           = "Ακύρωση",
    [QCTextHostPasswordNotSaved]   = "Δεν ήταν δυνατή η αποθήκευση του κωδικού πρόσβασης.",
    [QCTextHostPasswordInvalid]    = "Ο κωδικός πρόσβασης περιέχει μη επιτρεπόμενους χαρακτήρες.",
    [QCTextHostPasswordTitle]      = "Αλλαγή κωδικού πρόσβασης",
}};

static const qc_sprache QC_ET = { "et", "Eesti", {
    [QCTextHostReady]              = "Valmis ühendusteks",
    [QCTextHostConnected]          = "Ühendatud: {n}",
    [QCTextHostDeviceId]           = "Seadme ID: {i}",
    [QCTextHostPassword]           = "Parool: {p}",
    [QCTextHostCopied]             = "Kopeeritud",
    [QCTextHostChangePassword]     = "Muuda parooli …",
    [QCTextHostRandomPassword]     = "Uus juhuslik parool",
    [QCTextHostNewPassword]        = "Uus parool (vähemalt 8 märki)",
    [QCTextHostRepeatPassword]     = "Korda parooli",
    [QCTextHostPasswordsDiffer]    = "Paroolid ei ühti.",
    [QCTextHostPasswordShort]      = "Kasuta vähemalt 8 märki.",
    [QCTextHostPasswordSaved]      = "Parool on salvestatud.",
    [QCTextHostPasswordUnreadable] = "Paroolifaili ei saa lugeda – uued seadmed ainult nupuga \"Luba\".",
    [QCTextHostDevices]            = "Lubatud seadmed",
    [QCTextHostNoDevices]          = "Seadmeid veel pole",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – alates {d}",
    [QCTextHostRemove]             = "Eemalda",
    [QCTextHostRemoveAll]          = "Eemalda kõik seadmed …",
    [QCTextHostRemoveAllAsk]       = "Kas eemaldada kõik lubatud seadmed? Siis vajavad need uuesti parooli.",
    [QCTextHostListDamaged]        = "Seadmete loend on rikutud",
    [QCTextHostListReset]          = "Lähtesta seadmete loend",
    [QCTextHostRequest]            = "{n} (ID {i}) soovib seda arvutit juhtida.",
    [QCTextHostAllow]              = "Luba",
    [QCTextHostDeny]               = "Keela",
    [QCTextHostStartLogin]         = "Käivita sisselogimisel",
    [QCTextHostStartWindows]       = "Käivita koos Windowsiga",
    [QCTextHostMoveToApps]         = "Teisalda QuadChroma kõigepealt kausta Rakendused",
    [QCTextHostScreenMissing]      = "Ekraanisalvestus pole lubatud – ava Süsteemiseaded …",
    [QCTextHostAccessMissing]      = "Juurdepääsetavus pole lubatud – ava Süsteemiseaded …",
    [QCTextHostPortBusy]           = "Porti {p} kasutab teine programm",
    [QCTextHostQuit]               = "Välju QuadChromast",
    [QCTextHostStopSharing]        = "Lõpeta jagamine",
    [QCTextHostTooltip]            = "QuadChroma – seda arvutit jagatakse (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Kood: {c}",
    [QCTextAccessCancel]           = "Katkesta",
    [QCTextHostPasswordNotSaved]   = "Parooli ei õnnestunud salvestada.",
    [QCTextHostPasswordInvalid]    = "Parool sisaldab lubamatuid märke.",
    [QCTextHostPasswordTitle]      = "Muuda parooli",
}};

static const qc_sprache QC_LV = { "lv", "Latviešu", {
    [QCTextHostReady]              = "Gatavs savienojumiem",
    [QCTextHostConnected]          = "Savienots: {n}",
    [QCTextHostDeviceId]           = "Ierīces ID: {i}",
    [QCTextHostPassword]           = "Parole: {p}",
    [QCTextHostCopied]             = "Nokopēts",
    [QCTextHostChangePassword]     = "Mainīt paroli …",
    [QCTextHostRandomPassword]     = "Jauna nejauša parole",
    [QCTextHostNewPassword]        = "Jauna parole (vismaz 8 rakstzīmes)",
    [QCTextHostRepeatPassword]     = "Atkārtojiet paroli",
    [QCTextHostPasswordsDiffer]    = "Paroles nesakrīt.",
    [QCTextHostPasswordShort]      = "Lūdzu, vismaz 8 rakstzīmes.",
    [QCTextHostPasswordSaved]      = "Parole saglabāta.",
    [QCTextHostPasswordUnreadable] = "Paroles failu nevar nolasīt – jaunas ierīces tikai ar \"Atļaut\".",
    [QCTextHostDevices]            = "Atļautās ierīces",
    [QCTextHostNoDevices]          = "Vēl nav ierīču",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – kopš {d}",
    [QCTextHostRemove]             = "Noņemt",
    [QCTextHostRemoveAll]          = "Noņemt visas ierīces …",
    [QCTextHostRemoveAllAsk]       = "Noņemt visas atļautās ierīces? Tām atkal būs vajadzīga parole.",
    [QCTextHostListDamaged]        = "Ierīču saraksts ir bojāts",
    [QCTextHostListReset]          = "Atiestatīt ierīču sarakstu",
    [QCTextHostRequest]            = "{n} (ID {i}) vēlas vadīt šo datoru.",
    [QCTextHostAllow]              = "Atļaut",
    [QCTextHostDeny]               = "Noraidīt",
    [QCTextHostStartLogin]         = "Palaist pēc pieteikšanās",
    [QCTextHostStartWindows]       = "Palaist kopā ar Windows",
    [QCTextHostMoveToApps]         = "Vispirms pārvietojiet QuadChroma uz mapi Lietotnes",
    [QCTextHostScreenMissing]      = "Ekrāna ierakstīšana nav atļauta – atvērt Sistēmas iestatījumus …",
    [QCTextHostAccessMissing]      = "Pieejamība nav atļauta – atvērt Sistēmas iestatījumus …",
    [QCTextHostPortBusy]           = "Portu {p} izmanto cita programma",
    [QCTextHostQuit]               = "Iziet no QuadChroma",
    [QCTextHostStopSharing]        = "Pārtraukt koplietošanu",
    [QCTextHostTooltip]            = "QuadChroma – šis dators tiek koplietots (ID {i})",
    [QCTextHostOk]                 = "Labi",
    [QCTextAccessCode]             = "Kods: {c}",
    [QCTextAccessCancel]           = "Atcelt",
    [QCTextHostPasswordNotSaved]   = "Paroli neizdevās saglabāt.",
    [QCTextHostPasswordInvalid]    = "Parolē ir neatļautas rakstzīmes.",
    [QCTextHostPasswordTitle]      = "Mainīt paroli",
}};

static const qc_sprache QC_LT = { "lt", "Lietuvių", {
    [QCTextHostReady]              = "Pasirengęs ryšiams",
    [QCTextHostConnected]          = "Prisijungta: {n}",
    [QCTextHostDeviceId]           = "Įrenginio ID: {i}",
    [QCTextHostPassword]           = "Slaptažodis: {p}",
    [QCTextHostCopied]             = "Nukopijuota",
    [QCTextHostChangePassword]     = "Keisti slaptažodį …",
    [QCTextHostRandomPassword]     = "Naujas atsitiktinis slaptažodis",
    [QCTextHostNewPassword]        = "Naujas slaptažodis (bent 8 simboliai)",
    [QCTextHostRepeatPassword]     = "Pakartokite slaptažodį",
    [QCTextHostPasswordsDiffer]    = "Slaptažodžiai nesutampa.",
    [QCTextHostPasswordShort]      = "Naudokite bent 8 simbolius.",
    [QCTextHostPasswordSaved]      = "Slaptažodis išsaugotas.",
    [QCTextHostPasswordUnreadable] = "Slaptažodžio failo neįmanoma perskaityti – nauji įrenginiai tik per \"Leisti\".",
    [QCTextHostDevices]            = "Leidžiami įrenginiai",
    [QCTextHostNoDevices]          = "Įrenginių dar nėra",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – nuo {d}",
    [QCTextHostRemove]             = "Pašalinti",
    [QCTextHostRemoveAll]          = "Pašalinti visus įrenginius …",
    [QCTextHostRemoveAllAsk]       = "Pašalinti visus leidžiamus įrenginius? Jiems vėl reikės slaptažodžio.",
    [QCTextHostListDamaged]        = "Įrenginių sąrašas sugadintas",
    [QCTextHostListReset]          = "Iš naujo nustatyti įrenginių sąrašą",
    [QCTextHostRequest]            = "{n} (ID {i}) nori valdyti šį kompiuterį.",
    [QCTextHostAllow]              = "Leisti",
    [QCTextHostDeny]               = "Atmesti",
    [QCTextHostStartLogin]         = "Paleisti prisijungus",
    [QCTextHostStartWindows]       = "Paleisti kartu su Windows",
    [QCTextHostMoveToApps]         = "Pirmiausia perkelkite QuadChroma į aplanką Programos",
    [QCTextHostScreenMissing]      = "Ekrano įrašymas neleidžiamas – atidaryti Sistemos nustatymus …",
    [QCTextHostAccessMissing]      = "Prieinamumas neleidžiamas – atidaryti Sistemos nustatymus …",
    [QCTextHostPortBusy]           = "Prievadą {p} naudoja kita programa",
    [QCTextHostQuit]               = "Išeiti iš QuadChroma",
    [QCTextHostStopSharing]        = "Nutraukti bendrinimą",
    [QCTextHostTooltip]            = "QuadChroma – šis kompiuteris bendrinamas (ID {i})",
    [QCTextHostOk]                 = "Gerai",
    [QCTextAccessCode]             = "Kodas: {c}",
    [QCTextAccessCancel]           = "Atšaukti",
    [QCTextHostPasswordNotSaved]   = "Nepavyko išsaugoti slaptažodžio.",
    [QCTextHostPasswordInvalid]    = "Slaptažodyje yra neleistinų simbolių.",
    [QCTextHostPasswordTitle]      = "Keisti slaptažodį",
}};

static const qc_sprache QC_SL = { "sl", "Slovenščina", {
    [QCTextHostReady]              = "Pripravljeno za povezave",
    [QCTextHostConnected]          = "Povezano: {n}",
    [QCTextHostDeviceId]           = "ID naprave: {i}",
    [QCTextHostPassword]           = "Geslo: {p}",
    [QCTextHostCopied]             = "Kopirano",
    [QCTextHostChangePassword]     = "Spremeni geslo …",
    [QCTextHostRandomPassword]     = "Novo naključno geslo",
    [QCTextHostNewPassword]        = "Novo geslo (vsaj 8 znakov)",
    [QCTextHostRepeatPassword]     = "Ponovite geslo",
    [QCTextHostPasswordsDiffer]    = "Gesli se ne ujemata.",
    [QCTextHostPasswordShort]      = "Uporabite vsaj 8 znakov.",
    [QCTextHostPasswordSaved]      = "Geslo je shranjeno.",
    [QCTextHostPasswordUnreadable] = "Datoteke z geslom ni mogoče prebrati – nove naprave samo prek \"Dovoli\".",
    [QCTextHostDevices]            = "Dovoljene naprave",
    [QCTextHostNoDevices]          = "Še ni naprav",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – od {d}",
    [QCTextHostRemove]             = "Odstrani",
    [QCTextHostRemoveAll]          = "Odstrani vse naprave …",
    [QCTextHostRemoveAllAsk]       = "Želite odstraniti vse dovoljene naprave? Potem bodo spet potrebovale geslo.",
    [QCTextHostListDamaged]        = "Seznam naprav je poškodovan",
    [QCTextHostListReset]          = "Ponastavi seznam naprav",
    [QCTextHostRequest]            = "{n} (ID {i}) želi upravljati ta računalnik.",
    [QCTextHostAllow]              = "Dovoli",
    [QCTextHostDeny]               = "Zavrni",
    [QCTextHostStartLogin]         = "Zaženi ob prijavi",
    [QCTextHostStartWindows]       = "Zaženi s sistemom Windows",
    [QCTextHostMoveToApps]         = "Najprej premaknite QuadChroma v mapo Aplikacije",
    [QCTextHostScreenMissing]      = "Snemanje zaslona ni dovoljeno – odpri Sistemske nastavitve …",
    [QCTextHostAccessMissing]      = "Dostopnost ni dovoljena – odpri Sistemske nastavitve …",
    [QCTextHostPortBusy]           = "Vrata {p} uporablja drug program",
    [QCTextHostQuit]               = "Končaj QuadChroma",
    [QCTextHostStopSharing]        = "Ustavi deljenje",
    [QCTextHostTooltip]            = "QuadChroma – ta računalnik je deljen (ID {i})",
    [QCTextHostOk]                 = "V redu",
    [QCTextAccessCode]             = "Koda: {c}",
    [QCTextAccessCancel]           = "Prekliči",
    [QCTextHostPasswordNotSaved]   = "Gesla ni bilo mogoče shraniti.",
    [QCTextHostPasswordInvalid]    = "Geslo vsebuje nedovoljene znake.",
    [QCTextHostPasswordTitle]      = "Spremeni geslo",
}};

static const qc_sprache QC_HR = { "hr", "Hrvatski", {
    [QCTextHostReady]              = "Spremno za veze",
    [QCTextHostConnected]          = "Povezano: {n}",
    [QCTextHostDeviceId]           = "ID uređaja: {i}",
    [QCTextHostPassword]           = "Lozinka: {p}",
    [QCTextHostCopied]             = "Kopirano",
    [QCTextHostChangePassword]     = "Promijeni lozinku …",
    [QCTextHostRandomPassword]     = "Nova nasumična lozinka",
    [QCTextHostNewPassword]        = "Nova lozinka (najmanje 8 znakova)",
    [QCTextHostRepeatPassword]     = "Ponovite lozinku",
    [QCTextHostPasswordsDiffer]    = "Lozinke se ne podudaraju.",
    [QCTextHostPasswordShort]      = "Upotrijebite najmanje 8 znakova.",
    [QCTextHostPasswordSaved]      = "Lozinka je spremljena.",
    [QCTextHostPasswordUnreadable] = "Datoteka s lozinkom nije čitljiva – novi uređaji samo putem \"Dopusti\".",
    [QCTextHostDevices]            = "Dopušteni uređaji",
    [QCTextHostNoDevices]          = "Još nema uređaja",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – od {d}",
    [QCTextHostRemove]             = "Ukloni",
    [QCTextHostRemoveAll]          = "Ukloni sve uređaje …",
    [QCTextHostRemoveAllAsk]       = "Ukloniti sve dopuštene uređaje? Tada će ponovno trebati lozinku.",
    [QCTextHostListDamaged]        = "Popis uređaja je oštećen",
    [QCTextHostListReset]          = "Poništi popis uređaja",
    [QCTextHostRequest]            = "{n} (ID {i}) želi upravljati ovim računalom.",
    [QCTextHostAllow]              = "Dopusti",
    [QCTextHostDeny]               = "Odbij",
    [QCTextHostStartLogin]         = "Pokreni pri prijavi",
    [QCTextHostStartWindows]       = "Pokreni sa sustavom Windows",
    [QCTextHostMoveToApps]         = "Najprije premjestite QuadChroma u mapu Aplikacije",
    [QCTextHostScreenMissing]      = "Snimanje zaslona nije dopušteno – otvori Postavke sustava …",
    [QCTextHostAccessMissing]      = "Pristupačnost nije dopuštena – otvori Postavke sustava …",
    [QCTextHostPortBusy]           = "Port {p} koristi drugi program",
    [QCTextHostQuit]               = "Izlaz iz programa QuadChroma",
    [QCTextHostStopSharing]        = "Zaustavi dijeljenje",
    [QCTextHostTooltip]            = "QuadChroma – ovo računalo se dijeli (ID {i})",
    [QCTextHostOk]                 = "U redu",
    [QCTextAccessCode]             = "Kod: {c}",
    [QCTextAccessCancel]           = "Odustani",
    [QCTextHostPasswordNotSaved]   = "Lozinku nije bilo moguće spremiti.",
    [QCTextHostPasswordInvalid]    = "Lozinka sadrži nedopuštene znakove.",
    [QCTextHostPasswordTitle]      = "Promijeni lozinku",
}};

static const qc_sprache QC_UK = { "uk", "Українська", {
    [QCTextHostReady]              = "Готово до підключень",
    [QCTextHostConnected]          = "Підключено: {n}",
    [QCTextHostDeviceId]           = "ID пристрою: {i}",
    [QCTextHostPassword]           = "Пароль: {p}",
    [QCTextHostCopied]             = "Скопійовано",
    [QCTextHostChangePassword]     = "Змінити пароль …",
    [QCTextHostRandomPassword]     = "Новий випадковий пароль",
    [QCTextHostNewPassword]        = "Новий пароль (щонайменше 8 символів)",
    [QCTextHostRepeatPassword]     = "Повторіть пароль",
    [QCTextHostPasswordsDiffer]    = "Паролі не збігаються.",
    [QCTextHostPasswordShort]      = "Потрібно щонайменше 8 символів.",
    [QCTextHostPasswordSaved]      = "Пароль збережено.",
    [QCTextHostPasswordUnreadable] = "Файл пароля не читається – нові пристрої лише через \"Дозволити\".",
    [QCTextHostDevices]            = "Дозволені пристрої",
    [QCTextHostNoDevices]          = "Пристроїв ще немає",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – з {d}",
    [QCTextHostRemove]             = "Видалити",
    [QCTextHostRemoveAll]          = "Видалити всі пристрої …",
    [QCTextHostRemoveAllAsk]       = "Видалити всі дозволені пристрої? Їм знову знадобиться пароль.",
    [QCTextHostListDamaged]        = "Список пристроїв пошкоджено",
    [QCTextHostListReset]          = "Скинути список пристроїв",
    [QCTextHostRequest]            = "{n} (ID {i}) хоче керувати цим комп'ютером.",
    [QCTextHostAllow]              = "Дозволити",
    [QCTextHostDeny]               = "Відхилити",
    [QCTextHostStartLogin]         = "Запускати під час входу",
    [QCTextHostStartWindows]       = "Запускати разом із Windows",
    [QCTextHostMoveToApps]         = "Спочатку перемістіть QuadChroma до папки Програми",
    [QCTextHostScreenMissing]      = "Запис екрана не дозволено – відкрити Системні параметри …",
    [QCTextHostAccessMissing]      = "Доступність не дозволено – відкрити Системні параметри …",
    [QCTextHostPortBusy]           = "Порт {p} зайнятий іншою програмою",
    [QCTextHostQuit]               = "Вийти з QuadChroma",
    [QCTextHostStopSharing]        = "Припинити надання доступу",
    [QCTextHostTooltip]            = "QuadChroma – доступ до цього ПК надано (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Код: {c}",
    [QCTextAccessCancel]           = "Скасувати",
    [QCTextHostPasswordNotSaved]   = "Не вдалося зберегти пароль.",
    [QCTextHostPasswordInvalid]    = "Пароль містить неприпустимі символи.",
    [QCTextHostPasswordTitle]      = "Змінити пароль",
}};

static const qc_sprache QC_RU = { "ru", "Русский", {
    [QCTextHostReady]              = "Готов к подключениям",
    [QCTextHostConnected]          = "Подключено: {n}",
    [QCTextHostDeviceId]           = "ID устройства: {i}",
    [QCTextHostPassword]           = "Пароль: {p}",
    [QCTextHostCopied]             = "Скопировано",
    [QCTextHostChangePassword]     = "Изменить пароль …",
    [QCTextHostRandomPassword]     = "Новый случайный пароль",
    [QCTextHostNewPassword]        = "Новый пароль (не менее 8 символов)",
    [QCTextHostRepeatPassword]     = "Повторите пароль",
    [QCTextHostPasswordsDiffer]    = "Пароли не совпадают.",
    [QCTextHostPasswordShort]      = "Нужно не менее 8 символов.",
    [QCTextHostPasswordSaved]      = "Пароль сохранён.",
    [QCTextHostPasswordUnreadable] = "Файл пароля не читается – новые устройства только через \"Разрешить\".",
    [QCTextHostDevices]            = "Разрешённые устройства",
    [QCTextHostNoDevices]          = "Устройств пока нет",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – с {d}",
    [QCTextHostRemove]             = "Удалить",
    [QCTextHostRemoveAll]          = "Удалить все устройства …",
    [QCTextHostRemoveAllAsk]       = "Удалить все разрешённые устройства? Им снова понадобится пароль.",
    [QCTextHostListDamaged]        = "Список устройств повреждён",
    [QCTextHostListReset]          = "Сбросить список устройств",
    [QCTextHostRequest]            = "{n} (ID {i}) хочет управлять этим компьютером.",
    [QCTextHostAllow]              = "Разрешить",
    [QCTextHostDeny]               = "Отклонить",
    [QCTextHostStartLogin]         = "Запускать при входе",
    [QCTextHostStartWindows]       = "Запускать вместе с Windows",
    [QCTextHostMoveToApps]         = "Сначала переместите QuadChroma в папку Программы",
    [QCTextHostScreenMissing]      = "Запись экрана не разрешена – открыть Системные настройки …",
    [QCTextHostAccessMissing]      = "Универсальный доступ не разрешён – открыть Системные настройки …",
    [QCTextHostPortBusy]           = "Порт {p} занят другой программой",
    [QCTextHostQuit]               = "Выход из QuadChroma",
    [QCTextHostStopSharing]        = "Закрыть доступ",
    [QCTextHostTooltip]            = "QuadChroma – доступ к этому ПК открыт (ID {i})",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "Код: {c}",
    [QCTextAccessCancel]           = "Отмена",
    [QCTextHostPasswordNotSaved]   = "Не удалось сохранить пароль.",
    [QCTextHostPasswordInvalid]    = "Пароль содержит недопустимые символы.",
    [QCTextHostPasswordTitle]      = "Изменить пароль",
}};

static const qc_sprache QC_ZH = { "zh", "简体中文", {
    [QCTextHostReady]              = "等待连接",
    [QCTextHostConnected]          = "已连接：{n}",
    [QCTextHostDeviceId]           = "设备 ID：{i}",
    [QCTextHostPassword]           = "密码：{p}",
    [QCTextHostCopied]             = "已复制",
    [QCTextHostChangePassword]     = "更改密码 …",
    [QCTextHostRandomPassword]     = "新的随机密码",
    [QCTextHostNewPassword]        = "新密码（至少 8 个字符）",
    [QCTextHostRepeatPassword]     = "再次输入密码",
    [QCTextHostPasswordsDiffer]    = "两次输入的密码不一致。",
    [QCTextHostPasswordShort]      = "请至少输入 8 个字符。",
    [QCTextHostPasswordSaved]      = "密码已保存。",
    [QCTextHostPasswordUnreadable] = "无法读取密码文件 – 新设备只能通过 \"允许\" 接入。",
    [QCTextHostDevices]            = "已允许的设备",
    [QCTextHostNoDevices]          = "暂无设备",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – 自 {d} 起",
    [QCTextHostRemove]             = "移除",
    [QCTextHostRemoveAll]          = "移除所有设备 …",
    [QCTextHostRemoveAllAsk]       = "要移除所有已允许的设备吗？ 之后它们需要重新输入密码。",
    [QCTextHostListDamaged]        = "设备列表已损坏",
    [QCTextHostListReset]          = "重置设备列表",
    [QCTextHostRequest]            = "{n}（ID {i}）想要控制这台电脑。",
    [QCTextHostAllow]              = "允许",
    [QCTextHostDeny]               = "拒绝",
    [QCTextHostStartLogin]         = "登录时启动",
    [QCTextHostStartWindows]       = "随 Windows 启动",
    [QCTextHostMoveToApps]         = "请先将 QuadChroma 移到应用程序文件夹",
    [QCTextHostScreenMissing]      = "屏幕录制未获允许 – 打开系统设置 …",
    [QCTextHostAccessMissing]      = "辅助功能未获允许 – 打开系统设置 …",
    [QCTextHostPortBusy]           = "端口 {p} 已被其他程序占用",
    [QCTextHostQuit]               = "退出 QuadChroma",
    [QCTextHostStopSharing]        = "停止共享",
    [QCTextHostTooltip]            = "QuadChroma – 正在共享此电脑（ID {i}）",
    [QCTextHostOk]                 = "确定",
    [QCTextAccessCode]             = "校验码：{c}",
    [QCTextAccessCancel]           = "取消",
    [QCTextHostPasswordNotSaved]   = "无法保存密码。",
    [QCTextHostPasswordInvalid]    = "密码包含不允许的字符。",
    [QCTextHostPasswordTitle]      = "更改密码",
}};

static const qc_sprache QC_JA = { "ja", "日本語", {
    [QCTextHostReady]              = "接続を待機中",
    [QCTextHostConnected]          = "接続中: {n}",
    [QCTextHostDeviceId]           = "デバイス ID: {i}",
    [QCTextHostPassword]           = "パスワード: {p}",
    [QCTextHostCopied]             = "コピーしました",
    [QCTextHostChangePassword]     = "パスワードを変更 …",
    [QCTextHostRandomPassword]     = "新しいランダムパスワード",
    [QCTextHostNewPassword]        = "新しいパスワード（8 文字以上）",
    [QCTextHostRepeatPassword]     = "パスワードを再入力",
    [QCTextHostPasswordsDiffer]    = "パスワードが一致しません。",
    [QCTextHostPasswordShort]      = "8 文字以上で入力してください。",
    [QCTextHostPasswordSaved]      = "パスワードを保存しました。",
    [QCTextHostPasswordUnreadable] = "パスワードファイルを読み込めません – 新しいデバイスは「許可」でのみ接続できます。",
    [QCTextHostDevices]            = "許可したデバイス",
    [QCTextHostNoDevices]          = "デバイスはまだありません",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – {d} から",
    [QCTextHostRemove]             = "削除",
    [QCTextHostRemoveAll]          = "すべてのデバイスを削除 …",
    [QCTextHostRemoveAllAsk]       = "許可したデバイスをすべて削除しますか？ 削除すると再びパスワードが必要になります。",
    [QCTextHostListDamaged]        = "デバイスリストが壊れています",
    [QCTextHostListReset]          = "デバイスリストをリセット",
    [QCTextHostRequest]            = "{n}（ID {i}）がこのコンピュータを操作しようとしています。",
    [QCTextHostAllow]              = "許可",
    [QCTextHostDeny]               = "拒否",
    [QCTextHostStartLogin]         = "ログイン時に起動",
    [QCTextHostStartWindows]       = "Windows と同時に起動",
    [QCTextHostMoveToApps]         = "先に QuadChroma を「アプリケーション」フォルダに移動してください",
    [QCTextHostScreenMissing]      = "画面収録が許可されていません – システム設定を開く …",
    [QCTextHostAccessMissing]      = "アクセシビリティが許可されていません – システム設定を開く …",
    [QCTextHostPortBusy]           = "ポート {p} は別のプログラムが使用中です",
    [QCTextHostQuit]               = "QuadChroma を終了",
    [QCTextHostStopSharing]        = "共有を停止",
    [QCTextHostTooltip]            = "QuadChroma – この PC を共有中（ID {i}）",
    [QCTextHostOk]                 = "OK",
    [QCTextAccessCode]             = "確認コード: {c}",
    [QCTextAccessCancel]           = "中止",
    [QCTextHostPasswordNotSaved]   = "パスワードを保存できませんでした。",
    [QCTextHostPasswordInvalid]    = "パスワードに使用できない文字が含まれています。",
    [QCTextHostPasswordTitle]      = "パスワードを変更",
}};

static const qc_sprache QC_TR = { "tr", "Türkçe", {
    [QCTextHostReady]              = "Bağlantılara hazır",
    [QCTextHostConnected]          = "Bağlı: {n}",
    [QCTextHostDeviceId]           = "Cihaz ID'si: {i}",
    [QCTextHostPassword]           = "Parola: {p}",
    [QCTextHostCopied]             = "Kopyalandı",
    [QCTextHostChangePassword]     = "Parolayı değiştir …",
    [QCTextHostRandomPassword]     = "Yeni rastgele parola",
    [QCTextHostNewPassword]        = "Yeni parola (en az 8 karakter)",
    [QCTextHostRepeatPassword]     = "Parolayı tekrarlayın",
    [QCTextHostPasswordsDiffer]    = "Parolalar eşleşmiyor.",
    [QCTextHostPasswordShort]      = "Lütfen en az 8 karakter girin.",
    [QCTextHostPasswordSaved]      = "Parola kaydedildi.",
    [QCTextHostPasswordUnreadable] = "Parola dosyası okunamıyor – yeni cihazlar yalnızca \"İzin ver\" ile.",
    [QCTextHostDevices]            = "İzin verilen cihazlar",
    [QCTextHostNoDevices]          = "Henüz cihaz yok",
    [QCTextHostDeviceLine]         = "{n} – ID {i} – {d} tarihinden beri",
    [QCTextHostRemove]             = "Kaldır",
    [QCTextHostRemoveAll]          = "Tüm cihazları kaldır …",
    [QCTextHostRemoveAllAsk]       = "İzin verilen tüm cihazlar kaldırılsın mı? Bu cihazlar yeniden parolaya ihtiyaç duyacak.",
    [QCTextHostListDamaged]        = "Cihaz listesi bozuk",
    [QCTextHostListReset]          = "Cihaz listesini sıfırla",
    [QCTextHostRequest]            = "{n} (ID {i}) bu bilgisayarı kontrol etmek istiyor.",
    [QCTextHostAllow]              = "İzin ver",
    [QCTextHostDeny]               = "Reddet",
    [QCTextHostStartLogin]         = "Oturum açılınca başlat",
    [QCTextHostStartWindows]       = "Windows ile başlat",
    [QCTextHostMoveToApps]         = "Önce QuadChroma'yı Uygulamalar klasörüne taşıyın",
    [QCTextHostScreenMissing]      = "Ekran Kaydı izni yok – Sistem Ayarları'nı aç …",
    [QCTextHostAccessMissing]      = "Erişilebilirlik izni yok – Sistem Ayarları'nı aç …",
    [QCTextHostPortBusy]           = "{p} numaralı port başka bir program tarafından kullanılıyor",
    [QCTextHostQuit]               = "QuadChroma'dan çıkış",
    [QCTextHostStopSharing]        = "Paylaşımı durdur",
    [QCTextHostTooltip]            = "QuadChroma – bu bilgisayar paylaşılıyor (ID {i})",
    [QCTextHostOk]                 = "Tamam",
    [QCTextAccessCode]             = "Kod: {c}",
    [QCTextAccessCancel]           = "İptal",
    [QCTextHostPasswordNotSaved]   = "Parola kaydedilemedi.",
    [QCTextHostPasswordInvalid]    = "Parola izin verilmeyen karakterler içeriyor.",
    [QCTextHostPasswordTitle]      = "Parolayı değiştir",
}};

static const qc_sprache *const g_sprachen[] = {
    &QC_EN, &QC_DE, &QC_FR, &QC_ES, &QC_IT, &QC_PT, &QC_NL, &QC_SV, &QC_DA, &QC_NB,
    &QC_FI, &QC_IS, &QC_PL, &QC_CS, &QC_SK, &QC_HU, &QC_RO, &QC_BG, &QC_EL, &QC_ET,
    &QC_LV, &QC_LT, &QC_SL, &QC_HR, &QC_UK, &QC_RU, &QC_ZH, &QC_JA, &QC_TR,
};

#define QC_SPRACHEN ((int)(sizeof g_sprachen / sizeof g_sprachen[0]))

// Gewaehlte Sprache (Tabellenplatz). Gesetzt beim Start der Oberflaeche,
// gelesen aus jedem Faden - daher atomar.
static _Atomic int g_aktuell = 0;

int qc_texte_sprachen(void) { return QC_SPRACHEN; }

const char *qc_texte_code(int sprache) {
    return sprache >= 0 && sprache < QC_SPRACHEN ? g_sprachen[sprache]->code : NULL;
}

const char *qc_texte_name(int sprache) {
    return sprache >= 0 && sprache < QC_SPRACHEN ? g_sprachen[sprache]->name : NULL;
}

const char *qc_texte_eintrag(int sprache, QCText t) {
    if (sprache < 0 || sprache >= QC_SPRACHEN || (int)t < 0 || t >= QCTextAnzahl) return NULL;
    return g_sprachen[sprache]->t[t];
}

static int platz_fuer(NSString *code) {
    for (int i = 0; i < QC_SPRACHEN; i++)
        if ([code isEqualToString:@(g_sprachen[i]->code)]) return i;
    return -1;
}

int qc_texte_waehlen(NSArray<NSString *> *bevorzugt) {
    for (NSString *roh in bevorzugt) {
        if (![roh isKindOfClass:[NSString class]]) continue;
        // "de-DE", "pt_BR", "zh-Hans-CN": erst ganz, dann der Sprachteil.
        NSString *s = [[roh lowercaseString] stringByReplacingOccurrencesOfString:@"_" withString:@"-"];
        int p = platz_fuer(s);
        if (p >= 0) return p;
        NSRange r = [s rangeOfString:@"-"];
        if (r.location != NSNotFound) {
            p = platz_fuer([s substringToIndex:r.location]);
            if (p >= 0) return p;
        }
    }
    return 0;
}

void qc_texte_setzen(int sprache) {
    atomic_store(&g_aktuell, sprache >= 0 && sprache < QC_SPRACHEN ? sprache : 0);
}

int qc_texte_aktuell(void) { return atomic_load(&g_aktuell); }

void qc_texte_systemsprache(void) {
    qc_texte_setzen(qc_texte_waehlen([NSLocale preferredLanguages]));
}

NSString *qc_text(QCText t) {
    if ((int)t < 0 || t >= QCTextAnzahl) return @"";
    const char *s = g_sprachen[atomic_load(&g_aktuell)]->t[t];
    if (!s) s = g_sprachen[0]->t[t];
    return s ? @(s) : @"";
}

NSString *qc_text_mit(QCText t, NSDictionary<NSString *, NSString *> *werte) {
    NSString *vorlage = qc_text(t);
    NSMutableString *aus = [NSMutableString stringWithCapacity:vorlage.length + 32];
    NSUInteger n = vorlage.length, i = 0, stueck = 0;
    while (i < n) {
        // Platzhalter: genau "{x}" mit einem Zeichen, fuer das ein Wert da ist.
        // Alles andere wird stueckweise uebernommen, wie es steht.
        if ([vorlage characterAtIndex:i] == '{' && i + 2 < n && [vorlage characterAtIndex:i + 2] == '}') {
            NSString *wert = werte[[vorlage substringWithRange:NSMakeRange(i + 1, 1)]];
            if (wert) {
                [aus appendString:[vorlage substringWithRange:NSMakeRange(stueck, i - stueck)]];
                [aus appendString:wert];
                i += 3;
                stueck = i;
                continue;
            }
        }
        i++;
    }
    [aus appendString:[vorlage substringFromIndex:stueck]];
    return aus;
}
